### ISSUE TITLE
Feature Request: Archived Github Action Labeler

### ISSUE THREAD

**Issue by olblak** [rancher/fleet#1034]
### Is your feature request related to a problem?

I noticed the github action used to label issue has been archived by its autor.

### Solution you'd like

I would like to replace the https://github.com/rancher/fleet/blob/master/.github/workflows/label-all-opened-issues.yml by https://github.com/github/issue-labeler maintained by Github

**Comment by kkaempf** [comment]
I'd rather label issues manually 😉
