### ISSUE TITLE
Rancher Provisioning v2 overwrites labels on local cluster

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1079]
There is a bug in in [Rancher v2 provisioning](https://github.com/rancher/rancher/blob/release/v2.7/pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go#L138) which overwrites the labels on the local cluster resource.

Provisioning would need to use a two way merge to keep the labels, but this has not been scheduled.

### Current Behavior

The labels from fleet(e.g. `name: local`) as well as user provided labels are lost.

This leads to problems with targetting and target target customization overlays. The changes are first applied to the local cluster, then after some hours the customizations are lost.

The removal of the `name: local` label makes the local cluster group unusable.

### Expected Behavior

* User provided labels should persist.
* Target customizations should always be applied to matching local clusters.
* The local cluster group should be usable

### Steps To Reproduce

Example repository:  https://github.com/axeal/fleet-test/tree/354076-monitoring

### Workaround

A partial workaround could:

* advise users to set their labels on ~~`cluster.provisioning.cattle.io`~~, according to the [source](https://github.com/rancher/rancher/blob/release/v2.7/pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go#L112) `clusters.management.cattle.io`
* add the `name: local` label to `provisioningv2`

### Notes

There are several issues around target customization which seem related:

* https://github.com/rancher/fleet/pull/1011 (not all values propagated)
* https://github.com/rancher/fleet/issues/234 (target customization and cluster group)
* https://github.com/rancher/fleet/issues/373 (target customization needs Chart.yaml?)
* https://github.com/rancher/fleet/issues/598 (namespace mapping)
* https://github.com/rancher/fleet/issues/759 (name=local  label missing)
* https://github.com/rancher/fleet/issues/716 (bootstrap removes local cluster label)
* #1163 

This issue refers to SURE-5082

**Comment by manno** [comment]
Fleet only changes the local cluster via `bootstrap.go`. This happens for controller restarts and changes to the fleet-controller config map. However apply makes sure no user created labels are lost.

When Fleet is running in Rancher the cluster resource is updated multiple times and the "name: local" label from fleet is removed. This also breaks the default cluster group.

**Comment by manno** [comment]
Moving this back to the backlog so we can discuss how to proceed

**Comment by mguggi** [comment]
@manno Is there already a plan in which release this fix is included?

**Comment by manno** [comment]
@mguggi this fix will be in 2.7.2. We have some [doubt if it will be effective ](https://github.com/rancher/fleet/issues/1365)though.

**Comment by manno** [comment]
Note to myself, the [QA Template](https://github.com/rancher/rancher/pull/40176) is in the PR.
