### ISSUE TITLE
Calculating "resourceKey" Calls "helm template" With Insufficient Deployment Options

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1101]
When fleet creates the bundledeployment from the bundle it runs "helm template" to generate a list of resources which are included in the bundle. This list is stored in the bundle status as `resourceKey`. They're also [synced to the gitrepo resource](https://github.com/rancher/fleet/blob/e5b7646d34124fa725a128543a703b715dd24a6c/pkg/display/gitrepo.go#L194) status. 

The resource list is [used in the dashboard](https://github.com/rancher/dashboard/blob/92c81e6d14657cad83e8be6c63e09504e828994c/shell/detail/fleet.cattle.io.bundle.vue).

The problem is, helm is normally executed on a downstream cluster to install a bundledeployment. Here we run helm on the upstream cluster. So, helm charts that use "helm chart capabilities" fail: https://github.com/rancher/fleet/issues/399

Furthermore, the resourceKey generation does not run against actual, matched target cluster, so deployment options are missing. These options could come from target customizations. The cluster labels are missing, too, so replacement of `global.fleet.clusterLabels.` in helm values fails, which breaks charts that verify their values. 

Ideas: 
* don't treat a failing resourceKey calculation as fatal error (https://github.com/rancher/fleet/pull/1103)
* run resourceKey generation on the [actually matched clusters](https://github.com/manno/fleet/commit/769fcd729eee70edce2eada67b38d95788791a08), which have real deployment options
* optionally disable resourceKey generation for fleet-standalone, as it's only used in the UI
* move helm processing completely to the downstream cluster: https://github.com/rancher/fleet/issues/399

**Comment by romejoe** [comment]
@manno I implemented a combination of the second and fourth ideas a few months ago in #985 . We've been using that in production with minimal issues. The only issue I've noticed is that the resource list for a bundle aren't showing up correctly in Rancher or the model yet.

That pull request is a bit out of date now and I need to run the e2e tests against it, but I can do that later today if anyone is interested.

**Comment by manno** [comment]
@romejoe I was aware of the PR. I think the current situation with #1103 is "good enough"? 

The "resource key" was never calculated exactly. Taking target customizations and helm chart logic into account, it's not even clear what the correct way would be. One bundle can have many bundledeployments, each with a different set of resources. How to store these in a bundle's status? Merge the lists, build sub groups, ..? Also with many clusters, calculating all these options is expensive and probably repetitious in most scenarios. 

If the current implementation fixes https://github.com/rancher/fleet/issues/399 I would close https://github.com/rancher/fleet/pull/985? What do you think?

**Comment by romejoe** [comment]
I think #1103 is good enough for the time being. It should resolve the original issue we were facing that caused me create #985. I'm planning to test it out in our deployments in a few days.

I didn't think about those cases with the bundle deployments. #985 just merges all the resource keys from the bundle deployment's status into a single list in the bundle's status and keeps the unique resources. Thinking about it now, #985 has the potential to add a lot of unnecessary and repetitive overhead as the number of clusters increases.

When I first tried to resolve #399, I had each cluster report back their capabilities and version information so they could be fed into Helm on the controller. Perhaps collecting that information and generating resource keys for unique cluster capabilities would eliminate that redundant resource key calculation. Although, collecting that cluster information is probably overkill if it's only used for resource key generation.

I think #1103 would resolve #399, I'll close #985.
