### ISSUE TITLE
Investigate if GitRepo can get stuck in Failed state if git server temporarily unavailable

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1118]
I was under the impression that GitRepo's are checked regularly.

SURE-3841, SURE-4049

**Edited on 2023-01-26**

### Problem
If the Git server is temporarily unavailable for any reason all GitRepos will enter a failed state with error similar to `Git ls-remote http://188.166.42.125:7990/scm/test/fleet-test.git refs/heads/master error: exit status 128, detail: fatal: unable to access 'http://188.166.42.125:7990/scm/test/fleet-test.git/': Failed to connect to 188.166.42.125 port 7990 after 1 ms: Connection refused` and Fleet reconciliation of these will not occur automatically again until a Force Update is applied

### Solution

Retry git repo updates after errors

to allow git repos to be usable after short network outages or similar
issues.

Without this change it was necessary to manually force an update to

make the gitrepo reusable again.

### Testing

* Provision a Rancher instance and single node custom cluster (I used github.com/superseb/tf-do-rancher2)
* Start a Bitbucket instance `docker run -v /data/bitbucket:/var/atlassian/application-data/bitbucket --name="bitbucket" -d -p 7990:7990 -p 7999:7999 atlassian/bitbucket:7.6.0`, add an evaluation license, create a test project, a test repo within this and make the repo publically readable, then commit a simple deployment.yaml manifest to the repo
* In the fleet-default workspace add the Bitbucket repo via http e.g.  http://188.166.42.125:7990/scm/test/fleet-test.git
* Once the GitRepo is active stop the Bitbucket container `docker stop <container-id>`
* Observe GitRepo enters Failed state with error of the format ``Git ls-remote http://188.166.42.125:7990/scm/test/fleet-test.git refs/heads/master error: exit status 128, detail: fatal: unable to access 'http://188.166.42.125:7990/scm/test/fleet-test.git/': Failed to connect to 188.166.42.125 port 7990 after 1 ms: Connection refused``
* Start Bitbucket container `docker start <container-id>
* Wait for Bitbucket to becomes available again (takes a while c.5-10mins)
* Observe GitRepo remains in Failed state until a Force Update is performed

#### Automated Testing
/

### QA Testing Considerations
/

#### Regressions Considerations
/

**Comment by Martin-Weiss** [comment]
I have seen this issue multiple times and only a "force update" helped in this situation..

**Comment by thardeck** [comment]
I can reproduce the issue with stand alone https://github.com/rancher/gitjob.
Keeping this issue open though since there is no real gain by just moving everything over there since we have to fix it anyway.

**Comment by Martin-Weiss** [comment]
Quick update on this issue! 

 I have seen the same issue with the http URL to the specified helm repo not reachable as well! So when fixing this issue -> could you also ensure we take are about fixing the problem with helm repo not reachable as well or do we need an other Jira ticket for that as well?

fleet.yaml has i.e. this:

```

defaultNamespace: kubewarden
helm:
  releaseName: kubewarden-controller
  chart: kubewarden-controller
  version: 1.4.1
  repo: https://susemanager.suse/pub/helm
```

![grafik](https://user-images.githubusercontent.com/13362573/218741880-d15d96f6-c597-4422-8f6f-b1f0933c627b.png)

**Comment by olblak** [comment]
@Martin-Weiss Could I ask you to open a another issue to track what needs to be done for the helm repo. The scope seems to be different than git

**Comment by olblak** [comment]
@sowmyav27 Out of curiosity have you tested this issue? 
I see in the issue history that you requested for a QA template which is available in the issue description but I don't see anything else.

The fix for this issue is already available in https://github.com/rancher/fleet/releases/tag/v0.6.0-rc.5

@Martin-Weiss is a valid and good feedback but seems out of the scope of the current issue and IMHO should be track in a different issue

**Comment by olblak** [comment]
For context the bug has been fixed in gitjob 0.1.33

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss Could I ask you to open a another issue to track what needs to be done for the helm repo. The scope seems to be different than git

https://github.com/rancher/fleet/issues/1387 created

**Comment by kkaempf** [comment]
@manno - please check the security review in Jira

**Comment by kkaempf** [comment]
QA template is in the initial description
