### ISSUE TITLE
Fleet - Clusters show 0 node ready after upgrading from v2.4.8 to v2.5-head 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/fleet#114]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:v2.4.8 HA
- add some custom clusters
- upgrade Rancher to v2.5-head 65f3525
- go the dashboard -> continues delivery -> clusters

**Result:**
- some clusters show 0 nodes available 
<img width="1598" alt="Screen Shot 2020-10-05 at 6 32 11 PM" src="https://user-images.githubusercontent.com/6218999/95149325-78bbc000-073a-11eb-8bca-36638654ba6d.png">

- `force upgrade` the cluster can solve the problem
  

**Other details that may be helpful:**

All clusters show the right number of nodes after a while.

**Comment by StrongMonkey** [comment]
@jiaqiluo I was not able to reproduce it very easily. Can you let me know if you reproduce it and keep the setup? This could be a race condition issue.

**Comment by jiaqiluo** [comment]
I cannot reproduce this bug either. 
The steps are the same as the issue provides, upgrade rancher from HA from `v2.4.8` to  `v2.5-61a8a3691063108bc775c8e4e6f6db971541c253-head`, all nodes are ready.

![screencapture-jiaqi203-qa-rancher-space-dashboard-c-c-8kshn-fleet-fleet-cattle-io-cluster-2020-10-21-14_02_21](https://user-images.githubusercontent.com/6218999/96787381-7c8c4b00-13a6-11eb-99ca-2118712fcd37.png)

This issue will be reopened if I hit the bug again.
