### ISSUE TITLE
High CPU Usage in Fleet Controller

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1142]
Master issue for all issues/tickets related to this symptom.

 - https://github.com/rancher/fleet/issues/606
 - https://github.com/rancher/fleet/issues/721
 - https://jira.suse.com/browse/SURE-4967
 - https://jira.suse.com/browse/SURE-3613

**Comment by moio** [comment]
Currently waiting on user feedback.

**Comment by moio** [comment]
Feedback received, needs to be revisited in early 2023

**Comment by moio** [comment]
New version of experimental image published. Waiting for new feedback

**Comment by kkaempf** [comment]
Moving to 'Needs QA review'

@sowmyav27, @moio please sync on if/how to test this.

**Comment by moio** [comment]
@sowmyav27: work linked to this issue had the aim of reducing fleetcontroller CPU usage.

A rough way to test such improvement is described in the "Test" section of the following PR description:

https://github.com/rancher/fleet/pull/1062

There are definitely better ways, eg. using Rancher's Monitoring features.

A defect in those changes should completely break main Fleet functionality, so I believe current tests are sufficient to cover for that.

Please contact me if there is anything I can do to help.

**Comment by moio** [comment]
All sub-issues and JIRA tickets closed. I remain available in case of questions.
