### ISSUE TITLE
Credentials management

### ISSUE THREAD

**Issue by arthurh4** [rancher/fleet#115]
Hey, I'm very interested in using rancher fleet for our cluster apps but I have one concern.

We do not want to store sensitive data in clear text inside our repo and we currently we rely hashicorp vault integration to pull the data when our push based deploys runs.

Is there a way to somehow inject sensitive data at deploy time in fleet so we don't have sensitive data in clear text in our repos ?

Thanks a lot

**Comment by kkaempf** [comment]
See #144 - SOPS will be used for that.
