### ISSUE TITLE
https://<your rancher url>/v1/schemas/fleet.cattle.io.gitrepo returns 404

### ISSUE THREAD

**Issue by zhaoyi0113** [rancher/fleet#1167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The issue has been discussed on Rancher dashboard but they suggested to log a issue here: https://github.com/rancher/dashboard/issues/7616

I am launching Rancher docker container on Mac M1 12.6. Below is the command I used to launch Rancher container:

docker run -d --restart=unless-stopped  -p 80:80 -p 443:443 --privileged rancher/rancher:latest
The version of Rancher is v2.7.0.

I am able to login to the dashboard but there is Continuous Delivery in the menu. How can I use fleet as gitops to deploy resources to K8S cluster managed by Rancher?

![image](https://user-images.githubusercontent.com/3355579/206838161-74379598-089e-4397-990d-d0c3da603857.png)

### Expected Behavior

It should show `Continuous Delivery` on the top menu.

### Environment

```markdown
- Architecture:
- Fleet Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

**Comment by kkaempf** [comment]
adapted the title to match the actual problem identified in rancher/dashboard#7616 ( [comment](https://github.com/rancher/dashboard/issues/7616#issuecomment-1344610317) )

**Comment by kkaempf** [comment]
Probably Fleet needs more time to start
