### ISSUE TITLE
Feature Request: Replace existing helm releases in-place. 

### ISSUE THREAD

**Issue by ryanpeach** [rancher/fleet#1175]
### Is your feature request related to a problem?

I have a helm release that was released manually a long time ago and I'd like to migrate managing this resource to using fleet. Deleting it and reinstalling it with fleet would cause system downtime.

### Solution you'd like

The ability to install the release with fleet using the same name and fleet should discover it already exists and begin to manage it. I'd like to confirm this works.

**Comment by manno** [comment]
There is an undocumented option in fleet.yaml `helm.takeOwnership`, does that work?


https://fleet.rancher.io/next/ref-crds#helmoptions

**Comment by ryanpeach** [comment]
Yes that's very helpful, thanks!
