### ISSUE TITLE
Adopt existing resources?

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1177]
From SURE-3976

> Is there a way to have Fleet "adopt" existing resources in a k8s cluster? I have existing manual deployments of an application. I would like to begin managing the application with Fleet in a non-disruptive manner. So far, it seems like Fleet refuses to take over existing resources that it hasn't deployed. To be sure, that is a reasonable default. I'm hoping maybe there's an annotation that I can use to say "Yes, these resources already exist. Go ahead and take them over."

**Comment by manno** [comment]
https://github.com/rancher/fleet/issues/440

**Comment by kkaempf** [comment]
duplicate
