### ISSUE TITLE
Private Git Repo Usage - Fails Auth

### ISSUE THREAD

**Issue by egallis31** [rancher/fleet#118]
All attempts to use a private github repo following the specific syntax either git@github:username/repo.git (ssh) and https://github.com/username/repo.git (https) fail during the inital authentication stage. Secrets are properly listed in namespace.

![apm-server-http-auth](https://user-images.githubusercontent.com/18443524/95349000-99942a80-088c-11eb-9694-9e5b8bbdbc39.PNG)

Verified that the https auth is correct and ran the highlighted git ls-remote command manually.

Additionally when testing the ssh auth, the same error occurs as in <https://github.com/rancher/fleet/issues/93#issuecomment-703642672>. 

![apm-server-ssh-auth](https://user-images.githubusercontent.com/18443524/95349604-453d7a80-088d-11eb-86e9-b42048dab835.PNG)

Again verified ssh is working properly by executing the git ls-remote command manually. If I understand the usage the ssh git url should be correct. If not please let me know.

**Comment by egallis31** [comment]
Closing Related to <https://github.com/rancher/fleet/issues/93#issuecomment-704998482>, step worked as stop gap for ssh auth.

**Comment by philipp1992** [comment]
having the same problem when trying to authenticate against a gitlab private repo with basic-auth

**Comment by shane-davidson** [comment]
> Closing Related to [#93 (comment)](https://github.com/rancher/fleet/issues/93#issuecomment-704998482), step worked as stop gap for ssh auth.

This relates to SSH auth not HTTP auth

Also having the same issue.

**Comment by smoretto** [comment]
Should be cause by this issue rancher/wrangler#134

**Comment by Shaked** [comment]
> Should be caused by this issue [rancher/wrangler#134](https://github.com/rancher/wrangler/issues/134)

Any idea when this is going to be available in the Rancher latest repository?

**Comment by StrongMonkey** [comment]
Duplicated of https://github.com/rancher/fleet/issues/134, should be fixed in fleet v0.3.1-rc2 and 2.5.2.

**Comment by cloudnautique** [comment]
Closing since #134 was closed and shipped.
