### ISSUE TITLE
How to do force update at particular interval of time through fleet yaml file 

### ISSUE THREAD

**Issue by sunny092318** [rancher/fleet#1223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently using fleet gitops pipeline for our organization project. I think fleet GitHub repo resource  will sync with cluster state at some interval of time in day to keep the environment similar. But in our use cases we want to sync the fleet created resources with cluster after some interval of time. like 2 hours or 4 hours through yaml file. 
We are creating all fleet resources through login into rancher dashboard on continuous delivery option. Hence we are not getting the sync option to apply after 2 hours or 4 hours. After creation force update option will be there but we wanted to execute through yaml and after interval of time.

Please help
   
Is there way to do force update kind of cron job defining in fleet yaml file.

### Expected Behavior

There has to yaml file definition to force update 

### Steps To Reproduce

n/a

### Environment

```markdown
- Architecture:
- Fleet Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

### Logs

```markdown
n/a
```

### Anything else?

n/a

**Comment by sunny092318** [comment]
one more query: What is the standard time duration for fleet to do sync up with GitHub resource state with cluster resource state.

**Comment by manno** [comment]
By default Fleet polls every 15 minutes: https://fleet.rancher.io/next/webhook

Indeed fleet does not support drift correction yet. It's on the agenda, though. 
As a workaround you might be able to script something with [ForceSyncGeneration](https://fleet.rancher.io/next/gitrepo-add)
