### ISSUE TITLE
Feature Request: Explicit message when fleet.yaml references a chart that doesn't exist

### ISSUE THREAD

**Issue by devpro** [rancher/fleet#1235]
### Is your feature request related to a problem?

I have spent some time investigating a blocking issue with GitRepos in error with the only message "bad response code: 404". In the job fleet container log, there was only one line with this error.

It turned out the fleet.yaml was using a version of an Helm chart that has been deleted.

### Solution you'd like

It would have helped me to have a more explicit error message, saying the referenced chart 1.2.3 doesn't exist.

I don't know on the technical side, but either test directly the referenced chart or check the response code and suggest the chart is missing.

**Comment by manno** [comment]
Was the error copied into the status of the GitRepo resource?

**Comment by manno** [comment]
Please reopen if this still happens with 0.11
