### ISSUE TITLE
Long bundle names will still be cleaned up continuously

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1272]
SURE-4160

This is a follow up to https://github.com/rancher/fleet/issues/523

Under certain conditions a long bundle name might be shortened again, resulting in a different checksum suffix. The agent will then clean up the helm installation and install again.

**Comment by manno** [comment]
We test this automatically with these releases
https://github.com/rancher/fleet-examples/tree/test-bundle-names

It seems that for the previous attempt to fix https://github.com/rancher/fleet/pull/973 QA was not needed.

**Comment by olblak** [comment]
> We test this automatically with these releases https://github.com/rancher/fleet-examples/tree/test-bundle-names
> 
> It seems that for the previous attempt to fix #973 QA was not needed.

Out of curiosity, based on the previous attempt to fix, how did you concluded that QA wasn't needed
