### ISSUE TITLE
[v0.5] Backport Upgrade Fix for Rancher 2.5

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1274]
Backport https://github.com/rancher/fleet/pull/1269 to fix https://github.com/rancher/rancher/issues/40127 in 0.5

QA template in PR: https://github.com/rancher/fleet/pull/1269#issuecomment-1401944714

**Comment by kkaempf** [comment]
[Fleet-0.5.2-rc3](https://github.com/rancher/fleet/releases/tag/v0.5.2-rc.3) is out.

**Comment by anupama2501** [comment]
Verified fleet installed `rancher/fleet-agent:v0.5.2-rc.3` by upgrading rancher server from 2.5.17 to 2.6.11-rc4 works as expected and the errors that were seen in fleet-agent were resolved:

- Create a rancher serves on rancher version 2.5.17
- Created a downstream rke1 1 custom clusters on k8s 1.20 
- Create a fleet git repo
- Upgrade rancher server to version 2.6.11-rc4 
- Notice no errors in the fleet agent logs of the downstream clusters.
- Grab the local kubeconfig file and verify the downstream clusters have secrets and configmaps in the namespaces cattle-fleet-system

Verified fresh install of 2.6.11-rc4 and fleet `rancher/fleet-agent:v0.5.2-rc.3`
- Created a downstream rke1 1 custom clusters on k8s 1.23
- Create a fleet git repo
- Notice no errors in the fleet agent logs of the downstream clusters.
- Grab the local kubeconfig file and verify the downstream clusters have secrets and configmaps in the namespaces cattle-fleet-system





```
> k get secret -n cattle-fleet-system
NAME                                        TYPE                                  DATA   AGE
fleet-agent                                 Opaque                                4      35m
fleet-agent-token-dmfgh                     kubernetes.io/service-account-token   3      35m

> k get cm -n cattle-fleet-system
NAME               DATA   AGE
fleet-agent        1      35m
fleet-agent-lock   0      35m
```
