### ISSUE TITLE
Fleet Installation on Mac Rancher desktop fails

### ISSUE THREAD

**Issue by LefterisBanos** [rancher/fleet#1284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi all,
I am trying to follow the installation here: https://fleet.rancher.io/quickstart, on Mac Rancher desktop.

Although crd installation is done properly, but when I try to install fleet :

`helm -n cattle-fleet-system install --create-namespace --wait \
    fleet https://github.com/rancher/fleet/releases/download/v0.5.0/fleet-0.5.0.tgz`

I get following error: 
`Error: INSTALLATION FAILED: timed out waiting for the condition`

Any suggestions, please?
Thank you.

### Expected Behavior

To properly install fleet on Rancher Desktop.

### Steps To Reproduce

1. Install fleet using :  `Error: INSTALLATION FAILED: timed out waiting for the condition`
2. Error: `Error: INSTALLATION FAILED: timed out waiting for the condition`

### Environment

```markdown
- Mac
- Rancher Desktop
```

Logs:

Running the install command with `--debug` getting following output: 
`install.go:192: [debug] Original chart version: ""
install.go:209: [debug] CHART PATH: /Downloads/fleet-0.5.1.tgz

client.go:229: [debug] checking 17 resources for changes
client.go:512: [debug] Looks like there are no changes for ServiceAccount "gitjob"
client.go:512: [debug] Looks like there are no changes for ServiceAccount "fleet-controller"
client.go:512: [debug] Looks like there are no changes for ServiceAccount "fleet-controller-bootstrap"
client.go:512: [debug] Looks like there are no changes for ConfigMap "fleet-controller"
client.go:512: [debug] Looks like there are no changes for ClusterRole "gitjob"
client.go:512: [debug] Looks like there are no changes for ClusterRole "fleet-controller"
client.go:512: [debug] Looks like there are no changes for ClusterRole "fleet-controller-bootstrap"
client.go:512: [debug] Looks like there are no changes for ClusterRoleBinding "gitjob-binding"
client.go:512: [debug] Looks like there are no changes for ClusterRoleBinding "fleet-controller"
client.go:512: [debug] Looks like there are no changes for ClusterRoleBinding "fleet-controller-bootstrap"
client.go:512: [debug] Looks like there are no changes for Role "gitjob"
client.go:512: [debug] Looks like there are no changes for Role "fleet-controller"
client.go:512: [debug] Looks like there are no changes for RoleBinding "gitjob"
client.go:512: [debug] Looks like there are no changes for RoleBinding "fleet-controller"
client.go:512: [debug] Looks like there are no changes for Service "gitjob"
client.go:512: [debug] Looks like there are no changes for Deployment "gitjob"
client.go:512: [debug] Looks like there are no changes for Deployment "fleet-controller"
wait.go:66: [debug] beginning wait for 17 resources with timeout of 5m0s
ready.go:277: [debug] Deployment is not ready: cattle-fleet-system/gitjob. 0 out of 1 expected pods are ready
ready.go:277: [debug] Deployment is not ready: cattle-fleet-system/gitjob. 0 out of 1 expected pods are ready
...
ready.go:277: [debug] Deployment is not ready: cattle-fleet-system/gitjob. 0 out of 1 expected pods are ready
ready.go:277: [debug] Deployment is not ready: cattle-fleet-system/gitjob. 0 out of 1 expected pods are ready
Error: INSTALLATION FAILED: timed out waiting for the condition
helm.go:84: [debug] timed out waiting for the condition
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:141
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.5.0/command.go:918
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1571`

**Comment by manno** [comment]
Works for me on M1,  are the deployments fine? Any pods not started, something in the pod logs?
