### ISSUE TITLE
[SURE-5330] Large number of zombie processes in gitjob pod

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1305]
### Troubleshooting steps:
Add a custom gitrepo in the fleet and keep changing the yaml, which will redeploy the pods on the local/downstream cluster. The zombie process won't appear all of a sudden. Keep the environment for a few days, zombie processes eventually appear on the gitjob container

### Repro steps:

    Rancher >> Continuous Delivery >> GitRepos >> Add repository with GitHub auth
    Keep changing the deployment codes in the gitrepo to allow at least 10 re-deployments continuously 
    Keep the environment for a day, zombie process will appear in gitjob container

 

### Workaround:
Is workararound available and implemented? yes
What is the workaround: Rollout restart gitjob deployment

### Actual behavior:
A large number of zombie processes appear on the gitjob container

### Expected behavior:
No or very minimal zombie processes should appear and should have a mechanism to automatically cleanup without restarting the gitjob container(parent process)

### Files, logs, traces:

```
$ kubectl -n cattle-fleet-system exec -it gitjob-6dbbc7b749-fp4fg sh

sh-4.4$ ps -ef

UID          PID    PPID  C STIME TTY          TIME CMD

gitjob         1       0  0 Sep22 ?        00:57:16 gitjob --tekton-image rancher/tekton-utils:v0.1.6

gitjob       153       1  0 14:32 ?        00:00:00 [git] <defunct>

gitjob       157       1  0 14:32 ?        00:00:00 [git] <defunct>

gitjob       161       1  0 14:32 ?        00:00:00 [git] <defunct>

gitjob       169       1  0 14:32 ?        00:00:00 [git] <defunct>

gitjob       173       1  0 14:32 ?        00:00:00 [git] <defunct>

gitjob       177       1  0 14:32 ?        00:00:00 [git] <defunct>

gitjob       180       0  0 19:51 pts/0    00:00:00 sh

gitjob       186     180 83 19:51 pts/0    00:00:00 ps -ef
```

**Comment by Bixlid** [comment]
Hi, 
Same problem here but with a huge number of defunct processes : 458 .
Redeploying made the trick but in two days i had to do it twice ...
Running on Rancher 2.7.1 and fleet version 0.5.1.

**Comment by raulcabello** [comment]
@rancher/qa
 
### Problem
Zombie processes are left in the gitjob pod. This is happening because gitjob runs with PID 1, therefore defunct processes are not reaped .
 
### Solution
Use [catatonit](https://github.com/openSUSE/catatonit) as init process

### Engineering Testing
#### Manual Testing
- create a `GitRepo` with an invalid git url. For example:
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: dev
spec:
  repo: https://github.com/rancher/invalid-repo
  branch: main
  paths:
  - dev
  targets:
    - name: dev
      clusterSelector:
        env: test

```
- Verify no defunct processes exist in the pod:
```
kubectl -n cattle-fleet-system exec -it gitjob-6dbbc7b749-fp4fg sh
ps -ef
```

**Comment by raulcabello** [comment]
fixed by https://github.com/rancher/gitjob/pull/201

**Comment by sbulage** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1| Test if zombie process exists in the `gitjob` pod after giving invalid github repository link.|

**Comment by sbulage** [comment]
Verified first two test cases QE Test Plan in above comment.

**TEST RESULT**

Scenarios
|Scenario|Test Case| Result
|---|---|---|
|1| Test if zombie process exists in the `gitjob` pod after giving invalid github repository link.| :white_check_mark:|


**REPRO STEPS**

**Scenario 1**
1. Get access to the kubectl shell.
2. Create a `GitRepo` from this github repo: `https://github.com/sbulage/test-fleet/blob/main/defunct-zombie-process/gitrepo.yaml`
3. Make sure GitRepo is created.
4. Verified that no zombie processes are created.
    ```
      satya@rancher:~> kubectl get pods -n cattle-fleet-system
      NAME                               READY   STATUS    RESTARTS   AGE
      fleet-controller-fcdc554f8-b2kl9   1/1     Running   0          30h
      gitjob-7848ddb6bb-rhg4k            1/1     Running   0          30h

      satya@rancher:~> kubectl -n cattle-fleet-system exec gitjob-7848ddb6bb-rhg4k -- ps -ef 
      UID        PID  PPID  C STIME TTY          TIME CMD
      gitjob       1     0  0 01:06 ?        00:00:00 catatonit -- gitjob --tekton-image rancher/tekton-utils:v0.1.17
      gitjob       7     1  0 01:06 ?        00:01:06 gitjob --tekton-image rancher/tekton-utils:v0.1.17
      gitjob     255     0 60 16:13 ?        00:00:00 ps -ef
    ```
