### ISSUE TITLE
[SURE-5680] Fleet failed to assign RKE2 with Hardened profile CIS-1.6 cluster to a workspace

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1308]
#### Issue description:
not able to assign RKE2 v1.24.4+rke2r1 with Hardened profile cis-1.6 clusters to a workspace.

#### Business impact:
Not able to perform tasks based on workspaces. 

#### Troubleshooting steps:

> In continuous delivery > Advanced, tried to create a new workspace, and then when we try to assign a cluster (which is currently in fleet-default workspace) to the newly created workspace, it shows nothing and the cluster remain in fleet-default workspace. We tried assigning to another workspace, but no luck
    The above behaviour is seen only for RKE2 clusters with CIS-1.6 profile enabled.

#### Repro steps:

 > Create RKE2 downstream cluster with CIS-1.6 profile
 > In continuous delivery > Advanced, create a new workspace, and then try to assign a cluster (which is currently in fleet-default workspace) to the newly created workspace, nothing happens, the cluster remain in fleet-default workspace. 

#### Workaround:
Is workaround available and implemented? No. There is no workaround so far. 
What is the workaround:NA

#### Actual behavior:
not able to assign RKE2 v1.24.4+rke2r1 with Hardened profile cis-1.6 clusters to different workspaces in Fleet.

#### Expected behaviour:
should able to change the workspace.

**Comment by manno** [comment]
This seems to be a known issue, moving clusters across workspaces only works with RKE1, and is probably not related to the CIS profile.

**Comment by manno** [comment]
Not a Fleet issue, might be solvable in provisioning.

**Comment by kkaempf** [comment]
https://github.com/rancher/rancher/issues/36132
