### ISSUE TITLE
[SURE-3281] Enabling "pod_security_policy: true" in cluster breaks Ranchers Fleet install

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1319]
#### Environment
3 node installation, launched with:

```
services:
  kube-api:
    pod_security_policy: true
```

In the cluster.yml file with rke 1.1.19

Then install stable rancher, fleet will fail to install.

#### Issue description:
Rancher does not install with a functional fleet if cluster is launched with rke and pod_security_policy: true enabled

#### Business impact:
Cannot install rke cluster with pod_security_police enabled and get a functioning fleet install in rancher.

#### Troubleshooting steps:
Run repro steps, check fleet-system, observe no pods deployed.

#### Repro steps:

Install cluster with rke and pod_security_policy: true
Install stable rancher
when finished, check the fleet-system namespace.

#### Actual behavior:
Fails to install

#### Expected behavior:
Installs

#### Files, logs, traces:
Only thing I found was stuff waiting for fleet pods.

**Comment by manno** [comment]
We'll have to investigate, but Fleet needs API access to k8s.

**Comment by raulcabello** [comment]
This is not a Fleet issue. The problem is that the defaul psp created with rke rejects the creation of the fleet pods. This is the error I see:
```
 message: 'Error creating: pods "fleet-controller-6898c9fdf-" is forbidden: PodSecurityPolicy: 
```
psp is not supported in the latest rke versions as it was deprecated and removed in kubernetes 1.25
