### ISSUE TITLE
Continuous Delivery : terminal prompts disabled

### ISSUE THREAD

**Issue by eatrisno** [rancher/fleet#134]
git ls-remote https://gitlab.com/altoshift/project.git refs/heads/staging error: exit status 128, detail: fatal: could not read Username for 'https://gitlab.com': terminal prompts disabled

I'm trying to add a private GitLab project to Continuous Delivery but got an Error

gz#13105

**Comment by StrongMonkey** [comment]
We need to test both http and ssh auth.

**Comment by wbagdon** [comment]
Also having issues with both basic and ssh auth, let me know if I can assist by testing any fixes

**Comment by StrongMonkey** [comment]
@izaac Available to test on 2.5-head/master with fleet v0.3.1-rc2.

**Comment by izaac** [comment]
`fleet:v0.3.1-rc2` 
Rancher `v2.5-head (10/30/2020)` _cc777eb_

I duplicated the git repository and created a new private repository for testing
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/duplicating-a-repository

Then I created a GitRepo configuration in Continuous Delivery in the Dashboard using http auth. I generated a developer key to use as a password as I have 2FA enabled.
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

This worked and I saw the simple bundle deployed to the downstream clusters.

Then I deleted this GitRepo and configured the repository to use SSH auth. I generated a new SSH key pair this way as it seems not all ssh formats are supported:

`ssh-keygen -t rsa -b 4096 -m pem -C "izaac@email.com"` (No passphrase)

This SSH auth setup also worked and I saw a bundle deployed to downstream clusters.

**Comment by izaac** [comment]
opened #134 for the ssh key formats

**Comment by jmlp1** [comment]
I am having similar issues, trying to create a GitLab Repo in Rancher 2.5.5. via Continous Delivery. 

Tried creating an HTTP Basic Authentication Secret and  SSH, setup the project and my profile to use the SSH Keys created as per below

SSH Key Secret, tried two methods, no passphrase set
- ssh keygen: exit status 128, detail: fatal: could not read Username for 'https://gitlab.com': terminal prompts disabled
- ssh-keygen -t rsa -b 4096 -m pem -C "personal email address": data does not contain a valid RSA or ECDSA private key

HTTP Basic Auth Secret
exit status 128, detail: fatal: could not read Username for 'https://gitlab.com': terminal prompts disabled

Any given help will be very much appreciatted

**Comment by glitterlip** [comment]
usually your repository should have two kind of repository url format
First : `git@e.coding.x/x/x.git` is for `git clone`,
Second: `https://e.coding.net/xx/xx/xx.git` is for download zip
Change

**Comment by FullofQuarks** [comment]
Just to reiterate, as glitterlip's response helped me: 

Ensure that you are using the URL path and that it ends in `.git`

**Comment by SnehaPanda** [comment]
yess... I was missing out that ".git" and adding it solved my issue. Thanks a lot for highlighting it  @glitterlip and @FullofQuarks
