### ISSUE TITLE
[SURE-4821] fleet update bundle even if no changes are done

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1352]
#### Issue description:

The user has gitrepo with multipath i.e., gitrepo in fleet that point to root and has 2 paths “monitoring” and “trident”, and  committing some changes to “monitoring” folder in GIT  will reflect( regenerate) both bundles, and takes action also on “trident” bundle where as there is no changes in trident bundle.

> I have a gitrepo with many folder and in the fleet GitRepo configuration I have several path since I need to set dependencies
> between different pieces of components installed in the cluster. The problem is that every time I push some changes to git
> fleet re-update also all the pathes that point to folders that have not been changed. This causes the deletion and reinstallation
> of NetApp bwackend config that ends up in "deleting" status since there are volumes mounted and so is not possible to remove it.
  

 as per the documentation 

#### Repro steps:

- a gitlab with this structure
root
   /monitoring
   /trident
- I define a gitrepo in fleet that point to root and has 2 pathes "monitoring" and "trident"
- I commit some changes to "monitoring" folder in GIT

#### Actual behavior:
 as per the documentation https://fleet.rancher.io/gitrepo-structure/#how-repos-are-scanned, fleet will scan each path as separate bundled and  monitored it independently . in customer case update in on path will reflect to recreate  other path bundles(trident) as well [in addition to the required bundle(monitor)] (edited) 

#### Expected behavior:
It should not impact another path when end user perform any change to one path (bundle)

#### Additional notes:

1) I have a gitlab with this structure
root
   /monitoring
   /trident
2) I define a gitrepo in fleet that point to root and has 2 pathes "monitoring" and "trident"
3) I commit some changes to "monitoring" folder in GIT
4) fleet regenerate both bundles and take action also on "trident" bundle that has not any differences/changes (it seems that it removes previous bundle and apply the new one (that should be the same))
5) I need to have all in the same GitRepo resource since I need to express dependency and it seems to work only within the same gitrepo, but obviously since the git is the same I'm expecting fleet to be smart enough to undestand that the folder in the path did not have any changes so not doing any actions
6) the problem is that acting for the "trident" bundle is not an update but a delete+install and this means that it tryies to remove a CR that is the TridentBackendConfig that cannot be deleted unless you remove all volumes generated by the StorageClass based on that config so as you can imagine we end up not being able to remove volumes nor being able to use the config anymore (its in deleting state)

#### The request is:
1) can fleet be configured to act only on changes at path level and not a whole gitrepo level (should be done a diff in the bundle and if no diff than no changes are requested so the bundle should not be touched)
2) can fleet be configured so that it does an update and not a delete+install?

**Comment by manno** [comment]
The longhorn crd chart https://github.com/rancher/charts/raw/dev-v2.8/assets/longhorn-crd/longhorn-crd-102.3.0%2Bup1.5.1.tgz keeps the CRDs in the template folder, to add a customizable label.
I can't be sure the protection described in https://helm.sh/docs/topics/charts/#limitations-on-crds applies to CRDs in `template/`.

However, during [my experiment](https://github.com/manno/fleet-experiments/blob/main/crds/fleet.yaml) I could not observe any delete.

This report was generated for Rancher 2.6.5 (likely Fleet 0.3.9), so maybe this has been fixed.
There are several, fixed bugs which could have been involved in this:

* long or conflicting bundle names, which might uninstall and reinstall the bundle under a different name.
* a problem in the longhorn chart, like using a random value, which would trigger updates, but no deletes?
* old helm versions might have behaved different for templated CRDs

**Comment by kkaempf** [comment]
JIRA got rejectd
