### ISSUE TITLE
Fleet yaml parsing

### ISSUE THREAD

**Issue by boxboatmatt** [rancher/fleet#136]
Examples show `fleet.yaml` without a stream separator (`---`) at the top of the file. However, it seems that `fleet` does not properly parse a `fleet.yaml` without that separator. 

For example, if I create a fleet.yaml to put raw manifests in a namespace. like this:
```
defaultNamespace: foo
```
`fleet` will not honor that properly and the helm chart that is generated will be deployed to `default`

**Comment by kkaempf** [comment]
Workaround exists: Add stream separator.
