### ISSUE TITLE
Support more SSH key formats for GitRepos

### ISSUE THREAD

**Issue by izaac** [rancher/fleet#138]
While testing #134 I had to create a special SSH key using the following command:

`ssh-keygen -t rsa -b 4096 -m pem -C "izaac@email.com"`

As my usual SSH keys were problematic to GitRepo throwing this error:

`data does not contain a valid RSA or ECDSA private key`

Can we support more ssh keys formats?

**Comment by domhdp** [comment]
@izaac  I can't get SSH to work with Bitbucket repos.

What format should I be using for the SSH key? I have run the `ssh-keygen` command with the same format and parameters as your message above.

**Comment by travis-sobeck** [comment]
Any Progress on this?  I'm having the same issue.

**Comment by Martin-Weiss** [comment]
+1 - this issue caused some hours of troubleshooting before I could get the first deployment working. I believe we should have two fixes: 1. better documentation and 2. allow OpenSSH key support. Thanks!

**Comment by xenuser** [comment]
Thanks for sharing how to create a working key @izaac  ! I wished Rancher would have given me this information when creating a new fleet repo..

**Comment by nickgerace** [comment]
Closed by https://github.com/rancher/fleet/issues/221 being resolved

**Comment by lindhe** [comment]
@nickgerace This is still an issue! I'm running Rancher v2.7.6 and still have the same issue.

Neither `ssh-keygen -b 4096` nor `ssh-keygen -t ed25519` works.

The container `step-git-source` in `fleet-default/required-platform-applications-4e2d3-mjw8n` says:

> Load key \"/tekton/creds/.ssh/id_auth-gxdf5\": invalid format

![image](https://github.com/rancher/fleet/assets/7773090/fa3f6b07-5db0-4fd1-bebc-99c20aa2b59c)

**Comment by Dannymex420** [comment]
[]()
