### ISSUE TITLE
Move Workload between Namespaces (Q2)

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1390]
# Draft:

We want to keep deployments as the clusters moves to another workspace. CRD workloads should not be deleted.

Note:
* keepResources can be used for this.
* gitrepos can already be `paused: true`. This marks the resource as "out of sync". Possible in fleet.yaml, too. So this works on bundles.
* we can scale down the agent to 0 replicas, this would also stop status updates, but this has to work on bundles.

**Comment by raulcabello** [comment]
`keepResources` could be used to move workload between workspaces. This is how it currently works:
- All `GitRepos` **must** have `keepResources` set to true
- Move the `Cluster` to a different workspace
- `BundleDeployments` are deleted in the old workspace, but resources are kept.
- Delete `GitRepos` in old workspace
- Create same `GitRepos` in the new workspace. Resources are adopted. Resources stay in the same namespace in the downstream cluster.

This requires some manual work to move the `GitRepo` from the old workspace to the new one. Maybe this can be automated in Rancher?
Rancher UI needs to add the `keepResources` field for `GitRepos` and `Bundles`.

**Comment by sowmyav27** [comment]
@kkaempf Can you confirm the design doc for this enhancement

**Comment by raulcabello** [comment]
## QA Template
 
### Problem
There is no way to move a `Cluster` to a different workspace without deleting all resources.
 
### Solution
Use the [keepResources feature](https://github.com/rancher/fleet/issues/680) to move a `Cluster` to a different workspace without deleting all resources.
 
### Testing
Moving  a `Cluster` to a different workspace is just supported on rke. So an rke downstream cluster needs to be created.

This feature depends on the [keepResources flag](https://github.com/rancher/fleet/issues/680). `keepResources` is all we need for moving `Cluster` to a different workspace, there is no additional code added in this feature.

Steps:
- Set `keepResources` to true in all `GitRepos`, and wait until the `GitRepo` are `Ready` again and all `Bundles` have the `keepResources` set to true
- Move the `Cluster` to a different workspace
- Verify that `BundleDeployments` are deleted in the old workspace, but resources are kept.
- Delete `GitRepos` in old workspace
- Create same `GitRepos` in the new workspace. Verify that the `GitRepos` have all their resources, resources are not recreated and they stay in the same namespace in the downstream cluster.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|Create a Git Repo that has resource handling enabled with a provisioned RKE1 node driver cluster selected, move cluster to a different workspace and validate resources are not removed
|2|Create a Git Repo that has resource handling disabled with a provisioned RKE1 node driver cluster selected, move cluster to a different workspace and validate resources are removed

**Comment by markusewalker** [comment]
Validated that this against Fleet version `v0.7.0-rc.2`, Rancher `v2.7-head` https://github.com/rancher/rancher/commit/2efc8340e83d8f21bb0553f13e65e2b25a45821d. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/2efc8340e83d8f21bb0553f13e65e2b25a45821d
- Fleet version: `v0.7.0-rc.2`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|Create a Git Repo that has resource handling enabled with a provisioned RKE1 node driver cluster selected, move cluster to a different workspace and validate resources are not removed|:white_check_mark:|
|2|Create a Git Repo that has resource handling disabled with a provisioned RKE1 node driver cluster selected, move cluster to a different workspace and validate resources are removed|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As an admin user, provisioned a downstream RKE1 v1.25.9 node driver cluster.
2. Navigated to Continuous Delivery.
3. Created a new workspace named `new-workspace`.
4. Navigated to Git Repos and validated that there is now a `Resource Handling` section that allows resources to be kept after deletion:
![image](https://user-images.githubusercontent.com/52591819/236071715-0b01dc65-93f7-4158-ba03-b58d5f52d2e9.png)
5. Created a Git Repo with resource handling enabled and my RKE1 cluster selected:
![image](https://user-images.githubusercontent.com/52591819/236071727-7b6af284-9855-49d2-bc3a-284d7a16fcc8.png)
     - Validated in the network traffic that `keepResources: true`, as expected.
6. Moved the RKE1 downstream cluster from `fleet-default` workspace to `new-workspace`.
7. Validated that resources have been retained in the `fleet-default` namespace.
8. Deleted the old Git Repo in the `fleet-default` namespace now that the cluster has been moved to `new-workspace`.
9. Created same Git Repo in the `new-workspace` and validated resources were not recreated and all resources are in the Git Repo.
__________
**Scenario 2**
1. Repeated scenario 1 steps 1-4.
2. Created a Git Repo with resource handling disabled and my RKE1 cluster selected.
3. Repeated scenario 1 steps 6-9, but validated the following points:
     - All resources were deleted and not retained after moving the cluster to the `new-workspace`.
     - Creating same Git Repo in the `new-workspace` results in new resources being created as there are no retained resources to used; this is expected.
