### ISSUE TITLE
Clean Up: Replace fleet-examples in e2e Tests

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1391]
The e2e tests initially used the fleet-examples. However there is some overlap between the tests and the deployments are quite big.

* Simplify e2e tests for PR validation
* Use a separate repo for test data (not fleet-examples, which is used for docs)
* Create scheduled acceptance tests to make sure fleet-examples are working (actually check the services?)

**Comment by sowmyav27** [comment]
@manno does this need any QA validations?

**Comment by manno** [comment]
@sowmyav27 no this doesn't need QA.
