### ISSUE TITLE
[Epic] Agent Config for Tolerations/Affinity/Resources per Cluster (Q2)

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1392]
We want to make affinity and resource limits for the fleet agent configurable per cluster. 

- [x] extend structs, crds
- [x] update cluster controller to redeploy agents if one of the fields, "agentTolerations", "agentAffinity" and "agentResources", changes.

- [x] rancher/fleet#1445
- [x] rancher/fleet#1446
- [x] rancher/fleet#1447

**Comment by sowmyav27** [comment]
Need info/design doc for determining QA LOE

**Comment by sowmyav27** [comment]
@kkaempf Need info/design doc for determining QA LOE

**Comment by kkaempf** [comment]
QA is done for the sub-issues.
