### ISSUE TITLE
Overlay-resource only deployed to 1 cluster due to clusterName selector

### ISSUE THREAD

**Issue by strowi** [rancher/fleet#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

i have scoured the docs and  tried debugging for a couple of hours now, but couldn't find anything explaining this issue.
I have a fleet-repsitory containg bare-yaml + overlays. The overlays all contain a secret with the same file- and kubernetes-name/metadata but different content.

Now it seems that the secret gets deployed only to a single cluster (which ever  is first i guess).

PS: I have a similiar behaviour when using kustomize overlays.

### Expected Behavior

I would expect that each secret gets deployed to the matching cluster.

### Steps To Reproduce

I created a demo-repo at https://gitlab.com/strowi/fleet-test/-/tree/master/test .

1. Create 2+ clusters
2. Create an  overlay for each of the cluster containing the same secret with same name, but different data.
3. deploy the bundle
4. see that the secret gets only deployed to 1 cluster.

### Environment

```markdown
- Fleet Version: rancher-2.7.1
- Cluster:
  - Provider: k3s
  - Kubernetes Version: 1.24.10
```

**Comment by strowi** [comment]
Further tests show it seems to be working when i  use the following matchLabels instead of `clusterName`.

```yaml
targetCustomizations:
- name: c0530
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: test-cluster-0530
  yaml:
    overlays:
      - cluster-0530
- name: c0531
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: test-cluster-0531
  yaml:
    overlays:
      - cluster-0531
```

Is there some limitation to the clustername?  (ours are named 'abcd-efgh-4digits' which i didn't reflect in the first example)

**Comment by strowi** [comment]
Okay after some sleep i feel a bit  "un-smart" ...  This is the correct way to use the clusterName:

```
targetCustomizations:
- name: cluster-0533
  clusterSelector:
    clusterName: cluster-0533
```

Which would make the documentation wrong:
![image](https://user-images.githubusercontent.com/589662/224933028-a2e9ed23-07d7-4839-92f9-d62d7fbce7cb.png)

**Comment by kkaempf** [comment]
internal ref SURE-6499

**Comment by manno** [comment]
> replacing the clusterName kafka with the clusterID c-xyz seems to work.

It seems there is no bug then and we can close this?

Rancher has three different cluster resources:

* clusters.management.cattle.io
* clusters.provisioning.cattle.io
* clusters.fleet.cattle.io

The management cluster is not namespaced and has a random name. Fleet will only match the fleet cluster name, which should be the same as the provisioning cluster name.

I find it strange that Rancher's `dashboard/c/local/explorer/provisioning.cattle.io.cluster` shows you the provisioning clusters, but when you click "View YAML", you are presented with the management cluster's YAML. 

Anyhow, Fleet will only use the clusters from `dashboard/c/local/explorer/fleet.cattle.io.cluster`, which is what `/dashboard/c/_/fleet/fleet.cattle.io.cluster` shows.

**Comment by strowi** [comment]
Thx for checking! 

I created a couple of clusters via rancher-ui and named them "abcd", "efgh" .

Now when i check on the management cluster, i get the following - some names are correct some have a unique `c-$hash` ?

```bash
~< kg clusters.fleet.cattle.io --all-namespaces                                                                                                                                                                        (rancher:cattle-system)
NAMESPACE       NAME      BUNDLES-READY   NODES-READY   SAMPLE-NODE                        LAST-SEEN              STATUS
fleet-default   c-76kfg   0/1             1/1           xyz               2023-04-26T09:13:46Z   
fleet-default   c-ftczs   14/14           3/3           xyz   2023-07-18T12:07:38Z   
fleet-default   c-hg6jv   12/12           4/4           xyz       2023-07-18T12:00:10Z   
fleet-default   c-rczdc   11/11           4/4           xyz        2023-07-18T12:05:45Z   
fleet-default   abcd   12/12           1/1           xyz     2023-07-18T12:03:45Z   
```

So this gives very inconsistent and confusing results when using a targetMatch on `clusterName`. 

Thinking about it. this sounds a bit more of a rancher problem instead of fleet?

( On top of that i probably got confused between the `clusters.management` and `clusters.fleet`.. )

**Comment by manno** [comment]
The Rancher UI is definitely confusing with the three types of clusters, but it does seem to do the right thing when I target a cluster.

And there is no UI for customization, I can add something to the Fleet docs to warn users about picking the right cluster name.

**Comment by strowi** [comment]
A note would be good, because the fleet-clusterName is nowhere visible in the rancher-ui (except when hovering the links).

So using "clusterName" in fleet in rancher is no useable because the name can be random. Guess i should open another issue in rancher/rancher then?

**Comment by manno** [comment]
Not sure, I think the fleet cluster name is actually visible in most pages in Rancher. I'm using 2.7.5, though.

**Comment by manno** [comment]
Oh, but from your example `name: c-rczdc` should *not* work as selector. `stagingk8s` and `kafka` should work. 

That's what I meant earlier, it's very confusing that Rancher shows you the `apiVersion: management.cattle.io/v3` YAML for clusters. But, well it's "Rancher" clusters, as opposed to "Continuous Delivery" clusters.

**Comment by strowi** [comment]
Sorry if i didn't make it clearer, i guess at some point everyone is just left confused...

In my example above, `kafka` is the name i gave the new cluster, when creating it via the Rancher-UI. And that is displayed (everywhere) in "Rancher" and the "Continuous Integration"-part.

But in the back rancher created a `clusters.management.cattle.io`-resource with name: `c-...`.
And this is what is used for fleet, also just in the back, while dispaying `spec.displayName`of `kafka` in the Rancher-UI (except the `view Yaml` which shows the kubernetes-resource.)

On the UI everything seems to work fine, but if i try a `targetCustomization` or other selector using `clusterName`, i have to use the `c-...` instead of the everywhere displayed Rancher-Name of the Cluster.

Hence why i tried clarifying  when creating a new cluster `kafka` - `clusters.managment.cattle.io` contains:

- `metadata.name: c-....`   (displayed nowhere in Rancher-UI) 
- vs. `spec.name kafka` (contains the Name displayed in Rancher-UI and everywhere, but doesn't work for matching `clusterName`).


If you create clusters via UI, and create the fleet.yaml via code - naturally you would use `clusterName: kafka` which is wrong.
If you ignore Rancher-UI completely and have access to it's kubernetes-api, you will see the correct `c-...` names.

And i just noticed: If you EDIT a GitRepo via Ranchers `Continous-Integration` changing the `Target` to `kafka`  it will use `c-...` for the yaml.

So i am not sure, but would say rancher is creating the confusion (definitely) and bug (?) by displaying a different Name than is being used in the back for the kubernetes-resources and fleet.


Hope i could make it clearer this time, otherwise i'm also happy to have a direct chat about it. ;)

**Comment by manno** [comment]
Thanks for describing the problem again :)

> But in the back rancher created a clusters.management.cattle.io-resource with name: c-....
And this is what is used for fleet, also just in the back, while dispaying spec.displayNameof kafka in the Rancher-UI (except the view Yaml which shows the kubernetes-resource.)
> On the UI everything seems to work fine, but if i try a targetCustomization or other selector using clusterName, i have to use the c-... instead of the everywhere displayed Rancher-Name of the Cluster.

Yes, Rancher creates a management cluster and syncs it with fleet and provisioning cluster resources.
However Fleet doesn't even know the management cluster CRD. It should always use the `clusters.fleet.cattle.io` resource and can only match against that name.

> If you ignore Rancher-UI completely and have access to it's kubernetes-api, you will see the correct c-... names.

`kubectl get clusters.fleet.cattle.io -A` should show you the usable names.

> And i just noticed: If you EDIT a GitRepo via Ranchers Continous-Integration changing the Target to kafka it will use c-... for the yaml.

That would be a UI bug.

> So i am not sure, but would say rancher is creating the confusion (definitely) and bug (?) by displaying a different Name than is being used in the back for the kubernetes-resources and fleet.

Yes, the three cluster resources are confusing, but well, it's for historic reasons.

**Comment by strowi** [comment]
Thx for being untiring. ;)

I understand that on the fleet-part everything works as intended (after the initial irritation and hour-long debugging of the initial problem).

I just want to stress on the rancher-ui part, that it is very weird and not really user-friendly if the UI displays name 'kafka' consistently, but fleet uses a non-visible (except clicking through the cluster -> view yaml) different "name" 'c-...'.
(as mentioned, this probably belongs more in rancher/rancher than here at this point).

Otherwise i now know to use:

```yaml
clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: kafka
...
```

to not run into this problem. ;)

**Comment by manno** [comment]
Should I leave this open for now, as a reference for possible UI enhancements? I think there is nothing to do on the fleet side (for now).

**Comment by manno** [comment]
Closing this until work is needed from fleet :)
