### ISSUE TITLE
BundleNamespaceMapping ignoring bundle selector

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1427]
A BundleNamespaceMapping can be limited to certain  bundles by using a  BundleSelector. Only bundles with the label should be deployed to the mapped clusters.  (https://fleet.rancher.io/namespaces#cross-namespace-deployments)

However, fleet ignores the configured bundle selector and always matches.
 
Originally reported in https://github.com/rancher/fleet/pull/1401

**Comment by manno** [comment]
Probably doesn't need separate QA as it's a bug in one of the "multi user" resources? I added a test and future QA on the whole multi user feature would notice a regression if "bundle selectors" are used in a  "bundle namespace mapping".

**Comment by sowmyav27** [comment]
@kkaempf If this issue doesn't need QA, can you pls add `QA/None` label?

**Comment by kkaempf** [comment]
Closing per last comments.
