### ISSUE TITLE
Helm charts with external schema references do not work in air-gapped environment

### ISSUE THREAD

**Issue by xgcssch** [rancher/fleet#1430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deploying charts which contain a `values.schema.json` file, which in turn contains references to external schemata fails in airgapped environments with messages like
```
Message:           ErrApplied(1) [Cluster fleet-local/local: values don't meet the specifications of the schema(s) in the following chart(s):
nginx-ingress:
Get "https://raw.githubusercontent.com/nginxinc/kubernetes-json-schema/master/v1.26.1/_definitions.json": dial tcp 185.199.109.133:443: i/o timeout]
```
One notable chart is [nginx-ingress](https://github.com/nginxinc/kubernetes-ingress).

This external reference can be found [here](https://github.com/nginxinc/kubernetes-ingress/blob/3db26cbe98e94f8ad7110d292a11fe9eb0464ca7/deployments/helm-chart/values.schema.json#L49) in this chart:
```
"$ref": "https://raw.githubusercontent.com/nginxinc/kubernetes-json-schema/master/v1.26.1/_definitions.json#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta/properties/annotations"
```

Fleet seems to validate the schema and therefor tries to resolve the external references.

As we are running air-gapped this fails.

### Expected Behavior

As i can't see an easy way to proxy the referenced requests to local accessible versions i would like to see an switch in `fleet.yaml` to  prevent fleet from validating the scheme before submitting it to helm.

### Steps To Reproduce

```fleet.yaml
defaultNamespace: nginx
helm:
  chart: nginx-ingress
  repo: https://ourcompanyproxy.com/repository/helm-p-nginx/
  releaseName: nginx
  values:
    controller:
      image:
        repository: ourcompanyproxy.com:5102/nginx/nginx-ingress
```
in an air-gapped environment should reproduce the problem

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.6.0rc1
- Cluster:
  - Kubernetes Version: v1.22.17
```

**Comment by manno** [comment]
Maybe fixable by #1332

**Comment by xgcssch** [comment]
Thanks!
