### ISSUE TITLE
[SURE-5776] Allow dependsOn to target GitRepos of other namespaces

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1435]
[SURE-5776]
#### Request description:
We would like to be able to use the dependsOn field on the fleet.yaml of a Repository object to target Bundles which are in another namespaces.

#### Actual behavior:

Fleet already offers the possibility to use the dependsOn keyword to create a dependency to another Bundle, which we've been using already. Unfortunately, we can't create a dependency between a Bundle in the fleet-local namespace and one in the fleet-default namespace.

Moving the Bundles would be difficult; the fleet cluster resource for the upstream rancher cluster is per default created in the fleet-local namespace. This separation is meaningful in our case, and we would like to keep it this way, even if it can be modified.

#### Expected behavior:
To be possible to create dependencies between bundles of different namespaces.

#### Workaround:
Is workararound available and implemented? no
What is the workaround:

**Comment by manno** [comment]
This is more complicated, we need to move the depends on logic into the controller. We can't give the fleet-agents access to all the bundledeployments, as that would allow them to look at resources deployed into other clusters.

**Comment by manno** [comment]
Moving the dependsOn code into the controller is a lot of work and complicated with regards to performance. We're postponing this feature.
