### ISSUE TITLE
Rancher Fleet bundle dependencies support for repo's having names starting with similar patterns. 

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1436]
[SURE-5156]

#### Usecase
For bundle dependencies to work well when multiple gitrepos are declared with a name that includes a similar naming convention like "monitoring-". When the same name is used with different gitrepo's the bundle dependency does not work.

Example: If the customer is deploying the monitoring chart with Fleet, they would want to have the ability to declare dependency between crd bundle and the monitoring one so that the CRDs are installed first.

The dependency should be independent of that bundle name as having the same name for different bundles does not help in installing the chart correctly. 

#### Request description:
Ways to set up bundle dependencies with different gitrepos having similar naming patters like "monitoring-" and having independent bundle names. so the bundle dependency should not include the git repo name, so we can use the same code with different gitrepos

#### Actual behavior:
When bundle dependencies are implemented with different gitrepo's having a different name, we have to hardcode dependency and create different repos with the same codebase just by changing the dependency name. The first part of the dependency name includes the gitrepo name. So we can't use the same codebase for different fleet git repos.

#### Expected behavior:
Setup one repo git repo which can be used with any name, not the name described in the dependency name.

#### Workaround:
Is workaround available and implemented? yes/no
What is the workaround:
Create multiple Github repos with fleet git repo name hardcoded .

**Comment by manno** [comment]
Maybe this happened, because of incorrectly shortened long bundle names?

**Comment by manno** [comment]
Cleaning up the backlog.
