### ISSUE TITLE
Name is ambiguous in Swedish

### ISSUE THREAD

**Issue by SimonAlling** [rancher/fleet#1453]
In spoken Swedish, "with Fleet" is indistinguishable from ["on purpose"](https://en.wiktionary.org/wiki/med_flit), giving rise to ambiguity in sentences like "Did we deploy it with Fleet?"

**Comment by SimonAlling** [comment]
> Well, interesting. What should we do about it ?

Seems like we have to rename the application or patch the Swedish language! 😵

**Comment by wrkode** [comment]
Suggesting closing this issue as unthinkably complex to solve with modern technologies. 🥇

**Comment by manno** [comment]
If you're using Fleet in Rancher, you can say "Continuous Delivery"
