### ISSUE TITLE
Instance of CRDs stays missing in Bundle

### ISSUE THREAD

**Issue by ma-ble** [rancher/fleet#1460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I put a self-created kubevirt chart in the /var/lib/rancher/k3s/server/static/charts (tgz) folder and the manifest in the manfiest folder. When you start k3s, the Helm Chart and CRDs install successfully.

In a next step, I would now like to gain control of the installed Helm chart using fleet. For this I deployed the same Helm chart (without CRDs) in a git repository and connected it to Rancher. All resources up to and including the kubeVirt resource (Kind: KubeVirt) can be successfully installed.

The kubevirt resource looks like this:

```
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: []
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
```

The necessary crds are installed in the k3s.

```
> kubectl get crds | grep kubevirt
kubevirts.kubevirt.io                                         2023-04-03T13:06:52Z
virtualmachineinstances.kubevirt.io                           2023-04-03T13:08:54Z
virtualmachineinstancepresets.kubevirt.io                     2023-04-03T13:08:54Z
virtualmachineinstancereplicasets.kubevirt.io                 2023-04-03T13:08:54Z
```

The following error messages appear both in the log of the Fleet agent and in the Rancher's GUI.

```
> kubectl logs fleet-agent-7d4b6456fd-2694d -n cattle-fleet-system
time="2023-04-03T14:02:56Z" level=info msg="getting history for release kubevirt-kubevirt-operator"
W0403 14:03:56.461317       1 reflector.go:442] pkg/mod/github.com/rancher/client-go@v0.24.0-fleet1/tools/cache/reflector.go:167: watch of *v1alpha1.BundleDeployment ended with: an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 413; INTERNAL_ERROR; received from peer") has prevented the request from succeeding
time="2023-04-03T14:04:04Z" level=info msg="getting history for release fleet-agent-andreas-labrechner"
time="2023-04-03T14:04:04Z" level=info msg="getting history for release kubevirt-kubevirt-operator"
time="2023-04-03T14:04:04Z" level=info msg="getting history for release fleet-agent-andreas-labrechner"
time="2023-04-03T14:04:04Z" level=info msg="getting history for release kubevirt-kubevirt-operator"
time="2023-04-03T14:04:04Z" level=info msg="getting history for release fleet-agent-andreas-labrechner"
time="2023-04-03T14:04:04Z" level=error msg="bundle kubevirt-kubevirt-operator: kubevirt.kubevirt.io kubevirt/kubevirt missing"
time="2023-04-03T14:04:04Z" level=info msg="getting history for release kubevirt-kubevirt-operator"
```

### Expected Behavior

I can update all resources using fleet - including the kubevirt resource.

### Steps To Reproduce

1. Install kubeVirt CRDs and kubevirt-operator per kubectl or helm-operator: kubevirt-operator.yaml | kubevirt-cr.yaml - [kubevirt v0.59.0 release manifests](https://github.com/kubevirt/kubevirt/releases/download/v0.59.0/kubevirt-operator.yaml)
3. Check that kubeVirt is running as expected 
4. Setup GitRepo Resource in Rancher to update kubevirt-operator (without CRDs)

### Environment

```markdown
- Architecture: x86
- Fleet Version: v0.5.1
- Cluster:
  - Provider: k3s
  - Options:
  - Kubernetes Version: v1.26.1
```

### Anything else?

![kubevirt_fleet](https://user-images.githubusercontent.com/95223860/229538149-e1c45596-c0c1-4022-8845-fb6125874ecb.png)

**Comment by manno** [comment]
Might be fixed by https://github.com/rancher/fleet/pull/1201

**Comment by manno** [comment]
Moving to blocked till we get confirmation this is still an issue in 0.7

**Comment by sbulage** [comment]
Followed this [comment](https://github.com/rancher/fleet/pull/1201#issuecomment-1387102755) and with cert-manager it works as expected.
