### ISSUE TITLE
[BUG] Unable to add annotations to Kubernetes namespaces

### ISSUE THREAD

**Issue by spkane** [rancher/fleet#1461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are using Fleet to install the [KUMA helm chart](https://github.com/kumahq/charts), but we need to add some Kubernetes annotations to the namespace, so we are also configuring Fleet to use Kustomize to make some additional tweaks, including adding the namespace annotations.

```yaml
scheduler.alpha.kubernetes.io/node-selector: agentpool=system
scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator": "Exists", "key": "CriticalAddonsOnly"}]' 
```

- See: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podtolerationrestriction

Although the Kustomize/Helm setup is perfectly fine, the fact that Kustomize is attempting the alter the namespace causes Fleet to fail the installation.

### Expected Behavior

There should be an officially supported way to handle the use-case where additional annotations and labels need to be added to a namespace, which can be achieved using Kustomize and without forking the underlying Helm chart, or by feeding Fleet the required labels/annotations and letting it inject them into the namespace that it creates. 

### Steps To Reproduce

1. Register a cluster with fleet.
2. Use fleet to install a bundle from a repo that uses a Helm chart and has Kustomize configured to add some annotations to the namespace for that Helm chart. 

### Environment

```markdown
- Architecture: amd64
- Fleet Version: Rancher 2.6.9
- Cluster:
  - Provider: AKS
  - Options:
  - Kubernetes Version: 1.24.6
```

### Anything else?

Related (closed) issue: https://github.com/rancher/fleet/issues/285

**Comment by manno** [comment]
See also #1484

**Comment by manno** [comment]
We added a mechanism to provide labels and annotations for the "defaultNamespace" in https://github.com/rancher/fleet/issues/1553

We also have reports that a kustomize overlay can modify the `defaultNamespace`, e.g. https://github.com/manno/fleet-experiments/commit/e1e833526f44ec184dc3759b5934e77bdc835251 however it does not work when a helm chart is involved.

**Comment by manno** [comment]
I believe this is fixed by https://github.com/rancher/fleet/issues/1553
