### ISSUE TITLE
Document fleet command-line client including 'fleet test' 

### ISSUE THREAD

**Issue by ron1** [rancher/fleet#147]
The fleet command-line client documentation was removed as part of the v0.3.0 release. In particular, the fleet test command documented [here](https://github.com/rancher/fleet/blob/v0.2.0/docs/cli.md#fleet-test-bundle_dir) in the v0.2.0 release is essential for testing fleet-based deployments.

**Comment by kkaempf** [comment]
`fleet test -h` provides documentation.
