### ISSUE TITLE
No local cluster in dashboard UI after migrating to fleet-default workspace

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1489]
### Issue description:

No local cluster in dashboard UI after migrating to fleet-default workspace

### Repro steps:

Follow this procedure: https://fleet.rancher.io/troubleshooting/#migrate-the-local-cluster-to-the-fleet-default-cluster :

Continuous Delivery -> Clusters
Select Local cluster -> Click on "Change Workspace" below tab
Assign Cluster to fleet-default. The cluster disappears from the Rancher UI and no longer exists.

Note: The customer said they experienced this bug after performing an upgrade from Rancher 2.6.5 to 2.6.8. They also updated rke from 1.3.11 to 1.3.13. Other customers didn't perform any update.

I also found this message on the logs:

[ERROR] error syncing ‘local’: handler provisioning-cluster-create: failed to create fleet-default/local [provisioning.cattle.io/v1](http://provisioning.cattle.io/v1), Kind=Cluster for provisioning-cluster-create local: admission webhook “[rancherauth.cattle.io](http://rancherauth.cattle.io/)” denied the requeset: cluster name must be 63 characters or fewer, cannot be “local” nor of the form “c-xxxxx”, requeuing

### Workaround:
Is workararound available and implemented? yes
What is the workaround: the local cluster can still be reached by navigating to the /dashboard/c/local endpoint.

### Actual behavior:

The local cluster will no longer appear in the /dashboard/home nor under EXPLORE CLUSTER in the ☰ menu.

### Expected behavior:
The local cluster should always appear in the /dashboard/home page, and under EXPLORE CLUSTER in the ☰ menu

Additional notes:
This GitHub issue is related: https://github.com/rancher/rancher/issues/39202

**Comment by kkaempf** [comment]
[UI team reviewed](https://github.com/rancher/dashboard/issues/7745) and believes it's a backend bug:

> Confirmed this is a bug - cluster vanishes if you move it to the `fleet-default` workspace.
> This is a backend bug - the API to fetch fleet clusters returns an empty set after doing the move.

**Comment by manno** [comment]
I don't think it's possible to move the local cluster, without side effects, until https://github.com/rancher/fleet/issues/1365 is solved. I'm afraid the fleet-controller would just duplicate the local cluster, when the pod restarts.

**Comment by stefanlasiewski** [comment]
> I don't think it's possible to move the local cluster, without side effects, until https://github.com/rancher/fleet/issues/1365 is solved.

Moving the local cluster is actually in the FAQ at https://fleet.rancher.io/troubleshooting#migrate-the-local-cluster-to-the-fleet-default-cluster . If it's not supported at the moment, it should be removed from the FAQ.

I'm a user and was considering doing this.

**Comment by manno** [comment]
Indeed, I hope we can fix this for the next release. There is also a warning against moving the cluster in https://fleet.rancher.io/gitrepo-content#proper-namespace 🤷

**Comment by manno** [comment]
<p>I looked into resources installed on 2.7.5 and came up with this table, which might be helpful when checking for missing resources after a failed cluster move:</p>

<p> </p>
<div class="table-wrap">


Type | Name | Namespace
-- | -- | --
From Helm, intial setup: |   |  
ClusterRole | fleet-controller | -
ClusterRole | gitjob | -
ClusterRoleBinding | fleet-controller | -
ClusterRoleBinding | gitjob-binding | -
ConfigMap | fleet-controller | cattle-fleet-system
Deployment | fleet-controller | cattle-fleet-system
Deployment | gitjob | cattle-fleet-system
Role | fleet-controller | cattle-fleet-system
Role | gitjob | cattle-fleet-system
RoleBinding | fleet-controller | cattle-fleet-system
RoleBinding | gitjob | cattle-fleet-system
Service | gitjob | cattle-fleet-system
ServiceAccount | fleet-controller | cattle-fleet-system
ServiceAccount | gitjob | cattle-fleet-system
Generated: |   |  
Cluster clusters.fleet.cattle.io | local | fleet-local
clusters.provisioning.cattle.io | local | fleet-local
clusters.management.cattle.io | local | -
ClusterGroup | default | fleet-local
Bundle | fleet-agent-local | fleet-local
For each registered cluster: |   |  
clusters.provisioning.cattle.io |   | by default fleet-default
clusters.management.cattle.io |   | -
clusters.fleet.cattle.io |   | fleet-default
Bundle |   | fleet-default


</div>


<p>There is also a dynamically created "cluster namespace", like 
"cluster-fleet-local-local-1a3d67d0a899", which contains the 
bundledeployment resources. And a "system registration namespace", like 
"cattle-fleet-clusters-system", which is used during registration of the
 cluster.</p>

<p> </p>

<p>See <a href="https://fleet.rancher.io/namespaces#special-namespaces" class="external-link" target="_blank" rel="nofollow noopener">https://fleet.rancher.io/namespaces#special-namespaces</a> for more information on namespaces and resources, like those created during the registration of clusters.</p>
