### ISSUE TITLE
Unify git implementations

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1504]
Fleet currently has (resp. uses) three different implementations of the `git` protocol.
This should be unified.

Git usage in Fleet:

* git shell-out in gitjob for ls remote
* tekton git-init in gitjob's job to clone repo
* go-git in fleet-controller's imagescan
* (go-git in e2e test)

Tasks:
- [x] replace the shell-out in Gitjob with go-git
- [x] replace tekton's git-init
- [ ] ~~maybe: extract imagescan git usage  into module~~
- [x] add more tests around git 
- [x] manually(?) test with bitbucket, github, ...
- [x] works with personal access token, https, ssh, ...

**Comment by weyfonk** [comment]
`git-init` code has been [removed](https://github.com/tektoncd/pipeline/releases/tag/v0.47.0) from tektoncd/pipeline in v0.47.0. There are [plans](https://github.com/tektoncd-catalog/git-clone/issues/2) to move it to a new repo, but migration has not yet happened.

**Comment by manno** [comment]
> `git-init` code has been [removed](https://github.com/tektoncd/pipeline/releases/tag/v0.47.0) from tektoncd/pipeline in v0.47.0. There are [plans](https://github.com/tektoncd-catalog/git-clone/issues/2) to move it to a new repo, but migration has not yet happened.

We only use [`git-init`](https://github.com/rancher/gitjob/blob/89708adf7fe2e076e8a68f0a887f37c33f485684/pkg/controller/gitjob/gitjobs.go#L303) and [`entrypoint`](https://github.com/rancher/gitjob/blob/89708adf7fe2e076e8a68f0a887f37c33f485684/pkg/controller/gitjob/gitjobs.go#L260) from tekton  [scripts/build](https://github.com/rancher/build-tekton/blob/master/scripts/build#L12-L13).

I wonder if we need `entrypoint`: 
> This binary is used to override the entrypoint of a container by wrapping it and executing original entrypoint command in a subprocess.
> Tekton uses this to make sure TaskRuns' steps are executed in order, only after sidecars are ready and previous steps have completed successfully.
(https://github.com/tektoncd/pipeline/tree/main/cmd/entrypoint)

And [git-init](https://github.com/tektoncd/pipeline/blob/v0.41.2/pkg/git/git.go#L75) is just another shell-out to the git binary.

**Comment by manno** [comment]
This story could fix https://github.com/rancher/fleet/issues/1402

**Comment by ywluogg** [comment]
Hi there I'm from Tekton world - I'm trying to pick up the work to migrate git-init into git-clone task mentioned in https://github.com/tektoncd-catalog/git-clone/issues/2 Since this is linked under that issue, I'm just curious in general is there a particular reason the GitOps job needs to use git-init?

**Comment by raulcabello** [comment]
# QA Template

## Solution
Unify git implementations. Use go-git for everything, which means git shell out, and tekto dependencies have been removed.

## Testing
Fleet should keep working as usual. No new functionality has been added in this story. Most of the code that interacts with git has been changed, therefore we need to assure it keeps working as before.
Things to test:
- GitRepo with public repository should be successfully deployed.
- GitRepo with https private repository.
- GitRepo with ssh private repository.
- Fleet keep watching the git repo. Changes in the git repository are reflected in fleet. 
- Git Webhooks
- Upgrade from previous version of fleet

## Additional info

I have done manual tests with Github, and we use gogs in the integration tests. It would be great to do some testing with other git providers such as bitbucket, gitlab, ...

**Comment by sbulage** [comment]
@raulcabello is this not available in the latest Fleet RC?
What is task 3 meaning ?

**Comment by raulcabello** [comment]
@sbulage yes it is available in v0.9.0-rc3. 
task 3 was not needed/implemented

**Comment by sbulage** [comment]
For this git implementations testing, used below entities.

System Information:
- Rancher version: 2.8.0-alpha1
- Fleet version: 0.9.0-rc3
- Upgrade scenario:
   - Rancher version used: 2.7.6 and 2.7.7
   - Fleet version: 0.7.1 and 0.8.0


Following things need to test:

- [ ] `GitRepo` with public repository should be successfully deployed.
- [ ] `GitRepo` with private repository with http credentials.
- [ ] Proxy should work https://github.com/rancher/fleet/blame/v0.9.0-rc.3/charts/fleet/charts/gitjob/values.yaml#L9-L11

**Comment by sbulage** [comment]
Tested private repositories from `Bitbucket`, `GitLab` and `GitHub` and it worked well.

**System Information:**
- Rancher Version: `2.8-head`
- Fleet Version: `0.9.0-rc.5`
- Installed Gitjob version: `0.1.96`

All git related operations are happened without any error/warning in respective pods.(fleet-agent, fleet-controller, gitjob etc.)

Other P0 tests are performed around latest version of fleet(`0.9.0-rc.5`).

See below screenshot:
![Selection_113](https://github.com/rancher/fleet/assets/12134754/ef097881-a09e-4816-a24a-d3c76f8f7e65)

**Comment by Littlericket** [comment]
@sbulage it should also be tested using a outgoing http proxy, since this has not been migrated over to go-git.
https://github.com/rancher/gitjob/issues/348

**Comment by sbulage** [comment]
@Littlericket I have tested the http-proxy while testing this issue and I don't find any issue. I see all connections are happening through the proxy server which I had configured.

I will double check issue rancher/gitjob#348.

**Comment by Littlericket** [comment]
@sbulage, thanks for looking into it again!
This may indeed work for fleet itself, but its not getting inherited to the generated job. The job is missing the environment variables (which may be set on fleet) and therefore is not communicating / cloning through the proxy (especially gitcloner-initializer).
For the tekton release, the generated job has the environment variables set by getting appended by the mentioned code line in https://github.com/rancher/gitjob/pull/302/files#diff-d8502e4f5b09fbcbcb9b11e66e4e2d72c33d0b70b2def399245866b80fc9d975L272

If you saw some requests on the proxy, it can be only ones that have been requested by fleet itself.
