### ISSUE TITLE
Periodically deleting bundles because of "unknown bundle ID" even though they look identical

### ISSUE THREAD

**Issue by snovak7** [rancher/fleet#1511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From watching logs I finally found the pattern that resource (deployment) is periodically re-created

The interval is random, but consistently around 20-30 minutes

### Expected Behavior

Resources are not re-created

### Steps To Reproduce

I don't know what steps are to reproduce

I do have multiple GitRepos with same Repo, but different "paths"
The image has Umbraco CMS

### Environment

```markdown
- Architecture: Linux amd64
- Fleet Version: 0.3.9 - 0.6.0
- Cluster:
  - Provider: RKE2
  - Options:
    - Management Cluster: 1 node, NFS storage class, no LB (hostport)
    - Development Cluster: 4 nodes, NFS storage class, no LB (hostport)
  - Kubernetes Version: 1.24.8
```

### Logs

```markdown
time="2023-05-07T17:06:31Z" level=info msg="Deleting unknown bundle ID gl-konstanta-ops-k8s-sites-viaint-si-viaint-si--ff6e8, release via-international/gl-konstanta-ops-k8s-sites-viaint-si-viaint-si-ff6e8, expecting release via-international/gl-konstanta-ops-k8s-sites-viaint-si-viaint-si--ff6e8"
time="2023-05-07T17:06:31Z" level=info msg="uninstall: Deleting gl-konstanta-ops-k8s-sites-viaint-si-viaint-si-ff6e8"
time="2023-05-07T17:06:31Z" level=info msg="getting history for release gl-konstanta-ops-k8s-sites-viaint-si-viaint-si-ff6e8"
time="2023-05-07T17:06:31Z" level=info msg="purge requested for gl-konstanta-ops-k8s-sites-viaint-si-viaint-si-ff6e8"
time="2023-05-07T17:06:31Z" level=info msg="getting history for release gl-konstanta-ops-k8s-sites-viaint-si-viaint-si-ff6e8"
time="2023-05-07T17:06:31Z" level=info msg="Deleting orphan bundle ID rke2, release kube-system/rke2-canal"
time="2023-05-07T17:06:32Z" level=info msg="getting history for release gl-konstanta-ops-k8s-sites-viaint-si-viaint-si-ff6e8"
time="2023-05-07T17:06:32Z" level=info msg="getting history for release gl-konstanta-ops-k8s-sites-viaint-si-viaint-si-ff6e8"
time="2023-05-07T17:06:32Z" level=info msg="getting history for release gl-konstanta-ops-k8s-sites-viaint-si-viaint-si-ff6e8"
time="2023-05-07T17:06:32Z" level=info msg="Helm: Installing gl-konstanta-ops-k8s-sites-viaint-si-viaint-si--ff6e8"
time="2023-05-07T17:06:33Z" level=info msg="getting history for release gl-konstanta-ops-k8s-sites-viaint-si-viaint-si-ff6e8"
time="2023-05-07T17:06:33Z" level=info msg="getting history for release gl-konstanta-ops-k8s-sites-viaint-si-viaint-si-ff6e8"
time="2023-05-07T17:06:33Z" level=error msg="bundle gl-konstanta-ops-k8s-sites-viaint-si-viaint-si--ff6e8: deployment.apps via-international/website [progressing] Deployment does not have minimum availability., Available: 0/1"
```
```


### Anything else?

_No response_

**Comment by snovak7** [comment]
Follow up

It's similar to this one https://github.com/rancher/fleet/issues/795

The bundle id seems to be undeterministic with relation to release name?

As a workaround I can make separate git repo for each site. Other sites seem to be handling better because they don't have "double dash" in the bundle id.

**Comment by manno** [comment]
I thought this was fixed by https://github.com/rancher/fleet/issues/1272

**Comment by snovak7** [comment]
These cases are with kustomize based resources, not helm charts

The cluster(s) auto-updates rancher, recently to 2.7.3 (as of today), but checking with UptimeRobot this happened more regularly in the past, recently the "uptime" improved, I see less 404 errors (which normally denoted deletion of resources from cluster)

**Comment by snovak7** [comment]
Another observation, after re-bundling (delete, force git-repo update), this seems to have stabilized.

**Comment by snovak7** [comment]
Still can happen with longer names

**Comment by thsnielsen** [comment]
I have a customer with this problem related to longer names thought resolved multiple times (SURE-4160) 
Are we sure this will make it to Q323?

**Comment by weyfonk** [comment]
## Additional QA

### Problem

Bundles with long release names have their IDs trimmed to fit within the Helm release name length (53 chars).
Trimming results in the following format: `<trimmed-release-name>-<6-char-hash>`, eg.`12345678901234567890123456789012345678901234567-d0bce`.

When the 47th character of the original release name is already a dash (`-`), the release name would previously be computed with a double dash, eg. `1234567890123456789012345678901234567890123456-890123` would become `1234567890123456789012345678901234567890123456--d0bce`.

In turn, this would lead to discrepancies between the deployed release name and the one expected by Fleet to be deployed, so Fleet would then delete and redeploy the corresponding bundle.

### Solution
When the 47th character of the original release name is already a dash, Fleet does not include an additional dash in the trimming process, which eliminates inconsistencies. In such cases, the resulting release name is one character shorter (ie 52 chars long).

### Testing

### Engineering Testing
#### Manual Testing
##### Before
1. Deployed a bundle with name `gitrepo-test-examples-many-many-many-many-many-more-characters`, which release name became `gitrepo-test-examples-many-many-many-many-many--da317`
1. Could see the following in the Fleet agent pod logs after ~20 min:
```
time="2023-07-12T10:44:26Z" level=info msg="Deleting unknown bundle ID gitrepo-test-examples-many-many-many-many-many--da317, release default/gitrepo-test-examples-many-many-many-many-many-da317, expecting release default/gitrepo-test-examples-many-many-many-many-many--da317"
```
##### After
1. Deployed the same bundle again; its release name became `gitrepo-test-examples-many-many-many-many-many-da317`
1. Did not see it being re-created after >1h.

#### Automated Testing
* [unit tests](https://github.com/rancher/fleet/blob/master/internal/name/name_test.go#L56) cover Helm release name generation with the edge case where the 47th character of the release name is a dash.

### QA Testing Considerations

#### Regressions Considerations
* N/A (other cases Helm release name generation cases were already covered by unit tests)

**Comment by sbulage** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---
|1| Test `GitRepo` name with 47 characters and it trims it.
|2| Test `GitRepo` name more than 47 characters and see bundle name trims it.
|3| Test `GitRepo` name with mix of alpha-num characters with more than 47 characters and check bundle name trims it.
|4| Test `GitRepo` name with unsupported characters are not accepted (as per RFC 1123 complient)

**Comment by sbulage** [comment]
**TEST RESULT**

|Scenario|Test Case|Results
|---|---|---|
|1| Test `GitRepo` name with 47 characters and it trims it. | :heavy_check_mark: |
|2| Test `GitRepo` name more than 47 characters and see bundle name trims it.|  :heavy_check_mark:|
|3| Test `GitRepo` name with mix of alpha-num characters with more than 47 characters and check bundle name trims it.| :heavy_check_mark:|
|4| Test `GitRepo` name with unsupported characters are not accepted (as per RFC 1123 complient)| :heavy_check_mark: |

**REPRO STEPS**

**Scenario 1**
1. Create a `GitRepo` with name `test-test-test-test-test-test-test-test-test-t` (47 characters)
2. Goto the Advanced --> Bundles
3. Verify that the bundle name is created with the 6 characters suffux(including `-`)

**Scenario 2**
1. Create a `GitRepo` with name `test-test-test-test-test-test-test-test-test-test-test-test` (60 characters)
2. Goto the Advanced --> Bundles
3. Verify that the bundle name is trimmed to the 54 characters in total including the 6 characters suffix at the end (including `-`)

**Scenario 3**
1. Create a `GitRepo` with name `test-test-test-test-123-456-789-0--test-test-test-test` (55 Alpha-num characters)
2. Goto the Advanced --> Bundles
3. Verify that the bundle name is trimmed to the 54 characters in total including the 6 characters suffix at the end (including `-`)

**Scenario 4**
1. Create a `GitRepo` with name `ryhhskh-123456789+-+abdhg%^/`
2. Verify that the `GitRepo` didn't get create and shows the warning about naming conventions as per the RFC 1123 (See below screenshot)
![Selection_046](https://github.com/rancher/fleet/assets/12134754/6258f0e0-8783-433d-bdf5-b7ea406dd6ce)
