### ISSUE TITLE
.ClusterAnnotations helm template variables "map has no entry for key xxx"

### ISSUE THREAD

**Issue by eCloudJTuttle** [rancher/fleet#1516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I define an annotation on the cluster: region="us-west-2".
Then I define a fleet helm repo with the following fleet.yaml:

```yaml
# fleet.yaml
helm:
  values:
    region: "${ .ClusterAnnotations.region }"
...
```

This gives me the error on the bundle:

> Failed to render helm values template: template: values:4:30: executing "values" at <.ClusterAnnotations.region>: map has no entry for key "region"

The same test using .ClusterLabels.region works, but I need to add this and several other annotations instead.

### Expected Behavior

Helm values template successfully rendered.

### Steps To Reproduce

1. Create cluster and assign it an annotation region="us-west-2".
2. Create fleet GitRepo with the above fleet.yaml.
3. See the error in the Bundles page of rancher-2.7.3

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.6.0
- Cluster:
  - Provider: Imported
  - Options:
  - Kubernetes Version: 1.25
```

### Logs

```markdown
failed to render helm values template: template: values:4:30: executing "values" at <.ClusterAnnotations.region>: map has no entry for key "region"
```

**Comment by raulcabello** [comment]
I can't reproduce this in Rancher 2.7.5 and fleet 0.7.0.   
 ` region: "${ .ClusterAnnotations.region }"` works fine if the annotation is present in the cluster. I see the above error if the annotation is not present, which is expected.

@eCloudJTuttle Please try with the latest Rancher 2.7.5 and make sure the cluster has the annotation
