### ISSUE TITLE
Fleet allows creation of workspace even though the namespace already exists

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1519]
### Issue description:
Fleet allows the creation of workspace even though the namespace already exists.

Deleting that workspace causes the deletion of namespace along with its contents.

### Business impact:
Deleting unwanted fleet workspace results in data loss

### Repro steps:

```
> kubectl get FleetWorkspace
NAME            AGE
fleet-default   13d
fleet-local     13d*
```

- List contents of fleet-system namespace

```
> kubectl get all -n fleet-system 
NAME                                    READY   STATUS    RESTARTS   AGE
pod/fleet-agent-d59db746-hxwvz          1/1     Running   0          13d
pod/fleet-controller-79554fcbf5-qpbnc   1/1     Running   0          13d
pod/gitjob-568c57cfb9-v8mkv             1/1     Running   0          13d
NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/gitjob   ClusterIP   10.43.19.174   <none>        80/TCP    13d
NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/fleet-agent        1/1     1            1           13d
deployment.apps/fleet-controller   1/1     1            1           13d
deployment.apps/gitjob             1/1     1            1           13d*
```

- Create new fleetworkspace

```
apiVersion: management.cattle.io/v3
kind: FleetWorkspace
metadata:
  name: fleet-system*
```

- List the workspaces and we can see that it gets created even though the namspace already exists.
  
```
> kubectl get FleetWorkspace
NAME            AGE
fleet-default   13d
fleet-local     13d  
fleet-system    119s*
```

- Delete the workspace (From UI we can't do it and it says permission denied)

- Deleting workspace from localcluster works , but the existing namespace also gets deleted.!!!

```
> kubectl delete FleetWorkspace fleet-system
fleetworkspace.management.cattle.io "fleet-system" deleted
```

```
> kubectl get all -n fleet-system 
NAME                                    READY   STATUS    RESTARTS   AGE
pod/fleet-agent-d59db746-hxwvz          1/1     Running   0          13d
pod/fleet-controller-79554fcbf5-qpbnc   1/1     Running   0          13d
pod/gitjob-568c57cfb9-v8mkv             1/1     Running   0          13d
NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/gitjob   ClusterIP   10.43.19.174   <none>        80/TCP    13d
NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/fleet-agent        1/1     1            1           13d
deployment.apps/fleet-controller   1/1     1            1           13d
deployment.apps/gitjob             1/1     1            1           13d
NAME                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/fleet-agent-7bddb87d57        0         0         0       13d
replicaset.apps/fleet-agent-d59db746          1         1         1       13d
replicaset.apps/fleet-controller-79554fcbf5   1         1         1       13d
replicaset.apps/gitjob-568c57cfb9             1         1         1       13d*
```

```
> kubectl get all -n fleet-system 
NAME                                    READY   STATUS        RESTARTS   AGE
pod/fleet-agent-d59db746-hxwvz          0/1     Terminating   0          13d
pod/fleet-controller-79554fcbf5-qpbnc   0/1     Terminating   0          13d
pod/gitjob-568c57cfb9-v8mkv             0/1     Terminating   0          13d
```

```
> kubectl get all -n fleet-system 
No resources found in fleet-system namespace.
```

```
> kubectl get all -n fleet-system
```

 - After few minutes, then namespace created back , but there are no fleet-agent
 
 ```
> kubectl get all -n fleet-system
NAME                                    READY   STATUS    RESTARTS   AGE
pod/fleet-controller-79554fcbf5-l2pgx   1/1     Running   0          5m48s
pod/gitjob-568c57cfb9-7k6b4             1/1     Running   0          5m48s
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/gitjob   ClusterIP   10.43.212.114   <none>        80/TCP    5m48s
NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/fleet-controller   1/1     1            1           5m48s
deployment.apps/gitjob             1/1     1            1           5m48s
NAME                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/fleet-controller-79554fcbf5   1         1         1       5m48s
replicaset.apps/gitjob-568c57cfb9             1         1         1       5m48s
```

### Workaround:
Is workararound available and implemented? No

### Expected behavior:
1. Fleet should not create workspace when namespace exist
2. Provide a way to delete workspace without deleting actual namespace and its contents

**Comment by manno** [comment]
We will need to throw an error from the rancher controller, if the namespace for a workspace already exists. 
Adopting existing namespaces into a workspace is not supported, yet.

**Comment by raulcabello** [comment]
> Expected behavior:
> - Fleet should not create workspace when namespace exist

This [PR](https://github.com/rancher/webhook/pull/260) rejects a workspace if the namespace already exists. 

> Provide a way to delete workspace without deleting actual namespace and its contents

The `provisioning.cattle.io/managed` annotation can be used for that. If the annotation `provisioning.cattle.io/managed`  is `false` namespace will not be deleted when deleting the workspace. The `fleet-local` workspace uses this annotation.

**Comment by raulcabello** [comment]
### Solution

rancher-webhook rejects a workspace creation if the namespace already exists.
 
### Testing

* Verify you can't create a workspace for a namespace that already exists. Error should be displayed.

### QA Testing Considerations

Workspaces for non-existing namespaces can be created. Everything around workspaces should work as before.

**Comment by sbulage** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1| Test workspace create disabled while there is namespace with same name present(ns created via application).
|2| Test workspace create after deploying application with same namespace.
|3| Test after upgrade workspace create throws error when same namespace exists.

**Comment by sbulage** [comment]
**TEST RESULT**

Scenarios
|Scenario|Test Case| Result
|---|---|---|
|1| Test workspace create disabled while there is namespace with same name present(ns created via application).|:heavy_check_mark:
|2| Test workspace create after deploying application with same namespace.|:heavy_check_mark:
|3| Test after upgrade workspace create throws error when same namespace exists.|:heavy_check_mark:

**REPRO STEPS**

**Scenario 1**
1. Created a namespace in the local cluster `test-ns`.
2. Created a pod and secret.
3. Create workspace `test-ns` same name as namespace created.
5. Verified that workspace with the same didn't create and warning in the UI is shown. 
(Expected warning: `admission webhook "rancher.cattle.io.fleetworkspaces.management.cattle.io" denied the request: namespace 'test-ns' already exists`)

**Scenario 2**
1. Created a `GitRepo` with `grafana` application installed in `test-grafana` namespace.
2. Checked that GitRepo and resources are created.
3. Go to the Continuous Delivery --> Advanced --> Workspaces.
4. Create workspace which has same name as `test-grafana` namespace.
5. Verified that workspace with the same didn't create and warning in the UI is shown. 
(Expected warning: `admission webhook "rancher.cattle.io.fleetworkspaces.management.cattle.io" denied the request: namespace 'test-grafana' already exists`)

**Scenario 2**
1. Installed the released version of Rancher and Fleet.
2. Created a `GitRepo` with `nginx` application installed in `test-nginx` namespace.
3. Checked that GitRepo and resources are created.
4. Go to the Continuous Delivery --> Advanced --> Workspaces.
5. Create workspace which has same name as `test-nginx` namespace.
6. Workspace got created (Reproduce of this issue.)
7. Upgraded Rancher version to the dev-2.8., also fleet gets upgraded to 0.9.0-rc.3
8. Repeated steps from 2-5
9. Verified that proper warning message shown in the UI.
Warning message: `admission webhook "rancher.cattle.io.fleetworkspaces.management.cattle.io" denied the request: namespace 'test-nginx' already exists`)

*Note: Namespace is created in the `local cluster` not in `downstream cluster`.*
