### ISSUE TITLE
fleet-getting git repo  has no deployed releases

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1522]
### Issue description:
While trying to do a deployment using continuous delivery, getting the below error.  "k8s007-uat1-corporate" has no deployed releases

### Business impact:
Business impact is less but The customer is  exploring fleet options before implementing in production, got stuck (applied workaround), and expecting answers before proceeding in production

### Steps:

Add a git repo  when fleet agent is  not running
restart the fleet-agent

### Workaround:
Is workaround available and implemented? yes
What is the workaround:

removed the corresponding bundle of the stuck job, it internally removed the app.Then able to  register the app successfully

### Actual behavior:
deploying an application using git repo is failing with  repo  has no deployed release

### Expected behavior:
customer is asking "with out impacting the application is there a way to update bundle desired state or handle" Repo  has no deployed releases" state."

### Addtional notes:

Noticed GitJob stuck in k8s007-uat1-corporate" has no deployed releases
Verified that the fleet agent is not running,  So we scaled up agent to 2 and back to 1 
kubectl get pods -n cattle-fleet-system
 The reason for fleet agent is not running is,  while trouble shooting issue, customer   removed pod but the  it fail to create again because of constrain defined in the template. Once the constrains removed then scaling of  replica triggered the agent creation
Later we perform Force sync but still it is failing to sync actual state.
Tried another git repo it is working fine. 
Then removed the corresponding bundle of the stuck job, it internally removed the app.
After removing the bundle, it starts syncing it and  GitJob state to changed to  active state.

**Comment by manno** [comment]
I added a GitRepo to Fleet 0.7.0-rc while the agent was scaled down to 0 replicas. The Bundle showed a WaitApplied state. After scaling up the fleet-agent deployment, the bundle was deployed immediately.

**Comment by kkaempf** [comment]
Add to QA backlog

@prabalsharma can probably be closed as it was verified by @manno as of last comment.

**Comment by kkaempf** [comment]
Dicussed during weekly meeting and agreed to close it.

**Comment by MaaeYeng2517** [comment]
Why is git not deploy to 

fatal: remote origin already exists.
remote: Permission to xxx/xx.git denied to xxxx.
fatal: unable to access 'https://github.com/xxx/xx.git': The requested URL returned error: 403
