### ISSUE TITLE
Feature Request: Access to Git repo via Github App

### ISSUE THREAD

**Issue by gauravngandhi** [rancher/fleet#1523]
### Is your feature request related to a problem?

With Basic Auth or SSH the fleet gets access to all the repos the user has access to. It would be nice to limit this access

### Solution you'd like

We can use github app to do this. We install the github app only on the repos we want to expose to fleet and fleet can utilize github app to authenticate itself against the repository it is trying to access

### Alternatives you've considered

Fine grained token is another solution to this, but since its in beta we cannot currently use it.

**Comment by manno** [comment]
Please reopen if this doesn't work with the newest version.
