### ISSUE TITLE
Support for Jsonnet/Tanka

### ISSUE THREAD

**Issue by ghostsquad** [rancher/fleet#153]
**Is your feature request related to a problem? Please describe.**
I use jsonnet to generate my yaml manifests, and those yaml files do not get checked into Git. As such, I cannot use the Rancher CD GitOps without support for....

**Describe the solution you'd like**
At minimum, the ability to run an arbitrary step to generate the files that RancherCD then looks for.

**Describe alternatives you've considered**
I've thought about generating yaml files and committing them to a separate repo via an automated workflow, but that seems complicated for no good reason.

**Comment by strowi** [comment]
Yes please. We're also using tanka to template multiple environments. Would love something similar, maybe a plugin-based approach, to the way [argocd does it](https://hodovi.cc/blog/gitops-argocd-and-tanka/). ;)
