### ISSUE TITLE
Add custom labels to bundle namespaces

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1553]
## SURE-6393

[PSA](https://kubernetes.io/docs/concepts/security/pod-security-admission/) need labels on namespaces.

Fleet only creates the `defaultNamespace` or `targetNamespace` and it does so by setting helm's `CreateNamespace=true`.

_Note: We assumed any other namespaces mentioned in one of the the bundle's resources will also be created, but this is not the case. Fleet will error with `'ErrApplied(1) [Cluster fleet-local/local: namespaces "example" not found]'`._

Fleet also creates namespace resources which are contained in the bundle and controls their lifecycle.

Acceptance Criteria:

- [x] namespace resources in a bundle are processed correctly, including labels and annotations (works already)
- [x] annotations and labels for `defaultNamespace` (= `targetNamespace`) can be configured
- [x] mention in the docs that namespace resources contained in a bundle will be deleted with the bundle. this might affect non-bundle resources in the namespace.

## Discussion

Including a resource for the `defaultNamespace` in the bundle doesn't work, we would need to set helm's `Force` option and we would change the uninstall behavior.
We probably need to configure the default namespace explicitly from `fleet.yaml`. 

```
namespaceLabels:
    env: test
namespaceAnnotations: 
    pod: deny
```

* To add the labels and annotations we could use a Helm post install hook.
* We could also create the namespace from code and turn off `CreateNamespace`.

## Related

* https://github.com/rancher/fleet/issues/1484 (labels PSA)
* https://github.com/rancher/fleet/issues/1461 (annotations)

**Comment by raulcabello** [comment]
# QA Template

## Problem
There is no way to add annotations or labels to namespaces created by Fleet.

## Solution
Fleet uses the option `--create-namespace` from helm install to create namespaces. Namespaces are created with only one label with `name` as key and no annotations.

This PR adds two new fields `NamespaceLabels` and `NamespaceAnnotations` to the fleet.yaml in order to add labels or annotations to the namespace created by Fleet.

## Testing

- If no `NamespaceLabels` or `NamespaceAnnotations`  is present no labels or annotations should be added (just the name label added by helm)
- Add `NamespaceLabels` and `NamespaceAnnotations`. Verify annotations and label are added.
- Modify existing labels and annotations
- Delete labels or annotations. labels or annotations that were added using  `NamespaceLabels` and `NamespaceAnnotations` will be removed if they are removed from  `NamespaceLabels` or `NamespaceAnnotations`.
Keep in mind that if you want to remove all labels or annotations yo need to pass {} to `NamespaceLabels` or `NamespaceAnnotations`.

For example:
```
NamespaceAnnotations: {}
NamespaceLabels: {}
```
will remove all labels or annotations previously added.

**Comment by sbulage** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1| Test add custom label to the namespace created via fleet while creating new `GitRepo`|
|2| Test add custom label to the namespace created via fleet for exising `GitRepo`|
|3| Test update custom label to the namespace created via fleet for exising `GitRepo`|
|4| Test add multiple custom label to the namespace created via fleet for exising `GitRepo`|
|5| Test add custom annotation to the namespace created via fleet while creating new `GitRepo`|
|6| Test add annotation to the namespace created via fleet  for exising `GitRepo`|
|7| Test update custom annotation to the namespace created via fleet for exising `GitRepo`|
|8| Test add multiple custom annotation to the namespace created via fleet for exising `GitRepo`|
|9| Test remove exising custom label to the namespace created via fleet for exising `GitRepo`|
|10| Test remove exising custom annotation to the namespace created via fleet for exising `GitRepo`|

**Comment by sbulage** [comment]
**TEST RESULT**

|Scenario|Test Case|Results
|---|---|---|
|1| Test add custom label to the namespace created via fleet while creating new `GitRepo`|:heavy_check_mark:
|2| Test add custom label to the namespace created via fleet for exising `GitRepo`|:heavy_check_mark:
|3| Test update custom label to the namespace created via fleet for exising `GitRepo`|:heavy_check_mark:
|4| Test add multiple custom label to the namespace created via fleet for exising `GitRepo`|:heavy_check_mark:
|5| Test add custom annotation to the namespace created via fleet while creating new `GitRepo`|:heavy_check_mark:
|6| Test add annotation to the namespace created via fleet  for exising `GitRepo`|:heavy_check_mark:
|7| Test update custom annotation to the namespace created via fleet for exising `GitRepo`|:heavy_check_mark:
|8| Test add multiple custom annotation to the namespace created via fleet for exising `GitRepo`|:heavy_check_mark:
|9| Test remove exising custom label to the namespace created via fleet for exising `GitRepo`|:heavy_check_mark:
|10| Test remove exising custom annotation to the namespace created via fleet for exising `GitRepo`|:heavy_check_mark:

**REPRO STEPS**

**Scenario 1**
1. Create fleet.yaml with `namespaceLabels` like [this](https://github.com/sbulage/test-fleet/blob/main/update-namespaces/fleet.yaml#L2-L3).
2. Created a `GitRepo` in the UI (https://github.com/sbulage/test-fleet having path `update-namespaces`)
3. Goto the Imported cluster --> Project/Namespaces
4. Verify that the namespace mentioned in the fleet.yaml has the associated label assigned to it.

**Scenario 2**
1. Update fleet.yaml with `namespaceLabels`
2. Wait for `GitRepo` to update the latest commit.
3. Goto the Imported cluster --> Project/Namespaces
4. Verify that the namespace label is updated and showing latest label.

**Scenario 3**
1. Update the `namespaceLabels` to the fleet.yaml of already created `GitRepo`
2. Wait for `GitRepo` to update the latest commit.
3. Goto the Imported cluster --> Project/Namespaces
4. Verify that the namespace label is added to the existing `GitRepo`

**Scenario 4**
1. Create fleet.yaml with multiple `namespaceLabels` in it [for e.g.](https://github.com/sbulage/test-fleet/blob/main/update-namespaces/fleet.yaml#L2-L6)
2. Created a `GitRepo` in the UI (https://github.com/sbulage/test-fleet having path `update-namespaces`)
3. Goto the Imported cluster --> Project/Namespaces
4. Verify that the namespace mentioned in the fleet.yaml has multiple labels added.

**Scenario 5**
1. Create fleet.yaml with `namespaceAnnotations` like [this](https://github.com/sbulage/test-fleet/blob/main/update-namespaces/fleet.yaml#L4-L5).
2. Created a `GitRepo` in the UI (https://github.com/sbulage/test-fleet having path `update-namespaces`)
3. Goto the Imported cluster --> Project/Namespaces
4. Verify that the namespace mentioned in the fleet.yaml has the associated annotation assigned to it.

**Scenario 6**
1. Update fleet.yaml with `namespaceAnnotations`
2. Wait for `GitRepo` to update the latest commit.
3. Goto the Imported cluster --> Project/Namespaces
4. Verify that the namespace annotation is updated and showing latest annotation.

**Scenario 7**
1. Update the `namespaceAnnotations` to the fleet.yaml of already created `GitRepo`
2. Wait for `GitRepo` to update the latest commit.
3. Goto the Imported cluster --> Project/Namespaces
4. Verify that the namespace annotation is added to the existing `GitRepo`

**Scenario 8**
1. Create fleet.yaml with multiple `namespaceAnnotations` in it [for e.g.](https://github.com/sbulage/test-fleet/blob/main/update-namespaces/fleet.yaml#L7-L11)
2. Created a `GitRepo` in the UI (https://github.com/sbulage/test-fleet having path `update-namespaces`)
3. Goto the Imported cluster --> Project/Namespaces
4. Verify that the namespace mentioned in the fleet.yaml has multiple annotations added.

**Scenario 9**
1. Update the `namespaceLabels` with empty dictionary `{}` in the fleet.yaml
2. Wait for `GitRepo` to update the latest commit.
3. Goto the Imported cluster --> Project/Namespacesname
4. Verify that the namespace label is removed from the namespace.

**Scenario 10**
1. Update the `namespaceAnnotations` with empty dictionary `{}` in the fleet.yaml
2. Wait for `GitRepo` to update the latest commit.
3. Goto the Imported cluster --> Project/Namespacesname
4. Verify that the namespace annotation is removed from the namespace.
