### ISSUE TITLE
fleet test missing resources from helm chart

### ISSUE THREAD

**Issue by strowi** [rancher/fleet#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

running `fleet test` and `helm template` with equal/no values show very different output.
`fleet test` is missing some resources that are present in the helm-chart.

### Expected Behavior

Outcome should be the same in both cases and same when deployed.

### Steps To Reproduce

This test-case shows the resource `name: alertmanager-rancher-monitoring-alertmanager` present in helm, but missing from `fleet test`

```bash
~> helm repo add rancher-charts https://charts.rancher.io
"rancher-charts" has been added to your repositories

~> helm fetch rancher-charts/rancher-monitoring --version 102.0.0+up40.1.2
~> tar xvf rancher-monitoring-102.0.0+up40.1.2.tgz 

~> helm template rancher-monitoring rancher-monitoring |grep -i alertmanager-rancher-monitoring-alertmanager
  name: alertmanager-rancher-monitoring-alertmanager


~> fleet --version
fleet version v0.6.0 ()

~> mkdir fleet && cat <<EOF> fleet/fleet.yaml
helm:

  repo: https://charts.rancher.io
  chart: rancher-monitoring
  version: 102.0.0+up40.1.2
  releaseName: rancher-monitoring
EOF

~> fleet test -f fleet.yaml fleet|grep -i alertmanager-rancher-monitoring-alertmanager
# Matched: default
```

### Environment

```markdown
- Architecture: amd64
- Fleet Version: v0.6.0
- Cluster:
  - Provider: k3s
  - Kubernetes Version: 1.25
```

### Anything else?

Seems similar to https://github.com/rancher/fleet/issues/186

**Comment by manno** [comment]
Related to https://github.com/rancher/fleet/issues/1385

**Comment by manno** [comment]
This should be fixed in newer versions.
