### ISSUE TITLE
Allow use of '+' character in kustomize directory name

### ISSUE THREAD

**Issue by ron1** [rancher/fleet#156]
Use of a `+` character in a kustomize directory name causes `fleet test` to generate the following error:
```
FATA[0000] error while running post render on files: illegal name 'dev+test' in directory creation
```

Steps to reproduce the problem:
1. Apply [patch](https://github.com/ron1/fleet-examples/commit/4cc4e9252d0f61c5b82b7f41e6daf4cdf6ae2cfb) to fleet-examples
2. Change into patched `fleet-examples/multi-cluster/kustomize` directory
3. Execute command `fleet test -t dev`

Expected result: yaml manifests are displayed
Actual result: the above error is displayed

**Comment by hyunsun** [comment]
I also ran into the same problem with files containing "@" character in the name, which is unavoidable in YANG modeling.

**Comment by Mo9a7i** [comment]
no fix yet ?
