### ISSUE TITLE
Add option to disable polling for Git repos

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1572]
When this option, e.g. "disableGitPolling", is set, the gitjob will not check the repo every syncInterval seconds. This allows users to build workflows that only use webhooks.

Normally Fleet checks the repo regularly, even when using Webhooks, to make sure it can recover from a failed Webhook http request.

## Notes

Currently Fleet/gitjob will [interpret a syncInterval of 0 as 15 minutes](https://github.com/rancher/gitjob/blob/master/pkg/controller/gitjob/gitjobs.go#L68-L72).
Furthermore, if webhooks are used and the interval is at "0", the default, the interval [will be changed to one hour](https://github.com/rancher/gitjob/blame/master/pkg/webhook/webhook.go#L235-L242).

## Open Questions

How does this interact with the "pause" option from the GitRepo spec?

> Paused this cause changes in Git to not be propagated down to the clusters but instead mark resources as OutOfSync

Maybe paused should be propagated to gitjob instead of creating a new option?

**Comment by manno** [comment]
Note, there is an (unused?) `Provider: polling` field in the gitjob spec: https://github.com/rancher/gitjob/blob/master/pkg/apis/gitjob.cattle.io/v1/types.go#L65

**Comment by 0xavi0** [comment]
# QA Template

## Solution
When new option `disablePolling` is set to `true` git repositories are not scanned periodically

## Testing
Apply a `fleet.yaml` file which refers to a git repository and don't set the `disablePolling` option. 
That should scan the repository every 15 seconds. (as of now)
Push something to the repo in that interval of time and it should be scanned and applied by Fleet.

Add the `disablePolling` option set to true and push some more changes to the repository.
Fleet should not scan the repository and changes should not be applied.

## Additional info

**Comment by sbulage** [comment]
**System Information** 
* Rancher version: v2.9-f26d9888
* Fleet Version: 104.0.0+up0.10.0-rc.13
---
**TEST RESULT**

Scenarios
|Scenario|Test Case| Result | QASE ID added
|---|---|---|---|
|1|As an admin user, add `GitRepo` with disablePolling option set to `false` which will update GitRepo with latest changes made in GitHub repository.| :white_check_mark: |:ballot_box_with_check:
|2|As an admin user, add `GitRepo` with disablePolling option set to `true` which will not sync latest changes to the GitRepo with from GitHub repository.| :white_check_mark: |:ballot_box_with_check:
|3|As an admin user, add `GitRepo` with disablePolling option set to `true` which will sync latest changes to the GitRepo with from GitHub repository when `Force Update` applied.| :white_check_mark: |:ballot_box_with_check:
|4|As an admin user, add `GitRepo` with disablePolling option set to `true` which will sync latest changes to the GitRepo with from GitHub repository when `Pause-Unpause` executed.| :white_check_mark: |:ballot_box_with_check:
