### ISSUE TITLE
Could not resolve host: github.com with step-git-source container

### ISSUE THREAD

**Issue by oskapt** [rancher/fleet#160]
I'm unable to update a Git repository in Fleet in Rancher 2.5. It errors out with `Could not resolve host: github.com` in the logs.

This is due to `ndots: 5` and the musl/DNS stuff documented elsewhere on the Internet. I'm running this cluster under a subdomain of `cl.monach.us`, which results in the following `resolv.conf`:

```
search fleet-local.svc.cluster.local svc.cluster.local cluster.local cl.monach.us
nameserver 10.43.0.10
options ndots:5
```

When searching for `github.com` it will try every permutation of `github.com.fleet-local.svc.cluster.local` and so on through the searches, never arriving at `github.com.` and thus failing. 

```
/workspace # ping github.com
ping: bad address 'github.com'
/workspace # ping github.com.
PING github.com. (140.82.112.3): 56 data bytes
64 bytes from 140.82.112.3: seq=0 ttl=46 time=147.003 ms
```

Of course, the FQDN with the trailing dot works. That shows it's a musl/DNS search domain issue.

The way to fix this is with `ndots: 1` in a `dnsConfig` block in the workload, but since this workload is entirely managed by Fleet, that's not possible. 

It's running in Rancher 2.5.2 on K3s v1.19.3+k3s2.

**Comment by nikkelma** [comment]
It'll also try resolving `github.com.cl.monach.us` - does this return anything of interest?

**Comment by oskapt** [comment]
```
$ curl github.com.cl.monach.us | jq '.'
{
  "status": 200,
  "response": "hahahahahahaha"
}
```

**Comment by oskapt** [comment]
seriously, though - no. there are no wildcards in `cl.monach.us` - it's just the internal domain for my house. (responding to your slack question). i've seen this time and time again - there are too many search domains, so it never exits. 

the upstream DNS server is my pi-hole.

```
➤ host github.com.cl.monach.us
Host github.com.cl.monach.us not found: 3(NXDOMAIN)
```

**Comment by oskapt** [comment]
https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html

**Comment by oskapt** [comment]
This mysteriously fixed itself overnight, so I'll close the ticket and open a new one with more debug info if/when it happens again.
