### ISSUE TITLE
[Epic] Add Fleet auto-reconciliation of missing/deleted resources

### ISSUE THREAD

**Issue by chipzoller** [rancher/fleet#163]
It appears that as of 0.3, Fleet does not auto-reconcile resources that were deleted or modified after Fleet has run and applied a given bundle. This is a fairly basic function of any GitOps tool that should be supported out of the box.Although there is an as-yet-undocumented parameter in the `GitRepo` resource called `spec.forceSyncGeneration` which is of type int, it only works once and thereafter not again.

**Comment by brlbil** [comment]
+1

**Comment by andreracz** [comment]
+1

**Comment by stenwt** [comment]
I would ask to extend the scope of this to say, if a resource exists prior to Fleet management, it would be good if Fleet could take it over. Currently, if I have a deployment in place, I have to delete it and re-deploy it with Fleet before Fleet will manage it.

**Comment by ibrokethecloud** [comment]
you could take a look at this in the spec: https://github.com/rancher/fleet/blob/master/pkg/apis/fleet.cattle.io/v1alpha1/bundle.go#L222

**Comment by vijaytrainer** [comment]
+1 to have the auto reconcile for deleted/missed resources. Flux and ArgoCD already provides the same functionality.

**Comment by travis-sobeck** [comment]
+1 I removed a fleet.yaml (simple helm chart deploy) and it left both the bundle and everything it deployed.

**Comment by stenwt** [comment]
I ran into this recently: I had a deployment manifest that I accidentally deleted with "kubectl delete -f". This put Fleet into a state where bundles were listed as missing, but were not reconciled, and no further updates to the repo specified in the GitRepo would be applied to the cluster. In order to get back to working, I had to git rm the manifest from the repo, commit and push, then do a `kubectl rollout restart deploy` on all the deployments in the fleet-system namespace. Removing the resource from git was not enough to get Fleet unstuck, the commit hash associated with the gitrepo wouldn't change. After I restarted the pods in fleet-system, the commit hash got updated and Fleet started applying changes from the repo again.

**Comment by wagnst** [comment]
Any update here? This is still not working in rancher `v2.6.2`

**Comment by crossett** [comment]
I'm really surprised this feature doesn't exist yet.  Is this something that's being worked on?

**Comment by jayroam** [comment]
Update as of Rancher `v2.6.6`. This feature is still not implemented. This is basic GitOps functionality. I will try to push this via my organization's customer success manager at Rancher.

Interestingly, the state 'missing' is not even documented as a state a bundle can be in: https://fleet.rancher.io/cluster-bundles-state/

**Comment by gsfd2000** [comment]
I sense that nothing happened on this matter so far and another two months passed. I also consider this as absolutely basic/critical, at least the ability to configure reconciliation. It already detects the drift, it should be rather easy also to have the ability to reconcile. Unfortunately I do not have sufficient expertise to develop/submit that change myself. I am surprised that this need has not a higher priority. It is basically one of THE critical GITOPS functionalities. Can anyone help on WHERE and HOW this need can be raised and sombody may listen?

**Comment by Klaven** [comment]
I feel like this is kind of a big deal here. If there are issues implementing it or concerns I would love to be apart of the conversation. Maybe there is a canonical way to deal with this that I don't see in the documentation? Even just a solid way to alert on it would be fantastic. This is kind of a big deal and while we had wanted to use fleet, without a solid system to do this or a good understanding of how to deal with this ourselves in an automated fashion it would be hard to difficult to use at massive scale.

**Comment by chipzoller** [comment]
I never thought when opening this issue (it has become the most "liked" issue in the repo since) that such a fundamental capability of any self-described "GitOps" tool wouldn't be added even after two years. In looking at the release history from then until now (v0.3 was the then-current minor release which only changed as of October, one month ago) and the nature of changes in those releases, it's pretty apparent this project has basically been put out to pasture.

**Comment by kkaempf** [comment]
It's rather high on the backlog, actually 😉

**Comment by mirzak** [comment]
Updates?

**Comment by kwaberski** [comment]
+1

**Comment by atterdag** [comment]
+1

**Comment by Arzzka** [comment]
Please try to get this feature out of the door. Our organisation is considering dropping Rancher Fleet altogether because this feature does not exist. It's just painful to manage deployments without it.

**Comment by pstefka** [comment]
+1 a must have feature missing for years?! Is there a way we can help push the priority? Otherwise we'd need to reconsider usage of Fleet for our customers 😐

**Comment by kkaempf** [comment]
See #1551, closing as done
