### ISSUE TITLE
Traefik - Helm >= 3.9.0 is required

### ISSUE THREAD

**Issue by JamesTurland** [rancher/fleet#1643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Have been using fleet to deploy Traefik for almost a year. Have just rebuilt my cluster and connected my Git account. When I try to deploy Traefik shows the following error:

ErrApplied(1) [Cluster fleet-local/local: execution error at (traefik/templates/deployment.yaml:3:8): ERROR: Helm >= 3.9.0 is required]

### Expected Behavior

Should deploy without error.

`helm version
version.BuildInfo{Version:"v3.11.3-rancher1", GitCommit:"8853d6f9875eb3138d10f4af7a4a67130039e28b", GitTreeState:"clean", GoVersion:"go1.19.4"}`

### Steps To Reproduce

Try to deploy Traefik using Fleet.

### Environment

```markdown
- Architecture: x86
- Fleet Version: 2.7.5
- Cluster:
  - Provider: K3S
  - Options: 8 nodes, Longhorn, Metallb
  - Kubernetes Version: 1.25.9
```

### Logs

```markdown
ErrApplied(1) [Cluster fleet-local/local: execution error at (traefik/templates/deployment.yaml:3:8): ERROR: Helm >= 3.9.0 is required]
```

**Comment by weiyentan** [comment]
am getting the same issue

**Comment by manno** [comment]
The [traefik chart has an explicit check](https://github.com/traefik/traefik-helm-chart/blob/2dd3b1848ff88f053a7cb01fdc997ab47bc3afd3/traefik/templates/deployment.yaml#L2) for the version:

```
{{- if (semverCompare "<v3.9.0" (.Capabilities.HelmVersion.Version | default "v3.0.0")) -}}
    {{- fail "ERROR: Helm >= 3.9.0 is required" -}}
{{- end -}}
```

Fleet supports capabilities now, but doesn't set a helm version: https://github.com/rancher/fleet/blob/master/internal/helmdeployer/capabilities.go#L56-L63

To fix this bug, it's probably sufficient to add this line: https://github.com/helm/helm/blob/main/pkg/chartutil/capabilities.go#L48

**Comment by manno** [comment]
## Additional QA
 
### Problem

Fleet didn't provide all ["Capabilities"](https://helm.sh/docs/chart_template_guide/builtin_objects/) to helm charts it deployed. For the helm version it provided an old default.

### Solution

Update how we use the helm SDK.
 
### Testing

A helm chart can now use
`{{ .Capabilities.HelmVersion.Version }}` in templates. One popular helm chart that does that is "traefik". 



### Engineering Testing
#### Manual Testing

Tested that the helm version values are now present.

#### Automated Testing

There is an integration test to make sure the capabilities are filled.

* `{{ .Capabilities.KubeVersion.Version }}`
* `{{ join \", \" .Capabilities.APIVersions |  }}`
* `{{ .Capabilities.HelmVersion.Version }}`

### QA Testing Considerations
 
-

#### Regressions Considerations

-

**Comment by senpro-ingwersenk** [comment]
Hello there!

Our company recently lost someone who specialized in Kubernetes and I was basically "made" to continue taking care of the cluster, although I am relatively new to Kubernetes (I come from Docker Compose).

I noticed this morning that I was getting this very error. However, there seems to be no helm installed in the system.

How can I effectively make this error cease? Got any pointers?

Thanks a lot and kind regards!
