### ISSUE TITLE
Docs: Feature documented but not released (doNotDeploy)

### ISSUE THREAD

**Issue by strowi** [rancher/fleet#1645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

there is again a feature documented for the current release 0.7.0 that will only be released in 0.8.0.

After trying to debug this, i found out:

Docs for 0.7.0 have doNotDeploy: https://fleet.rancher.io/0.7/ref-fleet-yaml#reference
But earliest release mentioned is 0.8.0-rc2: https://github.com/rancher/fleet/releases/tag/v0.8.0-rc.2

### Expected Behavior

only features documented that are contained in specified version. Otherwise the version selection at the top doesn't make any sense.

### Environment

```markdown
- Architecture:
- Fleet Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

**Comment by manno** [comment]
Should  be fixed by https://github.com/rancher/fleet-docs/pull/87
