### ISSUE TITLE
[v0.7.1]Backport  Periodically deleting bundles because of "unknown bundle ID" even though they look identical

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1660]
This is a backport issue of #1511 to go into v2.7.6.

Need to manually backport PRs into release/v0.7:
* https://github.com/rancher/fleet/pull/1647
* https://github.com/rancher/fleet/pull/1649

**Comment by sbulage** [comment]
Installed `Rancher 2.7.5-rc-6` and upgraded `Fleet 0.7.1-rc.1`.
Performed below tests mentioned on this same issue https://github.com/rancher/fleet/issues/1511#issuecomment-1649602371

All test passed successfully without any error.

**Comment by sbulage** [comment]
**I have re-tested this issue again on the `Rancher 2.7.6-rc2` and `Fleet 0.7.1-rc.2`.**

P.S. Earlier, I have tested this on only `Rancher 2.7.5-rc-6` and `Fleet 0.7.1-rc.1`
