### ISSUE TITLE
Correct GitRepo manifest namespaces of multi-cluster Fleet example README.md files to be "fleet-default" not "fleet-local"

### ISSUE THREAD

**Issue by ron1** [rancher/fleet#170]
Steps to reproduce:
1. Provision a Rancher 2.5.3+ Management k8s cluster
2. Register a downstream k8s cluster with label env=dev
3. kubectl apply the GitRepo manifest extracted from the [Multi-Cluster Kustomize Fleet Example README.md](https://github.com/rancher/fleet-examples/blob/master/multi-cluster/kustomize/README.md#multi-cluster-kustomize-example)
4. kubectl get the GitRepo above in yaml format

Expected Results: the status of the GitRepo includes no resource errors
Actual Results: the status of the GitRepo includes the following resource errors:
```
resourceErrors:
- 'error while running post render on files: Object ''Kind'' is missing in ''{"resources":["frontend-deployment.yaml","frontend-service.yaml","redis-master-deployment.yaml","redis-master-service.yaml","redis-slave-deployment.yaml","redis-slave-service.yaml"]}'''
- 'error while running post render on files: Object ''Kind'' is missing in ''{"resources":["frontend-deployment.yaml","frontend-service.yaml","redis-master-deployment.yaml","redis-master-service.yaml","redis-slave-deployment.yaml","redis-slave-service.yaml"]}'''
- 'error while running post render on files: Object ''Kind'' is missing in ''{"resources":["frontend-deployment.yaml","frontend-service.yaml","redis-master-deployment.yaml","redis-master-service.yaml","redis-slave-deployment.yaml","redis-slave-service.yaml"]}'''
```

Fix the problem by changing the namespace of the GitRepo from "fleet-local" to "fleet-default". Note the new GitRepo status has no resourceErrors. This change is needed for all Multi-Cluster Fleet Examples.

**Comment by ron1** [comment]
See fleet-examples [pr](https://github.com/rancher/fleet-examples/pull/4) with a proposed fix for this issue.

**Comment by kkaempf** [comment]
pr merged
