### ISSUE TITLE
[SURE-6557] Fleet deployment fails with error nil pointer evaluating interface 

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1700]
### Issue description:
While using fleet.yaml with additional values.yaml named as core-values.yaml, its contents with some special characters fail to get deployed. Same contents are deployed successfully while using the exact same contents in values.yaml

### Repro steps:

Deploy the files in the attached archive through fleet

### Workaround:
Is workararound available and implemented? yes
What is the workaround: Include the contents in values.yaml

### Actual behavior:
Fleet unable to deploy the ConfigMap while using "valuesFiles"

### Expected behavior:
Fleet should deploy the app successful while using valuesFiles where it has some special character([]) contents

### Files, logs, traces:

Getting the following error
~~~
Template: smoketest/templates/cm.yaml:4:19: executing "smoketest/templates/cm.yaml" at <.Values.credentials.secretContents.cloud>: nil pointer evaluating interface {}.secretContents

ErrApplied(1) [Cluster fleet-local/local: template: smoketest/templates/cm.yaml:4:19: executing "smoketest/templates/cm.yaml" at <.Values.credentials.secretContents.cloud>: nil pointer evaluating interface {}.secretContents]
~~~

**Comment by kkaempf** [comment]
> You can refer this example: https://github.com/skanakal/fleet-experiments/tree/SURE-6557

**Comment by kkaempf** [comment]
> I can repro this problem on the latest fleet and rancher versions: Its likely the similar issue  [https://github.com/rancher/fleet/issues/1101 ](https://github.com/rancher/fleet/issues/1101)
> 
> seems the problem is with the nested structure being used in valuesFiles,
> ~~~
>   creds: {{ .Values.credentials.secretContents.cloud | quote }}
> ~~~
> 
> The error `nil pointer evaluating interface {}.secretContents` can be workaround using the parenthesis something like
> 
> ~~~
> creds: "{{ ((.Values.credentials).secretContents).cloud }}"
> ~~~
> 
> or 
> 
> if possible you can use the flat values as `creds: {{ .Values.credentialssecretContentscloud | quote }}`
> 
> In another way, I have followed the below repro structure to workaround althouth there is no proper structure required: 
> 
> ~~~
> root@server-1:~/fleet-test-data/helm-verify# 
> root@server-1:~/fleet-test-data/helm-verify# tree .
> .
> ├── config-chart
> │   ├── Chart.yaml
> │   ├── templates
> │   │   ├── configmap.yaml
> │   │   └── _helpers.tpl
> │   └── values.yaml
> ├── fleet.yaml
> ├── README.md
> ├── values1.yaml
> ├── values2.yaml
> └── values.yaml
> 2 directories, 9 files
> root@server-1:~/fleet-test-data/helm-verify# 
> root@server-1:~/fleet-test-data/helm-verify# cat config-chart/templates/configmap.yaml | grep creds
>   creds: {{ .Values.credentials.secretContents.cloud | quote }}
> root@server-1:~/fleet-test-data/helm-verify# 
> root@server-1:~/fleet-test-data/helm-verify# kubectl get cm app-config -o yaml 
> apiVersion: v1
> data:
>   creds: |
>     [sandbox-rex-sddc]
>     aws_access_key_id = x-k8s-sandbox-rex-sddc-save-s3
>     aws_secret_access_key = +uH4hYJGtEz5uF9YZL5q7f8hE31kt8ItUr/nBI4I
>   server: master-0
>   test: value
> ~~~
> 
> While implementing any of the aforementioned workarounds, please feel free to let me know if you encounter any difficulties or issues. It is important to note that the encountered problem is considered a bug, and I will provide feedback to the Fleet team to address and rectify the issue.

**Comment by rubhanazeem** [comment]
I've tried the given attachment configs on `0.7.0` and the latest release but this is not reproducible on either of those releases. I think we can close this issue.

**Comment by kkaempf** [comment]
Not reproducible

**Comment by skanakal** [comment]
I confirm the issue is no longer reproducible on the latest version of rancher...
