### ISSUE TITLE
Release notes: Describe how to update to 'latest' Fleet

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1706]
Since #1590 takes more time to fix properly, the release notes need to mention how to upgrade Rancher to 'latest' Fleet.

**Comment by manno** [comment]
When upadting Rancher, sometimes fleet is not upgraded to the latest version. To make sure fleet is upgraded:
* refresh the rancher-charts catalog resource
* go to apps, select all workspaces and press the dot menu to select "upgrade"

**Comment by kkaempf** [comment]
@manno please review release notes and close this issue 🙏🏻
