### ISSUE TITLE
Improve status reporting for a GitRepo CR with no targets specified yet or with target clusters that do not yet exist

### ISSUE THREAD

**Issue by ron1** [rancher/fleet#171]
Sometimes I might want to create a GitRepo with no targets specified yet or with target clusters that do not yet exist. This workflow should be supported and not result in a GitRepo CR whose status includes resource errors.

Steps to reproduce:
1. Provision a Rancher 2.5.3+ Management k8s cluster
2. kubectl apply the GitRepo manifest extracted from the [Multi-Cluster Kustomize Fleet Example README.md](https://github.com/rancher/fleet-examples/blob/master/multi-cluster/kustomize/README.md#multi-cluster-kustomize-example) with namespace set to `fleet-default` and no targets specified
3. kubectl get the GitRepo above in yaml format

Expected Results: the status of the GitRepo includes a valid list of resources, no resource errors, and 0 desiredReady clusters
Actual Results: the status of the GitRepo includes no list of resources and the following completely unexpected resource error
```
resourceErrors:
- 'error while running post render on files: Object ''Kind'' is missing in ''{"resources":["frontend-deployment.yaml","frontend-service.yaml","redis-master-deployment.yaml","redis-master-service.yaml","redis-slave-deployment.yaml","redis-slave-service.yaml"]}'''
```

**Comment by lperrin-obs** [comment]
I got the same issue, even if a target cluster is already existing.

@ron1, did you manage to make this example work ?

**Comment by kkaempf** [comment]
no further reports, assuming fixed.
