### ISSUE TITLE
[SURE-6723] Allow to specify additional arbitrary Fleet chart values

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1717]
## SURE-6723

**Is your feature request related to a problem? Please describe.**

### Request description:
Goal: allow Rancher users to specify additional arbitrary values for the Fleet chart, so that their Fleet installation can be customized flexibly.

This is particularly useful as a catch-all measure when assisting customers to introduce Fleet-specific experimental tuning settings, debug settings, etc. even if they are not yet covered by the Rancher UI.

### Actual behavior:
Currently Rancher installs the Fleet with fixed values, making the solution less flexible than Fleet standalone cases.

### Expected behavior:
Parameters can be customized - feature parity with Fleet standalone.

### Workaround:
Manually editing Fleet deployments, ConfigMaps, etc.

### Additional notes:
Currently Rancher installs the Fleet with fixed values. Code reference:

https://github.com/rancher/rancher/blob/9c5a25675676b680898f933681abde88f53dba95/pkg/controllers/dashboard/fleetcharts/controller.go#L89-L100

A similar change was introduced for the webhook component: https://github.com/rancher/rancher/pull/42060

**Describe the solution you'd like**

Parameters can be customized - feature parity with Fleet standalone.

**Describe alternatives you've considered**

**Additional context**

**Comment by moio** [comment]
> Upon discussion, transferring to backend since no UI is required.

To elaborate this statement a bit: having a configurable ConfigMap that can achieve the same goal is sufficient as a starting point and should cover most cases, even without a UI (which can always be added later if necessary).
