### ISSUE TITLE
[Migration] Verify that migration path from onprem to hosted works as expected

### ISSUE THREAD

**Issue by davidstauffer** [rancher/fleet#1719]
## Background
We have a customer that is migrating from Rancher Self-hosted to hosted, including fleet. 
Currently, they are on v2.6.0 on the self-hosted

## Goals
We need to test the backup & restore + migration procedure so that we can provide some confidence in a path to the customer. 
It is very important to avoid redeployment of the workloads on the clusters when using the backup+restore procedure. 

CC @raulcabello @sbulage

**Comment by kkaempf** [comment]
Should go via JIRA, probably not Fleet(-only) related.
