### ISSUE TITLE
Helm Storage Backend With Caching

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1738]
The fleet agent stores the history in the default helm storage, which is secrets. However the backend does not cache,  limiting the number of history items helps with performance, but as discussed we need caching.

This should fix #1465 and replace https://github.com/rancher/fleet/pull/1609

**Comment by mattfarina** [comment]
For some history on history... the current lookup mechanism was designed for use with the Helm CLI which is not long running. Caching did not make sense for that case.

I would be curious how we keep the cache up to date. A watch of Helm secrets? Helm secrets are typed (i.e., `helm.sh/release.v1`) so they can be filtered from other secrets. Something else?

**Comment by moio** [comment]
> For some history on history... the current lookup mechanism was designed for use with the Helm CLI which is not long running. Caching did not make sense for that case.

👍 

> I would be curious how we keep the cache up to date. A watch of Helm secrets? Helm secrets are typed (i.e., helm.sh/release.v1) so they can be filtered from other secrets. Something else?

Fleet (specifically `fleet-agent`) originally had no caching whatsoever - all reads just go through Helm, and Helm fetches all data from the Kubernetes API client - no Informers or similar caching mechanisms were in place. In #1485 I added a cache to the whole `Storage.History()` results, which is expected to not always be coherent (cache results expire after 5 minutes) - that can arguably be described as a suboptimal workaround. Details here: https://github.com/rancher/fleet/pull/1485/commits/8b0d9b7031570b7f6c0b8b5e969e34542339d181

A better strategy could indeed be Informer-based. Or not saving history in Kubernetes/etcd altogether - which opens up the interesting question what other DB could be used.

BTW: one additional problem we have is that Helm's Storage API fetches more than we actually need, and then we filter results in-memory. It'd help if the new backend, however it looks like, could deal with this natively. Details:

https://github.com/rancher/fleet/blob/26c247a999decdda7e639db9a0cef6e36f8ec5a2/internal/helmdeployer/deployer.go#L538-L555
