### ISSUE TITLE
Fleet Bundle contains the wrong resources

### ISSUE THREAD

**Issue by shane-davidson** [rancher/fleet#175]
We are using Fleet to sync one git repo to each cluster we have. (deploying individual customer environments per cluster)

(I know fleet supports using different settings per cluster in a single repo but we already have each repo set up for our other automation)

Git Structure:
```
/containers
 - /folder1 <- helm chart + contains fleet.yaml
 - /folder2 <- helm chart + contains fleet.yaml
 - /folder3
   - /folder3subfolder1 <- helm chart + contains fleet.yaml
   - /folder3subfolder2 <- helm chart + contains fleet.yaml
```

Fleet Git Repo config watches the path /containers

The sub folders contain the **same** helm chart in the **same** namespace.  I have also tried to deploy yaml files without helm with the same error.

The bundles are showing the following logs:
```
time="2020-12-10T23:49:31Z" level=error msg="bundle BUNDLE: ingress.networking.k8s.io RESOURCE_FROM_DIFFERENT_BUNDLE missing"
```

Inside the same namespace and same chart the resources are constantly flapping and changing.

With different namespaces the resources are applied but fleet is stuck on WaitApplied

Also as part of all of this happening the agent starts reporting this:
```
time="2020-12-11T02:41:50Z" level=error msg="Failed to register agent: secrets \"fleet-agent\" is forbidden: User \"system:serviceaccount:fleet-system:fleet-agent\" cannot get resource \"secrets\" in API group \"\" in the namespace \"fleet-system\": RBAC: clusterrole.rbac.authorization.k8s.io \"fleet-system-fleet-agent-role\" not found"
```

Attempting to remove the Git Repo / Bundles /Resources and recreating it does not help.

Fleet sees and creates all the bundles but it also creates a top level bundle called "containers" that has resources in it when it is just a folder to contain the other fleet bundles.

I have deployed the cluster 3 times and get the same result each time.

**Comment by shane-davidson** [comment]
Creating the resources inside the Git Repo like this seems to work:

```
/containers
 - /folder1 <- helm chart + contains fleet.yaml
 - /folder2 <- helm chart + contains fleet.yaml
 - /folder3 <- yaml files + fleet.yaml
 - /folder4 <- yaml files + fleet.yaml
```

(I didn't test the yaml files in subdirectories instead of helm charts on a fresh cluster after it was stuck in WaitApplied)

**Comment by kkaempf** [comment]
Workaround exists.
