### ISSUE TITLE
Bump to wrangler/v2

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1777]
Mocks break, see https://github.com/rancher/rancher/pull/41817

**Comment by aruiz14** [comment]
related: https://github.com/rancher/gitjob/issues/315

**Comment by aruiz14** [comment]
@manno I'm afraid that we are still blocked here. I tried upgrading the import paths to `wrangler/v2` but there is still no version of `lasso` using `v2`. It's not possible to keep both versions of `wrangler` because `steve`'s `/pkg/aggregation` expects a `v1` handler.

**Comment by aruiz14** [comment]
Not blocked anymore, since we tackled: rancher/gitjob#339
