### ISSUE TITLE
[SURE-6871] Fleet: changing the Gitrepo watch from revision to branch results in an error.

### ISSUE THREAD

**Issue by bvankampen** [rancher/fleet#1779]
## SURE-6871, SURE-7365(?)

**Rancher Server Setup**
- Rancher version: 2.7.6
- Fleet version: 102.1.1+up0.7.1

**Information about the Cluster**
- Kubernetes version: v1.26.6+rke2r1

- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When editing a GitRepo changing from watch a Revision (tag) to Branch results in an error: Invalid Commit Id

**To Reproduce**
- Create a GitRepo
- Watch a Revision and Save
![Screenshot 2023-09-06 at 09 39 37](https://github.com/rancher/rancher/assets/8233206/ebe1dee6-cbdf-4a70-bca5-ae1d1195795d)
- Change to Watch a Branch as Save
![Screenshot 2023-09-06 at 09 39 52](https://github.com/rancher/rancher/assets/8233206/0d570317-c578-4d45-8ab7-268d2a479a26)

**Result**
Error: Invalid Commit Id

![Screenshot 2023-09-06 at 09 40 07](https://github.com/rancher/rancher/assets/8233206/d16b900c-afe8-44a3-ab16-9c032ca7de6b)

**Expected Result**
No error, GitRepo watches the Branch

**Additional context**
Changing the tag to a full commit id and then back to Branch works.

**Comment by bvankampen** [comment]
@thardeck I still can reproduce the issue with Rancher 2.8.0 with Fleet 0.9.0. Please let me know if you need more information.

**Comment by sbulage** [comment]
### **System Information:**

Rancher Version: `2.9-head`
Fleet Version: `fleet:104.0.0+up0.10.0-rc.11`


### Scenario's checked:
### 1. Test GitRepo deploys application without any error when change branch with tag --> :heavy_check_mark: 

1. Created a GitRepo with branch.
2. Checked that application is deployed successfully.
3. Edited GitRepo by changing branch to revision/tag.
4. Verified that installed application is not changed
5. Verified that there is no error in the UI after changing branch to tag.

**Comment by sbulage** [comment]
### Scenario's Un-checked: (In-Progress)
### 1. Test GitRepo deploys application without any error when change tag with branch --> :red_circle:  

1. Created a GitRepo with tag.
2. Checked that application is deployed successfully.
3. Edited GitRepo by changing revision/tag to branch.
4. Verified that installed application is not changed
5. Verified that there is no error in the UI after changing revision/tag to branch.

**Comment by sbulage** [comment]
#2404 and #2403 will fix the second scenario.

**Comment by sbulage** [comment]
> ~### Scenario's Un-checked: (~In-Progress~ Not Working as expected.)~

This scenario is working as expected.
> ~### 1. Test GitRepo deploys application without any error when change tag with branch --> 🔴~

 ### 1. Test GitRepo deploys application without any error when change tag with branch --> ✔️
> 1. Created a GitRepo with tag.
> 2. Checked that application is deployed successfully.
> 3. Edited GitRepo by changing revision/tag to branch.
> 4. Verified that installed application is not changed
> 5. Verified that there is no error in the UI after changing revision/tag to branch.

**Comment by sbulage** [comment]
**- Created GitRepo with tag/revision**

![Screenshot from 2024-06-12 16-47-15](https://github.com/rancher/fleet/assets/12134754/764dea83-3d75-4bd3-9c78-12ba0d24f861)

---
**- Changed to `main` branch from tag/revision**

![Screenshot from 2024-06-12 16-48-19](https://github.com/rancher/fleet/assets/12134754/edaf0b94-78f0-4732-b28e-c67541d30e57)
