### ISSUE TITLE
Change CLI to fleet and not flt

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/fleet#18]
The feedback, which seems valid, is that it's better if it's a simple word that can be easily typed the same way you say it.  Basically avoid saying, "Hey type fleet apply, that's F, L, T space apply."

**Comment by avirekghatia** [comment]
I would like to take this issue. Should the var names also change (like the names of vars and structs) or should it be just the commands?

**Comment by cloudnautique** [comment]
This seems to be resolved. Closing.
