### ISSUE TITLE
Fleet reports namespace as missing after upgrade to v0.8.0

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1839]
## SURE-6997

Issue description:

After a fleet upgrade to 0.8, the users are seeing issues with one of their trident-operator namespace, which is showing as missing:

~~~
Modified(3) [Cluster fleet-default/c-7fb4v]; NotReady(1) [Cluster fleet-default/c-z4mz7: not installed: rendered manifests contain a resource that already exists. Unable to continue with install: Namespace "trident-csi" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "trident"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "trident-csi"]; namespace.v1 trident-csi missing 
~~~

Initially, they believe that it has something to do with two GH issues [link1|https://github.com/rancher/fleet/pull/1627 [] |http://example.com]][2]/][link2|https://github.com/rancher/fleet/issues/1553|https://github.com/rancher/fleet/issues/1553]

They tried to fix the reported missing labels and annotations, which are now on the namespace, but Fleet still doesn't see the existing namespace as part of the git-repo:

~~~
// Script for annotations:
#!/bin/sh
# Fix the labels and annotations on the Trident Operator namespace

# Wait for Fleet created the trident-csi namespace
#!/bin/bash
retry=10
while [ $retry -gt 0 ]
do
    kubectl get namespace trident-csi
    if [ $? -eq 0 ]
    then
        break
    fi
    sleep 5
    retry=$(($retry-1))
done

# This label and annotation can be removed after the 'namespace' issue is resolved
kubectl label namespace trident-csi app.kubernetes.io/managed-by=Helm --overwrite
kubectl annotate namespace trident-csi meta.helm.sh/release-name=trident --overwrite
kubectl annotate namespace trident-csi meta.helm.sh/release-namespace=trident-csi --overwrite

# The Trident Operator tries to set the PSS level, but did not have the correct access rights.
# Therefore label the trident-csi namespace from here
kubectl label namespace trident-csi pod-security.kubernetes.io/enforce=privileged --overwrite 
~~~

Their fleet repo has the following structure

(see also JIRA)

~~~
└── trident-operator
    ├── fleet.yaml
    └── overlays
        ├── kustomization.yaml
        ├── namespace.yaml
        └── operator-deployment.yaml
~~~
 

The namespace "trident-csi" still exists. The customer would like to know if this can be fixed without the destruction of their PVC's and PVs associated with it. We tested "TakeOwnership" helm property but it did nothing in this case; the namespace is still not seen as part of the application or owned by it.

They ran a test on a similarly structured repo "ns-test", to check the safety of removing namespace.yaml, from kustomization.yaml, so that helm can define and "own" the namespace directly from fleet.yaml. Removing the namespace.yaml from kustomise destroys the namespace (namespace will be terminated) with all associated resources, so we assume that it may have a destructive effect on the storage as well.

### Business impact:
Upgrade to fleet 0.8 caused issues with trident-csi which the customer uses in their storage solution and we have not found a non-destructive workaround for this so far.

### Troubleshooting steps:
For "ns-test" (because trident-csi would destroy the existing PVCs)

### Test details:

(see JIRA)

1. fleet yaml -> Kustomize

2. ! namespace (no namespace)

All is well ^

3. Add a namespace.yaml to the kustomize.yaml

4. "namespace missing"

5. remove namespace.yaml from kustomize.yaml

6. deletion of complete namespace

7. When namespace deleted: we press "Force Update" in the web interface

8. The namespace gets recreated as if new. (So also empty of any PVC's or PV's since they were deleted with the namespace.)

### Question:

Is fleet or kustomize "owner" of namespaces? This question is because when watching the resources, the namespaces that fleet should own, also defined in kustomise namespaces.yaml is updated very frequently compared to others:

Can we prevent namespaces from being deleted by Fleet, kustomize or anything else?

### Workaround:
Is workararound available and implemented? no
What is the workaround:

### Actual behavior:
After upgrade Fleet lost control of the "trident-csi" namespace

### Expected behavior:
Even after an upgrade Fleet should recognize and own the trident-csi namespace without termination.

**Comment by manno** [comment]
This is the same issue as in https://github.com/rancher/fleet/issues/1461

**Comment by kkaempf** [comment]
closing as duplicate
