### ISSUE TITLE
Fleet at scale: Reliable, repeatable and comparable benchmarks (baseline)

### ISSUE THREAD

**Issue by p-se** [rancher/fleet#1850]
In the light of soon upcoming refactorings, it is suggested to create a reliable, repeatable and comparable benchmark for testing the performance and limitations of Fleet at scale. For this reason information has been compiled which can support in creation such an environment at https://github.com/rancher/fleet/issues/1739#issuecomment-1755480848.

**Comment by manno** [comment]
Let's do a reliable, manual benchmark first
