### ISSUE TITLE
Backup/Restore ResourceSet investigation

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1882]
Fleet team need to check:

> Backup-Restore Operator will backup exactly the resources mentioned in this resourceSet and the operator will restore those resources on the target cluster of migration. Once those resources are restored, the backup operator has functioned correctly, if those resources and the controllers working on them are unable to bring back that functionality after restore, respective teams need to analyze/fix those.

**Comment by manno** [comment]
See SURE-7117 for more information. Since this is targeted at 2.7 I'm changing the milestone. The fix won't be needed after Fleet upgrades to wrangler/v2.

Repo for the fix is: 
https://github.com/rancher/backup-restore-operator

**Comment by manno** [comment]
We discussed with BRO team recently.
