### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by guitarmanvt** [rancher/fleet#1906]
The README contains typos. As a first-time reader, I found this distracting.

I will bring a Pull Request for this file; however, I was unable to locate the documentation sources for https://fleet.rancher.io/ , so I think the most visible problem will still remain. How can I get access to bring Pull Requests to those docs, please?

**Comment by weyfonk** [comment]
Hi @guitarmanvt, thanks for raising this. Our docs repo is [rancher/fleet-docs](https://github.com/rancher/fleet-docs), see [this PR](https://github.com/rancher/fleet-docs/pull/102).
