### ISSUE TITLE
Null values are not supported inside fleet.yaml

### ISSUE THREAD

**Issue by aruiz14** [rancher/fleet#1908]
There is a [test case](https://github.com/rancher/fleet-test-data/blob/c1d618133765a11595ceee5b5db020f4c6dbd937/helm-cluster-values/fleet.yaml#L25) that relies on `randNumeric 0` to return an empty string, hence causing `replicaCount` to be blank, which causes this value to be treated as `null`, and ultimately removing `replicas` field from the deployment spec.

This is based on undefined behavior from the patch updates mechanism that Apply uses, so it only works partially (more specifically, at object creation time), since the HelmOptions values are encoded as part of the payload instead of a text blob.

One possible option to fix it us to replace the `GenericMap` type with a text serialization of the values, which will ensure that the contents of the `values` field is preserved when stored into Kubernetes.

**Comment by manno** [comment]
Is this related to https://github.com/rancher/fleet/issues/2180?

**Comment by manno** [comment]
Doesn't seem urgent. We do not intend to work on it yet.
