### ISSUE TITLE
Convert GitJob to controller-runtime

### ISSUE THREAD

**Issue by raulcabello** [rancher/fleet#1919]
This project is isolated and should be easier to migrate from wrangler to controller-runtime, giving us a good idea of the effort for migrating other components of the fleet controller.
During this migration, it will be likely a requirement that a new scheduling mechanism is added, replacing the use of the informers `workqueue` to schedule future runs of the handlers.

In addition, we can revisit if we really need to use the batch Kubernetes API to create `Jobs`, or they can be just replaced by creating pods directly (using `restartPolicy: never` makes the pod not to be restarted when it finishes).

**Comment by olblak** [comment]
@raulcabello Can we close this issue?
