### ISSUE TITLE
Support for using/filling variables at runtime

### ISSUE THREAD

**Issue by smnmtzgr** [rancher/fleet#193]
It would be good to have a mechanism that enables users to use variables in the git-repo which are populated at runtime, e.g. before applying the resources to the k8s-clusters.

This mechanism should enable users to define dynamic variables which are different between clusters. E.g. when using "external-dns" one would need other parameters based on where the k8s-cluster is deployed.

My goald would be to make the git-repo very generic so that I doesnt have to edit it (push new things...) everytime a new cluster is generated.
My preferred workflow should be:
1) create K8S-Cluster with terraform -> already working
2) import it into rancher -> already working
3) add the cluster into a fleet cluster group based on a label -> already working
4) use the defined git-repo for fleet and deploy things like ingress-nginx, external-dns..... per cluster, but partially with different values. 

Other examples and information are discussed here: based on this discussion: https://rancher-users.slack.com/archives/C013SSBKB6U/p1607538982296500?thread_ts=1607538982.296500&cid=C013SSBKB6U

gz#14407

**Comment by paulchoi** [comment]
I would love to be able to fill in the cluster name as a variable.
When deploying a monitoring/logging agent, I like to identify the cluster by its name. Right now I'd need to create a separate overlay per cluster.

**Comment by kkaempf** [comment]
Should be fixed by #1164
