### ISSUE TITLE
unknown field "*correctDrift"

### ISSUE THREAD

**Issue by strowi** [rancher/fleet#1933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

fleet-agent v0.8.0 produces a lot of log-spam a la :

```bash
time="2023-11-07T15:08:40Z" level=info msg="Deploying bundle cluster-fleet-default-c-s656z-f15871fba9c8/local-path-provisioner-local-path-provisioner"
W1107 15:08:40.149238       1 warnings.go:70] unknown field "spec.correctDrift"
W1107 15:08:40.149265       1 warnings.go:70] unknown field "spec.options.correctDrift"
W1107 15:08:40.149270       1 warnings.go:70] unknown field "spec.stagedOptions.correctDrift"
W1107 15:08:40.149275       1 warnings.go:70] unknown field "status.resources"
...
```

Although i haven't set "correctDrift" anywhere in GitRepo, Bundle these appear for every bundle that gets deployed (as far as i can see).

These also clutter the audit-Logs of rancher itself quite heavily.

### Expected Behavior

Do not throw those warnings.

### Steps To Reproduce

1. install rancher-2.7.6/2.7.9
2. import a custom cluster to rancher
3. check logs on fleet-agent to see those warnings.

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.8.0
- Cluster:
  - Provider: k3s
  - Options:
  - Kubernetes Version: 1.27
```

### Logs

```markdown
W1107 15:09:26.845838       1 warnings.go:70] unknown field "spec.correctDrift"
W1107 15:09:26.845854       1 warnings.go:70] unknown field "spec.options.correctDrift"
W1107 15:09:26.845865       1 warnings.go:70] unknown field "spec.stagedOptions.correctDrift"
W1107 15:09:26.845870       1 warnings.go:70] unknown field "status.resources"
W1107 15:09:26.907719       1 warnings.go:70] unknown field "spec.correctDrift"
W1107 15:09:26.907740       1 warnings.go:70] unknown field "spec.options.correctDrift"
W1107 15:09:26.907745       1 warnings.go:70] unknown field "spec.stagedOptions.correctDrift"
W1107 15:09:26.907749       1 warnings.go:70] unknown field "status.resources"
```

### Anything else?

Downgrading fleet to 0.7.0 seems to silence the logs again.

**Comment by manno** [comment]
Probably an issue with the CRD chart version not matching the fleet chart version.

**Comment by strowi** [comment]
Seems right. The error has been gone with one of the recent updates of rancher.
