### ISSUE TITLE
HTTP basic auth secret not removed when git repo is removed

### ISSUE THREAD

**Issue by dnoland1** [rancher/fleet#197]
1. In the Rancher v2.5.3 UI, go to Continous Delivery
2. Create a new git repo named "test". For authentication, select "Create a HTTP Basic Auth Secret" and enter a made up username and password. Click the create button
3. Note that a secret in the fleet-default namespace is created called "test":
```
$ kubectl get secrets -n fleet-default test
NAME                                                              TYPE                                          DATA   AGE
test                                                              kubernetes.io/basic-auth                      2      10m
```
Delete the "test" git repo. Note that the secret is not removed. It should be cleaned up.

**Comment by haswalt** [comment]
Appears to be any auth secret as I'm seeing the same with `kubernetes.io/ssh-auth`.

Because fleet stores these secrets in the local cluster there isn't a quick and obvious way to access, edit and remove these secrets when you are using cluster explorer.

**Comment by kkaempf** [comment]
too old
