### ISSUE TITLE
Remove cluster node status reporting from agent

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1973]
The agent reports the node status of the cluster it's running on. 

It [lists all nodes](https://github.com/rancher/fleet/blob/master/internal/cmd/agent/clusterstatus/ticker.go#L75) every 15min, or by the amount configured as `CheckInterval` in the agents config.

Since it also updates a timestamp, the bundledeployment is changed.

The UI only displays the timestamp for the clustergroups  `Last seen` column.

We could remove the node count and status reporting.

This is a follow-up to #1772

**Comment by 0xavi0** [comment]
# QA Template

## Solution
Deletes some information provided by `fleet` for the clusters.
Before this change we can get the following information from clusters:
```bash
$ kubectl get clusters -A                                                                                                                                                                                                                                                                                    
NAMESPACE     NAME    BUNDLES-READY   NODES-READY   SAMPLE-NODE             LAST-SEEN              STATUS
fleet-local   local   1/1             3/3           k3d-upstream-server-0   2024-03-13T10:34:07Z   
```

The change removes the values reported for "NODES-READY and SAMPLE-NODE".

## Testing
Just run a command to retrieve all clusters and you should not see the NODES-READY nor SAMPLE-NODE columns
Something like:
```bash
$ kubectl get clusters -A                                                                                                                                        
NAMESPACE     NAME    BUNDLES-READY   LAST-SEEN              STATUS
fleet-local   local   1/1             2024-03-13T10:49:27Z  
```

## Additional info

**Comment by thehejik** [comment]
### Test report
Tested on rancher `v2.9-c9be13b09329bbee60a5f6419d500198f83c44d1-head` with fleet App `fleet:104.0.0+up0.10.0-rc.11`

```
$ kubectl get clusters.fleet.cattle.io -A
NAMESPACE       NAME     BUNDLES-READY   LAST-SEEN              STATUS
fleet-local     local    1/1             2024-04-18T14:11:58Z   
fleet-default   dhcp12   2/2             2024-04-18T14:16:11Z   
```

Also in this diff it is visible that status information are reduced in `clusters` resource in v2.9 versus v2.8 and `fleet:103.1.3+up0.9.3-rc.3`:

![image](https://github.com/rancher/fleet/assets/12828077/bd191a55-3428-411f-8abf-87a2d6e78f8b)
