### ISSUE TITLE
Stuck on git updating when repo has directories with uppercase letters

### ISSUE THREAD

**Issue by dnoland1** [rancher/fleet#198]
1. In Rancher v2.5.3, go to Continuous Delivery
2. Add a git repo and use the repo https://github.com/dnoland1/fleet-test.git, master branch, click Create button.
Status is stuck in "Git Updating". If you click into the repo, you see the red error:
```
fleet-default/mytest time="2020-12-23T21:52:17Z" level=fatal msg="Bundle.fleet.cattle.io \"mytest-UbuntuTest\" is invalid: metadata.name: Invalid value: \"mytest-UbuntuTest\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')" 
```
![image](https://user-images.githubusercontent.com/468462/103039839-b1dc2300-4526-11eb-88f0-45ad482a47f4.png)

This appears to happen if the git repo has a directory that contains uppercase letters. In my example, there's a folder called "UbuntuTest".

gz#14549

**Comment by kravciak** [comment]
I reproduced on 3.5.3 and tested the fix on 2.5.6-rc4, it worked fine for me.
