### ISSUE TITLE
Eliminate the need for diffing customizations for well-known k8s types

### ISSUE THREAD

**Issue by ron1** [rancher/fleet#199]
Fleet should not require diffing customizations for well-known k8s types. The out-of-the-box Argo-CD `Diffing Customization` feature supports the following well-known k8s types: https://raw.githubusercontent.com/argoproj/argo-cd/master/util/argo/normalizers/diffing_known_types.txt. Fleet should likewise eliminate the need for diffing customizations for these types. Fleet should also allow "known type field" mapping for CRDs like the Argo-CD feature described here:  https://argoproj.github.io/argo-cd/user-guide/diffing/#known-kubernetes-types-in-crds-resource-limits-volume-mounts-etc.

**Comment by ron1** [comment]
See related issue https:/github.com/rancher/fleet/issues/189

**Comment by eest** [comment]
Is this ticket related to https://github.com/rancher/fleet/pull/291 that was worked on by @StrongMonkey ?
