### ISSUE TITLE
[v0.8] Azure Webhook Support [SURE-7047]

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1998]
backport of https://github.com/rancher/fleet/issues/1997

**Comment by raulcabello** [comment]
# QA Template

## Solution
Add webhook support for Azure Webhooks. It works the same way as existing webhooks for `GitHub`, `Gitlab` and `BitBucket`

## Testing
- Verify webhook in azure are working when no basic authentication is provided
- Wrong basic auth credentials should show an error, and it should not update the Bundle
- Valid auth credentials should work fine
- Webhooks for other providers (`GitHub`, `Gitlab` and `BitBucket`) should keep working

## Additional notes
- How to create Azure Devops Webhooks https://learn.microsoft.com/en-us/azure/devops/service-hooks/services/webhooks?view=azure-devops-2020
- How to configure webhooks in fleet https://fleet.rancher.io/webhook
- Make sure the `syncInterval` is set to something very high (e.g 10000), so it does not interfere with the webhook tests

**Comment by thehejik** [comment]
### Test report
* Works as expected for HTTPS Azure repos. 
* Verified it doesn't work for SSH Azure DevOps repos (support has been added to [v0.9.0 only](https://github.com/rancher/gitjob/pull/446))

#### Environment
Tested on local k3s with `v1.27.10+k3s2` on Prime `rancher:v2.7.11` with fleet App `fleet:102.2.2+up0.8.2` using following images:
```
registry.rancher.com/rancher/gitjob:v0.8.2
registry.rancher.com/rancher/fleet:v0.8.2
registry.rancher.com/rancher/fleet-agent:v0.8.2
```

#### Testing
1) Added an Azure DevOps private HTTPS GitRepo into fleet-local workspace with "disabled" polling via `spec.pollingInterval: 48h` set for GitRepos.

2) Created webhook secret for Azure:
```bash
kubectl create secret generic gitjob-webhook -n cattle-fleet-system \
  --from-literal=azure-username=<username> \
  --from-literal=azure-password=<password>
```
3) Made a change in Azure repo and pushed to origin, observing output on local cluster:
```bash
kubectl logs -n cattle-fleet-system -lapp=gitjob -f
```

* With wrong password set on Azure webhook - no change noticed
```
time="2024-03-11T15:03:29Z" level=debug msg="Webhook payload <nil>"
time="2024-03-11T15:03:29Z" level=error msg="Webhook processing failed: basic auth verification failed"
```

* With correct password set - change noticed and resources updated:
```
time="2024-03-11T15:02:16Z" level=debug msg="Webhook payload {..."
time="2024-03-11T15:02:16Z" level=debug msg="Enqueueing gitjob fleet-local/azure-https-wh in 172800 seconds"
time="2024-03-11T15:02:16Z" level=debug msg="Job change, syncing status for gitjob fleet-local/azure-https-wh: InProgress"
time="2024-03-11T15:02:16Z" level=debug msg="DesiredSet - Created batch/v1, Kind=Job fleet-local/azure-https-wh-0117a for sync-repo fleet-local/azure-https-wh"
time="2024-03-11T15:02:16Z" level=debug msg="DesiredSet - Delete batch/v1, Kind=Job fleet-local/azure-https-wh-5fd1c for sync-repo fleet-local/azure-https-wh"
time="2024-03-11T15:02:16Z" level=debug msg="Enqueueing gitjob fleet-local/azure-https-wh in 172800 seconds"
```

**Comment by kkaempf** [comment]
closing as of last comment.
