### ISSUE TITLE
Is fleet compatible with Managed Clusters?

### ISSUE THREAD

**Issue by shadycuz** [rancher/fleet#20]
When I hear the term "Managed Kubernetes" I think of hosted Kubernetes solutions like AWS, GCP and Digital Ocean. 

Since fleet uses the term "manage" 11 times in the readme and in the blog post it's not obvious to me if this works with "Managed" clusters or not. 

From the install instructions, it appears that it wouldn't matter if you had control over the Kubernetes Master servers and all fleet is really doing is taking care of what's deployed on the cluster. 

I really like the word fleet as it conveys really well the spirit of this project. I'm less convinced by the term "manage" as it already has a strong presence in the kubernetes community. 

I would also think about renaming the fleet manager to fleet controller or fleet master. 

I like what fleet is doing. I don't write much go but would love to contribute from time to time. Do you have a slack or gitter?

**Comment by cloudnautique** [comment]
@shadycuz, yes Fleet can be used on EKS, GKE, AKS and other hosted Kubernetes solutions. This project is now integrated into the Rancher 2.5 release and all clusters are automatically registered to it. 

We have a Slack workspace, and you can sign up on rancher.slack.io
