### ISSUE TITLE
Allow Diffing Customizations to be defined at a System-Level and not just within a GitRepo

### ISSUE THREAD

**Issue by ron1** [rancher/fleet#200]
I understand that `diff.comparePatches` can only be defined within a Fleet GitRepo currently. Fleet should also allow `diff.comparePatches` to be defined at a System-Level maybe via a ConfigMap like Argo-CD allows its similar `ignoreDifferences` feature to be defined here: https://argoproj.github.io/argo-cd/user-guide/diffing/#system-level-configuration.

**Comment by kkaempf** [comment]
should be fixed by #291
