### ISSUE TITLE
[SURE-7341] Override drift correction via targetCustomization

### ISSUE THREAD

**Issue by manno** [rancher/fleet#2001]
forward port of  https://github.com/rancher/fleet/issues/1794

**Comment by raulcabello** [comment]
# QA Template

## Solution
drift correction options added to `targetCustomization` in the `fleet.yaml`, so it can be overridden per clusters 

## Testing
Create a `GitRepo` with `correctDrift` configured, and override the configuration in the `targetCustomization` in the `fleet.yaml`.

## Additional info
Needs a new fleet RC

**Comment by mmartin24** [comment]
### QA Report

Retested as done for 2.8.3 [here](https://github.com/rancher/fleet/issues/1794#issuecomment-1983839123)  (also specified in [QASE: Fleet-102](https://app.qase.io/project/FLEET?suite=5&previewMode=side&case=102))

Tested on `v2.9-06d0eb0e18bec11752905ed6e9e7bca811dfbb5e-head` with Kubernetes version `v1.27.10+k3s1`
Tested on `v2.8-d2244ae036b6f5bcf6cd19716181ed258d9d513b-head`, then upgraded to `v2.9-06d0eb0e18bec11752905ed6e9e7bca811dfbb5e-head` with Kubernetes version `v1.27.10+k3s1`

---

#### Summary:
- Added labels to downstream clusters in `fleet-default` namespace
  - Cluster `117` has `environment: prod` label
  - Cluster `lub` has `environment: dev` label
- Added [driftoverride](https://github.com/fleetqa/fleet-qa-examples-public/tree/main/driftoverride) git repo with simple nginx app with fleet yaml containing `correctDrift: false` for `dev` environment and `correctDrift: true` for `prod` env. 
 
#### Observed:
- `Prod` environment, pointed through labels where `correctDrift` was set to `true`  DID NOT change replicas
- `Dev` environment, pointed through labels where `correctDrift` was set to `false` DID change replicas

  - After `Force Update` the amount of replicas on dev environment was reverted back to value defined in last commit (3, in this case)
 
Adding here a video better showing all this:

https://github.com/rancher/fleet/assets/37271841/9632dce2-f881-4f37-bf3f-c5a0d602d4e3


Working as expected. Closing ticket
