### ISSUE TITLE
[SURE-6203] Fleet deploying same repo multiple times

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#2002]
## SURE-6203

We're trying to debug a issue a customer is having that we suspect could be related to https://github.com/rancher/fleet/issues/344. There are two similar fleet manifests, one targeting an internal cluster, and the other targets an external cluster. They both use the same git repositories but with different paths, and the manifests select their respective clusters using targets clusterName.

What they're running into when deploying is the rancher interface shows deployment errors as if the deployment for the external cluster is also trying to deploy to the internal cluster, and erroring out. When the client checks the deployments manually, the resources actually being created match what they configured as intended.

### Business impact:
Fleet cannot deploy a repo more than once without looking like it fails

### Repro steps:

The fleet definitions look like:
~~~
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: aaa-001-ext
  namespace: fleet-default
spec:
  branch: cat2
  clientSecretName: secretToken
  insecureSkipTLSVerify: true
  paths:
  - ./k8s-resources/config-maps/external
  - ./k8s-resources/ingresses/external
  - ./k8s-resources/network-policies/external
  - ./k8s-resources/secrets/external
  - ./session-management
  pollingInterval: 60s
  repo: https://repo_url/
  targetNamespace: customNamespaceName
  targets:
  - clusterName: cluster001
~~~
  
and

~~~
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: aaa-001
  namespace: fleet-default
spec:
  branch: cat2
  clientSecretName: secretToken
  forceSyncGeneration: 3
  insecureSkipTLSVerify: true
  paths:
  - ./k8s-resources/config-maps/internal
  - ./k8s-resources/ingresses/internal
  - ./k8s-resources/network-policies/internal
  - ./k8s-resources/persistent-volume-claims/internal
  - ./k8s-resources/secrets/internal
  - ./path1
  - ./path2
  - ./path3
  - ./path4
  pollingInterval: 60s
  repo: https://repo_url/
  targetNamespace: customNamespaceName
  targets:
  - clusterName: cluster002
~~~ 

### Workaround:
Is workararound available and implemented? no
What is the workaround:

### Actual behavior:
The UI shows errors, but it deploys

**Comment by manno** [comment]
closed in JIRA
