### ISSUE TITLE
Merge Gitjob Controller into Fleet Controller / Chart

### ISSUE THREAD

**Issue by manno** [rancher/fleet#2008]
[rancher/gitjob](https://github.com/rancher/gitjob) is only used by Fleet, and adds to its maintenance/release overhead, both for Go code and for charts.
Instead, we could integrate `rancher/gitjob` contents into `rancher/fleet` and manage all Fleet-related logic from there.

Note:
Merging gitjob into the same code base adds some interesting possibilities in the future. We might be able to remove the gitjob CRD, the gitjob container image, so we have less complexity and a smaller download size.
This will become clearer when be build OCI repo support, but gitjob/gitrepo are as much their own component as oci repo is. So the split between gitjob vs gitrepo doesn’t make sense. Eventually, we might have “bundle” producing components (gitrepo, ocirepo) and a component which distributes bundles to clusters (fleetcontroller/targetting).
So, in short, we’re moving gitjob now, so maintenance and releases get easier, but it will also enable a clearer design in the future.

This would require us to:
- [x] move tests
- [x] remove the `gitjob` helm chart, placing it in the `fleet` chart (no more sub chart)
- [x] move the gitjob controller into fleet, keep it in a separate pod (it polls an external resource)
- [x] adapt drone workflow to publish image
- [ ] remove "subchart config" from rancher/charts a
- [x] optional, move into same directory struct as fleet (`internal/cmd/gitjob`)
- [x] can we get rid of the `GitJob` resource in the future and use GitRepo instead?
- [x] keep the webhook in the same pod as gitjob

## More housekeeping (in no particular order)
- [x] remove updatecli job
- [x] check `.gitignore`
- [x] update references to `rancher/gitjob` in docs throughout `rancher/fleet`
- [x] remove script `.github/scripts/check-for-gitjob-changes.sh`

**Comment by weyfonk** [comment]
Once #2098 is merged:
* Cherry-pick [gitjob#421](https://github.com/rancher/gitjob/pull/421)
* Cherry-pick [gitjob#422](https://github.com/rancher/gitjob/pull/422)

**Comment by weyfonk** [comment]
When next releasing Fleet from a branch including #2098:
- [ ] Remove [packages/fleet/gitjob](https://github.com/rancher/charts/tree/dev-v2.9/packages/fleet/gitjob) from `rancher/charts`' target branch (eg. by editing the PR generated by [release-against-charts](https://github.com/rancher/fleet/actions/workflows/release-against-charts.yml))
- [ ] Check if newly generated `index.yaml` entry in `rancher/charts` still includes gitjob as a chart; it should not.
- [ ] Check that [packages/fleet/fleet/generated-changes](https://github.com/rancher/charts/tree/dev-v2.9/packages/fleet/fleet/generated-changes) no longer contains references to `gitjob`
