### ISSUE TITLE
[SURE-7216] Some resources remain even after custom RKE1 cluster was deleted

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#2013]
## Follow up on SURE-6578
See also https://github.com/rancher/fleet/issues/1674

> the similar issue was previously addressed and worked on in ticket SURE-6578, with details available on [GitHub issue](https://github.com/rancher/fleet/issues/1674).
> However, it seems that the stale resources are only deleted by the provided fix during a Rancher/Fleet upgrade not when manually deleting a cluster, which is a current requirement.

**Comment by kkaempf** [comment]
@weyfonk commented

> This issue also occurs with Fleet standalone in k3d-managed clusters, as tested via Fleet's own [dev/setup-multi-cluster](https://github.com/rancher/fleet/blob/v0.9.0/dev/setup-multi-cluster) script on v0.9.0:
> ~~~
> $ kc get clusterregistration.fleet.cattle.io -A
> NAMESPACE     NAME            CLUSTER-NAME   LABELS
> fleet-local   request-6v9zg   local          {"fleet.cattle.io/created-by-agent-pod":"fleet-agent-dc85ffb5b-xv9tz","name":"local"}
> $ kc get rolebinding.rbac.authorization.k8s.io -A
> NAMESPACE                                NAME                                                              ROLE                                                                 AGE
> [...]
> fleet-local                              import-token-local-a3df0482-f221-4d01-a93b-67d55d14f109-to-role   Role/import-token-local-a3df0482-f221-4d01-a93b-67d55d14f109-role    33m
> fleet-local                              request-6v9zg                                                     Role/request-6v9zg                                                   33m
> [...]
> $ kc get role.rbac.authorization.k8s.io -A
> NAMESPACE                      NAME                                                            CREATED AT
> [...]
> fleet-local                    import-token-local-a3df0482-f221-4d01-a93b-67d55d14f109-role    2023-12-15T08:51:07Z
> fleet-local                    request-6v9zg                                                   2023-12-15T08:51:13Z
> [...]
> $ k3d cluster delete downstream
> INFO[0000] Deleting cluster 'downstream'                
> INFO[0002] Deleting 1 attached volumes...               
> INFO[0002] Removing cluster details from default kubeconfig... 
> INFO[0002] Removing standalone kubeconfig file (if there is one)... 
> INFO[0002] Successfully deleted cluster downstream!     
> $ kc get role.rbac.authorization.k8s.io -n fleet-local                                                                                                                                                                                           
> NAME                                                           CREATED AT
> import-token-local-a3df0482-f221-4d01-a93b-67d55d14f109-role   2023-12-15T08:51:07Z
> request-6v9zg                                                  2023-12-15T08:51:13Z
> $ kc get rolebinding.rbac.authorization.k8s.io -n fleet-local                                                                                                                                                                                    
> NAME                                                              ROLE                                                                AGE
> import-token-local-a3df0482-f221-4d01-a93b-67d55d14f109-to-role   Role/import-token-local-a3df0482-f221-4d01-a93b-67d55d14f109-role   34m
> request-6v9zg                                                     Role/request-6v9zg                                                  34m
> $ kc get clusterregistration.fleet.cattle.io -n fleet-local                                                                                                                                                                                      
> NAME            CLUSTER-NAME   LABELS
> request-6v9zg   local          {"fleet.cattle.io/created-by-agent-pod":"fleet-agent-dc85ffb5b-xv9tz","name":"local"}
> ~~~
> We need to check if this happens with the latest state of rancher/fleet's master, post migration to controller-runtime.
> 
> Results of those tests will inform the way forward, ie whether this is a matter of eg. implementing [Finalizers.](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/)

**Comment by kkaempf** [comment]
Moving to milestone 2.9, awaiting controller-runtime implementation.

**Comment by manno** [comment]
Needs ownership on the resources which are left behind after deleting  a cluster. That would trigger garbage collection.

**Comment by kkaempf** [comment]
wontfix.
Workaround exists and RKE1 is being phased out
