### ISSUE TITLE
[SURE-7253] Git pull issues

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#2023]
GitRepos are in an error state because the git server was probably not available for some time (500 Internal server error)
The behaviour seems random, and the error message disappears/is fixed when using force-update on the GitRepo, but it will re-occur, and the user has not noticed or tracked it for self-healing behaviour so far.
Rancher 2.7.6
Fleet 0.8

**Comment by manno** [comment]
Fixed in JIRA
