### ISSUE TITLE
Request entity too large

### ISSUE THREAD

**Issue by arifulislamat** [rancher/fleet#205]
Error: time="2020-12-30T06:44:28Z" level=fatal msg="Request entity too large: limit is 3145728"

I was trying to use the "continuous delivery", I have add my git repo but getting this error.

**Comment by kkaempf** [comment]
Workaround exists.

**Comment by iosifnicolae2** [comment]
wouldn’t be possible to store the content of the git repository in memory or in /tmp dir and on reboot, fetch the repository content again from git?

**Comment by naisanzaa** [comment]
I am having the exact came problem

**Comment by iosifnicolae2** [comment]
> I am having the exact came problem

In our case, the solution was not to use Sealed Secrets and then break the yaml files in multiple folders and then configure in Fleet each path separately.

**Comment by naisanzaa** [comment]
> > I am having the exact came problem
> 
> In our case, the solution was not to use Sealed Secrets and then break the yaml files in multiple folders and then configure in Fleet each path separately.

For me the GitHub repo doesn't add at all using all default settings and an https public GitHub repo
