### ISSUE TITLE
[v0.9] Reduce BundleDeployment triggering based on deployed resources changes

### ISSUE THREAD

**Issue by aruiz14** [rancher/fleet#2058]
Fleet agents have a mechanism to watch every individual resource that is deployed from a `BundleDeployment`. These [watch events](https://pkg.go.dev/k8s.io/apimachinery/pkg/watch#Event) can be of multiple types, but the current implementation processes `ADDED`, `MODIFIED` and `DELETED` events in order to trigger a BundleDeployment reconciliation, which then should detect any drift between the desired and current state of all the deployed objects.
This operation can be expensive (although it's run on the agent), but since it updates the status conditions in the BundleStatus, it may results on triggering the Fleet controller in the upstream cluster as well. The idea of this issue is to revisit this implementation in order to reduce the frequency of those actions.

**Comment by manno** [comment]
Reverting because of CPU usage problems: https://github.com/rancher/fleet/pull/2258
