### ISSUE TITLE
Fleet agent in downstream clusters dont get upgraded when one of the clusters is in "Error" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/fleet#206]
Fleet version - `rancher/fleet-agent:v0.3.2-rc6`
Steps to reproduce the issue:
In rancher server version 2.5.3 , deployed few clusters and created gitrepos to deploy apps in these clusters.
One of the clusters in the setup went to a bad state and was in "Error" state.

Upgrade to `v2.5-head`
After rancher server upgrade , `fleet-agent` got updated to `fleet-agent:v0.3.2-rc6` in the next 10 minutes.

Fleet agent did not get upgraded in any of the downstream clusters.

Once the cluster that was in "Error" state was deleted , fleet agents in the downstream clusters got upgraded to `fleet-agent:v0.3.2-rc6`.

gz#14550

**Comment by sangeethah** [comment]
@StrongMonkey Could you attach PR to this issue ?

**Comment by sangeethah** [comment]
Keeping this issue open to look into getting the default changed from 10% to a higher value.

**Comment by sowmyav27** [comment]
@StrongMonkey Reopening this issue to confirm if we want to change default  to 25% as discussed offline?

**Comment by janeczku** [comment]
We should also ensure, that clusters that the user has explicitly "paused" do not count while calculating the max. unavailable threshold.

**Comment by janeczku** [comment]
This seems to also cause newly added clusters to be stuck in "Waiting"  until the user performs a "Force Upgrade" on the cluster.

**Comment by jiaqiluo** [comment]
The bug fix is validated on the upgrade path from `v2.5.5` to `v2.5-head` a85f4d1

Fleet chart 0.3.400-rc06 is used in `v2.5-head`

Steps:
- run rancher/rancher:`v2.5.5` single install
- add multiple downstream clusters: c-1, c-2, c-3, c-4
- create a `gitRepo` to deploy [the `simple` app](https://github.com/rancher/fleet-examples/tree/master/simple) to all those downstream clusters 
- for each cluster, go to check the installed apps on the dashboard
- confirm that the `fleet-agent` app is installed successfully
- confirm that the `simple` app is installed successfully
- make one cluster to be in the `error` state by shutting down the node in AWS
<img width="1460" alt="Screen Shot 2021-02-22 at 11 50 17 AM" src="https://user-images.githubusercontent.com/6218999/108759874-2a9d3280-750a-11eb-8ce0-60aca6ca02d0.png">

- upgrade Rancher to `v2.5-head` a85f4d1
- wait about 10 mins for `fleet` to finish the upgrade 

Results:
- the `fleet-agent` in both the local cluster and downstream clusters are upgraded to the new version `0.0.0+s-b1f5756` automatically 
- existing `gitRepo` continue working 
- adding new `gitRepo` also works 

on the local cluster:
![image](https://user-images.githubusercontent.com/6218999/108764952-705cf980-7510-11eb-8c24-ef7a619610f7.png)

on the downstream cluster:
![image](https://user-images.githubusercontent.com/6218999/108765070-997d8a00-7510-11eb-819c-291869706e64.png)

**Comment by lbudai74** [comment]
We have upgraded rancher from 2.6.8 to 2.7.0 and the fleet-agent didn't got updated. We have the fleet controller 0.5.0 but the agent is 0.3.7 how can I move forward? (this is true for the local cluster as well)
Thanks.

**Comment by kkaempf** [comment]
@lbudai74 please open a new issue for that.
