### ISSUE TITLE
Feature Request: ValuesFrom using local cluster resources

### ISSUE THREAD

**Issue by shane-davidson** [rancher/fleet#2088]
### Is your feature request related to a problem?

Would it be possible to add support for ValuesFrom to be pulled from the local cluster?

Use cases would be syncing generated resources or things that can't easily be added to a git repo, such as:

- needing the same certificate from let's encrypt to be added to all downstream clusters. 

- Anything that uses a kubernetes operator to be generated but you need the "same" resource on the downstream clusters. 

- mapping the same dynamic volume (with the same ID) to multiple downstream clusters

**Comment by manno** [comment]
At this moment we don't plan to  implement secret/values management between upstream and downstream. You could use the external secrets operator. https://www.suse.com/c/rancher_blog/fleet-multi-cluster-deployment-with-the-help-of-external-secrets/
