### ISSUE TITLE
Backport Version Pinning to 2.7

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#2101]
This entails backporting the following to branch `release/v2.7`:
* [rancher#42304](https://github.com/rancher/rancher/pull/42304)
* [rancher#43498](https://github.com/rancher/rancher/pull/43498) - not yet merged because it targets Rancher 2.8.3, with 2.8.{1,2} still to be released.

**Comment by manno** [comment]
We are not planning to backport at this time.
