### ISSUE TITLE
[SURE-7117] Fleet controller won't function properly after a restore from backup due to lease lock configmap present

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#2120]
### Issue description:
After a customer migration from self-hosted Rancher to Hosted Rancher, the fleet-controller workload was stuck waiting for a lease lock.

### Business impact:

Fleet was not functioning properly.

### Troubleshooting steps:
Obtained fleet-controller logs. Investigated contents of backup file.

### Repro steps:

Create a backup using the rancher backup operator
On a new Kubernetes cluster, restore the backup

### Workaround:
Is workararound available and implemented? yes
What is the workaround: serveral - 1. remove the fleet-controller-lock configmap, 2. remove the fleet-controller-lock.json from the lock file. 3. Make sure fleet-controller workload is stopped when taking the backup

### Actual behavior:
Fleet-controller starts, but is waiting to obtain the lease lock indefinitely

### Expected behavior:
Fleet-controller starts normally.

### Files, logs, traces:

Fleet-controller log will have just a single line:
~~~
leaderelection.go:248] attempting to acquire leader lease cattle-fleet-system/fleet-controller-lock...
~~~
Example contents of backup:
~~~
backup/configmaps.#v1/cattle-fleet-system $ ls -l
total 32
8 -rw-r--r--@ 1 user  staff   616 Sep 20 11:55 fleet-controller-lock.json
8 -rw-r--r--@ 1 user  staff  1210 Sep 20 11:55 fleet-controller.json
8 -rw-r--r--@ 1 user  staff   577 Sep 20 11:55 gitjob.json
8 -rw-r--r--@ 1 user  staff  1709 Sep 20 11:55 kube-root-ca.crt.json 
~~~

**Comment by mmartin24** [comment]
QA will try to reproduce this issue.

**Comment by mmartin24** [comment]
I was not able to reproduce this issue with the following setup:
```
Rancher `v2.7.6`
Fleet version: `rancher/fleet:v0.7.1`
Rancher-backup version: `rancher/backup-restore-operator:v3.1.1`
```
---
Steps done for the backup:

- Successfully deployed locally gitrepo:
```
URL: https://github.com/rancher/fleet-examples
Branch: master
Path: simple
```
- Created s3 backup using the above-mentioned version. Result here: [276-local-b97d4a04-074d-4929-8fb8-5eab8a5ced51-2024-07-24T12-34-44Z.tar.gz](https://eu-central-1.console.aws.amazon.com/s3/object/epinio-ci?region=eu-central-1&bucketType=general&prefix=mmt-rancher-backup/276-local-b97d4a04-074d-4929-8fb8-5eab8a5ced51-2024-07-24T12-34-44Z.tar.gz)
- Created new cluster with exact same configuration as above
- Performed restore

Result: Backup is performed and applications are in place:
![image](https://github.com/user-attachments/assets/44dfbe70-54e0-4737-b28b-7cbaba3c5c71)

![image](https://github.com/user-attachments/assets/b52e6a8c-1a7d-4026-8ab5-a44a2c2ca1a0)

![image](https://github.com/user-attachments/assets/9d4d0544-c73c-4488-affa-1941e4e49d1d)

Logs on restore seemed ok:
```
k logs -n cattle-resources-system rancher-backup-c4d4fcb4b-hn2lp | tail 
INFO[2024/07/24 12:46:21] Marking resource rolebindings.rbac.authorization.k8s.io#v1/fleet-local/import-token-local-933e6ff5-fed0-4e69-89a0-951eb47c8da6-to-role for deletion 
INFO[2024/07/24 12:46:21] Marking resource rolebindings.rbac.authorization.k8s.io#v1/cattle-fleet-clusters-system/import-token-local-933e6ff5-fed0-4e69-89a0-951eb47c8da6-creds for deletion 
INFO[2024/07/24 12:46:21] Marking resource rolebindings.rbac.authorization.k8s.io#v1/cattle-fleet-clusters-system/import-token-local-933e6ff5-fed0-4e69-89a0-951eb47c8da6-creds for deletion 
INFO[2024/07/24 12:46:21] Marking resource secrets.#v1/cattle-system/rancher-token-kg78d for deletion 
INFO[2024/07/24 12:46:21] Marking resource secrets.#v1/cattle-system/rancher-token-kg78d for deletion 
INFO[2024/07/24 12:46:21] Will retry pruning resources by removing finalizers in 10s 
INFO[2024/07/24 12:46:31] Retrying pruning resources by removing finalizers 
INFO[2024/07/24 12:46:31] Processing controllerRef apps/v1/deployments/rancher 
INFO[2024/07/24 12:46:31] Scaling up controllerRef apps/v1/deployments/rancher to 1 
INFO[2024/07/24 12:46:31] Done restoring    
```

Logs on `fleet-controller` seemed ok also:
```
k logs -n cattle-fleet-system fleet-controller-79bdbcd9b4-2c4vr | tail                   
time="2024-07-24T12:48:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=Content controller"
time="2024-07-24T12:48:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=Bundle controller"
time="2024-07-24T12:48:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=ClusterGroup controller"
time="2024-07-24T12:48:10Z" level=info msg="All controllers have been started"
time="2024-07-24T12:48:10Z" level=info msg="Starting /v1, Kind=ServiceAccount controller"
time="2024-07-24T12:48:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=Cluster controller"
time="2024-07-24T12:48:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=GitRepo controller"
time="2024-07-24T12:48:10Z" level=info msg="Deleted old agent for cluster (fleet-local/local) in namespace cattle-fleet-local-system"
time="2024-07-24T12:48:11Z" level=info msg="Cluster import for 'fleet-local/local'. Deployed new agent"
time="2024-07-24T13:28:10Z" level=info msg="Deleting expired registration secret cattle-fleet-clusters-system/c-4d753ba9077397f672fd42630a52d7ffef9c61c1efed5641295fb1d5460a6"
```

Adding full logs here:
[276-fleetcontroller.log](https://github.com/user-attachments/files/16364737/276-fleetcontroller.log)
[rancher-backup-log-276.log](https://github.com/user-attachments/files/16364739/rancher-backup-log-276.log)

So, it seemed it worked at least in this particular version. Nevertheless, in future we should have lock files but not as configmaps so should not an issue.

Thanks. @p-se for the help here

**Comment by kkaempf** [comment]
closing
