### ISSUE TITLE
Replace Drone Pipeline With Github Workflow

### ISSUE THREAD

**Issue by manno** [rancher/fleet#2121]
We can start removing drone/dapper from Fleet. Looking at .drone.yaml we need a Github workflow to do the following when a release tag is pushed:
* run FOSSA check
* create Github release
* run some basic tests on the release
* build the binaries
* build the images, tag them and push them

The basic tests are currently unit tests and a check against ‘go generate’, ‘go mod verify’.
In the future we could do linting, unit, and integration.

We’d need to backport the final workflow to supported release branches, like release/v0.9

We already have an experiment with [goreleaser](https://github.com/goreleaser/goreleaser), which was slow and ran into trouble with windows container images: https://github.com/rancher/fleet/pull/1019/files

The nightly workflow builds and pushes images to [ghcr.io](http://ghcr.io/) using buildx: https://github.com/rancher/fleet/blob/04492e3f505aa6b30371623f383b6bb8c7a3701d/.github/workflows/nightly.yml

While we want to push to dockerhub, it might be easier to test with ghcr.io. Supporting both could be easy.

**Comment by manno** [comment]
- [ ] Do we need to build windows images for the agent? Fleet-agent is configured not to start on Windows nodes.
- [ ] Can goreleaser use buildx to build windows images?
- [ ] Need a separate issue/PR to remove drone/dapper.

**Comment by weyfonk** [comment]
Remaining work on images, including getting rid of the Windows-based agent Dockerfile, to be done as part of #2184.
