### ISSUE TITLE
Feature Request: Make it possible to keep bundle installed when a cluster is no-longer associated with a cluster group

### ISSUE THREAD

**Issue by spkane** [rancher/fleet#2126]
### Is your feature request related to a problem?

Making a simple change to what labels are used to identify the members of `clusterGroup`, can cause clusters to no longer be associated with the `clusterGroup`.

When this happens, the bundle will be uninstalled almost immediately, which can cause serious havoc, especially when one is using an app-of-apps pattern with tools like ArgoCD inside the cluster.

### Solution you'd like

I can imagine a few approaches to this, with a few tiers, ideally via a label or annotation on the related object.

- Set a cluster-wide default, on whether bundles should be deleted when a cluster leaves a `clusterGroup`.
- Allow that setting to be overridden at the `clusterGroup` level.
- Allow that setting to also be overridden for a single `cluster`.

### Alternatives you've considered

I have not discovered any obvious and simple workarounds so far.

**Comment by manno** [comment]
Thanks for the suggestion. That's currently out of scope for us.

As a workaround maybe [keepResources](https://fleet.rancher.io/ref-crds#gitrepospec) can help here.
