### ISSUE TITLE
fleet agent on downstream cluster is not changed to older version after a single node rollback from 2.5.4-rc to 2.5.3

### ISSUE THREAD

**Issue by sowmyav27** [rancher/fleet#213]
**Steps:**

- Deploy a single node install
- Deploy downstream cluster - 2 rke clusters.
- Run pre upgrade checks. (Deploys workloads, ingress and service discoveries)
- Upgrade rancher using these steps:  https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/single-node-upgrades/
- Run post up grade checks (Validates existing resources and Deploys workloads, ingress and service discoveries) 
- Rollback to 2.5.3 using these steps: https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/single-node-rollbacks/
- fleet agent for local cluster goes back to 0.3.1 version
- fleet agent for downstream clusters is seen in 0.3.2 version

**Expected:**
fleet agent for downstream clusters should be 0.3.1 version

**Comment by StrongMonkey** [comment]
Same https://github.com/rancher/rancher/issues/30707#issuecomment-770282139

**Comment by sowmyav27** [comment]
Closing this issue as per https://github.com/rancher/fleet/issues/213#issuecomment-770282290
