### ISSUE TITLE
Spike: Bootstrapping Rancher through Fleet

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#2131]
Fleet is mainly used within _existing_ Rancher setups, where Rancher installs Fleet.
But users may be interested to know how to use Fleet to install Rancher, to track Rancher with GitOps and take it from there.

A typical use case would be as follows:
1. Install Fleet
2. Apply `GitRepo`s pointing to Rancher charts
3. Have Rancher somehow "adopt" the already installed Fleet release

We need to check whether step 3. actually works out-of-the-box, and to document the process through [fleet-docs](https://github.com/rancher/fleet-docs) for users to know what can be done and how.

**Comment by manno** [comment]
Sounds like a good demo or blog post

**Comment by manno** [comment]
Cleaning up the backlog, won't work on this for now.
