### ISSUE TITLE
Document fine tuning of Fleet for scale

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#2133]
We should write a kind of implementation guide explaining how to tune Fleet for larger sets of clusters, eg.:
* adjusting polling intervals / using webhooks for git jobs
* gotchas with target customisation vs etcd entry size? (see #1650)
* partitioning

**Comment by shane-davidson** [comment]
I came here for exactly the same reason, I have questions around scaling the fleet controller. I can scale up the deployment but I can see the fleet controller acquires a leader lock inside the logs so I'm not sure if scaling the deployment will increase the performance of servicing the downstream fleet agents

**Comment by weyfonk** [comment]
@shane-davidson as you've guessed, scaling up a controller deployment will currently not increase performance. See also #1740 for more context on what we plan to do about this.

**Comment by manno** [comment]
Possible table of contents:

* Intro: hub and spoke, where to compute? What does that mean for the location of credentials.
* Git repo layout and polling, webhooks, intervals and provider request limits
* etcd
  * resource count per CRD: gitrepo, cluster
  * tuning: resource size limit, ...
* Networking considerations
  * control cluster to git repo: repo size, repo count
  * control cluster to agents: checkin intervall
* Horizontal  scaling: sharding fleet controllers
* Worker count per reconciler

**Comment by manno** [comment]
Cleaning up the backlog.
