### ISSUE TITLE
[SURE-7572] gitjob robustness problem: connectivity problem that ends up in a lock not being released

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#2138]
### Issue description:
gitjob pod is still running but seems to be in a hung state showing this error:

time="2024-01-25T17:45:23Z" level=fatal msg="leaderelection lost for gitjob"

Since that timestamp, none of the updates in their Git Repos are being pushed to configured Rancher managed clusters. And new Git Repos are not being pushed to configured Rancher managed clusters.

### Business impact:
This prevented Fleet CD from pushing any of the updates their devs were making in their Git Repos

### Workaround:
Is workararound available and implemented? yes/no
What is the workaround: restart the gitjob pod

### Actual behavior:
gitjob pod hangs  with a a fatal leader election lost error and breaks fleet CD

### Expected behavior:
If the gitjob pod has a fatal leader election lost issue, it should restart, not hang.

### Files, logs, traces:
see JIRA

**Comment by manno** [comment]
Gitjob uses an old lease mechanism, called "ConfigMapsLeasesResourceLock". It consists of a lease resource and a config map.

After checking that there is exactly one gitjob controller running, the lease resource can be deleted. Leader election should renew the lock [within the minute](https://github.com/rancher/wrangler/blob/8a1858d3883c7e0eed81204b614397472449627f/pkg/leader/leader.go#L53C1-L55C34).


Check the output of `kubectl get lease -A` for possible lease resources.

**Comment by manno** [comment]
In this case the gitjob controller was unable to reach the API server.

```


E0125 17:40:57.357995       7 leaderelection.go:330] error retrieving resource lock cattle-fleet-system/gitjob: Get "https://192.168.0.1:443/api/v1/namespaces/cattle-fleet-system/configmaps/gitjob": dial tcp 192.168.0.1:443: connect: connection refused
```

The controller must be able to reach the k8s API to do any leaderelection.

**Comment by dnoland1** [comment]
@manno Agree, but shouldn't the controller either retry or exit instead of hang indefinitely?

**Comment by manno** [comment]
Let's see if we can exit after a  long time.
