### ISSUE TITLE
Release Candidate for Fleet 0.10 / Rancher 2.9

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#2151]
With recent refactorings (migration to `controller-runtime`, #2008, etc), Fleet 0.10 will require special attention.

This includes the following checklist, copied over from #2008:
- [x] Remove [packages/fleet/gitjob](https://github.com/rancher/charts/tree/dev-v2.9/packages/fleet/gitjob) from `rancher/charts`' target branch (eg. by editing the PR generated by [release-against-charts](https://github.com/rancher/fleet/actions/workflows/release-against-charts.yml))
- [x] Check if newly generated `index.yaml` entry in `rancher/charts` still includes gitjob as a chart; it should not.
- [x] Check that [packages/fleet/fleet/generated-changes](https://github.com/rancher/charts/tree/dev-v2.9/packages/fleet/fleet/generated-changes) no longer contains references to `gitjob`
- [ ] Check that the auto-generated release PR against `rancher/charts` does not add any `docker.io/rancher/gitjob` tag entry to [regsync.yaml](https://github.com/rancher/charts/blob/dev-v2.9/regsync.yaml#L234), but generates an entry for `docker.io/rancher/fleet-gitjob` instead.
- [ ] Test installing that Fleet release in Rancher.

**Comment by manno** [comment]
@weyfonk can we close this? :)
