### ISSUE TITLE
gitjob:v0.1.11 in 0.3.2

### ISSUE THREAD

**Issue by boxboatmatt** [rancher/fleet#216]
The gitjob image v0.1.11 in 0.3.2 does not have a uid entry for 1000 in `/etc/passwd` This results in an error when the gitjob attempts to read the git repository. 

~The workaround is to patch the gitjob deployment with a `securityContext.runAsUser`. It appears the `nobody` user works...~

```yaml
  securityContext:
    runAsUser: 65534
```

**Comment by boxboatmatt** [comment]
This is the error encountered on the git repos when attempting to update 
```
git ls-remote git@gitlab.com:foo/bar.git refs/heads/master error: exit status 128, detail: No user exists for uid 1000
 fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.
 ```
 
 Changing the user to 65534 eliminates that error... but now my GitRepos are stuck in a stalled state - not sure why

**Comment by boxboatmatt** [comment]
My workaround doesn't work because the next level deep has the same UID problem `rancher/tekton-utils` also needs to have a uid `1000` added

```
k --namespace fleet-default logs field-nos-apps-28fe5-78lfg step-git-source
{"level":"error","ts":1610039432.5848572,"caller":"git/git.go:47","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force 8395d720263fd09052583eb5484aba38e5d88e95]: exit status 128\nNo user exists for uid 1000\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:47\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:137\nmain.main\n\t/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:52\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"fatal","ts":1610039432.584922,"caller":"git-init/main.go:53","msg":"Error fetching git repository: failed to fetch [8395d720263fd09052583eb5484aba38e5d88e95]: exit status 128","stacktrace":"main.main\n\t/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

**Comment by StrongMonkey** [comment]
https://github.com/rancher/gitjob/pull/21 this PR breaks it. We changed the default user from root to 1000 to support harden cluster.

**Comment by boxboatmatt** [comment]
Yup.. saw that in the change log. I think if you create a user with uid 1000 on `gitjob` and `tekton-utils` the issue would be resolved

**Comment by StrongMonkey** [comment]
@boxboatmatt Thanks for reporting this, working on a fix now.

**Comment by Skasselbard** [comment]
I have the same issue. With the current deployment fleet does not work. Rolling back the deployments for ``git-job`` and ``fleet-controller`` in the ``fleet-system`` Namespace to a previous version (older than 10hours at the time of writing) seems to work around the issue in the meantime. Although I'm not quite sure of the implications of manual rollbacks.

**Comment by Shaked** [comment]
@StrongMonkey / @boxboatmatt 
We are experiencing the same issue as stated in fleet's slack channel. 

Does this mean that the git-job/fleet deployments are being automatically updated when using rancher (2.5.2)? Just trying to figure how it suddenly appeared without us updating anything. 

Thank you! 
Shaked

**Comment by StrongMonkey** [comment]
@Shaked Yes it is automatically upgraded once we update in the release channel

**Comment by Shaked** [comment]
> @Shaked Yes it is automatically upgraded once we update in the release channel

Is it possible to control this (e.g with a feature flag maybe)? 

Any chance you could point where this happen in the source? I'm going through it and learning how everything works from the inside

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/blob/master/pkg/controllers/dashboard/fleetcharts/controller.go

**Comment by jiaqiluo** [comment]
The bug is reproduced on Rancher:v2.5-head with Fleet v0.3.2 
![image](https://user-images.githubusercontent.com/6218999/103943931-2d75cc80-50f0-11eb-9c91-95611787ec46.png)


Steps:
Add a gitRepo which uses a private GH repo + ssh key auth

Result:

<img width="1627" alt="Screen Shot 2021-01-07 at 1 55 02 PM" src="https://user-images.githubusercontent.com/6218999/103944125-6c0b8700-50f0-11eb-83ed-491b20857e33.png">

**Comment by StrongMonkey** [comment]
https://github.com/tektoncd/pipeline/issues/3509 Looks like there are more work to support this.

**Comment by boxboatmatt** [comment]
@StrongMonkey can you set the `DefaultMode` here in this mount to `0600`
https://github.com/rancher/gitjob/blob/master/pkg/controller/gitjob/gitjobs.go#L224

Something like:
```go
	if obj.Spec.Git.ClientSecretName != "" {
		job.Spec.Template.Spec.Volumes = append(job.Spec.Template.Spec.Volumes,
			corev1.Volume{
				Name: "git-credential",
				VolumeSource: corev1.VolumeSource{
					Secret: &corev1.SecretVolumeSource{
						SecretName: obj.Spec.Git.ClientSecretName,
                                                DefaultMode: 0600,
					},
				},
			},
		)
	}
```

**Comment by boxboatmatt** [comment]
@StrongMonkey opened this PR... 
https://github.com/rancher/gitjob/pull/26

Is there a way to stop the Rancher auto update for fleet?

**Comment by StrongMonkey** [comment]
@boxboatmatt Currently there is no way, I am trying to put these fixes(including yours) soon.

**Comment by boxboatmatt** [comment]
@StrongMonkey ahhh.. ok. Thanks!

**Comment by Shaked** [comment]
@StrongMonkey 

Did you push this fix to the release channel already? I'm still seeing gitjob 0.1.11 and all of my deployments are still stuck:  

```
k -n fleet-system describe pod  gitjob-5fcddb74db-4qhxh | grep 'Image:'
    Image:         rancher/gitjob:v0.1.11
```

Is there anything I should do? 

Thank you

**Comment by oak-tree** [comment]
@StrongMonkey This issue breaks on `production` env 👎, 😞, 🤯   . Any idea when a fix will arrive?

**Comment by CarpathianUA** [comment]
Experiencing the same issue

**Comment by tuxpeople** [comment]
Once this is fixed, can we get a RCA how this slipped trough QA? Self-upgrading stuff needs extra careful QA :-)

**Comment by livneros** [comment]
same issue here. our production is down!

**Comment by jiaqiluo** [comment]
The bug fix is validated on v2.5-head with the fleet chart `0.3.300-rc1`
![image](https://user-images.githubusercontent.com/6218999/104248408-aba2dd80-5426-11eb-81d1-ab48f89fadba.png)

The following checks are passed:

- Add a gitRepo which uses a private GH repo + ssh key auth
- Add a gitRepo which uses a private GH repo + basic auth 


Results:
- the gitrepo is added Succesful and the app is installed to the target cluster

**Comment by Shaked** [comment]
Hey @jiaqiluo,

Thank you for the update. 

Few questions:

1. Do you know how long it takes until the update is released on our side? Currently I'm seeing `Image:         rancher/gitjob:v0.1.11` 
2. Any chance you guys will add the ability to control automatic updates? It would have been nice to either rollback the update or be aware when such thing happens as this broke our production environment for more than 3 days. 
3. Are you considering some sort of pre-release (canary like) feature where users could enable/disable the automatic update and only when it is officially available and working, it will be installed for everyone else? 
4. As we are already using rancher/fleet/k3s in our production environment, we are a bit worried. Any idea how this happened?

All the best,
Shaked

**Comment by jiaqiluo** [comment]
Hi @Shaked, thank you for the feedback! 

We are working on releasing the new version of the fleet chart right now and it should be available soon when the attached PRs are merged. 

I don't have a clear answer for the rest of your questions but I will bring them up to the management & dev team. 

Please stay tuned.

**Comment by oak-tree** [comment]
Hey @jiaqiluo  in my end, I can say we **were** very happy about `Rancher` ,`Fleet` and `K3s`. It is real game changer. But, for us to be **4 days down** because of a wrong push, that has not been fix yet, is a **big red alert** .  I'll be happy to hear that this is **not** usual at `Rancher`. I was wondering what happens to Rancher paid users. Did they get this update as well? 

I'm not mean to be rude, but I want to emphasis the importance of the stability  of a production system. We selects our tech stack both in terms of functionally & abilities, but stability and majoring are also factors to be consider.

A `production system` should be `treat as production`.

As I mention above, beside this incident we are **very happy about**  `Rancher` ,`Fleet` and `K3s` and hope this incident is not something to be worried about.

**Comment by boxboatmatt** [comment]
Just want to circle back to say that https://github.com/rancher/fleet/releases/tag/v0.3.3 addresses the issue and fleet is functional again with private repos.

**Comment by jiaqiluo** [comment]
Hi @oak-tree @Shaked 

Thank you for the feedback. I am sorry that the bug causes your service down, and I can promise that this is **NOT** usual at Rancher! I don't know the details about Rancher's support, but here is the only place the bug is reported (thanks @boxboatmatt for reporting the bug).

Fleet is still growing and evolving, and we are trying our best to improve its functionality and stability at the same time. We are optimizing our releasing and bug-fixing process to avoid this kind of incident and consider a better approach to deliver fleet. 


I am thrilled to hear that `Rancher` + `Fleet` + `K3s` suits your needs and is adapted into your production environment. We are always here to hear from you and everyone in the community and try our best to make Fleet meet your needs better. 

All the best,
Jack

**Comment by gna582** [comment]
Also hit with this issue. How does one fix this in a out-of-band cluster?

Tried updating the helm chart manually, but a few minutes later its downgraded back to 0.3.2 again:
```
REVISION        UPDATED                         STATUS          CHART           APP VERSION     DESCRIPTION
3               Tue Jan 19 14:52:43 2021        superseded      fleet-0.3.200   0.3.2           Upgrade complete
4               Tue Jan 19 15:54:15 2021        superseded      fleet-0.3.3     0.3.3           Upgrade complete
5               Tue Jan 19 15:07:36 2021        superseded      fleet-0.3.200   0.3.2           Upgrade complete
6               Wed Jan 20 10:54:32 2021        superseded      fleet-0.3.3     0.3.3           Upgrade complete
7               Wed Jan 20 10:07:35 2021        deployed        fleet-0.3.200   0.3.2           Upgrade complete
```

Added our helm repo to "Catalogs" (g/catalog) and to "Chart Repositories" (c/local/apps/catalog.cattle.io.clusterrepo) but this behaviour doesn't change.

**Comment by kalinon** [comment]
> @boxboatmatt Currently there is no way, I am trying to put these fixes(including yours) soon.

any update on disabling auto-update in rancher? 
https://github.com/rancher/rancher/issues/30791#issuecomment-884327723
