### ISSUE TITLE
.fleetignore not being respected

### ISSUE THREAD

**Issue by skaven81** [rancher/fleet#2175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I add a `.fleetignore` to the top level of my bundle:
```
tests/*
samples/*
suite.yaml
```

But the Bundle still contains all those files:

```
❯ kubectl -n fleet-drekar get bundle gkopa-constraints-dev-templates -o json | jq -r '.spec.resources[].name' | grep -c /tests/
140
❯ kubectl -n fleet-drekar get bundle gkopa-constraints-dev-templates -o json | jq -r '.spec.resources[].name' | grep -c /samples/
324
```

Interestingly, the `suite.yaml` files were removed, so it's at least partially working.  But the directory tree removal does not seem to work.

### Expected Behavior

As described in #1634, .fleetignore should prevent the ignored files from appearing in the Bundle resource.  The docs in #1634 say:

> A match may be found for a file _or directory_ at any level below
> the directory where a .fleetignore lives, ie foo.yaml will
> match ./foo.yaml as well as ./path/to/foo.yaml

emphasis added -- _or directory_ suggests that this should work.

### Steps To Reproduce

Create a fleet bundle that contains some subdirectories you want excluded

Add a `.fleetignore` that names those subdirectories

Examine the generated `Bundle` resource and see the directories were not excluded.

### Environment

```markdown
- Architecture: x86_64
- Fleet Version: v0.8.0 (Rancher 2.7.10)
- Cluster:
  - Provider: RKE1
  - Kubernetes Version: 1.26
```

**Comment by skaven81** [comment]
It does seem that this works:
```
tests
samples
suite.yaml
```
But I would have expected the wildcard version of it to work (which would differentiate a directory named `tests` from a file named `tests`).

**Comment by grbsystems** [comment]
I'm also seeing the same issue.  All the .fleetignore files are being ignored.  I have a directory with 2 bundles for nginx and neo4j.  The .fleetignore file has:

```
neo4j
nginx
```

in an effort to ignore the bundles I did not want installed.  The bundles always appear in the deployment list.

### Environment

Rancher Docker Image rancher/rancher:latest

```
- Rancher V2.8.2
- Dashboard v2.8.0
- Helm v2.16.8-rancher2
- Machine v0.15.0-rancher106
- Fleet Agent v0.9.0
```

**Comment by mverleun** [comment]
Similar issue here.

A wild card at the highest level works.

```
# .fleetignore
*
```

```
$ fleet test
# Matched: default
```
But does not render anything

**Comment by mverleun** [comment]
We have a similar problem. Our woraround is to place a `.fleetignore` in each directory.

Instead of:
`.fleetignore`
```
exclude-me/
```
we do
`exclude-me/.fleetignore`
```
*
```

**Comment by ant-fedorich** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> I add a `.fleetignore` to the top level of my bundle:
> 
> ```
> tests/*
> samples/*
> suite.yaml
> ```
> 
> But the Bundle still contains all those files:
> 
> ```
> ❯ kubectl -n fleet-drekar get bundle gkopa-constraints-dev-templates -o json | jq -r '.spec.resources[].name' | grep -c /tests/
> 140
> ❯ kubectl -n fleet-drekar get bundle gkopa-constraints-dev-templates -o json | jq -r '.spec.resources[].name' | grep -c /samples/
> 324
> ```
> 
> Interestingly, the `suite.yaml` files were removed, so it's at least partially working. But the directory tree removal does not seem to work.
> 
> ### Expected Behavior
> As described in #1634, .fleetignore should prevent the ignored files from appearing in the Bundle resource. The docs in #1634 say:
> 
> > A match may be found for a file _or directory_ at any level below
> > the directory where a .fleetignore lives, ie foo.yaml will
> > match ./foo.yaml as well as ./path/to/foo.yaml
> 
> emphasis added -- _or directory_ suggests that this should work.
> 
> ### Steps To Reproduce
> Create a fleet bundle that contains some subdirectories you want excluded
> 
> Add a `.fleetignore` that names those subdirectories
> 
> Examine the generated `Bundle` resource and see the directories were not excluded.
> 
> ### Environment
> ```
> - Architecture: x86_64
> - Fleet Version: v0.8.0 (Rancher 2.7.10)
> - Cluster:
>   - Provider: RKE1
>   - Kubernetes Version: 1.26
> ```
> 
> ### Logs
> _No response_
> 
> ### Anything else?
> _No response_

    "files.exclude": [".DS_Store", ".git", ".gradle", ".idea", "gradlew.bat", ".kotlin/*", "composeApp/build.gradle.kts", "composeApp/*"],

**Comment by 0xavi0** [comment]
## Additional QA

### Testing
manual test only 

#### Manual Testing
create a `gitrepo` which points to a folder with a .fleetignore file in it.

For example, with the following structure:
```bash
.fleetignore
root
   dir1
     test <--- this is a folder
       file1
       file2
   file3
test <--- this is a file
file4
```

Note files should be yaml files with any resource. 

`.fleetignore`:
```bash
test/*
```

Test that before the fix the pattern is ignored. (`root/dir1/test/file1` and `root/dir1/test/file2` should be deployed in the `bundle`)

Test that after the fix the resources `root/dir1/test/file1` and `root/dir1/test/file2` are ignored and not present in the `bundle`.
Check that the `root/test` is *not* ignored (as the pattern `test/*` ignores folders only)

**Comment by sbulage** [comment]
### System Information: 
| **Rancher** | **Fleet** |
|--------|--------|
| **v2.9-0d8af1460cfc73c3bf4bafecc38f399ea5c187a3-head** | **0.10.1-rc.1** |

### Steps Executed.
1. Created a GitRepo using this: `https://github.com/sbulage/test-fleet` path: `fleet-ignore-test`
2. Wait for GitRepo to deploy application to the cluster
3. Above GitHub repository has `.fleetignore` and structure shown in below screenshot.

### Screenshots

<details>
<summary><b>Repository structure and files/folders to ignore</b></summary>

![Screenshot from 2024-08-05 18-55-21](https://github.com/user-attachments/assets/6ffb4564-e096-4ccc-bca4-99ac1dfb4d4d)
---
![image](https://github.com/user-attachments/assets/40ad46ec-7195-4b8c-85ea-26b2779cacc6)


</details>

<details>
<summary><b>Screenshot showing deployed applications</b></summary>

![Screenshot from 2024-08-05 18-44-36](https://github.com/user-attachments/assets/ac23c518-52aa-4385-8515-d19dc07c7cc0)

</details>

<details>
<summary><b>GitRepo Bundle excluded ignored folder and resource present on the path. </b></summary>

![Screenshot from 2024-08-05 18-53-01](https://github.com/user-attachments/assets/bc89ad4e-d7b6-487f-87b0-96e502a0e30c)

</details>

**Comment by sbulage** [comment]
### System Information: 
| **Rancher** | **Fleet** |
|--------|--------|
| **v2.9-0d8af1460cfc73c3bf4bafecc38f399ea5c187a3-head** | **0.10.1-rc.1** |

### Steps Executed.
1. Created a GitRepo using this: `https://github.com/sbulage/test-fleet` path: `fleet-ignore-test`
2. Wait for GitRepo to deploy application to the cluster
3. Above GitHub repository has `.fleetignore` and structure shown in below screenshot.

### Screenshots

<details>
<summary><b>Repository structure and files/folders to ignore</b></summary>

![Screenshot from 2024-08-05 18-55-21](https://github.com/user-attachments/assets/6ffb4564-e096-4ccc-bca4-99ac1dfb4d4d)
---
![image](https://github.com/user-attachments/assets/40ad46ec-7195-4b8c-85ea-26b2779cacc6)


</details>

<details>
<summary><b>Screenshot showing deployed applications</b></summary>

![Screenshot from 2024-08-05 18-44-36](https://github.com/user-attachments/assets/ac23c518-52aa-4385-8515-d19dc07c7cc0)

</details>

<details>
<summary><b>GitRepo Bundle excluded ignored folder and resource present on the path. </b></summary>

![Screenshot from 2024-08-05 18-53-01](https://github.com/user-attachments/assets/bc89ad4e-d7b6-487f-87b0-96e502a0e30c)

</details>

**Comment by sbulage** [comment]
Thanks @0xavi0 for your help :smile:
