### ISSUE TITLE
`rancher login` fails for a recreated clusters.

### ISSUE THREAD

**Issue by livneros** [rancher/fleet#218]
hey. 
1. having an existing cluster called `X`
2. delete the existing cluster `X`.
3. recreate a cluster named `X`.
4. `./rancher login -t $TOKEN --context $PROJECT $URL` returns the following error:
`level=fatal msg="Get c-vzdtl:p-9dc6x/v3: unsupported protocol scheme \"c-vzdtl\"`

recreating a new pod with a different name than `X` solved the problem.

**Comment by kkaempf** [comment]
Workaround exists.
