### ISSUE TITLE
Old Kubernetes version in helm template function

### ISSUE THREAD

**Issue by xhejtman** [rancher/fleet#2187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current stable version 0.9.0 of the fleetcontroller uses default kubeapi version (1.20.0) in case of rendering a helm template to get number and resource type. However, minimal rancher supported kubernetes version is 1.25.0. If a deployment contains minimal supported kubernetes version like 1.23.0, the helm template fails while actual deployment succeedes. The result is, that the bundle is deployed but reports 0 resources. 

If there is no planned rework of `internal/helmdeployer/template.go` to query kubernetes api for real version, it should at least set the newer api version like:

```
--- a/internal/helmdeployer/template.go
+++ b/internal/helmdeployer/template.go
@@ -29,6 +29,11 @@ func Template(bundleID string, manifest *manifest.Manifest, options fleet.Bundle
        mem.SetNamespace("default")

        h.globalCfg.Capabilities = chartutil.DefaultCapabilities
+       h.globalCfg.Capabilities.KubeVersion = chartutil.KubeVersion{
+                Version: "v1.25.0",
+                Major:   "1",
+                Minor:   "25",
+        }
        h.globalCfg.KubeClient = &kubefake.PrintingKubeClient{Out: io.Discard}
        h.globalCfg.Log = logrus.Infof
        h.globalCfg.Releases = storage.Init(mem)
```

### Expected Behavior

Correct helm templating if chart requires kubernetes api version > 1.20.0.

### Steps To Reproduce

install chart that contains:
`kubeVersion: '>=1.23.0-0'`
in the `Chart.yaml`

**Comment by manno** [comment]
We want to rework how resources are reported: https://github.com/rancher/fleet/issues/2115
