### ISSUE TITLE
Apps and deployments are left after deleting the gitRepo when moved into a new project

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/fleet#219]
Bug on v2.5-head with fleet chart version 0.3.300-rc1

Steps:
- add a `gitRepo` which uses `rancher/fleet-example` repo  with path `single-cluster/helm`
<img width="1614" alt="Screen Shot 2021-01-11 at 3 16 27 PM" src="https://user-images.githubusercontent.com/6218999/104244789-67acda00-5420-11eb-8b7c-36a3662fb0cd.png">

- see the namespace fleet-helm-example is created 
<img width="1443" alt="Screen Shot 2021-01-11 at 3 15 57 PM" src="https://user-images.githubusercontent.com/6218999/104244851-7b584080-5420-11eb-9ae3-11a393fcb0c7.png">

- move the namespace `fleet-helm-example` from no project to the `default` project 

- now we can see deployment in the default project
<img width="1445" alt="Screen Shot 2021-01-11 at 3 16 08 PM" src="https://user-images.githubusercontent.com/6218999/104244901-8f03a700-5420-11eb-843b-40f218e9da4f.png">

- delete the gitRepo

Results:
- the gitRepo and bundle are deleted 
- but the deployments are left in the cluster 

 
More info:
- ~the only thing I guess related is I moved the namespace from no project to default~
- Update 1: It looks like the bug is not related to moving the namespace: the deployment are still left when I do not move the namespace 
<img width="940" alt="Screen Shot 2021-01-11 at 3 36 16 PM" src="https://user-images.githubusercontent.com/6218999/104246319-03d7e080-5423-11eb-985f-f1803ae6b3af.png">

**Comment by slickwarren** [comment]
Reproducible on 2.5.5 (release). Followed exact steps from above: 
* add a gitRepo which uses rancher/fleet-example repo with path single-cluster/helm
* see the namespace fleet-helm-example is created
* move the namespace fleet-helm-example from no project to the default project
* now we can see deployment in the default project
* move the namespace fleet-helm-example from no project to the default project
* now we can see deployment in the default project
* delete git repo
* workload persists after removing repo
<img width="541" alt="Screen Shot 2021-01-11 at 3 39 48 PM" src="https://user-images.githubusercontent.com/16691014/104251077-cf185900-5423-11eb-879d-6b48225acff8.png">
<img width="756" alt="Screen Shot 2021-01-11 at 3 40 29 PM" src="https://user-images.githubusercontent.com/16691014/104251072-cd4e9580-5423-11eb-809c-e78e9de20a4d.png">

**Comment by slickwarren** [comment]
When following all steps above, but specifying a different path, `/simple` with the same `https://github.com/rancher/fleet-examples` repo, this bug does *not* occur on v2.5.5 .  
When this different path is used, the `fleet-helm-example` namespace does not default to an empty project, and is automatically installed to the `default` project of the cluster that the git repo was installed on.

**Comment by StrongMonkey** [comment]
I think this is a duplicate issue of https://github.com/rancher/fleet/issues/233. @jiaqiluo If you want to retest and close this when you have time that will be great

**Comment by jiaqiluo** [comment]
The bug fix is validated on v2.5-head 5a5c039 with fleet chart 0.3.400-rc08

Following the same steps as my previous comment describes, now the deployments are deleted after the gitReop is deleted.
