### ISSUE TITLE
`Context deadline exceeded` error after cluster upgrade to 2.8.2

### ISSUE THREAD

**Issue by mmartin24** [rancher/fleet#2224]
**Rancher Server Setup**

Intiital Rancher version: 2.7.9
Upgraded Rancher version: 2.8.2
Fleet version: 103.1.0+up0.9.0
Information about the Cluster
Kubernetes version: v1.26.6+rke2r1
Cluster Type (Local/Downstream): Local

**User Information**

What is the role of the user logged in? Admin

**Describe the bug**
After upgrading cluster connected to Bibucket repo from Rancher 2.7.9 to 2.8.2 and later disconnecting and reconnection the cluster, the following error is observed:

![Image](https://github.com/rancher/fleet/assets/37271841/47d5f21c-182f-450d-bef9-61cddc8b84e1)

**Reproduction steps:**
- Deploy k3s cluster
- Deploy RKE2 downstream cluster
- Deploy an app using private Bitbucket
- Upgrade to 2.8.2
- Disable service for main cluster:
`k3s.killall.sh`
- Enable back again main cluster:
`sudo systemctl start k3s.service`

Notes: it may be related to https://github.com/rancher/fleet/issues/2065

**Comment by manno** [comment]
closing as duplicate
