### ISSUE TITLE
Switch default Github branch from `master` to `main`

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#2234]
Following current practice, we should rename the default branch from `master` to `main` in the following repositories:
- [x] fleet
- [x] fleet-docs
- [ ] fleet-examples
- [x] ~~fleet-test-data~~ gitrepo still defaults to master

**Comment by manno** [comment]
fleet-examples and fleet-test-data are used by tests and in docs. We would need to copy the branch, not move it, so that old releases still have valid links.

**Comment by manno** [comment]
We would need an EIO ticket to switch fleet-examples.
