### ISSUE TITLE
v0.9.1 - PR: #2031 - agent cpu usage explodes

### ISSUE THREAD

**Issue by johnjcool** [rancher/fleet#2256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in contrast to 0.9.0 and 0.9.1 the fleet agent uses after the first DefaultResyncAgent much more cpu.

v0.9.1
<img width="586" alt="image" src="https://github.com/rancher/fleet/assets/3286267/1ebbcb4e-b568-47cd-ba7a-fb7dde9773e6">
<img width="694" alt="image" src="https://github.com/rancher/fleet/assets/3286267/dca259e4-a4f8-4369-a1fe-bdf911d5aca2">

v0.9.0
<img width="587" alt="image" src="https://github.com/rancher/fleet/assets/3286267/e2944016-579a-47ac-8aa1-2ee20622a7ef">
<img width="697" alt="image" src="https://github.com/rancher/fleet/assets/3286267/e8d64826-4ea2-4353-bf76-76b4a8742f27">

the main change between these two versions is this PR #2031. is it possible to revert this PR and fix the cpu usage problem first.__

### Expected Behavior

small footprint at downstream clusters.

### Steps To Reproduce

1. install fleet 0.9.1
2. deploy 40 BundleDeployments
3. wait until first DefaultResyncAgent
4. node cpu explodes

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.9.1
- Cluster:
  - Provider: K3S
  - Options: 2
  - Kubernetes Version: 1.28.5
```

**Comment by kkaempf** [comment]
@raulcabello

**Comment by johnjcool** [comment]
also tested v0.8.3 and resource usage is fine
<img width="640" alt="image" src="https://github.com/rancher/fleet/assets/3286267/d48a376b-a38d-4054-901e-289527a71d35">
<img width="729" alt="image" src="https://github.com/rancher/fleet/assets/3286267/793d9232-26ce-4001-9630-cb0ea6481327">

**Comment by johnjcool** [comment]
v0.9.2-rc.1 fixes the issue:
<img width="675" alt="image" src="https://github.com/rancher/fleet/assets/3286267/9d0a2ea3-5e38-4c06-b84d-56dad3e98744">
<img width="712" alt="image" src="https://github.com/rancher/fleet/assets/3286267/5bdf7f58-2a00-4f4c-bd80-61522ac22a5d">

**Comment by johnjcool** [comment]
many thanks for quick response time :-)
