### ISSUE TITLE
Documentation: How to escape the templating in fleet.yaml

### ISSUE THREAD

**Issue by aDisplayName** [rancher/fleet#2266]
### Is your feature request related to a problem?

In helm charts, we can escape the templating `{{ }}` using ```{{ `{{ }}` }}```. As fleet 0.9, templating is also supported in `fleet.yaml` by using `${ }`. My question is, how to escape `${ }` in fleet.yaml

**Comment by aDisplayName** [comment]
#1510

**Comment by manno** [comment]
We should add instructions to the docs.

In general it's possible to use backticks to escape the template delimiters.

    s3://${`${S3_ACCESS_KEY}`}:${`${S3_SECRET_ACCESS_KEY}`}@bucketname

* https://github.com/manno/fleet-experiments/blob/main/bundle-templating/bundle-templating.yaml#L25
* https://github.com/rancher/fleet/issues/1510#issuecomment-1539674589
* https://github.com/rancher/fleet/issues/1510#issuecomment-1547950067

**Comment by weyfonk** [comment]
Docs added via [rancher/fleet-docs#125](https://github.com/rancher/fleet-docs/pull/125). Closing.
