### ISSUE TITLE
[SURE-2620] Target Customization fails to be applied when using intersected groups

### ISSUE THREAD

**Issue by janeczku** [rancher/fleet#234]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Have two k3s clusters (`cluster-a`, `cluster-b`) registered in Rancher
2. Create a cluster group (`group-ab`) containing both clusters
3. Create two additional cluster groups containing one cluster each (`group-a`, `group-b`)
4. Create a repository containing the Kubernetes manifests to apply to both clusters ([see example](https://github.com/janeczku/k3s-fleet-demos/tree/master/hello-world))
5. Create a fleet.yaml to specify a  named cluster group customization for `group-b`:
```
targetCustomizations:
  - name: colorize
    yaml:
      overlays:
        - green-color
    clusterGroup: group-b
```
6. Create a GitRepo resource in Rancher using the `clusterGroup` target type and specifying the group containing both clusters, ie.  -> Deploy To -> Target Type: Cluster Group -> `group-ab`

**Expected Result:**

The green-color overlay is applied to `cluster-b` as it is contained in `group-b`

**Actual  Result:**

The green-color overlay is not applied to `cluster-b`

**Environment information**

Rancher 2.5.2

**Comment by janeczku** [comment]
https://github.com/rancher/rancher/issues/30252

**Comment by Negashev** [comment]
Any updates?

**Comment by dagan** [comment]
It seems like this continues to be an issue. Targeting a cluster group for customization seems to be entirely unsupported despite being a documented feature.

**Comment by kkaempf** [comment]
See #1079

**Comment by manno** [comment]
This is not a duplicate. 

However, according to https://fleet.rancher.io/gitrepo-structure when using a cluster group in a target customization, only the first match is applied:

> # Target customization are used to determine how resources should be modified per target
> # Targets are evaluated in order and the first one to match a cluster is used for that cluster.

**Comment by janeczku** [comment]
@manno @kkaempf  Since this is not a duplicate bug and there is no verified fix so far, it should be reopened.

**Comment by manno** [comment]
We believe this is fixed by https://github.com/rancher/fleet/issues/1254

**Comment by sbulage** [comment]
**System information:**
- Rancher version: `2.8-head`
- Fleet version: `0.9.0-rc.5`

**Below setup used to validate this issue**
- Imported 2 clusters --> `import-cluster-1` and `cluster-2`
- Assigned label on `import-cluster-1` --> `color: green`, `first: cluster`
- Assigned label on `cluster-2` --> `color: green`, `second: cluster`
- Created `group-ab` which matches 2 clusters with `matchLabel: color: green`
- Created 2 separate groups with different label matching
- `group-a` uses `first: cluster` label to list `import-cluster-1` similarly for `group-b` it uses `second:cluster` for `cluster-2`


**Scenario 1**
- Created GitRepo using @janeczku's [repository](https://github.com/janeczku/k3s-fleet-demos/blob/master/hello-world/fleet.yaml)
- Deploy To is mapped to `group-ab` (which has 2 clusters listed.)
- Able to see the `deployment_patch.yaml` is applied on the `hello-world` deployment.
- Verified that it is applied on both the cluster which are present in the `group-ab`.

![Selection_117](https://github.com/rancher/fleet/assets/12134754/b9d4a811-cf7e-4d4a-ae6f-48100a263e7f)


**Scenario 2**
- Created another GitRepo which installs `grafana` application with `nodeSelector` (overrides default parameter in Grafana charts `values.yaml`) [Grafana repository](https://github.com/sbulage/test-fleet/blob/main/target-customization/fleet.yaml).
- Added `env: prod` label on both clusters.
- Created `anther-group-ab` using `env: prod` which lists 2 clusters.
- Verified that `grafana` chart deployed in both the clusters and can see the overridden parameter is present in the `grafana` deployement. 

![Selection_119](https://github.com/rancher/fleet/assets/12134754/db6c9a6a-7d0f-41ef-b1d5-78ce7592f5c0)
