### ISSUE TITLE
[SURE-7578] Add managed annotation to Chart.yaml in fleet helm charts

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#2348]
A customer reported a bug where the user was able to manually upgrade the rancher-webhook app. According to [webhook documentation](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook), it is a managed app which means it is installed, upgraded, and deleted by codebase. So, when the users perform these actions on managed charts in the Apps page of Rancher UI, the UI will throw a warning that it is not a recommended action.

*** See JIRA for further information

Acceptance criteria
Add `catalog.cattle.io/managed:true` annotation for future versions of all fleet related charts

**Comment by manno** [comment]
Being able to upgrade fleet from the UI is a feature.

When we implemented version pinning for the fleet chart, we made sure that manual upgrades are allowed.
I wouldn't add the managed chart annotation, since manually upgrading Fleet is useful.
