### ISSUE TITLE
Helm repo with custom CA certificate fails

### ISSUE THREAD

**Issue by jensdt** [rancher/fleet#235]
When using a fleet.yaml that contains a reference to a Helm URL (either a direct chart URL, or using chart+repo+version combination), Fleet cannot deploy this because our private Helm repo is signed using a custom CA (enterprise env, you know how it goes).

Only log message I can find is in the Job (image rancher/tekton-utils:v0.1.1) that is created:
time="2021-01-22T13:41:59Z" level=fatal msg="Get \"https://redacted/index.yaml\": x509: certificate signed by unknown authority"

or using the URL directly

time="2021-01-22T13:30:39Z" level=fatal msg="Get \"https://redacted/mychart-1.0.0.tgz\": x509: certificate signed by unknown authority"

This message is also shown in the Rancher CD interface.

Fleet is on v0.3.3.

I see no option of configuring a custom CA cert for Helm. I tried setting the CA options here: https://fleet.rancher.io/gitrepo-add/#create-gitrepo-instance but that doesn't work and if I understand correctly this only applies to connecting to the Git repo itself, not Helm once the Git repo has been checked out.
gz#15816

**Comment by rowa78** [comment]
I have the same problem and looking for a way to provide a custom CA to access my private helm-repos via fleet.

**Comment by ron1** [comment]
Would you consider generalizing this issue to "Support private helm repos"? This includes basic-auth, ssh-auth, CA certs, etc.

**Comment by naartjie** [comment]
I hit this same issue this week. Fleet can't talk to an internal Helm repo (Sonatype Nexus), which is signed by private CA. I tried searching for the location where this call is made.

Could someone familiar with the codebase comment if this is even close, or point me in the right direction?:
https://github.com/rancher/fleet/blob/cdda39cc9a1292cc5dc7c2b1f90976e0c380dc54/pkg/helmdeployer/deployer.go#L184

**Comment by suryatejaboorlu** [comment]
gz#15816

**Comment by abelnieva** [comment]
I can see rancher container mounts the following volumes related to certificates 

        volumeMounts:
        - mountPath: /etc/ssl/certs/ca-additional.pem
          name: tls-ca-additional-volume
          readOnly: true
          subPath: ca-additional.pem
        - mountPath: /etc/rancher/ssl/ca-additional.pem
          name: tls-ca-additional-volume
          readOnly: true
          subPath: ca-additional.pem
        - mountPath: /etc/rancher/ssl/cacerts.pem
          name: tls-ca-volume
          readOnly: true
          subPath: cacerts.pem
so fleet should does the same.

**Comment by ibrokethecloud** [comment]
For now the cacert can be passed by creating a secret in the correct namespace(fleet workspace) for your cluster, and GitRepo spec can refer to the correct secret in the `helmSecretName` field. 

The secret can have the following fields:

```
username: yourUserName
password: yourPassword
cacerts: yourCaCert
ssh-privatekey: yourSshKey
```

These then get passed to the Gitjob pod.

**Comment by StrongMonkey** [comment]
Duplicate issue of https://github.com/rancher/fleet/issues/120. Should already be fixed in latest fleet version. Check private helm repo for more information at here https://fleet.rancher.io/gitrepo-structure/.
