### ISSUE TITLE
metrics: make sure metrics work well with sharding

### ISSUE THREAD

**Issue by p-se** [rancher/fleet#2355]
We need to ensure that metrics are collected against resources reconciled not just by the unsharded Fleet controller, but also by sharded controllers.

~~This could be an opportunity to improve shard label naming, for instance by supporting label-based filtering on the unsharded controller (currently not possible with an empty `shard` value). For instance, we could use `~` instead of an empty string, or simply add a label such as `fleet.cattle.io/empty-shard=true` or similar.~~

A new label `shard-default` with value `true` for the unsharded controller has been implemented in https://github.com/rancher/fleet/pull/2172/commits/436a81de5f452183e607e3983cffd7f02ee88bd0 as part of the PR with the implementation of metrics https://github.com/rancher/fleet/pull/2172. Metrics still does not work with sharded fleet controllers. This is to be remedied.

This is a follow-up on both #1740 and #1408.

**Comment by weyfonk** [comment]
Note: [this documentation](https://gist.github.com/bigkevmcd/41c897580e05475b42d0472c0f8e0bc9) on how Flux had planned to do it may be useful.
