### ISSUE TITLE
Clarify sharding label management

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#2358]
Fleet uses two labels for its current sharding implementation:
* controllers are labelled with `shard=<shard-id>`
* sharded resources bear label `fleet.cattle.io/shard=<shard-id>`

We should:
* [x] clarify how we want to name(space) those labels, making them consistent across Fleet, eg:
    * `shard.fleet.cattle.io/id=<shard-id>`
* [x] expose those labels in Fleet's public API, to enable users to consume them.

Note: [info](https://github.com/weaveworks/flux-shard-controller/tree/main/docs) on how Flux handles sharding.

Follow-up on #1740.

**Comment by manno** [comment]
controller label:
`fleet.cattle.io/shard-id=<shard-id>`

sharded resources bear label:
`fleet.cattle.io/shard-ref=<shard-id>`

**Comment by kkaempf** [comment]
considered done
