### ISSUE TITLE
[SURE-8270] Gitjob controller security context

### ISSUE THREAD

**Issue by manno** [rancher/fleet#2359]
The fleet-controller and fleet-agent dissallow privilege escalation and use a read only filesystem. Gitjob controller should do the same.

* https://github.com/rancher/fleet/blob/main/charts/fleet/templates/deployment.yaml#L172-L178
* https://github.com/rancher/fleet/blob/main/charts/fleet-agent/templates/deployment.yaml#L30-L36

See https://github.com/rancher/fleet/blob/main/charts/fleet/templates/deployment_gitjob.yaml
We will need to add empty dirs for the writablel directories.

 
These must be disabled in debug mode, so we can attach debuggers and profilers.

**Comment by sbulage** [comment]
QA Observation:

While checking the expected Security Context block under the GitJob deployment, below information was present:

<details>
<summary> Gitjob Deployment </summary>

![image](https://github.com/rancher/fleet/assets/12134754/f9cc1a54-90d3-4f02-9496-49ae12e9cded)
<details>

**Comment by sbulage** [comment]
### **System Information**
**Before upgrade:**
- Rancher Version: `2.8.5-rc3`
- Fleet Version: `v0.9.5`
---
**After upgrade:**
- Rancher Version: `2.9.0-alpha5`
- Fleet Version: `v0.10.0-rc.16`
---
**Below Steps performed:**

- Created GitRepo in Rancher `2.8.5-rc3`.
- Wait for the application to deploy
- Check Gitjob pod for `securityContext` values: `readOnlyRootFilesystem`, `allowPrivilegeEscalation` and `drop all capabilities`.
- Upgrade Rancher to `2.9.0-alpha5`
- Wait for the Fleet to upgrade to `0.10.0-rc.16`
- Wait for the GitRepo is ready.
- Verify that Gitjob pod has `securityContext` values: `readOnlyRootFilesystem`, `allowPrivilegeEscalation` and `drop all capabilities`.
---
<details>
<summary><b>See screenshot for more details.</b></summary>

![Screenshot from 2024-06-17 19-32-50](https://github.com/rancher/fleet/assets/12134754/68ef9086-4ee0-47bd-9350-f61e47a2f45b)

</details>
