### ISSUE TITLE
Make fleet-agent able to connect to rancher server if rancher server has ca-cert setting

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/fleet#239]
If rancher server is using certs signed by public ca but also have cacert setting, fleet-agent will fail to register since it will try to connect to a server behind public CA using cacert setting.

**Comment by StrongMonkey** [comment]
For qa to reproduce this, create a rancher setup using certs signed by public CA, while do not provide `--no-cacert` option in helm chart. Then try to add several clusters. Go to continous deployment, the cluster will get stuck at registering because of cert issue.

**Comment by slickwarren** [comment]
I was able to reproduce this on 
rancher HA v2.5.5 fleet-agent version `v0.3.4-rc3` with letsencrypt certs
steps to repro:
* ensure `rancher` deployment yaml does not have `--no-cacerts` flag (remove and save if it does)
* deploy some clusters
* check each `fleet-agent` deployment log, you should see errors with `x509`

I verified this is fixed on 
rancher HA v2.5.6-rc4 fleet-agent version `v0.3.4-rc3` with letsencrypt certs
* `fleet-agent` deployments no longer have errors
