### ISSUE TITLE
Documentation is missing for `disablePolling`

### ISSUE THREAD

**Issue by sbulage** [rancher/fleet#2394]
Information about `disablePolling` is missing from the Fleet documentation.

> # QA Template
> 
> ## Solution
> When new option `disablePolling` is set to `true` git repositories are not scanned periodically
> 
> ## Testing
> Apply a `fleet.yaml` file which refers to a git repository and don't set the `disablePolling` option. 
> That should scan the repository every 15 seconds. (as of now)
> Push something to the repo in that interval of time and it should be scanned and applied by Fleet.
> 
> Add the `disablePolling` option set to true and push some more changes to the repository.
> Fleet should not scan the repository and changes should not be applied.
> 
> ## Additional info
> 

_Originally posted by @0xavi0 in https://github.com/rancher/fleet/issues/1572#issuecomment-2007229977_

**Comment by 0xavi0** [comment]
Closing this as the documentation PR was already merged
