### ISSUE TITLE
Scalability of fleet

### ISSUE THREAD

**Issue by ddysher** [rancher/fleet#24]
Thanks for open sourcing the project.

Scaling the number of Kubernetes cluster under management is the main focus of fleet; however, it's not clear how fleet solves the problem with current architecture. From what I know by briefly scanning the code base, fleet is using Kubernetes standard API constructs like informer, listers, via client-go. If we compare Cattle'd `Cluster` with `Node`, then it sounds like saying "Kubernetes supports millions of Nodes" (ignoring external resources like ingress for now), which I think, is not a well-studied scalability issue for now.

Is my understanding correct? I'm happy to know more details :)

**Comment by ibuildthecloud** [comment]
I'll be publishing more information about this later as I prove it out.  We are currently in the process of building out a 1,000,000 cluster setup (simulated as I don't have infinite $$$), but as result we will share our findings.  But yes, it's largely based off a standard k8s controller architecture with careful care for some key things to make it scale.

**Comment by ddysher** [comment]
thanks for the response!

**Comment by cloudnautique** [comment]
@ddysher the blog was posted about scaling up Fleet to manage 1,000,000 clusters. You can find it here: https://rancher.com/blog/2020/scaling-fleet-kubernetes-million-clusters

Closing this issue.
