### ISSUE TITLE
Unable to deploy OPA Templates and Constraints

### ISSUE THREAD

**Issue by travis-sobeck** [rancher/fleet#240]
rancher-gatekeeper:3.2.101
fleet:0.3.300

Following something very simple like [this example](https://github.com/rancher/fleet-examples/tree/master/single-cluster/manifests) I have 2 folders in the root of my repo, one for OPA Gatekeep constraints and one for templates.  I deployed them with kubectl to verify they worked, then removed them. 

When I create the Git Repos for this repo and sync it, I get "Err Applied" and 'unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "K8sPSPCapabilities"' ... etc.  Basically it can't deploy the constraints because the templates are not there yet, but instead of deploying the templates and eventually coming back to the constraints it just errors out and stops (as best I can tell).  If I remove the constraints from the repo and re-sync, it applies the templates just fine, then I can go back and re-add the constraints and its works.  Clearly this will not a workable approach. 

Is there some way to tell it to do 'A' first, then 'B' or maybe tell it to ignore the errors .. do the best you can ?

Fleet seems like a great options to keep all my policies synced across multiple clusters so it would be nice if this worked :)
Thanks.

**Comment by ron1** [comment]
You might try defining two paths in your GitRepo, one to the templates folder and one to the constraints folder. This should cause two individual bundles to be deployed. The constraints bundle deployment should retry while the templates bundle is deploying and then successfully deploy once the templates bundle is finished.

**Comment by travis-sobeck** [comment]
@ron1 ok, I can give that a try

**Comment by travis-sobeck** [comment]
Although this did happen to work in this one case, I feel like its a poor hack to bypass a issue of k8s tooling not natively dealing with order of applying code (again unless I missed something).  It also means I have to manage more files (kind: GitRepo)

**Comment by ron1** [comment]
Fleet relies on helm 3 to apply resources to the cluster. Helm 3 outstanding issue https://github.com/helm/helm/issues/8439 seems to accurately describe the problem here. Until helm natively solves this problem for Fleet, using multiple paths/bundles within a single GitRepo manifest seems to solve this issue in a reasonably lightweight manner without the need for extra files. WDYT?

**Comment by travis-sobeck** [comment]
Fair enough.  I by no means claim to be an expert.  Thanks for the advice.

**Comment by travis-sobeck** [comment]
Is this is a consequence of the underlying tooling it probably makes sense to just close it.
