### ISSUE TITLE
Add debug logging to fleet controller and agents

### ISSUE THREAD

**Issue by Tejeev** [rancher/fleet#242]
We need more debug logging in the code and the ability to enable it via charts.  As is, we no logs or clear reason for failures such as chart changes that do not stick.  Detailed debug logging is vital to the supportability of Fleet.

**Comment by brendarearden** [comment]
v2.6.3-rc2

**Comment by nickgerace** [comment]
Available on Rancher `v2.6-head` with Fleet `v0.3.8-rc2`

**Comment by StrongMonkey** [comment]
To enable debug, Go to Dashboard -> Local cluster -> App & Marketplace -> Installed App, upgrade fleet chart with value `debug=true`. You can optionally set `debugLevel=5` too.

**Comment by StrongMonkey** [comment]
This also needs to be documented. Added docs labels to not forget.

**Comment by phillipsj** [comment]
I am going to dev-validate this one unless someone else started it.

**Comment by phillipsj** [comment]
When running Rancher 2.6-head I get v0.3.8-rc1 version of fleet installed. I will keep investigating.

**Comment by phillipsj** [comment]
@nickgerace @StrongMonkey is this correct?

**Comment by StrongMonkey** [comment]
@phillipsj It doesn't look correct as the latest version should be v0.3.8-rc2. When you go to app & marketplace -> installed app and select upgrade, are you able to see the new version?

**Comment by phillipsj** [comment]
No, I don't see a new version listed at all.

**Comment by StrongMonkey** [comment]
Aftering talking to @nickgerace this is a combination of build issue and race condition. The built-in catalog has the old fleet version so during install it gets installed first. Later new fleet chart is refreshed but rancher is not able to upgrade to that version because new fleet version also share the same semver(100.0.2+up0.3.8-rc2) since it is still fleet rc.

**Comment by nickgerace** [comment]
Another issue: at the time of our conversation, Drone publish builds of Rancher were nearly a week old, which is slightly older than our chart's merge time. We should wait for a new publish build (`v2.6-head` built today or newer) or Rancher RC.

@StrongMonkey I'm led to believe the chart updating issue is low priority since this seems to only affect RCs. Full releases should be covered by the minimum version setting in the Rancher Dockerfile.

**Comment by ryansann** [comment]
I picked this up for dev-validate

Steps used for testing:
1. Docker install of Rancher `v2.6-head` (``)
2. Edit the installed fleet app (`v0.3.8-rc2`) to have `debug=true`
3. Check fleet-controller logs

Seeing lots of debug logs from the fleet-controller deployment, e.g.
```
time="2021-12-02T22:27:11Z" level=debug msg="DesiredSet - No change(2) /v1, Kind=ServiceAccount fleet-default/import-token-c-crlvz-cad19748-d0a3-47b1-a171-2359a3e34e07 for cluster-group-token fleet-default/import-token-c-crlvz"
time="2021-12-02T22:27:11Z" level=debug msg="DesiredSet - No change(2) rbac.authorization.k8s.io/v1, Kind=Role fleet-default/import-token-c-crlvz-cad19748-d0a3-47b1-a171-2359a3e34e07-role for cluster-group-token fleet-default/import-token-c-crlvz"
time="2021-12-02T22:27:11Z" level=debug msg="DesiredSet - No change(2) rbac.authorization.k8s.io/v1, Kind=RoleBinding fleet-default/import-token-c-crlvz-cad19748-d0a3-47b1-a171-2359a3e34e07-8ab83 for cluster-group-token fleet-default/import-token-c-crlvz"
time="2021-12-02T22:27:11Z" level=debug msg="DesiredSet - No change(2) /v1, Kind=Secret fleet-default/import-token-c-crlvz for cluster-group-token fleet-default/import-token-c-crlvz"
time="2021-12-02T22:27:11Z" level=debug msg="DesiredSet - No change(2) /v1, Kind=ServiceAccount fleet-local/import-token-local-1b63b8f2-a0e0-44b8-a82b-0a7e9602d0b4 for cluster-group-token fleet-local/import-token-local"
time="2021-12-02T22:27:11Z" level=debug msg="DesiredSet - No change(2) rbac.authorization.k8s.io/v1, Kind=Role fleet-local/import-token-local-1b63b8f2-a0e0-44b8-a82b-0a7e9602d0b4-role for cluster-group-token fleet-local/import-token-local"
time="2021-12-02T22:27:11Z" level=debug msg="DesiredSet - No change(2) rbac.authorization.k8s.io/v1, Kind=RoleBinding fleet-local/import-token-local-1b63b8f2-a0e0-44b8-a82b-0a7e9602d0b4-to-role for cluster-group-token fleet-local/import-token-local"
time="2021-12-02T22:27:11Z" level=debug msg="DesiredSet - No change(2) /v1, Kind=Secret fleet-local/import-token-local for cluster-group-token fleet-local/import-token-local"
```

**Comment by Tejeev** [comment]
@ryansann @StrongMonkey I don't see this documented in https://fleet.rancher.io/gitrepo-add/#troubleshooting
I didn't see an edit link there or I'd add it myself.  Is it waiting to be published?  This issue can't really closed until it is documented.

**Comment by Jono-SUSE-Rancher** [comment]
I've coordinated with the Rancher docs team and @jtravee is going to make the appropriate Fleet docs updates. I am closing this issue out for v2.6.3 so we can continue with the release.

**Comment by Tejeev** [comment]
Thanks @Jono-SUSE-Rancher and crew!  Got some customers that are pretty excited about this :)
