### ISSUE TITLE
Bundle is not re-generated and Gitrepo status is not updated when deleting a bundle.

### ISSUE THREAD

**Issue by 0xavi0** [rancher/fleet#2449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deleting a `bundle` Fleet purges all the `bundledeployments` and doesn't re-deploy the `bundle`. 

Also... the `gitrepo` status is not updated, showing that all `bundles` are successfully deployed.

Looks like the reconciler for `bundles` is called but not the one for `gitrepo`

### Expected Behavior

As `gitrepo` still exists the `bundle` should just be re-deployed and `bundledeployments` should not be purged.

### Steps To Reproduce

1. Deploy a`gitrepo` 
2. Check that the `gitrepo` resource is ready, and that the `bundle`(s) and `bundledeployment`(s) is/are ready
```bash
$ kubectl get gitrepo -A                                                                                                                                              
NAMESPACE     NAME     REPO                                        COMMIT                                     BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   sample   https://github.com/rancher/fleet-examples   2ada7cca738877df8459b3a34839a15e5683edaa   1/1   
```
```bash 
$ kubectl get bundledeployments -A                                                                                                                                    
NAMESPACE                                NAME                DEPLOYED   MONITORED   STATUS
cluster-fleet-local-local-1a3d67d0a899   fleet-agent-local   True       True        
cluster-fleet-local-local-1a3d67d0a899   sample-simple       True       True  
```
```bash
$ kubectl get bundles -A                                                                                                                                               
NAMESPACE     NAME                BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local   1/1                       
fleet-local   sample-simple       1/1
```
3. Delete the `bundle` associated with the `gitrepo`
```bash
$ kubectl delete bundle sample-simple -n fleet-local                                                                                                                  
bundle.fleet.cattle.io "sample-simple" deleted
```
4. Check that the `bundle` is deleted
```bash
$ kubectl get bundles -A                                                                                                                                              
NAMESPACE     NAME                BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local   1/1 
```
5. Check that the `bundledeployments` are also deleted
```bash
$ kubectl get bundledeployments -A                                                                                                                                    
NAMESPACE                                NAME                DEPLOYED   MONITORED   STATUS
cluster-fleet-local-local-1a3d67d0a899   fleet-agent-local   True       True
```
6. Check that the `gitrepo` status is the same
```bash
$ kubectl get gitrepo -A                                                                                                                                              
NAMESPACE     NAME     REPO                                        COMMIT                                     BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   sample   https://github.com/rancher/fleet-examples   2ada7cca738877df8459b3a34839a15e5683edaa   1/1  
```

**Comment by manno** [comment]
Maybe just react to bundle delete here: https://github.com/rancher/fleet/blob/main/internal/cmd/controller/reconciler/gitrepo_controller.go#L330

**Comment by 0xavi0** [comment]
Gitrepo status is already fixed by recent changes in `gitrepo`/`gitopts` controllers.

This https://github.com/rancher/fleet/pull/2508 PR adds the predicate to react upon `bundle` deletes in the `gitrepo` controller to ensure that it is called then deleting a bundle. 

We're moving the re-generate part to on-hold until we decide is we rework/merge/etc `gitrepo`/`gitopts` controllers

**Comment by manno** [comment]
A GitRepo's bundle is deleted by a user, we don't recreate it automatically. Clicking on "Force Update", or making a new commit would re-create it. 
`kubectl patch gitrepos.fleet.cattle.io -n fleet-local test-chart --type=json -p '[{"op": "add", "path": "/spec/forceSyncGeneration", "value": 3}]'`
