### ISSUE TITLE
Enable node selection for shards

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#2456]
Fleet recently got basic sharding support through #1740, which allows a set of shards to be configured at deployment time.

This would be more flexible if users could configure which shard(s) would be handled by which node in their cluster, by means of a `nodeSelector` which would be set on each shard's `fleet-controller` deployment.

In turn, this means that the currently basic configuration/values format used to set shards should evolve to support a node for each shard.

**Comment by Tommy12789** [comment]
## Additional QA
### Issue: <link the issue or issues this PR resolves here>
2456
 
### Problem
N/A 
### Solution
Implemented a way to add nodeselector for controllers shards 
 
### Testing
manual test only 

### Engineering Testing
#### Manual Testing
Installing fleet with shards and nodeSelector then verify each shard is well deployed in the good node
#### Automated Testing
N/A
### QA Testing Considerations
- Testing basic functionment
- Testing with duplicate shards id
- Testing a shard without nodeSelector to verify it's also deployed without the parameter 
#### Regressions Considerations
N/A

**Comment by weyfonk** [comment]
Thanks @mmartin24 and @thehejik for raising this!
This looks like an omission in gitjob deployments, ie we most likely need to take the shard's node selector into account in [gitjob deployments](https://github.com/rancher/fleet/blob/main/charts/fleet/templates/deployment_gitjob.yaml) as we do for [fleet-controller deployments](https://github.com/rancher/fleet/blob/main/charts/fleet/templates/deployment.yaml#L235-L238).

**Comment by mmartin24** [comment]
To clarify the above pasting @weyfonk  comment on Slack over this issue:

>There was a bug with scheduling of gitjob pods, but we don't specify any scheduling for jobs created by Fleet.
>I think it would make sense for node selection to be present there as well, for the sake of consistency.
>This could work by detecting which shard (if any) a gitjob controller applies to, and applying the corresponding node selector [here](https://github.com/rancher/fleet/blob/main/internal/cmd/controller/gitops/reconciler/gitjob_controller.go#L603).

**Comment by mmartin24** [comment]
# Test 1 - Basic shard deployment with nodeSelector works
```json
{
  "debug": true,
  "debugLevel": 1,
  "shards": [
    {
      "id": "shard0",
      "nodeSelector": {
        "kubernetes.io/hostname": "k3d-3-server-3-agents-cluster-agent-0"
      }
    },
    {
      "id": "shard1",
      "nodeSelector": {
        "kubernetes.io/hostname": "k3d-3-server-3-agents-cluster-agent-1"
      }
    },
    {
      "id": "shard2"
    }
  ]
}
```

- Checked 3 shards controllers + 3 gitrepo shards are created

## Gitrepo WITH shard nodeSelector
https://github.com/rancher/fleet-examples
simple

## Label
fleet.cattle.io/shard-ref
shard0

Expected output:

```
➜  ~ k logs -n cattle-fleet-system fleet-controller-shard-shard0-7f9cdc95-rnlxx | tail -1 

k logs -n cattle-fleet-system fleet-controller-shard-shard0-748f9459df-zlbgs | tail -1 
2024-07-04T08:10:19Z	DEBUG	cluster	Cluster is not ready, because not all gitrepos are ready	{"controller": "cluster", "controllerGroup": "fleet.cattle.io", "controllerKind": "Cluster", "Cluster": {"name":"local","namespace":"fleet-local"}, "namespace": "fleet-local", "name": "local", "reconcileID": "5ed9da36-dd00-409a-a776-1cd7223e1d00", "namespace": "fleet-local", "name": "local", "ready": 0, "desiredReady": 6}
```

Rest has nothing


![image](https://github.com/rancher/fleet/assets/37271841/0d1441e6-9401-4a07-aed8-4e5fc6eedc3b)


# Test 2 - Test shard deployment with 2 samee shard id only 
```json
{
  "debug": true,
  "debugLevel": 1,
  "shards": [
    {
      "id": "shard1",
      "nodeSelector": {
        "kubernetes.io/hostname": "k3d-3-server-3-agents-cluster-agent-0"
      }
    },
    {
      "id": "shard1",
      "nodeSelector": {
        "kubernetes.io/hostname": "k3d-3-server-3-agents-cluster-agent-1"
      }
    },
    {
      "id": "shard2"
    }
  ]
}
```
## Gitrepo WITH shard nodeSelector
https://github.com/rancher/fleet-examples
simple

## Label
fleet.cattle.io/shard-ref
shard1


Expected output: Only 1 of 2 nodes with same shard id process the gitjob:


Node `k3d-3-server-3-agents-cluster-agent-0` process the work with shard id `shard1` 
```
k logs -n cattle-fleet-system fleet-controller-shard-shard1-67d6868b7f-48plx | tail -1
2024-07-04T08:21:01Z	DEBUG	bundle	Unchanged bundledeployment	{"controller": "bundle", "controllerGroup": "fleet.cattle.io", "controllerKind": "Bundle", "Bundle": {"name":"fleet-62-2-simple","namespace":"fleet-local"}, "namespace": "fleet-local", "name": "fleet-62-2-simple", "reconcileID": "66cb2527-5c39-4ffb-8ac8-c21fcd6d0724", "bundledeployment": {"apiVersion": "fleet.cattle.io/v1alpha1", "kind": "BundleDeployment", "namespace": "cluster-fleet-local-local-1a3d67d0a899", "name": "fleet-62-2-simple"}, "operation": "unchanged"}

```

And `shard0` dissappears:

```
k get pods -n cattle-fleet-system                                 
NAME                                             READY   STATUS    RESTARTS   AGE
fleet-controller-6845cf7495-5mn8v                3/3     Running   0          64m
fleet-controller-shard-shard1-67d6868b7f-48plx   1/1     Running   0          2m33s
fleet-controller-shard-shard2-c88786bd8-tdfsj    1/1     Running   0          64m
gitjob-646cdf9577-4vx2b                          1/1     Running   0          64m
gitjob-shard-shard1-849c555bf7-f5tf7             1/1     Running   0          64m
gitjob-shard-shard2-6c5c6ff4c9-88rsq             1/1     Running   0          64m
```


# Test 3 - Test shard deployment without nodeSelector
Given:
```json
{
  "debug": true,
  "debugLevel": 1,
  "shards": [
    {
      "id": "shard1",
      "nodeSelector": {
        "kubernetes.io/hostname": "k3d-3-server-3-agents-cluster-agent-0"
      }
    },
    {
      "id": "shard1",
      "nodeSelector": {
        "kubernetes.io/hostname": "k3d-3-server-3-agents-cluster-agent-1"
      }
    },
    {
      "id": "shard2"
    }
  ]
}
```

And 
## Gitrepo WITH shard nodeSelector
https://github.com/rancher/fleet-examples
simple

## Label
fleet.cattle.io/shard-ref
shard2

Expected output

```
k logs -n cattle-fleet-system fleet-controller-shard-shard2-c88786bd8-tdfsj | tail -1 
2024-07-04T08:28:27Z	DEBUG	bundle	Unchanged bundledeployment	{"controller": "bundle", "controllerGroup": "fleet.cattle.io", "controllerKind": "Bundle", "Bundle": {"name":"fleet-62-3-simple","namespace":"fleet-local"}, "namespace": "fleet-local", "name": "fleet-62-3-simple", "reconcileID": "b54e1424-3963-44ba-b650-3f0f1f521b7e", "bundledeployment": {"apiVersion": "fleet.cattle.io/v1alpha1", "kind": "BundleDeployment", "namespace": "cluster-fleet-local-local-1a3d67d0a899", "name": "fleet-62-3-simple"}, "operation": "unchanged"}

```


# Test 4 - Test Gitrepo is correctly reassigned after changeing nodeSelector option
Having initial setup setup of 3 shards and 1 git repo on `shard0`

```json
{
  "debug": true,
  "debugLevel": 1,
  "shards": [
    {
      "id": "shard0",
      "nodeSelector": {
        "kubernetes.io/hostname": "k3d-3-server-3-agents-cluster-agent-0"
      }
    },
    {
      "id": "shard1",
      "nodeSelector": {
        "kubernetes.io/hostname": "k3d-3-server-3-agents-cluster-agent-1"
      }
    },
    {
      "id": "shard2"
    }
  ]
}
```

When `shard0` is re-assigned to different node: `k3d-3-server-3-agents-cluster-agent-0`, and forced pushed, the `shard0` now is processed by `k3d-3-server-3-agents-cluster-agent-1`. So this:

```json
{
  "debug": true,
  "debugLevel": 1,
  "shards": [
    {
      "id": "shard0",
      "nodeSelector": {
        "kubernetes.io/hostname": "k3d-3-server-3-agents-cluster-agent-1"
      }
    },
    {
      "id": "shard1",
      "nodeSelector": {
        "kubernetes.io/hostname": "k3d-3-server-3-agents-cluster-agent-0"
      }
    },
    {
      "id": "shard2"
    }
  ]
}
```

So functionality seems to work well in Rancher `v2.9-e6fda5ab19ef27d81708dceb278aba422159ea81-head`

----
Comments / caveats observed non blocking for 2.9:

- As commented above Job processed in different shard than defined (not an issue)
- UI not prepared for labels `fleet.cattle.io/shard-ref` during gitrepo creation.
- No cleansing of shard related pods. For these tests we used 3 shards, which meant 8 pods. This pods will remain, unless some cleansing mechanism is implemented in the future:
```
k get pods -n cattle-fleet-system                                                    
NAME                                             READY   STATUS    RESTARTS   AGE
fleet-controller-6845cf7495-5mn8v                3/3     Running   0          77m
fleet-controller-shard-shard0-748f9459df-nr62x   1/1     Running   0          8m40s
fleet-controller-shard-shard1-6ccc7bb5fd-qc6l4   1/1     Running   0          8m40s
fleet-controller-shard-shard2-c88786bd8-tdfsj    1/1     Running   0          77m
gitjob-646cdf9577-4vx2b                          1/1     Running   0          77m
gitjob-shard-shard0-586b9989dc-n8whc             1/1     Running   0          8m40s
gitjob-shard-shard1-849c555bf7-f5tf7             1/1     Running   0          77m
gitjob-shard-shard2-6c5c6ff4c9-88rsq             1/1     Running   0          77m
```

**Comment by mmartin24** [comment]
Closing this issue as main functionality works.
Opened this other issue to resolve issue on Jobs commented [above](https://github.com/rancher/fleet/issues/2456#issuecomment-2203507977): https://github.com/rancher/fleet/issues/2606
