### ISSUE TITLE
when RollingUpdate deployment stategy, fleet fails to update Git Repo state back to Active

### ISSUE THREAD

**Issue by jmatis** [rancher/fleet#249]
https://github.com/jmatis/fleet-testing/tree/main/metrics-generator

is a simple fleet repository that works nicely as is but when I change deployment strategy to **RollingUpdate**
fleet git repo never comes back from Modified to Active

as far as I can tell everything gets executed correctly, it's just the "message" about it never comes back so git repo stays marked as "Modified"
![Dashboard](https://user-images.githubusercontent.com/7556436/106273639-ea100900-622a-11eb-9583-32f5a5ae4eca.png)

logs from fleet agent after manually hitting "Force Update"
[fleet-agent.log](https://github.com/rancher/fleet/files/5893733/fleet-agent.log)

**Comment by ron1** [comment]
Have you tried adding a diff.comparePatches to fleet.yaml for your Deployment as is done here: https://github.com/rancher/fleet/issues/189. I suspect a `/spec/strategy` removal may resolve the issue.

**Comment by jmatis** [comment]
Thank you.
adding: 
`diff:
  comparePatches:
  - apiVersion: apps/v1
    kind: Deployment
    name: php-nginx-deployment
    namespace: default2
    operations:
    - {"op": "remove", "path": "/spec/strategy" }`

did help. Now I do have to add **namespace:**  key and it does not inherit namespace from values.yaml (so i can't use something like `namespace: {{ .Values.namespace }}` )

also, is there some more deep documentation I'm missing ?  I did not find any mention of diff on https://fleet.rancher.io/

**Comment by ron1** [comment]
You can combine kustomize with helm for last mile patching like the namespace. See fleet-example helm-kustomize. The kustomize namespacetransformer is super easy to use.

You might want to like outstanding issue https://github.com/rancher/fleet/issues/251 to add diff.comparePatches documentation.

**Comment by jmatis** [comment]
thank you for advice
