### ISSUE TITLE
Submodules aren't cloned recursively anymore since Fleet 0.9.x

### ISSUE THREAD

**Issue by puffitos** [rancher/fleet#2492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating to Rancher 2.8.x (and thus getting Fleet 0.9.x), we noticed that some gitrepos which dependend on submodules being recursively cloned as well don't get updated anymore. The Gitjob pods fail with an error in the lines of "failed to download <path-to-local-submodule>".

This happens apparently, because the new `gitjob gitcloner` command that took the place of the tekton containers doesn't clone recursively:

https://github.com/rancher/gitjob/blob/1495df9fee27de43ec8104faece17028a96c7459/cmd/gitcloner/gogit/cloner.go#L71C1-L83C1

This results in our bundles being stuck and having to apply some workaround (like moving our charts/manifests from the local folder to a remote location - which is OK for the time being).

### Expected Behavior

The functionality of recursively cloning submodules is still present in the current fleet version.

### Steps To Reproduce

1. Install Fleet 0.8.x (before gitjob became the default cloner for gitrepos)
2. Deploy a Gitrepo that targets a repository that uses submodules, which include a helm chart (for example, just add a the https://github.com/bitnami/charts as a submodule and instruct fleet to deploy the `chart: ./charts/bitnami/nginx/` chart)
3. See the pod get deployed
4. Update to fleet 0.9.x
5. Fleet gitjob for the GitRepo should fail after a force update, because submodule isn't pulled and cannot be found

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.9.2
- Cluster: 
  - Provider: seems irrelevant
  - Options: seems irrelevant
  - Kubernetes Version: 1.27.13
```

**Comment by sbulage** [comment]
QA Template followed: https://github.com/rancher/fleet/pull/2557#issue-2375658491

**Comment by sbulage** [comment]
System Information| Before Upgrade | After Upgrade |
|--------|--------|--------|
Rancher Version| 2.8.5 | 2.9.0-alpha7 |
Fleet Version| 0.9.5 | 0.10.0-rc.18 | 

---

### **Steps Performed:**
**Before upgrade.**
1. Created GitRepo using @manno's [fleet-experiments](https://github.com/manno/fleet-experiments) with path: `fleet-test-data/qa-test-apps/nginx-app`.
2. Wait for the resources to be deployed.
3. There is error in the job pod, stating "No resource found at the following paths to deploy: [fleet-test-data/qa-test-apps/nginx-app]"
4. Job pods are continuously created and trying to load the submodule but failing at the end.

**After Upgrade.**

5. Upgraded cluster to 2.9.0-alpha7 which include fix.
6. Wait for the Rancher and Fleet to install in the cluster.
7. Waited for Gitjob/Job pod to be created.
8. The GitRepo still showing same status i.e. Error.
9. Applied `Force Update` on GitRepo and wait for it's status to change.
10. Verified that GitRepo is showing Active state and respective applications are installed via git submodule path.


---

<details><summary><b>Screenshots Before and After installation of Rancher.</b></summary>
      <details><summary><b>Before Upgrade</b></summary>

![Screenshot from 2024-07-08 20-21-35](https://github.com/rancher/fleet/assets/12134754/8028ca06-462d-45ab-9323-b9b722b0c5f5)
    </details>
      <details><summary><b>After Upgrade</b></summary>

![Screenshot from 2024-07-08 22-48-10](https://github.com/rancher/fleet/assets/12134754/07ce6165-4c1e-4604-8784-83c88daf731a)
    </details>


</details>
