### ISSUE TITLE
Fleet fails to deploy Helm chart dependencies

### ISSUE THREAD

**Issue by janeczku** [rancher/fleet#250]
**Steps to reproduce**
Create a GitRepo resource pointing to a repository containing a helm chart with `dependencies` defined in `chart.yaml`. Example: https://github.com/janeczku/hello-helm/tree/master/chart/hello

**Expected**
One of:

1. Dependencies referenced in `chart.yaml` are fetched by Fleet and deployed, e.g. by invoking `helm dep update`
2. Documentation exists about using 3rd party sub-charts in Fleet repositories.
E.g.: Are users expected to commit externally hosted sub-charts as .tgz binary artifacts to their GitRepo repository?

**Actual**
Dependencies defined in `chart.yaml` are ignored.

**Comment by normander** [comment]
I have found some workaround for that.
If you would like to prepare a chart with dependencies you need to create a chart repository with those dependencies, e.g.:  https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/requirements.yaml
Then in your `fleet.yaml` file you need to specify this repository:

`helm:
  chart: loki-stack
  repo: https://grafana.github.io/helm-charts
  releaseName: loki-stack
  version: ^2.3.0
  values:
    loki:
      enabled: true
    promtail:
      enabled: true
    fluent-bit:
      enabled: true`

Thanks to this solution you will be able to create a full stack of dependencies.
Reference: https://fleet.rancher.io/gitrepo-structure/#fleetyaml
Enjoy!

**Comment by mxm-tr** [comment]
> I don't think this is a bug. Fleet is doing everything correctly and uses helm exactly like helm is supposed to work.

Of course helm install fails too, but is there a reason why the dependencies build or update call could not be performed by fleet?

**Comment by elmariofredo** [comment]
> The Helm chart in the git repo must include its dependencies in the charts subdirectory. This means you must run `helm dependencies update` or `helm dependencies build` locally and then commit the whole charts directory to your git repository.

There is actually option `--dependency-update` https://helm.sh/docs/helm/helm_install/#options which will fetch dependencies before installing chart. Do you have any link to helm documentation to support statement that committing tgz files into git is the recommended way of handling dependencies?
