### ISSUE TITLE
Support non standard ports for private GitRepo

### ISSUE THREAD

**Issue by abal0011** [rancher/fleet#256]
I'm trying to add a private bitbucket project which has SSH access through non standard port say 7999 to Continuous Delivery but got an Error

![image](https://user-images.githubusercontent.com/32474278/106529277-56964b00-653e-11eb-83e4-380f73b4983a.png)

My observation  is that it does not accept any non standard port for SSH i.e. git@github.com:7999/wv/charts.git still tries for port 22 and not through non standard port 7999. 

When I tried to add my personal GitHub private repo and followed the same process ( adding secret private key in rsa 4096 format ) and uses port 22 .. it works as expected.

**Comment by GooseYArd** [comment]
We had a similar issue with our installation. Initially we prefixed the URI with "ssh://" and saw a message indicating that " ssh" was an unknown protocol. Not realizing that we had inadvertently included a leading space in the git uri, we assumed that the ssh:// protocol prefix was disallowed and removed it. Subsequently, git ls-remote commands failed in the same manner as they did for you.

After some debugging we realized that it was git itself which ignored the non-standard port when the ssh:// prefix wasn't used, and we later noticed the superfluous leading space and removed it, which fixed the issue.

It'd probably be good for Fleet to ignore the leading space when saving the Git URI.
