### ISSUE TITLE
Feature Request: Way to ignore whitespaces when doing diff with clipboard (compare)

### ISSUE THREAD

**Issue by dennnyb** [rancher/fleet#2568]
### Is your feature request related to a problem?

Assume that I want to compare different config files using Compare with clipboard feature, as I did not find way how to compare files directly. See the screenshot for the reference. Whitespaces are visible and I did not find any way how to ignore them. It is little distracting.
<img width="1019" alt="image" src="https://github.com/rancher/fleet/assets/28920699/5c787528-326e-4c4c-b275-25821079cf96">

### Solution you'd like

Ability to ignore whitespaces.

**Comment by manno** [comment]
Seems unrelated
