### ISSUE TITLE
Think about where Grafana dashboards for fleet metrics would fit into the UI

### ISSUE THREAD

**Issue by p-se** [rancher/fleet#2634]
Think about where Grafana dashboards for fleet metrics would fit into the UI and create a table with those suggestions.

**Comment by p-se** [comment]
| Rancher UI Page    | Grafana Dasbhoard | Position | Data Shown | 
| -------- | ------- | --- | --- | 
| Continuous Delivery -> Git Repos  | Fleet / GitRepo    | bottom | unfiltered (all) |
| (optional) Continuous Delivery -> Git Repos -> Particular Git Repo | Fleet / GitRepo | bottom | filtered to selected git repository |
| Continuous Delivery -> Clusters | Fleet / Clusters | bottom | unfiltered (all) |
| (optional) Continuous Delivery -> Clusters | Fleet / Clusters | bottom | filtered to selected cluster |
| Continuous Delivery -> Cluster Groups | Fleet / ClusterGroup | bottom | unfiltered (all) |
| (optional) Continuous Delivery -> Cluster Groups | Fleet / ClusterGroup | bottom | filtered by selected cluster group |
| Continuous Delivery -> Advanced -> Bundles | Fleet / Bundle | bottom | unfiltered (all) |
| (optional) Continuous Delivery -> Advanced -> Bundles | Fleet / Bundle | bottom | unfiltered (all) |


- Where `bottom` means after all other elements on the page.
- Where `(optional)` means that it could be too much or could even be integrated as replacement for the "overview" implementation.
- `Fleet / BundleDeployment` dashboard shall not be shown in the UI.
- `Fleet / Controller-Runtime` dashboard shall not be shown in the UI.
- Changes to the dashboards might be necessary to make them fit better into the UI, e.g. one panel of all visualized resources is showing data that the UI shows as well.

**Comment by richard-cox** [comment]
General Patterns To Resolve
- Grafana dashboards that represent a whole resource type displaying on same page as lists of that type
- Grafana dashboards that represent a specific resource displaying on the same page as the detail of that resource
  - We have this one partially solved given detail pages contain tabs

General Overlap between UI and Charts
- There's some, but it's not 1-1
- I couldn't find any contradictory stats
  - Bundles with no deployments were not counted in grafana though
- The UI does not show any state over time graphs

Next steps, will raise internally for a UX review

Specifics
- Git Repos
  - Chart Shows
    - cluster ready %, state counts, state over time
    - resource ready %, state counts, state over time
  - UI shows
    - git repo state,
    - git repo cluster ready fraction
    - git repo resource state counts
    - detail
      - bundle ready fraction, state counts
      - resource ready fraction, state counts
      - bundle deployment count
      - resources 
- Clusters
  - Chart Shows
    - git repo ready %, state counts, state over time
    - resource ready %, state counts, state over time
    - cluster ready %, state counts, state over time
  - UI shows
    - cluster state
    - git repo ready count
    - bundles ready count
    - details
      - git repo ready state
      - resource state counts
      - cluster resource state counts
- Cluster Groups
  - Chart shows 
    - bundle ready %, state counts, state over time
    - cluster ready %, state counts, state over time
    - resource ready %, state counts, state over time
  - UI shows
    - group state
    - per cluster ready count
    - per cluster resource state counts
    - detail
      - cluster ready %
      - resource state counts
      - cluster bundle ready count
      - cluster git repo ready count
      - cluster repo ready count
- Bundles
  - Chart Shows
    - bundle ready %, state counts, state over time
  - UI shows
    - bundle state
    - deployment count 
    - detail
      - resource count

**Comment by manno** [comment]
I think this issue is done?
