### ISSUE TITLE
Fleet-agent bundle is in flapping state between `wait Applied` and `modified`

### ISSUE THREAD

**Issue by Ellenqs** [rancher/fleet#267]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy rancher single install.
- Create a downstream cluster.
- Go to system project, find the workload fleet-agent, edit it, e.g. adding an environment variable.
- Go to cluster explorer ->continuous delivery -> bundles

**Result:**
The fleet-agent bundle state switches between `modified` and `waitApplied` state.
<img width="462" alt="Screen Shot 2021-02-06 at 3 23 22 PM" src="https://user-images.githubusercontent.com/75277058/107131956-0695ec00-6890-11eb-8087-38f4bb450c64.png">
<img width="425" alt="Screen Shot 2021-02-06 at 3 23 34 PM" src="https://user-images.githubusercontent.com/75277058/107131959-085faf80-6890-11eb-9f2e-4fcc1cb139cc.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5.6-rc4`
- Installation option (single install/HA): single install
- Fleet version: `v0.3.4-rc3`

**Comment by StrongMonkey** [comment]
This is not easy to address due to the nature of fleet.(it uses bundle to manage fleet-agent so it has to make sure the actual state of fleet-agent matches the spec). I would put a requirement to not modify fleet-agent from outside.

**Comment by sowmyav27** [comment]
@StrongMonkey Based on https://github.com/rancher/fleet/issues/267#issuecomment-844377177, should we release note this or have a docs issue logged for this?

**Comment by StrongMonkey** [comment]
@sowmyav27 I think putting a note in doc should be enough.

**Comment by Jono-SUSE-Rancher** [comment]
@sowmyav27 - Did you happen to log a docs issue for this yet, or do you need Sheilagh or myself to do that? Let me know, and if you did, go ahead and close this with the understanding that we're going to document it.

**Comment by aaronRancher** [comment]
Logged a docs issue: https://github.com/rancher/docs/issues/3339
