### ISSUE TITLE
Document for UI how to enable and use sharding

### ISSUE THREAD

**Issue by manno** [rancher/fleet#2671]
Sharding should be usable from the Rancher UI, this involves two parts, editing the Fleet installation options and adding internal sharding labels to resources. We need to create an issue in the dashboard repo.
 
* how does sharding work
* how to enable it
* how to use it with gitrepos
* how to configure node selectors

**Comment by weyfonk** [comment]
Issue created, see https://github.com/rancher/dashboard/issues/11665.
