### ISSUE TITLE
Add k8s events to reconcilers

### ISSUE THREAD

**Issue by manno** [rancher/fleet#2674]
Fleet writes information about deployments and errors into the status of resources. To assist users with troubleshooting, e.g. when they don't have access to the logs, we can record k8s events.

* record events for critical/terminal failures
* record events for noteworthy deployment steps
* don't add too many events, keep logging separate from events
* events should use the past tense 

Log and debug messages still exists for details and tracing.

See:
* https://book-v1.book.kubebuilder.io/beyond_basics/creating_events

**Comment by sbulage** [comment]
I can see the k8s events are generating for the Fleet operations i.e. GitRepo commit found, pod creation, deletion etc. See below screenshot for more details.

<details>
<summary><b>Screenshot showing Fleet events</b></summary>

![Screenshot from 2024-08-14 15-56-31](https://github.com/user-attachments/assets/0fa07116-a298-4d95-a63d-5438e222f0c4)

</details>
