### ISSUE TITLE
Cluster status is Not Ready after GitRepo showing Active status

### ISSUE THREAD

**Issue by sbulage** [rancher/fleet#2699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

GitRepo showing status `Active` after deploying applications to respective clusters. But Clusters are not updating their status immediately instead showing `Not Ready` state.

### Expected Behavior

Cluster status should be updated in sync with GitRepo status.

### Steps To Reproduce

1. Create a GitRepo (may be) targeting to local cluster.
2. Wait for the application to be deployed to the local cluster.
3. Go to Continuous Delivery --> Clusters
4. See the status of the local cluster it is in `Not Ready` state. (See attached screenshot for more detailed information)

### Environment

```markdown
- Architecture:
- Fleet Version: 0.10.0-rc.1
- Cluster:
  - Provider:k3s
  - Options:
  - Kubernetes Version:
```

### Anything else?

It is not happening in Rancher 2.8 or 2.7.

**Screenshot:**

- kubectl output:
![Screenshot from 2024-08-05 14-26-21](https://github.com/user-attachments/assets/daeaab7d-ddd4-43d9-a024-c816641e6b62)

- Actual Screenshot
![Screenshot from 2024-08-05 14-14-23](https://github.com/user-attachments/assets/a1bba4a2-2635-4488-b1ad-1572139974dc)

**Comment by slickwarren** [comment]
some other testing shows that forcing an update on the clusterGroups will update the resource count.

**Comment by sbulage** [comment]
### System Information

| Rancher Version | Fleet Version |
|--------|--------|
| **v2.9-head** | **104.0.2+up0.10.2-rc.1** |
---

### Steps followed from the description

1. Create a GitRepo (may be) targeting to local cluster.
2. Wait for the application to be deployed to the local cluster.
3. Go to Continuous Delivery --> Clusters
4. Verified that the status of the local cluster is Active in-sync with GitRepo status.
---
### Screenshot/Video
See below video for more detail (Check downstream cluster status using cluster groups)

https://github.com/user-attachments/assets/eb1c5296-e3a5-4fc0-8059-bb41fc0e88be

**Comment by slickwarren** [comment]
hello, I'm still seeing this on `v0.10.2-rc.4` using rancher 2.9.2-alpha5, but I'm using a downstream cluster instead of the local cluster. Is there a chance the downstream cluster sync works differently from the local cluster?

**Comment by sbulage** [comment]
@slickwarren I am not able to reproduce it with downstream cluster or with local cluster either, see below videos.

<details>
<summary><b>Downstream Cluster video</b></summary>

https://github.com/user-attachments/assets/e5b4d132-3b6f-470a-8e40-c59049b1a50a

</details>

<details>
<summary><b>Local Cluster video</b></summary>

https://github.com/user-attachments/assets/839cce85-a2d5-487b-b4c9-7f865ad387d5

</details>

**Comment by manno** [comment]
> Is there a chance the downstream cluster sync works differently from the local cluster?

No, it's the same. Setup is a bit different, but it's handled like any other cluster.

**Comment by slickwarren** [comment]
after viewing the video, you're right. what I'm seeing is closer to the linked customer reported issue; I'll post my comments there.
