### ISSUE TITLE
[SURE-8468] Fleet should handle symlinks in a GitRepo

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#2700]
### Request description:
Fleet should handle symlinks in a git repository.

### Actual behavior:

The customer is trying to use the following git repository in Fleet: https://github.com/nginxinc/kubernetes-ingress.git
They specify the /charts/nginx-ingress path. You can see in that path it contains a symlink to the crds directory.

This causes a problem where the git repo will not target any clusters in Rancher.
In the pod that gets created in the upstream fleet-default namespace, I can see this error:

```
Error (time="2024-05-17T19:17:30Z" level=fatal msg="failed to read . relative to /workspace/source/charts/nginx-ingress: read /workspace/source/charts/nginx-ingress/crds: is a directory" ) 
```

So Fleet does not seem to like the symbolic link.

### Expected behavior:
Fleet should work with symlinks in the git repository.

### Workaround:
Is workararound available and implemented? yes/no
What is the workaround: Instead of the symlink, manually create a directory and recreate the manifest files.

**Comment by manno** [comment]
They could use the helm chart instead of the upstream nginx git repo. We don't intend to add that feature.

**Comment by weyfonk** [comment]
If we ever decided to work on this, it could be made easier by Golang 1.24's new [os.Root](https://go.dev/blog/osroot).
