### ISSUE TITLE
fleet agent doesn't real like TLS/SSL certificates

### ISSUE THREAD

**Issue by Raboo** [rancher/fleet#275]
This is the fleet that came bundled with Rancher v2.5.5 that got installed automagically when I upgraded my Rancher v2.4.x cluster to v2.5.5.

The fleet agent in the "workload" cluster, i.e. rancher managed k8s cluster.

It doesn't seem to like TLS/SSL.
```
time="2021-02-11T13:38:47Z" level=error msg="Failed to register agent: looking up secret fleet-system/fleet-agent-bootstrap: Post \"https://rancher.mydomain.io/apis/fleet.cattle.io/v1alpha1/namespaces/fleet-default/clusterregistrations\": x509: certificate signed by unknown authority" 
```

I do have a valid certificate issued by Sectigo.

```bash
$ curl -v -XPOST "https://rancher.mydomain.io/apis/fleet.cattle.io/v1alpha1/namespaces/fleet-default/clusterregistrations" 2>&1|grep -A1 issuer
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo ECC Domain Validation Secure Server CA
*  SSL certificate verify ok.
```

I don't know if this is relevant but my Rancher cluster is behind an external load balancer which does the TLS termination and then relays the traffic to Rancher, but also via HTTPS, but Rancher uses a self signed certificate. However "rancher.mydomain.io" should be valid and terminated by the external load balancer and no application should actually be aware that it's an external load balancer.

How do I proceed?

**Comment by ron1** [comment]
It may be that recently committed PR https://github.com/rancher/fleet/pull/165 resolves this issue.

**Comment by Raboo** [comment]
Alright nice! PR #165 will be included in v0.3.4 it seems.
But since fleet was bundled with Rancher 2.5 and there is no documentation anywhere on how to upgrade the bundled fleet, what would be the proper way of bumping up fleet to v0.3.4 on a Rancher cluster once it is out?

**Comment by ron1** [comment]
I suspect Fleet 0.3.4 will be released along with Rancher 2.5.6.

**Comment by Raboo** [comment]
I mean this is a blocker for me since fleet won't work. So the only fix or work-around is to wait?

The whole big change in Rancher 2.5.x was that bundled apps can be installed and upgraded via "Apps and Marketplace" using Helm charts. But that didn't happen with fleet, however there must be a way to upgrade the bundled fleet via Helm or a plain Kubernetes manifest.
Maybe I should ask in the Rancher repo or the forum?

**Comment by ron1** [comment]
Fleet is deployed via helm charts. Suggest you ask how to patch upgrade fleet in the #fleet slack channel.

**Comment by Raboo** [comment]
I upgraded to v0.3.4-rc5. It seems to mitigate the problem. So I guess #165 fixes it.
