### ISSUE TITLE
Cluster state goes to "out of sync" which lead to failing to create Gitrepo on SELinux enabled instances.

### ISSUE THREAD

**Issue by Ellenqs** [rancher/fleet#278]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy rancher single install.
- Creating two downstream clusters.
- Go to cluster explorer -> Continuous Delivery.
- Go to clusters -> Edit config -> add label -> save.

**Result:**
The cluster will go into "out of sync" state. Then if create Gitrepo, the app can not be deployed.

<img width="1122" alt="Screen Shot 2021-02-11 at 3 53 27 PM" src="https://user-images.githubusercontent.com/75277058/107809707-5ce7ac80-6d20-11eb-8366-572728dc14a3.png">
<img width="888" alt="Screen Shot 2021-02-11 at 8 24 55 PM" src="https://user-images.githubusercontent.com/75277058/107810962-50fcea00-6d22-11eb-9cba-70487dd99042.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5-head, 761c805d`
- Installation option (single install/HA): single install
- Machine type (cloud/VM/metal) and specifications (CPU/memory): ` centos-8.2-selinux-ON`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom

**Comment by StrongMonkey** [comment]
@Ellenqs You can test this when the latest rc of fleet is pushed. This is related to https://github.com/rancher/fleet/issues/206

**Comment by Ellenqs** [comment]
Validated on Rancher `v2.5-head 03b8153`and `master-head 2bccb50`.

**Steps:**

- Deploy two setups of rancher v2.5.5 single install.
- Create several downstream clusters, remove etcd node from one cluster make it in `updating` state.
- Upgrade one setup to rancher to 2.5-head, another to master-head.
- Once the setup is active, go to cluster-explorer-> Apps& marketplace -> check fleet version.
- Go to continuous delivery.
- Go to clusters, edit config, add labels.

**Results**

The fleet version is upgraded to 0.3.400-rc06. The clusters upgraded successfully and after adding labels they are still in active state.

-
