### ISSUE TITLE
Could the GitRepo watch for a pull request?

### ISSUE THREAD

**Issue by jinzishuai** [rancher/fleet#281]
So far, I see only `branch` and `revision` as options when setting up a GitRepo (https://fleet.rancher.io/gitrepo-add/).  

I would like to only deploy bundles for pull requests, not just any branch. And in the perfect world, I would like to use keyword in the PR title or labels to trigger different behaviours.  Of course this is quite easy to do in Jenkins. I wonder if similar functionality exists in fleet. 

Thanks a lot

**Comment by kkaempf** [comment]
Not sure if triggering a deployment on a PR is a good idea 🤔
