### ISSUE TITLE
Does fleet support helm secrets plugin?

### ISSUE THREAD

**Issue by jinzishuai** [rancher/fleet#282]
We use the [helm-secrets](https://github.com/jkroepke/helm-secrets) to manage secrets using AWS KMS. 
I wonder if we could use it with fleet. If so, may I have some reference doc/example?

Thank you very much

gz#15522

**Comment by mumblez** [comment]
anything sops related seems broken atm, see https://github.com/rancher/fleet/issues/144

**Comment by strowi** [comment]
any update on this? Can't find any documentation about this..

**Comment by kkaempf** [comment]
see #144
