### ISSUE TITLE
[SURE-8993] CABundle secret not created for gitjob

### ISSUE THREAD

**Issue by sebastienmusso** [rancher/fleet#2824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When create a gitrepo with CABundle string, git-sync job is created with an extra volume secret wich does not exist.
The init container remain in pending state because of the missing secret

### Expected Behavior

When a gitrepo is created with CABundle spec field, the secret with gitrepoName-cabundle have to be created

### Steps To Reproduce

- Architecture: amd64
- Fleet Version: v0.10.1
- Cluster: 
  - Provider: rke2
  - Options: none
  - Kubernetes Version: v1.28.11+rke2r1

install fleet v0.10.1, create gitrepo with caBundle spec field set.
Wait gitsync pod de start

### Environment

```markdown
- Architecture:
- Fleet Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

**Comment by manno** [comment]
An integration test would be helpful, to make sure this stays in place.

**Comment by weyfonk** [comment]
## Additional QA
See [this comment](https://github.com/rancher/fleet/issues/2829#issuecomment-2346053122)

**Comment by kkaempf** [comment]
@manno shouldn't this be targeting 2.9.x instead ?

**Comment by mmartin24** [comment]
Verified in `v2.10-fe49760f4e50d0b78ca0102c8475bc93361336b0-head` with `fleet:105.0.0+up0.11.0-beta.3`

- ca-bundle secret IS created when TLS cert is added
- ca-bundle secret IS NOT created when TLS cert is not added

![image](https://github.com/user-attachments/assets/54f7f1fd-9ba9-4e19-aed7-95cef10b47ce)
