### ISSUE TITLE
[SURE-9010] Gitjob pod cannot create known_hosts, read-only filesystem

### ISSUE THREAD

**Issue by manno** [rancher/fleet#2826]
SURE-9010 -  Gitrepos are in Error state with read-only file system

- [x] add emptydir mount on tmp
- [ ] the security context should not be disabled when running e2e tests. can we still enable debug logging, do we want to?
- [x] sharding tests should not rely on debug logging: https://github.com/rancher/fleet/actions/runs/10809800641/job/29987822349?pr=2830

**Comment by manno** [comment]
- [ ] we need to figure out how to deal with debug logging in our tests, it disables the security context, but it's useful for finding errors.

**Comment by kkaempf** [comment]
Wouldn't this validate a `2.9.2` backport ?

**Comment by manno** [comment]
> Wouldn't this validate a `2.9.2` backport ?

We created separate backport  issues: https://github.com/rancher/fleet/issues/2828

**Comment by mmartin24** [comment]
Checked and working in `v2.10.0-alpha5` with `fleet:105.0.0+up0.11.0-beta.3`

Automation checking known-hosts with private gitrepos ok [here](https://github.com/rancher/fleet-e2e/actions/runs/11589622310/job/32265517007#step:9:289)

Manually rechecked that: 
- `known-host` is created and gitrepo needing it is correctly deployed. Confirmed secret is created.
- ![image](https://github.com/user-attachments/assets/988d94ee-5664-46d4-a4c1-af86ed257a30)
- Gitrepo is not created if `known-host` is not passed and needs it
