### ISSUE TITLE
Specify another values file from fleet.yaml

### ISSUE THREAD

**Issue by jinzishuai** [rancher/fleet#283]
We are evaluating using fleet (part of Rancher 2.5) to add some CI/CD functions.  Our helm charts already have different value files (used with `helm -f`) in the repo for difference clusters (pd/qa/dev for example).  I wonder if we could simply use  a pointer inside the `fleet.yaml` file to point to an existing yaml file instead of copying the contents into the new `fleet.yaml`.

Thanks

**Comment by ron1** [comment]
Duplicates https://github.com/rancher/fleet/issues/188?

**Comment by jinzishuai** [comment]
closing due to replication of existing #188 as mentioned above. thanks.
