### ISSUE TITLE
Vs Flux, Argo?

### ISSUE THREAD

**Issue by pestaa** [rancher/fleet#284]
Sorry I haven't found a better place to ask this. How does Fleet compare to Flux and ArgoCD?

It's tempting to just get started with Fleet since it's built into Rancher, but what are the differences from more mature or popular gitops operators? Thank you.

**Comment by ron1** [comment]
Suggest you ask this type of question in rancher #fleet slack channel.

**Comment by pestaa** [comment]
Thanks, just joined the community.

I also found this meetup with lots of details: https://www.youtube.com/watch?v=7o9_V-W60m8
