### ISSUE TITLE
Fleet seems unable to communicate within itself (  Get \"https://10.43.140.17/k8s/clusters/local/version?timeout=15s\": dial tcp 10.43.140.17:443: connect: no route to host, requeuing")

### ISSUE THREAD

**Issue by baptisterajaut** [rancher/fleet#2844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

All my cluster are showing an error in upstream cluster, eventough the local and production work
And i cant seem to import a new cluster nor recover one.
I am absolutely clueless on how to fix that.

### Expected Behavior

I should be able to import my clusters and create new ones.

### Steps To Reproduce

Not sure. I had rancher 2.8.5 and i updated to 2.9.1.

### Environment

```markdown
- Architecture: amd64
- Rancher 2.9.1 - Single docker node
- Fleet Version: v0.10.1 
- Cluster:
  - Provider: rke2
  - Options: none
  - Kubernetes Version: 1.28.10+rke2
```

### Logs

```markdown
time="2024-09-13T08:45:00Z" level=error msg="error syncing 'fleet-default/production': handler import-cluster: Get \"https://10.43.140.17/k8s/clusters/c-m-rh7vjf7x/version?timeout=15s\": dial tcp 10.43.140.17:443: connect: no route to host, requeuing"
time="2024-09-13T08:46:15Z" level=error msg="Cluster import for 'fleet-default/bureau'. Smoke test failed: Get \"https://10.43.140.17/k8s/clusters/c-m-p7k54glf/version?timeout=15s\": dial tcp 10.43.140.17:443: connect: no route to host"
time="2024-09-13T08:46:15Z" level=error msg="error syncing 'fleet-default/bureau': handler import-cluster: Get \"https://10.43.140.17/k8s/clusters/c-m-p7k54glf/version?timeout=15s\": dial tcp 10.43.140.17:443: connect: no route to host, requeuing"
time="2024-09-13T08:46:21Z" level=error msg="Cluster import for 'fleet-default/bureau'. Smoke test failed: Get \"https://10.43.140.17/k8s/clusters/c-m-p7k54glf/version?timeout=15s\": dial tcp 10.43.140.17:443: connect: no route to host"
time="2024-09-13T08:46:21Z" level=error msg="error syncing 'fleet-default/bureau': handler import-cluster: Get \"https://10.43.140.17/k8s/clusters/c-m-p7k54glf/version?timeout=15s\": dial tcp 10.43.140.17:443: connect: no route to host, requeuing"
time="2024-09-13T08:47:20Z" level=error msg="Cluster import for 'fleet-default/testcluster'. Smoke test failed: Get \"https://10.43.140.17/k8s/clusters/c-m-f9qr9b5w/version?timeout=15s\": dial tcp 10.43.140.17:443: connect: no route to host"
time="2024-09-13T08:47:20Z" level=error msg="error syncing 'fleet-default/testcluster': handler import-cluster: Get \"https://10.43.140.17/k8s/clusters/c-m-f9qr9b5w/version?timeout=15s\": dial tcp 10.43.140.17:443: connect: no route to host, requeuing"
time="2024-09-13T08:51:27Z" level=error msg="Cluster import for 'fleet-default/production'. Smoke test failed: Get \"https://10.43.140.17/k8s/clusters/c-m-rh7vjf7x/version?timeout=15s\": dial tcp 10.43.140.17:443: connect: no route to host"
time="2024-09-13T08:51:27Z" level=error msg="error syncing 'fleet-default/production': handler import-cluster: Get \"https://10.43.140.17/k8s/clusters/c-m-rh7vjf7x/version?timeout=15s\": dial tcp 10.43.140.17:443: connect: no route to host, requeuing"
time="2024-09-13T08:51:46Z" level=error msg="Cluster import for 'fleet-local/local'. Smoke test failed: Get \"https://10.43.140.17/k8s/clusters/local/version?timeout=15s\": dial tcp 10.43.140.17:443: connect: no route to host"
time="2024-09-13T08:51:46Z" level=error msg="error syncing 'fleet-local/local': handler import-cluster: Get \"https://10.43.140.17/k8s/clusters/local/version?timeout=15s\": dial tcp 10.43.140.17:443: connect: no route to host, requeuing"
```

### Anything else?

![image](https://github.com/user-attachments/assets/9dc8b921-330d-47d8-8643-967cf5d1184d)

**Comment by mmartin24** [comment]
Hello @baptisterajaut.
I tried to reproduce this issue using single node k3s + separate downstream cluster with gitrepos both locally and on default and upgrading from `2.8.5` to `2.9.1`and worked ok.

![2 8 5_ok](https://github.com/user-attachments/assets/ddd44a41-d80c-44a1-a19b-f04d60a7b99f)
![2 9 1_ok](https://github.com/user-attachments/assets/d953efb4-5c06-4da7-9221-f0ff6284d1f3)

Could you please provide further steps on how the original set up was deployed?

**Comment by baptisterajaut** [comment]
> Hello @baptisterajaut. I tried to reproduce this issue using single node k3s + separate downstream cluster with gitrepos both locally and on default and upgrading from `2.8.5` to `2.9.1`and worked ok.
> 
> ![2 8 5_ok](https://private-user-images.githubusercontent.com/37271841/367272893-ddd44a41-d80c-44a1-a19b-f04d60a7b99f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjc5NzcsIm5iZiI6MTcyNjIyNzY3NywicGF0aCI6Ii8zNzI3MTg0MS8zNjcyNzI4OTMtZGRkNDRhNDEtZDgwYy00NGExLWExOWItZjA0ZDYwYTdiOTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExNDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YTVhMjljYzNmYmYwOWRmNDhkZGM2NGFlZjI2OWVhYTAyZWM1ZmM0MzIxMjdmYTBlMzE2MDg2NmUwNWE2N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GOJROxcCNY_C6EIoUqAbN9es4zDfpDlS-SBVyzWtcLM) ![2 9 1_ok](https://private-user-images.githubusercontent.com/37271841/367272885-d953efb4-5c06-4da7-9221-f0ff6284d1f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjc5NzcsIm5iZiI6MTcyNjIyNzY3NywicGF0aCI6Ii8zNzI3MTg0MS8zNjcyNzI4ODUtZDk1M2VmYjQtNWMwNi00ZGE3LTkyMjEtZjBmZjYyODRkMWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExNDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YjViN2MxZjBkNTA0NzgyM2YzZjUwMTkyZTgzZmQzMjVjNGZhMjJlOTMxNWNkNTJjMDhkZDJlYTExZWIwMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FN8i0oZ7PQ2ETkXOFmUoJjQYvzghqJBa2w5hVZCxgNY)
> 
> Could you please provide further steps on how the original set up was deployed?

Thank you so much for your quick reply. This was actually not on fleet part. I spent the entire week trying to find the underlying problem, and found it. Its on rancher part https://github.com/rancher/rancher/issues/47102

Sorry for inconvenience.

**Comment by mmartin24** [comment]
> Thank you @mmartin24 so much for your quick reply. This was actually not on fleet part. I spent the entire week trying to find the underlying problem, and found it. Its on rancher part [rancher/rancher#47102](https://github.com/rancher/rancher/issues/47102)
> 
> Sorry for inconvenience.

Not at all @baptisterajaut. Thanks to you for reaching out.
