### ISSUE TITLE
Debug flag should not disable security context

### ISSUE THREAD

**Issue by manno** [rancher/fleet#2871]
Follow up on https://github.com/rancher/fleet/issues/2826

Installing the fleet helm chart with `--set debug` also disables the security contexts on pods to allow for a debugger to be attached.  Might also be related to profiling, etc.

This might be surprising and is not well documented. Furthermore, our e2e tests should test with a security context, they should however output debug messages, so we can download the logs and analyze them.

- [x] pod and container security contexts can be toggled on/off via helm chart, just like debug logging
- [x] agent [inherits](https://github.com/rancher/fleet/blob/main/internal/cmd/controller/agentmanagement/agent/manifest.go#L291-L297) debug logging and security context toggle if `propagateDebugSettingsToAgents` is set
- [ ] could the security context, at least for the controller, be a helm chart value? It's currently an if-switch in the template.
- [x] e2e tests have debug logging re-enabled

**Comment by sbulage** [comment]
### System Information
| Rancher Version | Fleet Version |
|--------|--------|
| **v2.10.0-alpha7** | **fleet:v0.11.0-rc.2** | 

---

### Security Context before `disableSecurityContext: false` and `debug OFF`

<details>
<summary>Fleet Debug level set in <b><i>rancher-config</i></b> ConfigMap</summary>

![Screenshot from 2024-11-05 19-22-06](https://github.com/user-attachments/assets/0d8b8404-d165-40c7-b2e6-bcff8918ba98)

</details>

| Fleet Controller Pod | Fleet Agent Pod | GitJob Pod |
|--------|--------|--------|
| ![Screenshot from 2024-11-05 19-06-10](https://github.com/user-attachments/assets/57dd25a8-5850-4874-9ecb-8e80e3309092) | ![Screenshot from 2024-11-05 19-07-17](https://github.com/user-attachments/assets/434beaa3-45a2-4ea8-854f-78325135c980) | ![Screenshot from 2024-11-05 19-06-46](https://github.com/user-attachments/assets/2961c5c9-e616-4fe9-9961-e697229cff19)| 

---

### Security Context before `disableSecurityContext: false` and `debug ON`

| Fleet Controller Pod | Fleet Agent Pod | GitJob Pod |
|--------|--------|--------|
|![Screenshot from 2024-11-05 19-10-43](https://github.com/user-attachments/assets/ceb413e3-d18b-41c0-97a8-7c58982a9b9a)|![Screenshot from 2024-11-05 19-11-57](https://github.com/user-attachments/assets/77266500-b566-4810-b48e-bc3d5b91c356) | ![Screenshot from 2024-11-05 19-11-16](https://github.com/user-attachments/assets/84fa07cd-a6cd-4f35-a121-f9d6ae67f4cb) | 

---

### Security Context before `disableSecurityContext: true` and `debug ON`

<details>
<summary>Set <b><i>disableSecurityContext</i></b> to <b><i>true</i></b> in <b><i>rancher-config</i></b> ConfigMap</summary>

![Screenshot from 2024-11-05 20-06-45](https://github.com/user-attachments/assets/8c8c82d6-1623-4ee4-b6a2-2a5e559686d3)

</details>

| Fleet Controller Pod | Fleet Agent Pod | GitJob Pod |
|--------|--------|--------|
| ![Screenshot from 2024-11-05 19-39-43](https://github.com/user-attachments/assets/c887e70c-0b1a-4599-af77-d86411907c98) | ![Screenshot from 2024-11-05 19-40-32](https://github.com/user-attachments/assets/1369c46b-ddd7-47b1-af16-07e6bd8339df) | ![Screenshot from 2024-11-05 19-40-09](https://github.com/user-attachments/assets/6eb894ba-b5f7-4414-b18b-ba0022c5b135) | 

---
