### ISSUE TITLE
Unable to deploy fleet-agent on downstream clusters

### ISSUE THREAD

**Issue by slickwarren** [rancher/fleet#290]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* rancher on master-head
* downstream cluster deployed normally

**Result:**
fleet-agent is not installed on the downstream cluster

**Other details that may be helpful:**
Manually installing fleet-agent through rancher charts/apps results in the following error on the downstream cluster:

`Error: template: fleet-agent/templates/validate.yaml:10:3: executing "fleet-agent/templates/validate.yaml" at <fail "apiServerURL is required to be set, and most likely also apiServerCA">: error calling fail: apiServerURL is required to be set, and most likely also apiServerCA`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (dbf1838)
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Linode, driver provisioned
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4vCPU
- Kubernetes version (use `kubectl version`): v1.20.4

- Docker version (use `docker version`): 20.10.3

**Comment by StrongMonkey** [comment]
Is this still reproducible? I am not able to reproduce it on master-head anymore. Also, if you want to test deploying fleet-agent separately, you must follow the steps here: http://fleet.rancher.io/agent-initiated/#install-agent-for-a-new-cluster

**Comment by StrongMonkey** [comment]
This is an issue for master not 2.5.8. We should put it in 2.6

**Comment by slickwarren** [comment]
on master-head 89c4d85
`secrets "c-fsv5c-kubeconfig" not found`
<img width="894" alt="Screen Shot 2021-04-01 at 2 10 31 PM" src="https://user-images.githubusercontent.com/16691014/113354461-14964500-92f4-11eb-801d-f8382dba11d3.png">

**Comment by StrongMonkey** [comment]
@slickwarren We should retest this. I see Master head is stable right now and fleet-agent should deploy successfully.

**Comment by slickwarren** [comment]
fleet-agent is deployed by default on downstream clusters, and appears to be working normally on master-head (3e89bb8):
* cluster deployed through ember has fleet-agent
* cluster deployed thorugh dashboard +rke2 has fleet-agent
* continuous delivery is working properly and shows nodes as active
<img width="621" alt="Screen Shot 2021-05-13 at 10 58 51 AM" src="https://user-images.githubusercontent.com/16691014/118166370-406c1680-b3da-11eb-8549-11e590eda617.png">
<img width="1104" alt="Screen Shot 2021-05-13 at 10 56 49 AM" src="https://user-images.githubusercontent.com/16691014/118166395-4530ca80-b3da-11eb-9921-a9dd91405a92.png">
