### ISSUE TITLE
[v0.10] Backport of [SURE-9061] Increase Worker Count Defaults

### ISSUE THREAD

**Issue by manno** [rancher/fleet#2908]
Backport of #2899
 Fleet uses a conservative defaults. The previous version used 50 queue workers

The worker count is only configurable for the gitops, bundle and bundledeployment controllers. Cluster and cluster groups are also involved in many requests.

**Comment by mmartin24** [comment]
## QA observations:
Tested on Rancher `v2.9-3511f1655eaf53f86df3d87b9d4ff6f754d18d80-head` with `104.0.3+up0.10.3-rc.2`

---

Worker count set to 50 confrmed to exist in Rancher `v2.9-3511f1655eaf53f86df3d87b9d4ff6f754d18d80-head` with fleet `104.0.3+up0.10.3-rc.2`

![image](https://github.com/user-attachments/assets/0685eb8f-7de8-456d-86de-a759150a24c0)

---
Regarding performance measured, I deployed 50 gitepos like [this](https://github.com/mmartin24/test-fleet/tree/master/multiple-gitrepos/gitrepo-1) one with nginx image  which took a few seconds between each and compared versions with previous and new versions. These are results:

Rancher `v2.9-3511f1655eaf53f86df3d87b9d4ff6f754d18d80-head` with `fleet:v0.10.3-rc.1`

- 35 gitrepos: 07:45 (1 gitrepo / 12.8 sec)
- 50 gitrepos: 14:34 (1 gitrepo / 27 2 sec)

Rancher `v2.9-3511f1655eaf53f86df3d87b9d4ff6f754d18d80-head` - with `fleet:v0.10.3-rc.2`

- 35 gitrepos : 07.15 (1 git repo / 12.3 sec)
- 50 gitrepos: :14:10 (1 girtrepo / 28 sec)

Results are quite similar for test done, but that does not mean there may other improvements for other situations.
