### ISSUE TITLE
Feature Request: Retry if GitRepo client fails

### ISSUE THREAD

**Issue by framctr** [rancher/fleet#2912]
### Is your feature request related to a problem?

When a Git repo is not reachable due to a maintenance (e.g., GitLab self-hosted update), Fleet fails to connect and the Fleet client does not retry, leading to a 502 error message:
```
Unexpected client error: unexpected requesting "https://gitlab.xyz/project.git/info/refs?service=git-upload-pack" status code: 502
```
To fix, we have to "Force Update" every single GitRepo.

### Solution you'd like

In case of failure, Fleet retries to connect to a git endpoint.

### Alternatives you've considered

Webhooks, but it would complicate the setup.

**Comment by framctr** [comment]
Other 2 related error messages are:
```
Get "https://gitlab.redacted/project/repo.git/info/refs?service=git-upload-pack": read tcp 10.0.1.181:45594->public-ip-redacted:443: read: connection timed out
```

and

```
Get "https://gitlab.redacted/project/sub-group/repo.git/info/refs?service=git-upload-pack": context deadline exceeded
```

**Comment by manno** [comment]
Shouldn't that re-check after the polling interval is reached?
What Fleet version are you using?

**Comment by framctr** [comment]
The recheck happens after many hours. I have the fleet that comes with Rancher v2.8.3

**Comment by manno** [comment]
Please retry with a more recent version.
