### ISSUE TITLE
[v0.10] Backport of Add run-once cleanup gitjobs job

### ISSUE THREAD

**Issue by 0xavi0** [rancher/fleet#2935]
Backport of #2926
After merging https://github.com/rancher/fleet/pull/2903 we need: 
- [ ] turn https://github.com/rancher/fleet/pull/2907 into a run-once job when #2903 is merged.
- [ ] make sure it's actually run when upgrading 0.10.2->0.10.4
- [ ] fix service account used

**Comment by mmartin24** [comment]
Tested 2 ways and working:

- Deployed Rancher `2.9.2-alpha7` with Fleet `104.0.2+up0.10.2` and upgraded Fleet to `104.1.0+up0.10.4-rc3` using same Rancher version -> WORKING

[Screencast from 10-10-24 09:47:57.webm](https://github.com/user-attachments/assets/e40d87b9-78ba-4df3-b806-915b55d9c63c)

- Deployed Rancher `2.9.2-alpha7` with Fleet `104.0.2+up0.10.2` and upgraded Rancher to latest `v2.9-af2463ff43418024ff86cfd9304836b7074a924a-head` and later Fleet to `104.1.0+up0.10.4-rc3` -> WORKING

[Screencast from 10-10-24 09:55:45.webm](https://github.com/user-attachments/assets/4f3fa47b-524a-4abe-9c17-eee0cb90a609)

Verified in both cases the following:
- Cleanup job generated upon upgrade
- Successful jobs from gitrepos withouth issues are cleaned after upgrade
- Jobs with errors from faulty gitrepos are not cleaned
