### ISSUE TITLE
[v2.9.3][SURE-9155]  Alignment of the sync behaviour of labels and annotations #1584 

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#2937]
Backport of #1584 to Rancher v2.9.3.

**Comment by weyfonk** [comment]
### Problem
Updating annotations on a cluster through the Rancher UI would not be reflected in the corresponding Fleet cluster resource, although propagation of updates did work for labels.
 
### Solution
Added annotations to fields taken into account when creating a Fleet cluster object.
 
### Testing
See repro steps above

### Engineering Testing
#### Manual Testing
Tested reproduction steps before and after the change, noticing that in the latter case.

#### Automated Testing
Added unit tests to Rancher covering cluster creation (which seems to be also run upon updating a cluster in the UI) and validating actual vs expected labels and annotations.

### QA Testing Considerations
Verify that update and deletion of labels through the UI works as expected, propagating changes to the corresponding Fleet cluster resource.
 
#### Regressions Considerations
N/A

**Comment by sbulage** [comment]
### System Information
**Before Upgrade**
| Rancher Version | Fleet Version |
|--------|--------|
| **Prime:2.9.2** | **Fleet: 0.10.2** | 

**After Upgrade**
| Rancher Version | Fleet Version |
|--------|--------|
| **v2.9-af2463ff43418024ff86cfd9304836b7074a924a-head** | **fleet-104.1.0+up0.10.4-rc.3** | 

---

### Before Upgrade
- Annotation added via Continuous Delivery --> Clusters are not propagated to the Management clusters.
- Also, same behavior observed via API endpoints --> 
  - Fleet cluster: `v1/fleet.cattle.io.clusters/fleet-default/imported-1`
  - Cluster Management: `v3/clusters/c-m-2r5g6cvc` (`c-m-2r5g6cvc --> imported-1`)

---

### After Upgrade
- Labels and annotations are updated from Continuous Delivery --> Clusters are updated to the Management clusters and _vice-versa_
- Same procedure performed via API `PUT` method and it did worked.
- Labels and Annotations updated via API endpoints are reflected on same cluster under Fleet Clusters and Management clusters.

_**I have recorded video to show the steps which I performed.**_

---

### Video:
<details>
<summary><b>Video shows the annotation via UI and API endpoints.</b></summary>

https://github.com/user-attachments/assets/475dbf3a-983d-446e-89a5-65a2cbd39f51

</details>
