### ISSUE TITLE
helmfile support

### ISSUE THREAD

**Issue by dmildh** [rancher/fleet#295]
Are there any plans to implement helmfile support.  We recently converted many of our cluster management helm installations from custom bash scripts to helmfile which simplifoed the installation of multiple charts at once for any one installed component and is able to show you the diff of changes.  For example of you have a chart such as external-dns that requires another chart to setup AWS Irsa roles then this is where helmfile really shines since it's all in a single yaml file.  It also contains the logic of which directories in your git repos to search for other helm vars as well.

**Comment by jmatsushita** [comment]
That's also something that would be a huge plus for adoption for us. 👍

**Comment by philomory** [comment]
This would be huge if for no other reason than that it would, as a side-effect, provide sane secrets-handling.

**Comment by aquam8** [comment]
I will link the Helmfile project for comprehensiveness https://github.com/roboll/helmfile

It supports so many chart hosting options out of the box 👍

**Comment by PatrickHuetter** [comment]
That would be a huge improvement.

**Comment by WolfspiritM** [comment]
I'm also looking for this. Currently we're using a devops pipeline to trigger helmfiles. It would be awesome if fleet could do that without the need of an extra pipeline. Helmfiles make it very easy to deploy multiple applications.

I know that in general fleet can deploy HelmChart resources which will then be handled by cattle but in our case we have custom charts combined with remote charts and want to depend on each other which isn't very easy to handle with HelmChart resources.

**Comment by kkaempf** [comment]
It's at https://github.com/helmfile/helmfile now

**Comment by kkaempf** [comment]
See #2962
