### ISSUE TITLE
Question: Fleet max cluster count

### ISSUE THREAD

**Issue by OrlandoWhite88** [rancher/fleet#2980]
What is fleets max cluster if I join lots of k3 clusters (edge devices) are we talking in the hundreds, thousands, tens of thousands, hundreds of thousands?

**Comment by manno** [comment]
https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-requirements has some numbers. 

We know of Fleet deployments with thousands of clusters. However, it depends on your workloads, too. If you deploy 600 gitrepos with dozens of large (in terms of manifest size) apps to 1000 clusters, that's different than deploying some paths of 10 gitrepos to a set of the 1000 clusters.
If your repos change once a month and reaction time should be within minutes, that's different from frequently changing repos you want to roll out within seconds.
