### ISSUE TITLE
Security: update Linux package Dockerfiles to fix security vulnerabilities

### ISSUE THREAD

**Issue by aquam8** [rancher/fleet#299]
Please update base image for Linux docker image to latest alpine as 3.12.3 contains security vulnerabilities (latest is 3.13.2)

better solution would be to move base to a ‘scratch’ image with go binary statically built. Is that something that has been considered? Happy to work on that if core maintainers support the idea.

**Comment by kkaempf** [comment]
Releases where moved to SUSE Enterprise Linux.
