### ISSUE TITLE
[SURE-9104] Prevent Continous Delivery UI slowness when GitRepos deploy a big number of resources

### ISSUE THREAD

**Issue by aruiz14** [rancher/fleet#3035]
The UI currently uses multiple sources to render Fleet information, including GitRepos and BundleDeployments. In particular, computing the list of resources for a GitRepo is very resource-intensive, sometimes causing the UI to temporarily freeze.
Initial investigation shows that starting on Fleet 0.10, the `gitrepo.status.resources` field now contains one entry per resource and cluster, while the UI would still consider it unique and try to correlate that with the BundleDeployments hence calculating (and effectively duplicating) the resource list.

Related:
- https://github.com/rancher/dashboard/issues/11643
- https://github.com/rancher/dashboard/issues/12424

**Comment by manno** [comment]
Pull request content for Rancher QA verification.

## Additional QA
### Issue: <link the issue or issues this PR resolves here>
< If your PR depends on changes from another pr link them here and describe why they are needed on your solution section. >
 
### Problem

The resource list of all resources on all clusters was repeated per cluster. 
 
### Solution

#### Manual Testing

Add a single git repo that deploys ~10 resources to 10 clusters.
For example a GitRepo that deploys this path https://github.com/manno/fleet-experiments/tree/main/scale/lotsofbundles

The resource list should have 100 entries, not 1000.

**Comment by mmartin24** [comment]
Checked in rancher `2.10.0-alpha7` with `fleet:105.0.0+up0.11.0-rc.2`

---
Deployed 3 downstream clusters with [above-mentioned](https://github.com/rancher/fleet/issues/3035#issuecomment-2454397509) git repo
Total entries in the UI in Gitrepos > resources were 33 as opposed to 99 in 2.9.2 which provides an improvement on UI rendering:

![image](https://github.com/user-attachments/assets/c9c4086a-e318-4341-87bc-87e8bfde97c3)

To better have an idea here is a video to ilustrate the entries saving:
[Screencast from 05-11-24 09:43:18.webm](https://github.com/user-attachments/assets/96db357b-2a29-499e-a748-44e6084fc081)
