### ISSUE TITLE
clientSecretName not getting passed in fleet GitRepo UI unless the value is selected in the ui

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#305]
This issue exists for reproduction results before handoff to UI folks.

Child issue: https://github.com/rancher/dashboard/issues/2503
CC:@vCra

**Comment by nickgerace** [comment]
This has been reproduced: https://github.com/rancher/dashboard/issues/2503#issuecomment-796865924

**Comment by nickgerace** [comment]
We will assign LoE once reproduced.

**Comment by kkaempf** [comment]
tracked in rancher/dashboard
