### ISSUE TITLE
[v0.11] Fleet's gitrepoJobsCleanup not disabled when continuous-delivery (Gitops) feature is off

### ISSUE THREAD

**Issue by weyfonk** [rancher/fleet#3127]
Forward-port of #3054 to v0.11.

**Comment by sbulage** [comment]
### System Information
| Rancher Version | Fleet Version |
|--------|--------|
| v2.10-e130b4bcc6909028d3aaa0d92aeab6b06f88665a-head | fleet:v0.11.2-rc.2 | 

### Steps Performed.

- Installed **Rancher Prime 2.9.2**
- **Deactivated** the Continuous Delivery option from the UI.
- Upgraded to **Rancher 2.10-head** and saw that Fleet version **0.11.2-rc.2** installed (by refreshing Repositories.)
- Verified that **Crontab** **gitrepoJobsCleanup** job is not created in the local cluster.
- Saw that **Crontab** **gitrepoJobsCleanup** was removed from the cluster as Continuous Delivery option is disabled in the UI.
- Also, observed that After activating Continuous Delivery from UI, saw that **Crontab** job for **gitrepoJobsCleanup** is added back.

<details>
<summary> Video for detailed steps </summary>

https://github.com/user-attachments/assets/498fee42-daea-41a7-8ce4-2c5e55ced8f0

</details>
