### ISSUE TITLE
GitRepo status "failed" shortly after creation - git ls-remote errors

### ISSUE THREAD

**Issue by mmiara** [rancher/fleet#315]
When creating a GitRepo in Rancher CD, the repository will show as active just after creation, and the latest commit is shown, but about a minute or so later, the status changes to "failed". If the repo is paused, and then un-paused, the repo will stay active once again for about a minute, and then return to the failed state. 

This behavior is occurring when using both SSH and personal access token - the error is a bit different, shown below.

SSH:
git ls-remote git@<ssh-github-url+repo> refs/heads/master error: exit status 128, detail: ssh: connect to host <github-server> port 22: Operation timed out
fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

HTTPS:
git ls-remote https://<https-git-repo-url> refs/heads/master error: exit status 128, detail: fatal: unable to access ‘https://<https-git-repo-url>’: OpenSSL SSL_read: Connection reset by peer, errno 104

![image](https://user-images.githubusercontent.com/56136555/112557616-3dbe4f00-8da3-11eb-9e06-7e790bc44247.png)
![image](https://user-images.githubusercontent.com/56136555/112557623-431b9980-8da3-11eb-88c3-bcd4567449a5.png)

**Comment by rafalfaro18** [comment]
I had this error too but in my case was a missing character at the end of the url (a typo in the git url) maybe worth try and double check that the url is correct.
