### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by asloan7** [rancher/fleet#317]
Does fleet have a way to send notifications (to slack, email, etc.) upon the updating or failure of a deployed resource?

**Comment by strowi** [comment]
Was looking for the same feature, since those success/failures might currently go unnoticed unless using a external pipeline which would also need credentials for those clusters while doing sth. like `kubectl wait`.

**Comment by telderfts** [comment]
Notifications of when a sync or deployment are ran should have been a day 1 feature. Does anyone have an idea or update as to when this might be available within fleet?

**Comment by sub2u** [comment]
Does anyone have an alternative approach to achieving this with fleet integration?
Monitoring release success or failure is challenging without proper alert or notification.

**Comment by telderfts** [comment]
Can you explain why this was closed as not planned since this is a highly requested feature and needed?

**Comment by asloan7** [comment]
I'm still interested

**Comment by billhong-just** [comment]
I'm still interested too. 👀

**Comment by BoyFromDubai** [comment]
I'm interested as well

**Comment by gouravsw** [comment]
I'm interested as well

**Comment by telderfts** [comment]
Still interested as well

**Comment by strowi** [comment]
@telderfts i tried looking at arogcd a while ago but couldn't find a good way to realize the pull-model (e.g. behind a firewall) instead of push. Did that change?

**Comment by stex79** [comment]
Is there a chance of a plan for an alert/notification feature in fleet?

**Comment by kkaempf** [comment]
See https://github.com/rancher/fleet/issues/2674
