### ISSUE TITLE
The patch_default_serviceaccount hook is not getting applied 

### ISSUE THREAD

**Issue by izaac** [rancher/fleet#320]
This hook is intended for Agent initiated fleet deployments (non-Rancher or Manager initiated)

But it seems the job not getting executed. @StrongMonkey did some analysis and seems to be a yaml formatting issue.

Steps:
Do the Agent Initiated installation http://fleet.rancher.io/agent-initiated/

- Deploy 2 RKE clusters
- Cluster 1 Install Fleet controller
  - Generate the Cluster Registration Token, etc.
- Cluster 2 Install the Fleet Agent
- no job [about patching](https://github.com/prachidamle/fleet/blob/9c97f90fa981b4295ae18c211a12f96c11d0f9bd/charts/fleet-agent/templates/patch_default_serviceaccount.yaml
) the sa account is found with `kubectl get jobs -A`

**Comment by StrongMonkey** [comment]
This ends up being a false alarm. The hook is executed correctly but it will be deleted after execution. The only way to verify a job image is to run `helm install --dry-run`.

**Comment by izaac** [comment]
The dry run verification was done as part of https://github.com/rancher/fleet/issues/311. Closing this.
