### ISSUE TITLE
Fleet token generation command not working 

### ISSUE THREAD

**Issue by saiyam1814** [rancher/fleet#33]
Steps to reproduce- 
- have a plain k3s cluster
- Install fleet 
- make it as a manager by running 
`fleet install manager | kubectl apply -f -`
- run `fleet install agent-token > token` 
above command results in error `Error: invalid host 127.0.0.1, use --server-url to set a proper server URL`
if you check the kubeconfig or kubectl config view the  API is at https://127.0.0.1:6443 but still fleet refuses to generate token

**Comment by saiyam1814** [comment]
@ibuildthecloud

**Comment by BenHimsel** [comment]
@saiyam1814  I think the url needs to be something resolvable from the agent's perspective. So 127.0.0.1 would be the agent attempting to communicate with itself. You likely need to use the fully qualified name of the host that the management cluster is running on and you will also likely need to put that FQDN of the host into Subject Alternate Name on the Certification on the API.

**Comment by saiyam1814** [comment]
hmm , what is the same cluster is the agent then IP should be resolvable right ?

**Comment by saiyam1814** [comment]
It worked by giving the publc ip of the instance where k3s is running

**Comment by tuananh** [comment]
what's the recommended fix for cluster create by kind or k3s here?
