### ISSUE TITLE
Windows fleet-agent missing from rancher-windows-images.txt

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#345]

**Comment by nickgerace** [comment]
Fleet v0.3.5-rc7 has been added to rancher/charts and contains the changes from https://github.com/rancher/fleet/pull/347

**Comment by izaac** [comment]
```
Pulling rancher/fleet-agent:v0.3.5-rc7-windows-1909
Error response from daemon: manifest for rancher/fleet-agent:v0.3.5-rc7-windows-1909 not found: manifest unknown: manifest unknown
```

But the tags in the docker hub are including the ARCH (amd64):

`v0.3.5-rc7-windows-amd64-1909`

**Comment by nickgerace** [comment]
This will be a similar result to the changes made to [rancher/fluent-bit-package](https://github.com/rancher/fluent-bit-package): dropping the ARCH from the manifest.

**Comment by nickgerace** [comment]
Fix available in v0.3.5-rc8 (now in rancher/charts)

**Comment by nickgerace** [comment]
The timing was close, but v0.3.5-rc8 did not make it into Rancher v2.5.8-rc12. This requires a new Rancher RC.

**Comment by izaac** [comment]
Rancher version `v2.5.8-rc15`
Fleet version `v0.3.5-rc9`
```yaml
status:
  branch: dev-v2.5
  commit: 1b856479033464d10ff5f2c6a523941fe1bd7157
```

Fleet agent, controller and gitjob images are included in `rancher-windows-images.txt`
I was able to schedule a windows image fleet agent in a windows cluster.
The cluster was displayed correctly in Continuous Delivery in the Dashboard.
