### ISSUE TITLE
Build pipeline with fleet

### ISSUE THREAD

**Issue by jsbrain** [rancher/fleet#356]
I'm currently using Rancher Pipelines to basically fulfill my whole DevOps needs and since I upgraded rancher to v2.5 I'm getting the message that Pipelines are now deprecated and in the future all will/should be managed using fleet.

But now looking into the project, I don't find anything about how I actually build my containers with fleet and I think that's actually not the intended use anyways?!

So my question is: Am I simply missing something or is building docker containers and pushing to registries totally a thing with fleet?

Also, if this is NOT part of fleet and most likely never will be, is there any "recommended" of basically replicating in fleet what I have with Rancher Pipelines?

Thanks :)

**Comment by dscham** [comment]
bump from me

**Comment by agracey** [comment]
Depending on what your needs are, [Epinio](epinio.io) might be a good solution here. It's a different project we are working on at Rancher to give a very flexible PaaS-like developer experience. We are even talking about some integrations between it and Fleet in the future as well!

**Comment by kkaempf** [comment]
Closing as of last comment
