### ISSUE TITLE
Old fleet agent on an upgraded rancher setup gets removed first before creating an updated one

### ISSUE THREAD

**Issue by sowmyav27** [rancher/fleet#365]
On an upgrade from 2.5.7 to 2.5.8-rc19

- fleet agent (0.3.4)gets removed and redeployed (new version(0.3.5) is seen) fleet-agent
- then another one gets deployed - fleet-agent-c-d9dgr
- and the first one - pod is deleted, but it is seen stuck in Uninstalling state

**Expected:**
In the first step ^^^ New fleet agent be deployed and the old one (0.3.4) gets removed

**Comment by deniseschannon** [comment]
This is related to what is occurring in https://github.com/rancher/fleet/issues/362 

It's due to a change in fleet to support HTTP proxy, which is between >=2.5.7 to 2.5.8+.

@sowmyav27 Can you test that from 2.5.8 to something greater (2.5.9 or 2.6) doesn't have this issue?

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.8 too master-head commit id: `def25f1`**

- On an upgrade, new fleet agent is deployed in `cattle-fleet-system` namespace.
- Old agent is removed from fleet-system after.
- Fleet version `fleet:100.0.0+up0.3.6-rc2`
- No errors seen in helm pods.
