### ISSUE TITLE
[Question] Comparison with kubefed

### ISSUE THREAD

**Issue by pingenglj** [rancher/fleet#38]
Interesting project. We are currently using kubefed (https://github.com/kubernetes-sigs/kubefed) in our project together with k3s to deploy services to our fleet of (edge) clusters. I'm wondering how this compares?

**Comment by ibuildthecloud** [comment]
It's just a different paradigm but in the end accomplishes the same.  At this point I wouldn't say one is particularly better than the other.  Kubefed takes the approach of managing individual k8s resources using kubectl against a "virtual namespace."  It then replicates that down to a bunch of clusters. Fleet is more oriented towards a paradigm of deploying "bundles" or packages to a bunch of clusters. The Fleet model was based off of how I saw users trying to manage a lot of clusters and the ideas of just managing a bunch of packages across clusters, the same way you would with rpms and linux servers seemed to make sense.

In the end I think the fleet model is easier for people to reason about, but time will tell.

**Comment by pingenglj** [comment]
Much appreciated. I hope to find some time to experiment with Fleet and evaluate our kubefed setup.

**Comment by gyliu513** [comment]
One more comment is fleet is `PULL` model while kubefed is `PUSH` model, but I can see kubefed also have plan to enable `PULL` model as well at https://github.com/kubernetes-sigs/kubefed/blob/master/docs/keps/20200619-kubefed-pull-reconciliation.md

**Comment by kkaempf** [comment]
Answered
