### ISSUE TITLE
Improvements to UI for status tracking

### ISSUE THREAD

**Issue by philomory** [rancher/fleet#394]
Currently, when a bundle is deployed to multiple clusters, and a particular resource within that bundle (a Deployment, say) has issues on _one_ of those clusters (say, it is stuck in the "updating" state), that resource shows as stuck "updating" on _all_ clusters within the Fleet UI. This makes the UI confusing, impedes understanding of the state of the fleet, and potentially makes it appear as if you have a fleet-wide problem just because one cluster is offline. This has the potential to be particularly problematic in the case of a fleet of IoT-ish devices, where it is not particularly unusual for a given cluster (or many clusters) to be offline at any given time.

![image](https://user-images.githubusercontent.com/200123/119731660-ebd18e00-be12-11eb-9760-c06117408bdf.png)
(only one of these clusters is actually having problems)

# Steps to Reproduce
1. Register multiple clusters with Rancher/Fleet, and add them all to the same cluster group
2. Set up a git repository that deploys a helm chart, and configure a GitRepo object for that repository targeting your cluster group
3. Arrange that one of your clusters (call it cluster A) will be unable to successfully deploy the helm chart (either because there aren't enough resources, or you specify some bad `targetCustomizations` for that cluster,).
4. Allow Fleet to deploy your GitRepo/Bundle

# Expectation
It should be possible to tell which cluster is causing problems.

# Actual behavior
Although the status for the GitRepo (under `fleet/fleet.cattle.io.gitrepo`) says 2/3 clusters are ready, when you view the GitRepo details (under `fleet/fleet.cattle.io.gitrepo/fleet-default/example-repo#resources`), the Deployment that is failing on cluster A shows as failing on _all_ of your clusters.

# Additional information/analysis
This seems to be because the Fleet UI (under GitRepos > Repo's table of resources) derives its display from the `status` field of the GitRepo object, and the status field contains information that looks like this:

```
resources:
- apiVersion: apps/v1
  error: true
  id: example/example
  name: example
  namespace: example
  perClusterState:
  - clusterId: fleet-default/c-12313
    error: true
    message: Deployment does not have minimum availability; Progress deadline exceeded
    state: updating
    transitioning: true
  state: updating
  transitioning: true
  type: apps.deployment
```

Specifically, only the cluster(s) on which this resource is failing are represented in the `perClusterState` field; moreover, as I understand it there is no guarantee that _all_ clusters with issues are represented there (based on a conversation in slack, I believe it is at most 10). This helps avoid a situation in which the GitRepo object status grows without bound, but it means that it cannot be safely assumed that any cluster not listed under `perClusterState` is necessarily in a good state.

# Possible solutions
I can think of a couple ways this could be addressed:

## Option 1
One way to address this would be to add a `failureCount` field to GitRepo's `status.resources[*]` entries, specifying the number of clusters on which this resource is failing. If the number of clusters with details listed in `perClusterState` is equal to the `failureCount`, then it can be safely assumed that all clusters not listed in `perClusterState` have the relevant resource in the Ready state, and they should be displayed accordingly. If there are fewer than `failureCount` clusters with details listed in `perClusterState`, then that resource's status on other clusters would be displayed as `unknown`, rather than assuming it was `updating`.

The upshot of this solution would be to improve the accuracy of the information displayed in the Fleet UI, so that you can (for small fleets) accurately assess which clusters are OK and which are not, or at least (for large fleets) accurately asses which clusters are _definitely_ having issues and which at least _might_ be OK.

## Option 2
Another way to address this would be to stop listing individudal resources within the `GitRepo` UI at all, and instead allow administrators to "drill down" to find details about problems.

In other words, when viewing the details of an individual GitRepo, instead of a table of resources display a table of the Bundles associated with that GitRepo. Each row would display the status of that particular bundle (ready on 2/3 clusters, etc.), and you could click on it to be taken to the Bundle details page for that particular bundle.

When viewing the details page of particular Bundle, in turn, you would be presented with a table of the clusters that bundle had been deployed to. This could show the name of the cluster, the state of the cluster, and then a numeric or "progress-bar" representation of the readiness of the resources in that particular BundleDeployment. Clicking on a specific row would take you to a details page (yet to be created) for that specific BundleDeployment object.

Finally, once you click through to view the details for an individual BundleDeployment, you would be presented with a table of resources associated with that bundle deployment, and their individual statuses (pulled from the existing `status.nonReadyStatus` field of the BundleDeployment).

While this method is more complex, and requires more substantial changes to the UI, it has the upside of being more accurate and informative.

Obviously, the Fleet team could address this in other ways besides what I've listed above, but either way the underlying UI issue needs to be addressed in _some_ manner.

# Note
Note that simply using the "Clusters" page to determine which cluster is the source of issues is insufficient. If you have two `NotReady` GitRepos, and two `NotReady` Clusters, it is not possible to determine which Cluster is having problems with which GitRepo.  This is because, when viewing a specific Cluster, the table of associated repositories shows a repo as in a bad state if it is failing on _any_ cluster, rather than showing its state in relation to the cluster you are actually looking at.

# Environment:
Rancher 2.5.8
Fleet 0.3.5

**Comment by kkaempf** [comment]
to be moved to rancher/dashboard

**Comment by kkaempf** [comment]
there were various UI improvements up to Rancher 2.7.0. Closing for now.
Please reopen if the issue persists.

**Comment by gthieleb** [comment]
This issue still exists. In version 2.7.3 there is still not a possibility to see which cluster is affected.

![Image](https://github.com/user-attachments/assets/67e594bf-5cb8-4d94-bff9-e15b9c2eb81e)

**Comment by kkaempf** [comment]
> This issue still exists. In version 2.7.3 there is still not a possibility to see which cluster is affected.

Thanks for your feedback.

Rancher 2.7.3 is out of support.
2.11.1 was released yesterday. Please check if the issue still exists in the latest version.
