### ISSUE TITLE
Update namespace from fleet-system to cattle-fleet-system

### ISSUE THREAD

**Issue by kinarashah** [rancher/fleet#395]
We don't want to continue using `fleet-system` as the default namespace for fleet components, this could cause conflict with user workloads running in the same namespace. We don't want to make it configurable either, we'd be updating it to `cattle-fleet-system` instead. 

Currently, this is set by `catalog.cattle.io/namespace` on fleet and fleet crd charts. 

Make sure upgrade works.

**Comment by kinarashah** [comment]
@StrongMonkey mentioned that the `catalog.cattle.io` annotation comes into play when UI installs the chart. Rancher itself installs fleet via controller, so need to update the release namespace there too https://github.com/rancher/rancher/blob/ea531a0970c0726fa9789210a868ceaa95612e08/pkg/controllers/dashboard/fleetcharts/controller.go#L16

**Comment by kinarashah** [comment]
Yeah, update both the places so we can get away completely from fleet-system name and make sure upgrade doesn't break.

**Comment by sowmyav27** [comment]
Issue on upgrade: https://github.com/rancher/rancher/issues/33163

**Comment by izaac** [comment]
Issue opened for Existing Downstream clusters with bundles installed: https://github.com/rancher/fleet/issues/422

**Comment by izaac** [comment]
Needs a new Fleet RC to check the last issue: https://github.com/rancher/fleet/issues/422

**Comment by izaac** [comment]
Validated and Closed: https://github.com/rancher/fleet/issues/422
Small issue for follow up: https://github.com/rancher/fleet/issues/442
