### ISSUE TITLE
CIS Hardening test failing with RKE2/Rancher due to fleet ClusterRole: group: serviceaccounts

### ISSUE THREAD

**Issue by szalayg** [rancher/fleet#397]
When running the CIS Hardening test for Kubernetes in an RKE2-based Rancher Clsuter, I got a failure because of the Clsuterrole fleet-content-manager, as it allows the group of serviceaccounts to read the contents from fleet. Since I haven't been able yet to figure out, what exactly it is doing, I am not sure if it is a real security issue or rather a bug of the checksript itself. Could you please check and advise whether it can be/should be modified, and what exactly contents are meant for?
Many thanks in advance

**Comment by pwurbs** [comment]
I face the same issue using Rancher 2.6.3 with custom RKE downstream cluster. CIS scan (1.6 hardened) fails with number 5.1.5 due to binding to group system:serviceaccounts in clusterRoleBinding fleet-agent-get-content.
