### ISSUE TITLE
fleet not pulling helm chart from my private repo

### ISSUE THREAD

**Issue by sorushsaghari** [rancher/fleet#398]
im using fleet with helm , the problem in that when i embed my helm chart in my repo its ok but when i try to use a helm repo containing that chart it is not working .
i have created a secret contaning user and password for that repo witch works when i test it with helm client.
this is `kubectl get fleet -n fleet-local` result: 
```
NAME                             REPO                                     COMMIT                                     BUNDLEDEPLOYMENTS-READY   STATUS
gitrepo.fleet.cattle.io/inside   my.git.repo.addr   b7fe91398fab5025352ba5f2889bbbea17170f11   0/0                       
```

**Comment by StrongMonkey** [comment]
Did you follow the guide here http://fleet.rancher.io/gitrepo-structure/#fleetyaml? There is an instruction on how to add private helm repo.
