### ISSUE TITLE
Support for private git repository authentication with client certs 

### ISSUE THREAD

**Issue by AshleyDumaine** [rancher/fleet#400]
Currently there is only http basic auth and ssh key support for authentication to private git repos: https://github.com/rancher/fleet/blob/master/docs/gitrepo-add.md#create-gitrepo-instance:
```
  # For a private registry you must supply a clientSecretName. A default
  # secret can be set at the namespace level using the BundleRestriction
  # type. Secrets must be of the type "kubernetes.io/ssh-auth" or
  # "kubernetes.io/basic-auth".
```

It would be helpful to also include authentication via client certificates, especially in cases where ssh auth cannot be used because of non-standard ports (see https://github.com/rancher/fleet/issues/256).

**Comment by NicolasGoeddel** [comment]
But why?

**Comment by xenuser** [comment]
How is enterprise supposed to fully adapt Fleet when such a feature keeps missing?
Could you please elaborate on why the team thinks such a feature should not be planned? Maybe the use-case needs to be described again.

**Comment by kkaempf** [comment]
We still have more than 200 open issues and _have_ to say "no, not now" to _a lot_ of them. We will focus to a few selected areas in the coming months. Sorry.
