### ISSUE TITLE
Add webhook integration for rancher

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/fleet#424]
Fleet in Rancher needs to add ability to expose webhook endpoint through rancher so that for users in fleet who want to use fleet webhook, they can use https://${server_url}/fleet/webhook to register as webhook receiver URL and that connects to gitjob service which handls webhook event.

**Comment by Jono-SUSE-Rancher** [comment]
@cbron - there is actually a PR for this that Daishan already made and Jacob thumbed. Can you just take a look and merge if it looks good?

**Comment by paynejacob** [comment]
version: `v2.6.0-rc1`

Steps:
1. install rancher
2. create a github repo and configure the webhook to point to my rancher instance
3. deploy the webhook ingress
4. deploy the gitrepo
5. push to git repo

observed a gitjob kicked off for the repository after the push.  I also verified this by forcing github to redeliver the message.
