### ISSUE TITLE
Failed to create BundleDeployment with long path within repo (63 characters limit)

### ISSUE THREAD

**Issue by petertang2012** [rancher/fleet#432]
I am seeing this error message from bundles page when I use a long `Paths` for my Git Repo cofig:

> failed to create `a-long-bundle-name-longer-than-63-characters` fleet.cattle.io/v1alpha1, Kind=BundleDeployment for bundle `a-long-bundle-name-longer-than-63-characters` : BundleDeployment.fleet.cattle.io `a-long-bundle-name-longer-than-63-characters` is invalid: metadata.labels: Invalid value: `a-long-bundle-name-longer-than-63-characters` : must be no more than 63 characters

It seems the `Paths` value is extracted as a whole along with `Git Repo name` to construct `metadata.labels` value for BundleDeployment's manifest but with the length being limited at 63 characters I am not able to use a long `Path`.

Workaround is just to use a `shallow` folder for storing configurations but it would be great if I have the freedom to use any arbitrary path for Fleet deployment.

The issue was observed with Fleet `0.3.500` and Rancher `2.5.8`

**Comment by keifgwinn** [comment]
I ran into this as well on starting to use fleet with my existing repo structure.

**Comment by sgapanovich** [comment]
## Steps to reproduce ##
### Test Environment: ###
Rancher version: v2.6.1
Rancher cluster type: HA
Docker version: 20.10
Downstream cluster type: ec2 3 node cluster
Fleet version: v0.3.7

----------

### Test Steps: ###

Log in as an admin
1. Navigate to Main Menu -> Continuous Delivery
2. In Namespace fleet drop down select "fleet-default"
3. Go to "Git Repos"
4. Click "Create"
  * name: `itstest`
  * Repository URL: `https://github.com/sgapanovich/fleet-examples`
  * Branch Name: `test`
    * click "Add Path"
  * Path: `/this-is-text-to-test-sixty-three-characters-in-path/helm`
  * Click "Create"
5. In the left menu click "Advanced"
6. Click "Bundles"
  * you might need to refresh the page to see a new bundle "created"

Issue:
error `Failed to create cluster-fleet-default-c-9fp2p-bbd359969808/itstest-this-is-text-to-test-sixty-three-characters-in-path-helm fleet.cattle.io/v1alpha1, Kind=BundleDeployment for bundle fleet-default/itstest-this-is-text-to-test-sixty-three-characters-in-path-helm: BundleDeployment.fleet.cattle.io "itstest-this-is-text-to-test-sixty-three-characters-in-path-helm" is invalid: metadata.labels: Invalid value: "itstest-this-is-text-to-test-sixty-three-characters-in-path-helm": must be no more than 63 characters`

![63.png](https://zube.io/files/rancher/ffb83383cfcb1686b97a45e030cf9187-63.png)
If you repeat the same steps BUT specify a name as `ittest` (notice not `itstest` - 1 letter less) and the total becomes 63
- bundle created with all deployments
![631.png](https://zube.io/files/rancher/c368d982668704f4911614bc038144be-631.png)

**Comment by nickgerace** [comment]
Available on Rancher v2.6-head in Fleet v0.3.8-rc1

**Comment by sgapanovich** [comment]
#### Test Environment: ####
Rancher version: v2.6-638b29a687f3818e7de676a573ec9b9156f193a9-head
Rancher cluster type: HA
Docker version: 20.10
Fleet version: fleet:v0.3.8-rc1

Downstream cluster type: ec2
Downstream K8s version: v1.21.6

----------

#### Testing: ####

- Having a long path should not be an issue anymore:
    - If the length of the name + path >= 63 
      - last 6 characters are replaced with `-hash`
- If the length of the name + path < 63
    - no change
 
![63.jpg](https://zube.io/files/rancher/ceaf3e52e7bce6d4765e4ab2f2c57dc2-63.jpg)

- in case there are multiple resources in the same long path
  - resources are created when a git repo is added 
  - if there is an update made to a resource and that change is pushed to the git repo 
      - resource(s) is updated as expected (screenshot: deployment is created when git repo is added, then I modified replicas for the deployment and pushed the code, the deployment got updated as expected)

![update + deploy.jpg](https://zube.io/files/rancher/3c9336e727f96e8ef5cb0c8a2e868f4e-update-deploy.jpg)

**Comment by E7David** [comment]
Hi,
I just ran into the same issue with the difference that I wanted to use dependencies in the fleet.yaml which are created with the bundle name:
```
dependsOn:
  # Format: <GITREPO-NAME>-<BUNDLE_PATH> with all path separators replaced by "-" 
  # Example: GitRepo name "one", Bundle path "/multi-cluster/hello-world" => "one-multi-cluster-hello-world"
  - name: one-multi-cluster-hello-world
```

In that case we would need to deploy the dependencies first to get the bundle names with the hash which are then added to the fleet.yaml

for example:
```
dependsOn:
  - name: testing-this-is-first-folder-in-path-this-is-second-folde-f8a7f
```

Which is not an impossible task but it's definitely not the prettiest one either so I don't know if there is a way to fix that or if we should just restructure our repos if we want proper bundle names in our dependencies and be able to deploy the resources in one go rather than dependency after dependency to get the hashes we need...

**Comment by StrongMonkey** [comment]
@E7David We are adding [name/label](https://github.com/rancher/fleet/pull/552) support for bundles in the next release and that should solve your issue.

**Comment by E7David** [comment]
@StrongMonkey Oh that's nice! Thanks for the fast reply 👍🏼

**Comment by frouzbeh** [comment]
Hi, this solution to add `-hash` to the end of the bundle name doesn't work as expected for me. Fleet agent doesn't know the bundle and keeps deleting and deploying it. 
```
time="2022-02-23T19:31:23Z" level=info msg="Deleting unknown bundle ID system-backup-infra-velero-backup-schedules, release default/system-backup-infra-velero-backu-60ba3, expecting release default/system-backup-infra-velero-backup-schedules"
```
Any idea why is this happening?

**Comment by Shaked** [comment]
@frouzbeh did you figure it out? I'm experiencing the same issue.

**Comment by 0x4c6565** [comment]
@frouzbeh @Shaked - can be worked around with method described in https://github.com/rancher/fleet/issues/795#issuecomment-1156497142 for now
