### ISSUE TITLE
Fleet Deployed Rancher Charts deployed to System Project by default.

### ISSUE THREAD

**Issue by serverbaboon** [rancher/fleet#435]
Can Fleet deployment of Rancher Apps such as Monitoring, Logging or Istio default to the System project or allow the Project to be specified.

I have worked around Istio by precreating the Namespace but doing that with monitoring will cause the Helm chart to fail, but in general precreating namespaces ( Rancher API + TF ) is unsatisfactory as it mixes deployemnt methods

I realise this could be classed as a duplicate of rancher/fleet#304 , so by all means close it if you agree, but wanted to higlight the default Rancher 'system' apps deployments that are done as part of a cluster creation.

**Comment by serverbaboon** [comment]
..or certainly cluster creation in our case.

**Comment by chfrank-cgn** [comment]
This is still a valid issue - Fleet should be able to deploy Rancher cluster tools easily into the System project

**Comment by chfrank-cgn** [comment]
Can you please reopen the issue @kkaempf ? Thank you!

**Comment by kkaempf** [comment]
Fleet engineering does not intend to work on this in a forseeable future.
However, we are accepting respective pull requests 😉
