### ISSUE TITLE
Error in deployment after creating git repo

### ISSUE THREAD

**Issue by aaronRancher** [rancher/fleet#437]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- On Rancher `master-head` `version c7f3cce` single install.
- Log in as admin.
- Provision 2 downstream clusters.
- Verify clusters are available and visible under Continuous Delivery > Clusters
- Navigate to dashboard > Continuous Delivery > Git repo
- Create a git repo with the following fields:
Repository URL: https://github.com/rancher/fleet-examples
Path: multi-cluster/helm
Deploy To: all clusters in the workspace
- Wait for git repo to become available in dashboard.
- Navigate to Ember UI > Local > System workloads

**Result:**
1 pod is available. 1 pod errors with: `Error: fleet-default/testrepo-simple time="2021-06-25T23:56:02Z" level=fatal msg="resource name may not be empty"`
![Screen Shot 2021-06-25 at 5 03 39 PM](https://user-images.githubusercontent.com/57409052/123504857-9b676f00-d610-11eb-816c-196317804c02.png)
This error is seen with both `multi-cluster/helm` and `/simple` path
This error is seen in both Rancher HA and single install

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-head` `version c7f3cce`
- Installation option (single install/HA): single install

**Comment by nickgerace** [comment]
Error reported comes from here: https://github.com/tektoncd/pipeline/tree/v0.16.3/cmd/entrypoint

**Comment by cbron** [comment]
Is this 2.6 only ? Would it have existing in 2.5.

**Comment by nickgerace** [comment]
It is. It was due to recent changes in the agent in v0.3.6-rc1.

**Comment by aaronRancher** [comment]
This issue is seen on Rancher `master-head` `version 9e0d1b2`. Tested with the above steps.
Fleet version `fleet-agent:v0.3.6-rc5`

Errors are seen on pods after git repo creation:
![Screen Shot 2021-07-22 at 4 32 44 PM](https://user-images.githubusercontent.com/57409052/126721533-c6354a1d-6f2d-4aac-9730-3fe2e2140809.png)

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head 21ab02c`

My fresh local cluster is still using previous `fleet-*:v0.3.6-rc6` chart/images (where I could reproduce the issue describe above) by default but the new fleet chart `v0.3.6-rc7` can be upgraded in `Apps & Marktplace` menu on local cluster prior adding the downstream clusters. 

@nickgerace When this now chart will became default?

Anyway now I don't see any error but the testapp is running only on one pod:
![fleet](https://user-images.githubusercontent.com/12828077/127537400-5d541412-587e-4774-b732-2576a992aa15.png)

@nickgerace I'm not sure if this is correct (only 1 pod there and not 2 as before), could you please say this is expected if I have 2 active downstream clusters?:
![fleet2](https://user-images.githubusercontent.com/12828077/127538080-1a976d0c-3281-455a-b410-c3bf16b75763.png)

**Comment by thehejik** [comment]
@nickgerace now the rc7 chart is deployed by default on fresh local with `rancher/rancher:master-head 94bca99` but there is still only one pod running (using 2 downstream cluster), please is it ok?

![fleet](https://user-images.githubusercontent.com/12828077/127636431-7a438bc4-3606-48a1-87f8-ff9402553589.png)

**Comment by nickgerace** [comment]
![Screen Shot 2021-07-30 at 3 17 21 PM](https://user-images.githubusercontent.com/39320683/127701533-d3bb2397-2a85-436f-9291-1082a2f694af.png)

@thehejik @sowmyav27 I see two completed containers for the local cluster for deploying the bundle. This works as intended.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `8397837e2`**

- On Rancher master-head version c7f3cce single install.
- Log in as admin.
- Provision 2 downstream clusters.
- Verify clusters are available and visible under Continuous Delivery > Clusters
- Navigate to dashboard > Continuous Delivery > Git repo
- Create a git repo with the following fields:
- Repository URL: https://github.com/rancher/fleet-examples
- Path: multi-cluster/helm
- Deploy To: all clusters in the workspace
- Wait for git repo to become available in dashboard.
- Navigate to Ember UI > Local > System workloads
- No error seen
- Fleet bundle is deployed successfully
<img width="1429" alt="Screen Shot 2021-08-01 at 2 53 08 PM" src="https://user-images.githubusercontent.com/26032343/127786389-68ce0485-7ea0-474f-bb16-37625d300025.png">
<img width="1234" alt="Screen Shot 2021-08-01 at 2 51 47 PM" src="https://user-images.githubusercontent.com/26032343/127786390-f49b7518-1044-4be1-b204-70a6746a7059.png">
