### ISSUE TITLE
[SURE-4418] Fleet webhook is not triggering the git sync process

### ISSUE THREAD

**Issue by BrundaBS** [rancher/fleet#438]
Hi,
 
Steps followed for configuring fleet webhook:
 
1. A webhook has been configured in the Bitbucket for push changes 
2. As we are using the same hostname for both rancher service and fleet webhook, Ingress resource has been configured in rancher cluster with /git prefix and gitjob service as backend. 
3. Rewrite annnotation has been added to "/". 
4. Set gitrepo object polling interval to 24h to make sure the fleet controller is not polling git.
 
With the above changes bitbucket server is receiving 200 HTTP response code with "succeeded" body for the triggered webhook from the gitjob service.
 
However, there is not trace of the triggered webhook in the gitjob controller pod log and the git sync process is not getting started.
 
rancher version - v2.5.8
Gitjob version - v0.1.15

**Comment by ritheshgm** [comment]
+1

**Comment by vijaytrainer** [comment]
Facing the same issue, somehow the incoming POST request from bitbucket isn't getting translated into the git pull though showing 200 as response code.

Any help here is highly appreciated.

**Comment by StrongMonkey** [comment]
Does gitjob get updated with a new commit?

**Comment by BrundaBS** [comment]
No. Gitjob is not getting updated with new commit when webhook is configured and polling interval is set to 24h.

**Comment by ritheshgm** [comment]
Hello Team, 
Any update on above issue?

**Comment by ritheshgm** [comment]
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/50571179/155665460-bb443ab1-113c-4a4c-b419-f6700920b5f7.png">

We are seeing the Repository refs updated successfully  and seeing below errors in the gitjob pod logs 

time="2022-02-25T05:59:42Z" level=error msg="error syncing 'fleet-default/predev-6335': handler sync-repo: DesiredSet - Replace Wait batch/v1, Kind=Job fleet-default/predev-6335-2a03e for sync-repo fleet-default/predev-6335, requeuing"
time="2022-02-25T06:03:43Z" level=error msg="Webhook processing failed: event not defined to be parsed"
2022/02/25 06:03:43 http: superfluous response.WriteHeader call from github.com/rancher/gitjob/pkg/webhook.logAndReturn (webhook.go:204)
time="2022-02-25T06:03:49Z" level=error msg="Webhook processing failed: event not defined to be parsed"

**Comment by vijaytrainer** [comment]
Ha ha ha

**Comment by kkaempf** [comment]
SURE-4418

**Comment by weyfonk** [comment]
Hi,

Are you still experiencing this issue?
I have tried reproducing it on the latest Rancher version, and the git sync process is triggered as expected when BitBucket receives a 200 HTTP response code to a webhook call resulting from a _push_ event.

If the issue persists, we would be interested to know a bit more about it, such as:
* are you creating the GitRepo via the [Rancher UI](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/deploy-apps-across-clusters/fleet#accessing-fleet-in-the-rancher-ui) or via `kubectl`?
* which ingress controller are you using? Traefik, Nginx, other?
* could you perhaps share some yaml specs (or screenshots if using the Rancher UI) of your relevant `GitRepo` and ingress config, barring any sensitive information?

If nobody can reproduce this with a recent Fleet/Rancher version, I am going to close this issue 2 weeks from now.
Of course, we can reopen it or create another one as soon as we have more information.
