### ISSUE TITLE
Support for gcp auth plugin in fleet controller?

### ISSUE THREAD

**Issue by genevieve** [rancher/fleet#443]
Hi! 👋🏻 
We're seeing this error when we try to setup a cluster resource to point to one of our gcp clusters:
```
time="2021-06-30T00:16:30Z" level=error msg="error syncing 'clusters/the-name-of-it': handler import-cluster: no Auth Provider found for name \"gcp\", requeuing"
```
In the fleet main.go the auth plugin is imported: 
https://github.com/rancher/fleet/blob/master/main.go#L15
It isn't included in the controller main.go though:
https://github.com/rancher/fleet/blob/master/cmd/fleetcontroller/main.go

Is this a known issue? We're going to test a fix and can open a PR if it resolves the issue.

**Comment by kkaempf** [comment]
PR got closed
