### ISSUE TITLE
Rancher UI is performing slow

### ISSUE THREAD

**Issue by monikaagarwal708** [rancher/fleet#444]
Hi folks,

We are using **Rancher version - 2.5.8** to manage 1750 odd k8s clusters. We have been experiencing performance issues with UI , listed below-

1) UI takes ~30seconds to load to any page post login. 
2) Importing any new cluster takes a while.
3) Indexing also takes time and hence search feature responds late.

Rancher is running on a 7 node cluster in GCP with 64cores and 236GB RAM

Could you suggest on how to improve the UI performance.

**Comment by ritheshgm** [comment]
+1

**Comment by BrundaBS** [comment]
+1
