### ISSUE TITLE
Use the latest image tag for rancher/gitjob and rancher/tekton-utils

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/fleet#451]
We need to update the Helm chart to use the latest images tags 
```
rancher/gitjob:v0.1.17
rancher/tekton-utils:v0.1.2
```

and https://github.com/rancher/fleet/blob/41b222f326ecd66a35a561ded5dfef21c4d3e49c/go.mod#L46

**Comment by nickgerace** [comment]
Awaiting new GitJob RC from https://github.com/rancher/rancher/issues/33112

**Comment by nickgerace** [comment]
Due to https://github.com/rancher/rancher/issues/33586 being in review, there will be a Fleet RC in the interim for this issue in order to unblock QA.

**Comment by cbron** [comment]
Assigning @jiaqiluo for dev-validate

**Comment by jiaqiluo** [comment]
this is validated in master-3e5f699146c8ef4823793e34deeba5adf7d9e14d-head single install setup

Steps:
- run rancher single-install
- add a downstream cluster 
- use the Continuous Delivery feature to deploy an app to the downstream cluster

Results:
- fleet chart version `100.0.0+up0.3.6-rc7` is installed by default
- tthe Continuous Delivery feature works as expected 
- `rancher/gitjob:v0.1.20` and `rancher/tekton-utils:v0.1.2` are used in both the value YAML of the fleet app and pods. 
<img width="1343" alt="Screen Shot 2021-08-03 at 5 05 43 PM" src="https://user-images.githubusercontent.com/6218999/128101456-48d4a065-1ba1-42c3-99c9-8e78ca765754.png">
<img width="1384" alt="Screen Shot 2021-08-03 at 5 06 16 PM" src="https://user-images.githubusercontent.com/6218999/128101463-f57929cc-392a-46b6-8f57-6888fb375588.png">
