### ISSUE TITLE
Feature Request: Ignore specific yaml files or allow yaml files to be deployed to specific clusters

### ISSUE THREAD

**Issue by amagura** [rancher/fleet#459]
Presently, Fleet allows users to use _overlays_ to customize one set of configuration files for different contexts (clusters).  

### Feature
In addition to this existing behavior, Fleet should allow users to either ignore specific yaml files in git repos or be able to configure on a file-by-file basis to which cluster each yaml file is deployed: if a yaml file does not indicate through labels/annotations what cluster it belongs in, the default cluster (as defined in fleet.yaml) should be used. 

### Problem
Currently, I have to hide yaml files by making them hidden files `.<FILE>` or by moving them outside of their corresponding directory into a separate one: our entire repo is laid out with config files placed in folders corresponding to their context, whether said context is `prod` or `staging`.

**Comment by kkaempf** [comment]
not planned
