### ISSUE TITLE
Names for secrets should be based on http/ssh

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/fleet#460]
When we create a git repo and add secrets we can not see on the names of the secrets if they are http or ssh:

![grafik](https://user-images.githubusercontent.com/13362573/125578201-89cb4e6c-58a6-4735-9050-4fe1434cb9fe.png)

--> could we add "http" or "ssh" to the secrets names?

**Comment by philomory** [comment]
Honestly it would be better if we just had the option to specify an actually-meaningful name, so that we could tell exactly which secret was which.

**Comment by Martin-Weiss** [comment]
> 
> 
> Honestly it would be better if we just had the option to specify an actually-meaningful name, so that we could tell exactly which secret was which.

Agreed - either give the user the chance to give the secret a nice name or append add the type of the content in the name.

**Comment by StrongMonkey** [comment]
You can do that directly through yaml(pre-create the secret and put name under gitrepo.spec.clientSecretName). UI doesn't have the option right now.

**Comment by Martin-Weiss** [comment]
> 
> 
> You can do that directly through yaml(pre-create the secret and put name under gitrepo.spec.clientSecretName). UI doesn't have the option right now.

Good workaround - but we really need this in the UI..

**Comment by kkaempf** [comment]
transferred to rancher/dashboard#7822
