### ISSUE TITLE
Cluster Workspace membership reset to fleet-local after Cluster update with Terraform

### ISSUE THREAD

**Issue by serverbaboon** [rancher/fleet#473]
We are using to Terraform to deploy our Custom Clusters then using Fleet to finalise the configuration by deploying monitoring, Logging and Istio with Fleet.

We have noticed that editing the cluster configuration such as adding updating the Kubernetes version (upgrade) , changing Kube service arguments or even just adding cluster labels cause the the Workspace that the cluster is associated with to reset back to fleet-local. As a consequance all the applications assigned to the cluster in that workspace are uninstalled which is  'dissapointing' especially when you have Istio installed.

The label 'rancher.cattle.io/claimed-by-namespace' is set back to fleet-local.

Kubernetes upgrades in the UI are fine.

Further investigation seems to point the finger at the version of Rancher2 Terraform provider, 1.16.0 demonstrates this problem and 1.15.0 seems to be ok so we are resetting our Terraform Provider versions back to 1.15.0.

There is an Enhancement in in the Provider that looks a likely cause of the issue, but since I have only found an issue with Fleet I am raising it here 1st.

ENHANCEMENTS:

Added timeout error message to CatalogV2Client, getObjectV2ByID and GetCatalogV2List functions
Updated rancher2_bootstrap resource to wait until local cluster is active
Updated rancher2_cluster.rke_config.cloud_provider.name argument from Optional/Computed to Optional
**_Updated rancher2_cluster resource to replace RKE cluster API info instead of update, if rancher2_cluster.rke_config has been updated_**
Updated rancher2_project resource to replace project API info instead of update
Updated rancher2_node_template.engine_install_url argument to be computed
Updated Rancher to v2.5.9
Updated golang to v1.16.5 and added darwin arm64 build

Rancher 2.5.8
Fleet 0.35
Kubernetes 1.18.20 --> upgrading to 1.19.13

Workspace membership is reset
Terraform 1.0.1
Terraform Rancher2 Provider 1.16.0

Workspace Membership NOT reset
Terraform 1.0.1
Terraform Rancher2 Provider 1.15.0

**Comment by serverbaboon** [comment]
Because of outstanding Fleet issues I am currently manually assigning Clusters to workspaces after the cluster is created which is probably a contributing factor.

**Comment by rawmind0** [comment]
@serverbaboon ,  Moving issue to rancher/terraform-provider-rancher2 repo. Please follow up at https://github.com/rancher/terraform-provider-rancher2/issues/725
