### ISSUE TITLE
Investigate and minimize transient Fleet CRD-related error logging during startup

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#479]
## Issue

During the init sequence of the `fleet-controller`, there are frequent error logs for unrecognized CRDs.
Perhaps, this is a Wrangler issue as well since similar things are seen in Rancher's init sequence. While cosmetic, these errors can be verbose and unclear to the user.

```
E0804 23:54:12.789558       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.GitJob: failed to list *v1.GitJob: the server could not find the requested resource (get gitjobs.meta.k8s.io)
E0804 23:54:14.345164       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.GitJob: failed to list *v1.GitJob: the server could not find the requested resource (get gitjobs.meta.k8s.io)
E0804 23:54:17.057299       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.GitJob: failed to list *v1.GitJob: the server could not find the requested resource (get gitjobs.meta.k8s.io)
```

## Source

Found for Fleet: https://github.com/rancher/rancher/issues/33112#issuecomment-893106078

## Solution Brainstroming

We should evaluate adding a timeout (customizable via arg/env/helm/etc.) for these checks; perhaps logging them after a specified amount of time

**Comment by nickgerace** [comment]
Not assigning an LoE since this needs to be reproduced first.

**Comment by kkaempf** [comment]
no further reports
