### ISSUE TITLE
Unable to decode an event from the watch stream has prevented the request from succeeding

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#480]
## Description
The following error appears in the _downstream_ `fleet-agent` logs:

```
W0805 16:41:06.685171 1 reflector.go:436] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: watch of *v1alpha1.BundleDeployment ended with: an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 1; INTERNAL_ERROR") has prevented the request from succeeding
```

Local fleet components do not log this error. The downsteam bundle is fine, so perhaps this is a transient error and low/no impact.

## Config
- Rancher v2.6.0-rc1 upgraded from Rancher v2.5.9 (v0.3.5 to v0.3.6-rc9 Fleet)
- Digital Ocean droplet Ubuntu 20.04 amd64 (downstream)
- single node install (macOS docker desktop) with ngrok

**Comment by nickgerace** [comment]
Not assigning an LoE until this is reproduced.

**Comment by kkaempf** [comment]
no further reports
