### ISSUE TITLE
Ensure Fleet only picks up YAML files and skips JSON files (or add a flag to the chart)

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#487]
JSON files are accidentally being picked up in GitRepo CR creations. If users like this, perhaps we can add a flag. However, the behavior is currently unexpected, and we should only pick up YAML files by default.

**Comment by nickgerace** [comment]
This would require an extended discussion. Since YAML is an unofficial spec and a superset of JSON, serialization uses JSON encoding. We would need a flag to check for file extension and/or validate if encoded bytestreams are valid YAML.

**Comment by kkaempf** [comment]
not planned
