### ISSUE TITLE
Add documentation for migrating the local cluster to fleet-default

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#489]
For users who want to deploy to the local cluster as well, they can move the cluster and its resources from `fleet-local` to `fleet-default`. We should document this process and **why** a user would do it.

**Comment by Martin-Weiss** [comment]
Would "renaming the local cluster" in Rancher have an impact, here?
It would also be nice to have a UI that would do the move...

**Comment by nickgerace** [comment]
> It would also be nice to have a UI that would do the move...
Not a bad decision, @StrongMonkey what do you think? I'll create a dashboard issue if you think it's a good idea too.

**Comment by Martin-Weiss** [comment]
I believe there is already a way to "move" via the "assign cluster to":

![grafik](https://user-images.githubusercontent.com/13362573/129537808-4b50d0e2-e4ac-4881-8f4c-b22ebd6780aa.png)

Just did not think that "assign" is the same as "move"..

**Comment by nickgerace** [comment]
Yes! There is; we just need to document it.
