### ISSUE TITLE
Downstream fleet agent uses old clusters system when namespace is changed

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#490]
The downstream fleet-agent needs to wait for its local secret to have the correct `systemRegistrationNamespace`. This value is populated by the fleet-controller. We need to requeue until this value is correct.

**Comment by nickgerace** [comment]
Staying in `Working` despite the new rc due to requiring additional backend-dev validation before moving to QA.

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to v2.6-head commit id: `c10ef4b0`**

- On 2.5.9 deploy a couple of downstream cluster
- In Continuous Delivery Deploy a Git repo
- It comes Up active and clusters in Active state
- On a rancher upgrade, New Fleet agent is deployed in `cattle-fleet-system` namespace, and the old one is deleted but the `fleet-system` namespace is still available.
- Existing clusters in Continuous delivery tab are Active. Able to deploy new bundles to the downstream clusters.
- Fleet version: `v0.3.6-rc12`
- Before Upgrade on 2.5.9
```
kubectl get --watch secrets -A | grep kubeconfig
fleet-default                                c-csfjx-kubeconfig                                                Opaque                                        1      143m
fleet-default                                c-lnvdc-kubeconfig                                                Opaque                                        1      27m
```
- After Upgrade on 2.6-head:
```
fleet-default                                c-csfjx-kubeconfig                                                Opaque                                        2      46s
fleet-default                                c-lnvdc-kubeconfig                                                Opaque                                        2      53s
fleet-local                                  local-kubeconfig                                                  Opaque                                        2      2m46s
```
- The secrets are recreated. 
- `fleet-clusters-system` is not available in the Rancher setup on an upgrade  but `cattle-fleet-clusters-system` namespace is.
