### ISSUE TITLE
cluster-fleet-default namespace for deleted clusters still exists in local cluster

### ISSUE THREAD

**Issue by BrundaBS** [rancher/fleet#494]
When the imported downstream cluster is deleted from Rancher, cluster-fleet-default-c-72t22-9bcead9108d0 namespace is not getting deleted from the local cluster.

_Expected behaviour:_ cluster-fleet-default namespace for the imported cluster should get deleted from the local cluster when the downstream cluster is deleted from Rancher

Rancher version : v2.5.8
Fleet agent version: v0.3.5

<img width="1444" alt="Screenshot 2021-08-17 at 2 08 16 PM" src="https://user-images.githubusercontent.com/43068139/129705436-877f374b-bbb0-46a9-863f-c3cc1cb6a4ce.png">

**Comment by ritheshgm** [comment]
+1

**Comment by selcuk-cofe** [comment]
+1

**Comment by kkaempf** [comment]
should be fixed. Please reopen if it still happens on 2.7.0 and add steps on how to reproduce.
