### ISSUE TITLE
[Upgrade] An extra cluster is created and is stuck in Wait Check-in

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#495]
Instead of updating, replacing, or using the old Fleet Cluster objects, a new one is created and is stuck in Wait Check-in. 

**EDIT: the existing cluster objects works and is unaffected by this issue. The extra cluster does not affect usage, barring GitRepos targeting it.**

- `fleet-controller` - no errors
- `fleet-agent` (local) - no errors
- `fleet-agent` (downstream) - no errors
- `gitjob` - pod is in a running state, but logs the following error (_this error is likely a consequence of the Cluster breakage and unrelated to `gitjob` itself_):

```
time="2021-08-17T15:29:24Z" level=error msg="error syncing 'fleet-default/foo': handler sync-repo: DesiredSet - Replace Wait batch/v1, Kind=Job fleet-default/foo-5bc06 for sync-repo fleet-default/foo, requeuing"
```

<img width="729" alt="Screen Shot 2021-08-17 at 11 49 26 AM" src="https://user-images.githubusercontent.com/39320683/129758844-27ddd1e9-a266-412b-a147-4ae1272289fd.png">

## Reproduction Steps

1. Create an HA Rancher v2.5.9 cluster (this was found with k3s v1.20.9 on a DO droplet)
1. Add a downstream cluster with "use existing nodes" (RKE1) (this was found with v1.20.9 on a DO droplet)
1. Create the `multi-cluster/helm` GitRepo CR from [rancher/fleet-examples](https://github.com/rancher/fleet-examples) and target all clusters
1. Wait the GitRepo CR to become active
1. Rancher helm upgrade to `v2.6-head`, which includes `v0.3.6-rc12` Fleet components (the exact commit was lost at the time of writing)

**Comment by nickgerace** [comment]
I tried to reproduce this issue again and could not. Removed the `release-blocker` due to the extra cluster not affecting overall usage (except when it's included as a target).

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to v2.6-head commit id: `c10ef4b0`**

- On 2.5.9 deploy a couple of downstream cluster
- In Continuous Delivery Deploy a Git repo
- It comes Up active and clusters in Active state
- On a rancher upgrade, New Fleet agent is deployed in `cattle-fleet-system` namespace, and the old one is deleted but the `fleet-system` namespace is still available.
- Existing clusters in Continuous delivery tab are Active. Able to deploy new bundles to the downstream clusters.
- Fleet version: `v0.3.6-rc12`
- No additional/extra cluster is seen created.

Closing the issue. Will reopen if we see the issue again.
