### ISSUE TITLE
[GitRepo] Without Sync Policy - Only Init

### ISSUE THREAD

**Issue by OpsPita** [rancher/fleet#498]
Hi,
Seems like we cannot just init applications without sync policy within-cluster creation from rancher

I know there is an option for `pause: true` 
But seems when creating a new cluster it won't apply for that new cluster this GitRepo.

The scenario we want to achieve is for example,
Creating CI Control plane cluster with Tekton deployed only once without any updates to the resource or auto sync option.

Is it possible?

**Comment by kkaempf** [comment]
not planned
