### ISSUE TITLE
Fleet reconciliation creates significant load on API server and it's database

### ISSUE THREAD

**Issue by nabam** [rancher/fleet#499]
In our setup we have a K3S (v1.20.6+k3s1) cluster with MySQL backend (Aurora RDS) managed by Rancher (v2.5.8).
We use fleet (**v0.3.5**) to deploy resources into k3s cluster. Installation is quite massive and have **231 fleet bundles** installed.

We noticed that network throughput from the MySQL database became a bottleneck for API performance and during investigation noticed that fleet constantly pulls helm secrets from K8S API when reconciling failing workloads. 

At the point when throughput reached about 4 Gbit/s we started investigation and was able to get it down to about 1.5 Gbit/s by limiting helm history to 2 releases in fleet bundles configuration. 

**I suggest that fleet should have an option to tune the reconciliation behavior to somehow make it less aggressive.**

Here is some data from an experiment I conducted to demonstrate the behavior:

```
# K3S Cluster
kubectl get secrets --all-namespaces | grep ' sh.helm' | wc -l
564
```
```
# Rancher Cluster
$ kubectl -n fleet-default get bundles | tail -n +2 | wc -l
231

$ kubectl -n fleet-default get bundles | grep NotReady | grep 'statefulset\|deployment' | wc -l
4
```

With 4 failing deployment database bandwidth stays around 1.5 Gbit/s and fleet is pulling about 3 secrets per second.

During the experiment, to see how behavior changes without failing deployments, I deleted bundles that were failing.
```
$ kubectl -n fleet-default delete bundles ...
bundle.fleet.cattle.io ... deleted
bundle.fleet.cattle.io ... deleted
bundle.fleet.cattle.io ... deleted
bundle.fleet.cattle.io ... deleted

$ kubectl -n fleet-default get bundles | grep NotReady | grep 'statefulset\|deployment' | wc -l
0
```

On the graphs below you can see database throughput and API read rate for secrets. Between blue bars are periods when there are no failing resources in fleet:

<img width="844" alt="Screenshot 2021-08-24 at 14 10 19" src="https://user-images.githubusercontent.com/751681/130613960-eb8df269-7b9c-4002-9b3f-059e032d54a3.png">
<img width="837" alt="Screenshot 2021-08-24 at 14 08 49" src="https://user-images.githubusercontent.com/751681/130613967-fb970d95-966c-4f5f-91e3-8fd93601d80b.png">

During high API rate periods fleet-agent logs are full of:
```
time="..." level=info msg="getting history for release ..."
```
and
```
time="..." level=error msg="bundle ...: deployment.apps ... error] Progress deadline exceeded"
```

**Comment by mirzak** [comment]
Any updates?

**Comment by mirzak** [comment]
Ping

**Comment by mattfarina** [comment]
This appears to be happening anytime there is a failing workload because the controller attempts to requeue it after every failure. This creates a constant cycle of trying to deploy the workload. The history lookup communicates directly with the k8s API server.

If workloads don't come online and there is an error the deployment should complete and leave the status in an error state rather than to try to re-deploy. The next time there is an update in Git it can try to update and fix the issue. Redeploying the same thing repeatedly is just causing load.

**Comment by moio** [comment]
Looks similar to the issue I am working on, #606. Will update if I have news.

**Comment by olblak** [comment]
Should we keep this issue for milestone [2023-Q1-v2.6x](https://github.com/rancher/fleet/milestone/21)? 
As far as I understand it, @moio has still some ongoing work related to the current issue

**Comment by manno** [comment]
We already have https://github.com/rancher/fleet/issues/1142 as an Epic. This issue is solved by https://github.com/rancher/fleet/pull/1042. Maybe we need to create separate issues to track the backports.

**Comment by olblak** [comment]
@mattfarina Do you have some update on this issue?

**Comment by moio** [comment]
I am waiting on feedback from several customers - including backported versions. Your choice where you prefer tracking progress.

**Comment by olblak** [comment]
> I am waiting on feedback from several customers - including backported versions. Your choice where you prefer tracking progress.

Thanks for the feedback, then I am removing it from the current milestone

**Comment by manno** [comment]
The QA template is here: https://github.com/rancher/fleet/pull/1042#issue-1417680330
This has been backported to 0.5.2-rc.2

**Comment by MSpencer87** [comment]
Verified on Rancher 2.5.8, RKE v1.20.11, fleet 0.3.5->0.5.0 upgrade
Verified on Rancher 2.6.7, RKE v1.3.13 - v1.24.2-rancher1-1, fleet 0.3.10->0.5.0 upgrade
Verified on Rancher 2.6.11-rc8, RKE v1.3.19-rc2 - v1.24.10-rancher3-1, fleet 0.5.2-rc3


Steps to reproduce:

1) Bring up HA Rancher setup on 2.5.8/2.6.7 with a downstream cluster
2) Install monitoring into the downstream cluster and ensure fleet version 0.3.5/0.3.10
3) Fork the fleet-examples repo https://github.com/rancher/fleet-examples and create a new branch for testing
4) Follow the fleet-agent pod logs in the downstream cluster, view workload metrics via monitoring
5) Navigate to Continuous Delivery via UI, select Git Reops and then select Create
6) Enter a name, the forked repository URL and the name of the test branch. Add path `/simple` and select Create
7) Confirm logs do not display errors, resource metrics are stable
8) Modify the test branch to cause an error. i.e. Add `foo: bar` inside the `spec:` field of the template yaml `simple/frontend-deployment.yaml`
9) Push up the changes and return to view the fleet-agent logs and workload metrics
10) Confirm recurring requeuing messages in logs and spike in metrics on fleet-agent
```
level=error msg="error syncing 'cluster-fleet-default-c-hgqwg-aeb8ba15dd9f/ms-fleet-example-simple': handler bundle-deploy: error validating \"\": error validating data: ValidationError(Deployment.spec.template.spec): unknown field \"foo\" in io.k8s.api.core.v1.PodSpec, requeuing"
```
11) Confirm error state `Err Applied` is displayed on bundle and git repo inside Continuous Delivery via UI

Steps to validate(upgrade):

1) Bring up HA Rancher setup on 2.5.8/2.6.7 with a downstream cluster
2) Install monitoring into the downstream cluster and ensure fleet version 0.3.5/0.3.10
3) Fork the fleet-examples repo https://github.com/rancher/fleet-examples and create a new branch for testing
4) Follow the fleet-agent pod logs in the downstream cluster, view workload metrics via monitoring
5) Navigate to Continuous Delivery via UI, select Git Reops and then select Create
6) Enter a name, the forked repository URL and the name of the test branch. Add path `/simple` and select Create
7) Confirm logs do not display errors, resource metrics are stable
8) Modify the test branch to cause an error. i.e. Add `foo: bar` inside the `spec:` field of the template yaml `simple/frontend-deployment.yaml`
9) Push up the changes and return to view the fleet-agent logs and metrics
10) Confirm recurring requeuing messages in logs and spike in workload metrics on fleet-agent
```
level=error msg="error syncing 'cluster-fleet-default-c-hgqwg-aeb8ba15dd9f/ms-fleet-example-simple': handler bundle-deploy: error validating \"\": error validating data: ValidationError(Deployment.spec.template.spec): unknown field \"foo\" in io.k8s.api.core.v1.PodSpec, requeuing"
```
11) Confirm error is displayed on bundle and git repo inside Continuous Delivery via UI
12) Upgrade to fleet version 0.5.0 on the local cluster via helm
```
helm upgrade -n cattle-fleet-system fleet https://github.com/rancher/fleet/releases/download/v0.5.0/fleet-0.5.0.tgz
helm upgrade -n cattle-fleet-system fleet-crd https://github.com/rancher/fleet/releases/download/v0.5.0/fleet-crd-0.5.0.tgz
```
13) Confirm error state `Not Ready` is displayed on git repo and error messages below are displayed on git repo and bundle after upgrade, confirm recurring requeuing messages are no longer present in fleet-agent logs(new pod)

Git Repos:
```
Not installed: error validating "": error validating data: ValidationError(Deployment.spec.template.spec): unknown field "foo" in io.k8s.api.core.v1.PodSpec
```
Bundle:
```
NotReady(2) [Cluster fleet-default/c-xb7ks: not installed: error validating "": error validating data: ValidationError(Deployment.spec.template.spec): unknown field "foo" in io.k8s.api.core.v1.PodSpec]
```
14) View downstream cluster metrics via monitoring to confirm:
- load from recurring requeuing is no longer present
- no significant spikes in metrics for workload or traffic on fleet-agent are present

Steps to validate(fresh installation):

1) Bring up HA Rancher setup on 2.6.11-rc8 with a downstream cluster
2) Install monitoring into the downstream cluster and ensure fleet version 0.5.2-rc3
3) Fork the fleet-examples repo https://github.com/rancher/fleet-examples and create a new branch for testing
4) Follow the fleet-agent pod logs in the downstream cluster, view workload metrics via monitoring
5) Navigate to Continuous Delivery via UI, select Git Reops and then select Create
6) Enter a name, the forked repository URL and the name of the test branch. Add path `/simple` and select Create
7) Confirm logs do not display errors, resource metrics are stable
8) Modify the test branch to cause an error. i.e. Add `foo: bar` inside the `spec:` field of the template yaml `simple/frontend-deployment.yaml`
9) Push up the changes, view the fleet-agent logs and workload metrics
10) Confirm error state `Not Ready` is displayed on git repo and error messages below are displayed on git repo and bundle after upgrade, confirm recurring requeuing messages are not present in fleet-agent logs

Git Repos:
```
Not installed: error validating "": error validating data: ValidationError(Deployment.spec.template.spec): unknown field "foo" in io.k8s.api.core.v1.PodSpec
```
Bundle:
```
NotReady(2) [Cluster fleet-default/c-clrpt: not installed: error validating "": error validating data: ValidationError(Deployment.spec.template.spec): unknown field "foo" in io.k8s.api.core.v1.PodSpec]
```
11) View downstream cluster metrics via monitoring to confirm:
- no persistent spikes in metrics for workload or traffic on fleet-agent are present
