### ISSUE TITLE
Fleet should publish images based on commits to master and Rancher's master-based images should use them

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#501]
In order to "fully" test Fleet in Rancher, you must either publish your own image or use a Fleet RC. We should publish Fleet images based on commits to master, and Rancher's master-based images should use them.

**Comment by nickgerace** [comment]
This would incredibly help both engineers and QA. If Rancher `master-head` included Fleet `master-head`, that would be game changing.

**Comment by kkaempf** [comment]
not planned
