### ISSUE TITLE
How to manage Git Repos 

### ISSUE THREAD

**Issue by usst830514** [rancher/fleet#510]
Dear all,

We have many applications(each one is related to a gitlab project used for source code). Most of them can share a common helm chart, the only difference is just like replicas/image , etc.  I'm wondering how to manage my Git Repos in fleet.
Firstly, should I have to create different gitlab project (a Bundle) for diffrernt applications?
Secondly, should I have to create diffrernt Git Repo in fleet's dashboard?

**Comment by kkaempf** [comment]
See https://rancher-users.slack.com/archives/C013SSBKB6U/p1671782009688179
