### ISSUE TITLE
Polish Fleet CRD files for `docs.crds.dev`

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#517]
Core repository: https://github.com/crdsdev/doc
Relevant comment: https://github.com/crdsdev/doc/issues/152#issuecomment-910537328
Current live CRD docs: https://doc.crds.dev/github.com/rancher/fleet

(thanks to @hasheddan for the site!)

**Comment by nickgerace** [comment]
This would be extremely helpful for users. We can pester Dan as needed too :)

**Comment by kkaempf** [comment]
not planned
