### ISSUE TITLE
Combine Cabundle from gitrepo to helm

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/fleet#519]
Today to access private helm chart in `fleet.yaml` user has to provide a helmSecret which contains auth and cabundle. Since we are already asking cabundle for git repo we can merge together so that user can provide cabundle for git and helm through gitrepo `spec.clientSecretName`.

**Comment by Martin-Weiss** [comment]
Just have hit this issue in Rancher 2.6.4 / Fleet 0.3.9 where fleet can not fetch the helm chart due to "x509: certificate signed by unknown authority". Is there any plan to get this fixed?

**Comment by kkaempf** [comment]
not planned
