### ISSUE TITLE
[FeatureReqest] New functions from sprig

### ISSUE THREAD

**Issue by PatrickHuetter** [rancher/fleet#520]
Dear rancher fleet team,

I wanted to deploy the MinIO Operator via fleet but I couldn't since fleet doesn't seem to support the new functions from [sprig](http://masterminds.github.io/sprig/dicts.html). You can find the exact problem here: https://github.com/minio/operator/issues/802

Is it planned to integrate these new functions into fleet? That would be nice to have furthermore support for all upcoming helm charts.

Best regards

**Comment by pthrasher** [comment]
I have also just run into this. Trying to deploy to standard RKE cluster using cluster explorer.

**Comment by ron1** [comment]
I believe fleet 0.3.8 fixes this problem by upgrading its included helm version.

**Comment by manno** [comment]
I'm closing this issue, because it is old. We updated to helm 3.9
