### ISSUE TITLE
fleet.yml blocks fleet-agent from adding/removing bundles

### ISSUE THREAD

**Issue by magiconair** [rancher/fleet#525]
We've just spend a couple of days because of a `fleet.yml` file in the repository. 

During this time the `fleet-agent` continued to work but stopped adding and removing bundles but applied updates to existing bundles. So it silently diverged from the descriptions in the git repo. This was quite nasty and there was nothing in the logs. 

There is an outdated PR https://github.com/rancher/fleet/pull/359 on this but this is really a bug. The agent shouldn't stop working because of a file with the wrong extension. 

fleet-agent 0.3.5
rancher 2.5.8

**Comment by magiconair** [comment]
And yes, this is a facepalm issue. I'd like to crawl under a rock for not seeing this... :/

**Comment by kkaempf** [comment]
fixed by #592 and #593 🤞🏻
