### ISSUE TITLE
Add the ability to test deployments after rollout

### ISSUE THREAD

**Issue by FlxPeters** [rancher/fleet#527]
Flux has the feature to run `helm test` in order to verify if a rollout was successful: https://fluxcd.io/legacy/helm-operator/helmrelease-guide/tests/

I could not find anything about this in the docs or code. Flux should also have a feature similar to this.

Here are some stories i want to cover:

* As a Fleet user i want Fleet to run `helm test` after applying a helm chart in order to validate my deployment
* As a Fleet user i want Fleet to rollback a deployment if the tests failed

I am looking forward to your feedback if you support such a feature and would like to have it. 

Cheers,
Felix

**Comment by sgran** [comment]
FYI here's how Flux does it:
https://github.com/fluxcd/helm-controller/blob/54db7fd1ccf2942b29039236470983a4c79b8d3a/controllers/helmrelease_controller.go#L365-L376
