### ISSUE TITLE
Enhance bundle dependency management allowing selection using regular expressions in dependsOn feature

### ISSUE THREAD

**Issue by juanbrny** [rancher/fleet#532]
Hi team!
For customers with long lists of dependencies, it may make management simpler if they are able to target bundles inside a given Git repo using regular expressions instead of listing them one by one in dependsOn using something like this:
<GITREPO-NAME>-<REGEX_FOR_BUNDLE_PATHS>

**Comment by ibrokethecloud** [comment]
would using labels to match bundles be of help? https://github.com/rancher/fleet/pull/552

**Comment by kkaempf** [comment]
not planned
