### ISSUE TITLE
Inconsistent/Unclear error message and help on fleet apply

### ISSUE THREAD

**Issue by ADustyOldMuffin** [rancher/fleet#534]
When using `fleet apply` the arguments are inconsistent to the help. The help output shows usage as 

```
Usage:
  fleet apply [flags] BUNDLE_NAME PATH...
```
But when using something like `fleet apply -f fleet.yml frontend deployments/**.yml` you receive the error of `the bundle name is required as the first argument` which doesn't make much sense.

I've found these lines, which define the errors/input but the errors don't make much sense as the first arg according to the help should be treated as the bundle name, and the rest as paths.
 https://github.com/rancher/fleet/blob/667022c1d661e8f4b1b4659a5f7c6b45dd749bae/modules/cli/cmds/apply.go#L92-L114

I'd be happy to tackle this myself, but require some guidance as to what the expected/wanted behavior should be.

Specifically my question is around this section 
https://github.com/rancher/fleet/blob/667022c1d661e8f4b1b4659a5f7c6b45dd749bae/modules/cli/cmds/apply.go#L98-L109

So if a fleet.yml is supplied we cannot pass the paths? The fleet.yml (at least according to the docs) doesn't have anything about paths defined in it.

**Comment by ADustyOldMuffin** [comment]
After further inspection I believe there's a bug, the `args` variable is never set like it is at the bottom `args = args[1:]` so it's searching for a folder with the same name as the bundle.

**Comment by manno** [comment]
The argument parser in the fleet CLI is very basic. Also see #1385
These tools should not be user facing.
