### ISSUE TITLE
on RANCHER when I was trying to assign the fleet group to the AKS cluster , cluster is in wait check-in state and never goes active

### ISSUE THREAD

**Issue by emp00001** [rancher/fleet#537]
Hello,

I am running rancher 2.5.9.
I used rancher to create azure AKS, after AKS was running , I trying to setup fleet:

So, I go to tools , then – cluster groups, then – created the cluster group, then – assigned that cluster group to  my AKS cluster, then waiting for that cluster to be active, but it stays in state = waiting check-in, I do not see any errors, but it does not go to state = active, how it can be fixed ?

**Comment by StrongMonkey** [comment]
Can you post the log of fleet-controller pod in local cluster?

**Comment by emp00001** [comment]
how I can get that log ?

**Comment by emp00001** [comment]
can you please tell me how to get that log ?


Thank you.
Michael.

**Comment by StrongMonkey** [comment]
Go to your local cluster and `fleet-system` namespace. There should be a pod `fleet-controller-xxxx`. You can do `kubectl logs -f fleet-controller-xxxx -n fleet-system`

**Comment by emp00001** [comment]
this is the log from controller:


cat controller.log
time="2021-09-21T21:55:42Z" level=info msg="No access to list CRDs,
assuming CRDs are pre-created."
I0921 21:55:42.751447       1 leaderelection.go:243] attempting to acquire
leader lease fleet-system/fleet-controller-lock...
I0921 21:55:42.797173       1 leaderelection.go:253] successfully acquired
lease fleet-system/fleet-controller-lock
E0921 21:55:45.948126       1 memcache.go:196] couldn't get resource list
for metrics.k8s.io/v1beta1: the server is currently unable to handle the
request
E0921 21:55:45.982179       1 memcache.go:101] couldn't get resource list
for metrics.k8s.io/v1beta1: the server is currently unable to handle the
request
time="2021-09-21T21:55:46Z" level=info msg="All controllers have been
started"
time="2021-09-21T21:55:46Z" level=info msg="Starting
fleet.cattle.io/v1alpha1, Kind=Cluster controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
fleet.cattle.io/v1alpha1, Kind=BundleDeployment controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
fleet.cattle.io/v1alpha1, Kind=ClusterRegistration controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
fleet.cattle.io/v1alpha1, Kind=ClusterRegistrationToken controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
fleet.cattle.io/v1alpha1, Kind=Bundle controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting /v1, Kind=Secret
controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
rbac.authorization.k8s.io/v1, Kind=Role controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
fleet.cattle.io/v1alpha1, Kind=GitRepo controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
fleet.cattle.io/v1alpha1, Kind=ClusterGroup controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
fleet.cattle.io/v1alpha1, Kind=Content controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
rbac.authorization.k8s.io/v1, Kind=ClusterRole controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
fleet.cattle.io/v1alpha1, Kind=GitRepoRestriction controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting /v1, Kind=Namespace
controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting gitjob.cattle.io/v1,
Kind=GitJob controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
fleet.cattle.io/v1alpha1, Kind=BundleNamespaceMapping controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting /v1, Kind=ConfigMap
controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting /v1,
Kind=ServiceAccount controller"
time="2021-09-21T21:55:46Z" level=info msg="Starting
rbac.authorization.k8s.io/v1, Kind=RoleBinding controller"
time="2021-09-21T22:08:04Z" level=error msg="error syncing
'fleet-default/c-6rwcj': handler import-cluster: secrets
\"c-6rwcj-kubeconfig\" not found, requeuing"
time="2021-09-21T22:08:08Z" level=info msg="Deployed new agent for cluster
fleet-default/c-6rwcj"
time="2021-09-21T22:12:19Z" level=info msg="Deleted old agent for cluster
fleet-default/c-6rwcj"
time="2021-09-21T22:12:21Z" level=info msg="Deployed new agent for cluster
fleet-default/c-6rwcj"
time="2021-09-21T22:13:32Z" level=info msg="Deleted old agent for cluster
fleet-default/c-6rwcj"
time="2021-09-21T22:13:34Z" level=info msg="Deployed new agent for cluster
fleet-default/c-6rwcj"
time="2021-09-21T22:15:36Z" level=info msg="Deleted old agent for cluster
fleet-default/c-6rwcj"
time="2021-09-21T22:15:38Z" level=info msg="Deployed new agent for cluster
fleet-default/c-6rwcj"
time="2021-09-21T22:21:23Z" level=error msg="error syncing
'fleet-default/import-token-c-6rwcj': handler cluster-group-token: failed
to delete
fleet-default/import-token-c-6rwcj-9163888b-f93f-45bf-ba80-282e3ab8b984
/v1, Kind=ServiceAccount for cluster-group-token
fleet-default/import-token-c-6rwcj: serviceaccounts
\"import-token-c-6rwcj-9163888b-f93f-45bf-ba80-282e3ab8b984\" not found,
failed to delete
fleet-default/import-token-c-6rwcj-9163888b-f93f-45bf-ba80-282e3ab8b984-role
rbac.authorization.k8s.io/v1, Kind=Role for cluster-group-token
fleet-default/import-token-c-6rwcj: roles.rbac.authorization.k8s.io
\"import-token-c-6rwcj-9163888b-f93f-45bf-ba80-282e3ab8b984-role\" not
found, requeuing"


Thank you.
Michael.

**Comment by emp00001** [comment]
how I can fid the RANCHER   IP  running on rke   ?

**Comment by emp00001** [comment]
I found the issue and it looks like: since I do not have the domain name and running the rancher on my own PC, my rancher VM can reach the azure, but azure can not reach my VM back, so I created the VM on azure site, installed:  helm, docker, kuber, rke and rancher, but can not start it on the web page, can somebody please help me - where I should look at.


when I was running rke config I got warnings:
WARN[0069] [reconcile] host [52.168.26.84] is a control plane node without reachable Kubernetes API endpoint in the cluster
WARN[0069] [reconcile] no control plane node with reachable Kubernetes API endpoint in the cluster found



when I ran rke up, I saw the error:
FATA[0412] Failed to get job complete status for job rke-metrics-addon-deploy-job in namespace kube-system

**Comment by selcuk-cofe** [comment]
Hey there , I m also have same problem on Rancher 2.6 Stable version.

when I check logs for pod under cattle-fleet-system namespace I saw below error. not sure where to look to fix that error it's looking for a secret.

`time="2021-10-04T16:02:39Z" level=info msg="Waiting for secret cattle-fleet-clusters-system/c-45b6993850c148d7c45c392716d288bcc0c7e79acdcd2e2853d9b1a728b60 for fleet-default/request-q44kt: secrets \"c-45b6993850c148d7c45c392716d288bcc0c7e79acdcd2e2853d9b1a728b60\" not found"`

I have added repo and can see all resources in ready state. also when I check bundles I see that error also.

`Failed to create cluster-fleet-default-clementine-nano-0001-525bfd0dee40/clementine-oasis fleet.cattle.io/v1alpha1, Kind=BundleDeployment for bundle fleet-default/clementine-oasis: bundledeployments.fleet.cattle.io "clementine-oasis" is forbidden: unable to create new content in namespace cluster-fleet-default-clementine-nano-0001-525bfd0dee40 because it is being terminated`

Is there anyone who faced with that issue or anyone can help ?

**Comment by xzxiaoshan** [comment]
me too.  state =Wait Check-In

**Comment by Aaroneus** [comment]
I am also having this issue attempting to try out Rancher from my local machine. 

I am unable to evaluate Rancher as a viable tool for my organisation without this.

Please can you suggest a fix.

Thanks

**Comment by kkaempf** [comment]
Should go to [Slack](https://rancher-users.slack.com/channels/fleet)

**Comment by marvinlnnx** [comment]
same here, I have tried 2.10, 2.9.3 both the same issue, but 2.9.0 is okay !

**Comment by kkaempf** [comment]
2.10 isn't even released yet 😕
