### ISSUE TITLE
Request: (Fleet CLI) Put bundle operations under bundle subcommand.

### ISSUE THREAD

**Issue by ADustyOldMuffin** [rancher/fleet#538]
The Fleet CLI has several commands, all of which currently are for bundles. It's possible that in the future the CLI could be expanded to do other things inside of Fleet, and so it would be useful (and more clear to users) to put the operations regarding a specific resource under a sub command. 

Examples include docker, or kubectl `kubectl get pods` so in this case, `fleet apply bundle ...` or `fleet bundle apply`.

I'm interested in thoughts and feedback.

**Comment by nickgerace** [comment]
I'm curious here. What specific examples would you like to see? Not opposed, but unsure which _specific_ ideas you have.
cc @StrongMonkey

**Comment by ADustyOldMuffin** [comment]
Examples would only be for bundles as that's the only thing I believe the fleet cli works with, but I can give some examples of thing I'd be interested in.

`fleet apply bundle [OPTIONS] {BUNDLE_NAME} [BUNDLE_PATH...]` - this would be more explicit that this will create a bundle, or bundles in rancher. This would be akin to `docker list container` or `docker list volume` which lets the user know what they're interacting with.

Features that I was planning on requesting/creating a PR for would be things like list.
`fleet list bundle`
`fleet list bundle --status`
`fleet list gitrepo`
`fleet list cluster`

From a user standpoint it's cleaner IMO as it's very obvious what you're looking for.

**Comment by kkaempf** [comment]
not planned
