### ISSUE TITLE
Fleet CLI expecting fleet file to be in JSON format

### ISSUE THREAD

**Issue by ADustyOldMuffin** [rancher/fleet#540]
As the title says, when running `fleet apply -f fleet.yml BUNDLE_NAME` the fleet.yml is being decoded as JSON currently instead of YML as all of the documentation suggests.

**Comment by ADustyOldMuffin** [comment]
I would love to take on this issue and submit a PR for it.

**Comment by nickgerace** [comment]
YAML is a superset of JSON, is there unintended behavior occurring that triggers this issue?

**Comment by ADustyOldMuffin** [comment]
https://github.com/rancher/fleet/blob/667022c1d661e8f4b1b4659a5f7c6b45dd749bae/modules/cli/apply/apply.go#L113-L132

These lines specifically will not parse a YAML file when a fleet.yml is specified. It gives JSON parsing errors, and once the format is changed to JSON it can parse it correctly.

**Comment by ADustyOldMuffin** [comment]
Funny enough though, with my PR #539 it actually corrects this issue as it removes this in favor of the `bundle.Read` function inside of `pkg/bundle`.

**Comment by kkaempf** [comment]
not planned
