### ISSUE TITLE
YAML for Azure CLI

### ISSUE THREAD

**Issue by emp00001** [rancher/fleet#545]
how I can use Azure CLI  in the yaml  script, I need to create the yaml template to deploy the Azure AKS to run that template form rancher

any examples how to run Azure CLI from yaml ?

**Comment by emp00001** [comment]
or is it possible to kick of the ansible playbook from rancher ?

**Comment by kkaempf** [comment]
Should go to [Slack](https://rancher-users.slack.com/channels/fleet)
