### ISSUE TITLE
Unable to fill in configuration form in UI with http based git address while creating gitrepo.

### ISSUE THREAD

**Issue by bluezd** [rancher/fleet#546]
When I specify the **http** based git address that would result in the rest configuration form disappear in the UI:

![image](https://user-images.githubusercontent.com/977107/134810818-d7bd6cdf-1f40-400c-bfd6-1cba07cade18.png)

To workaround this I got to modify the yaml instead. That is pretty inconvenient.

After switching back to **https**, this configuration form do appear properly:
![image](https://user-images.githubusercontent.com/977107/134810919-3471648b-e5f4-4dea-bca3-b370194cdffc.png)

**Comment by kkaempf** [comment]
Fixed in https://github.com/rancher/dashboard/issues/4395
