### ISSUE TITLE
Fleet CLI not respecting fleet.yml for bundles.

### ISSUE THREAD

**Issue by ADustyOldMuffin** [rancher/fleet#548]
Currently in the `fleet apply` command only a single fleet.yml is respected, and if none is given then it errors out. I believe it should work the way the docs describe it.

> fleet.yaml
The fleet.yaml is an optional file that can be included in the git repository to change the behavior of how the resources are deployed and customized. The fleet.yaml is always at the root relative to the path of the GitRepo and if a subdirectory is found with a fleet.yaml a new bundle is defined that will then be configured differently from the parent bundle.

This can be found [here](https://fleet.rancher.io/gitrepo-structure/#fleetyaml). I believe this would require some major changes to the folder walking code.

**Comment by ibrokethecloud** [comment]
If your repo only contains the workload yaml manifests then fleet.yaml is not needed, but the workload will be deployed to default namespace. An example is available here: https://github.com/rancher/fleet-examples/tree/master/simple

**Comment by kkaempf** [comment]
not planned
