### ISSUE TITLE
application status showing unknow.

### ISSUE THREAD

**Issue by yagashiraevil** [rancher/fleet#572]
I added the manifest file from the repo and added it to the fleet-local, the application gets deployed as expected but the fleet status shows as modified and the application status is unknown or orphaned.
![image](https://user-images.githubusercontent.com/26820733/138585000-f8a57c80-b1b3-4946-a36c-8c928b3c2e4c.png)
![image](https://user-images.githubusercontent.com/26820733/138585018-60af5c19-f987-4c69-8ccf-9fd0a6ebdb01.png)
![image](https://user-images.githubusercontent.com/26820733/138585033-d23b1a90-1c7a-497e-ac29-388fc9b1e419.png)
**Event**
![image](https://user-images.githubusercontent.com/26820733/138585071-99c2bf15-989d-4611-a7f3-c2fd1c8419a4.png)

Rancher version 2.6.0
k3s cluster

**Comment by raulcabello** [comment]
This is fixed by https://github.com/rancher/fleet/pull/1201 . It can be tested with this build https://github.com/rancher/fleet/actions/runs/3753943327
