### ISSUE TITLE
Target customization based on labels not working for fleet-local cluster

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/fleet#575]
We have to deploy some components to all downstream but also to fleet-local cluster (i.e. logging).

In this scenario we want to use one single git repo with targetCustomizations based on labels.

The targetCustomizations work well with the downtsteam clusters but the seem to be ignored completely for fleet-local.

Could we get this fixed or do we do something wrong?

Version we use at the moment: Rancher 2.5.9

**Comment by kkaempf** [comment]
not planned
