### ISSUE TITLE
Document API spec overview page expansion

### ISSUE THREAD

**Issue by jtravee** [rancher/fleet#576]
From customer feedback:

Every CRD used in Fleet needs to have detailed and complete documentation, for each version as can be found at https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/, except for the Fleet CRDs. This kind of documentation is essential when trying to answer a “can $this do $that?” type of question. I just want to look at the spec and find out if it has the feature I’m looking for.

Reference: https://fleet.rancher.io/concepts/ - build out this page with more details for CRDs.

**Comment by jtravee** [comment]
Closing; refer to #623, #624.

**Comment by nickgerace** [comment]
I think all issues could co-exist, but feel free to organize how you would like! The docs issues are open-ended and I'd be fine with changing them a bit.
