### ISSUE TITLE
How can we prevent fleet from adding non yaml files into bundles - can we have a .fleetignore?

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/fleet#583]
Just had to realize that a file called "ldap-toml" with "toml format content" I had in the git repo was added to the fleet bundle.

I believe we need a way to control which files are looked at by fleet so that i.e. readme or other txt files can be excluded or are excluded by default.

IMO we should "just" look at *.yaml files but probably we can add a `.fleetignore` or an option that allows control over which files should be taken and which not in the fleet.yaml..

**Comment by BryceTech122** [comment]
Is this still being looked at being implemented or no?

**Comment by skaven81** [comment]
+1 for this feature, it would be very helpful

**Comment by weyfonk** [comment]
@skaven81 what is your use case? Would simply excluding non-YAML files work for you?

**Comment by skaven81** [comment]
> @skaven81 what is your use case? Would simply excluding non-YAML files work for you?

It would be better than nothing I suppose.  But just excluding non-YAML files still creates opportunities for bundles to break in unexpected ways, with little recourse except to remove the offending file from the repository or to rename it to some other extension.  Implementing this properly with a `.fleetignore` file (that uses the same syntax and behavior as `.gitignore`) gives me the ability to explicitly ignore files that might be causing problems, without having to resort to workarounds like deleting the file or renaming it.

YAML files aren't _only_ for Kubernetes resources.  YAML can be used for configuration, CI/CD pipeline specifications, or any manner of machine-parseable metadata that might surround a git repository, but that aren't actually meant to be deployed into Kubernetes by Fleet.  It would be best if Fleet could be instructed to ignore such files, even if they have a `.yaml` or `.yml` extension.

**Comment by weyfonk** [comment]
## Additional QA
 
### Problem
By default, there was no way to control which files present at a path referenced in a `GitRepo` would end up in the corresponding bundle generated by Fleet.
This would result in some irrelevant files being included in bundles.
 
### Solution
Fleet now support `.fleetignore` files which can be placed in any of those git repo paths or in their subdirectories, to ignore files and/or directories (mostly) as one would do with `.gitignore` files.
 
### Testing

### Engineering Testing
#### Manual Testing
1. Added a `_typos.toml` file to a git repository, without `.fleetignore`
2. Applied a `GitRepo` resource pointing to that git repository path
3. Ran `kubectl describe bundle <bundle-name>` and could see the contents of `_typos.toml` in the output
4. Created a `.fleetignore` file containing a `_typos.toml` entry in the same git repository path
5. Applied the same `GitRepo` resource
6. Ran `kubectl describe bundle <bundle-name>` again and noticed that the contents of `_typos.toml` we no longer present in the output

#### Automated Testing
[Unit tests](https://github.com/rancher/fleet/blob/master/internal/bundlereader/loaddirectory_test.go) cover:
* empty `.fleetignore`
* no `.fleetignore`
* Comments,  ie lines starting with `#`
* Trailing whitespaces, which are ignored unless escaped with `\`
* Glob [patterns](https://pkg.go.dev/path/filepath#Match) for file/directory matching
* Ignoring a single file at the same level as `.fleetignore`
* Ignoring files at levels below `.fleetignore`, ie in subdirectories
* Ignoring directories
* Entries from `root/a/.fleetignore` not affecting `root/b/`
* Entries from `root/.fleetignore` being applied to subdirectories of `root`

### QA Testing Considerations
N/A
 
#### Regressions Considerations
* Create hidden files or directories in a git repo and ensure that those are ignored even without any `.fleetignore`.

**Comment by sbulage** [comment]
**TEST RESULT**
|Scenario|Test Case|Results
|---|---|---|
|1| Test `.fleetignore` ignores content of non-yaml file into `bundle`.| :heavy_check_mark:|
|2| Test `bundle` contains content from `*.yaml` or `*.yml` only, even though the hidden file is present.|:heavy_check_mark: |
|3| Test exising `GitRepo` removes the content of non-yaml file from the bundle when `.fleetignore` created beside `fleet.yaml` file.|:heavy_check_mark: |
|4| Test `.fleetignore` excludes files in the nested application structure.|:heavy_check_mark:|

**REPRO STEPS**

**Scenario 1**
1. Create an application directory like [this](https://github.com/sbulage/test-fleet/tree/main/check-fleet-ignore) which has `.fleetignore` excluding `*.toml`, `*.txt` and specific name of the file to ignore.
2. Create a `GitRepo` from above `GitHub repo` with path `check-fleet-ignore`
3. Goto the Advanced --> Bundles --> Edit YAML (to see the content of it.)
4. Verify that the bundle does not contain the contents from the `.toml`, `.txt` and `.mp3` file in it.

**Scenario 2**
1. Create an application directory like [this](https://github.com/sbulage/test-fleet/tree/main/check-fleet-ignore) which has hidden files created.
2. Create a `GitRepo` from above `GitHub repo` with path `check-fleet-ignore`
3. Goto the Advanced --> Bundles --> Edit YAML (to see the content of it.)
4. Verify that the bundle ignores the hidden file content when no `.fleetignore` file.

**Scenario 3**
1. Create a `GitRepo` with various files.
2. Verify that `bundle` has content of the other files in it.
2. Update a `GitRepo` with `.fleetignore` by files to exclude from the `bundle`.
3. Goto the Advanced --> Bundles --> Edit YAML (to see the content of it.)
4. Verify that the bundle removes the content of other files which are mentioned in the `.fleetignore` file.

**Scenario 4**
1. Create a directory structure which has 1 application with another nested application. Like [this](https://github.com/sbulage/test-fleet/tree/main/check-fleet-ignore). Both directories contains `.fleetignore` which ignores  `*.toml`, `*.txt`, specific name of the file and nested application ignores `*.md` file.
2. Create a `GitRepo` from above `GitHub repo` with path `check-fleet-ignore`
3. Goto the Advanced --> Bundles --> Edit YAML (to see the content of it.)
4. Verify that the bundle does not contain the contents from the `.toml`, `.txt` and `.mp3` file in it.
5. Verify another application `bundle` does obey the `.fleetignore` and excludes the mentioned file(s) content in the `bundle`.
