### ISSUE TITLE
Rancher Fleet automatically reset default cluster group config

### ISSUE THREAD

**Issue by akazakou-incomm** [rancher/fleet#584]
Each day I'm able to see that the `default` group of clusters reset his configuration to default values.
![image](https://user-images.githubusercontent.com/83806630/139629090-426301ab-b45c-4bb6-8a56-bb60bc73f429.png)

Rancher: v2.6.2
Fleet: 0.3.7

<details>
<summary>Cluster group YAML configuration</summary>
<pre>
apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3xOTU7zMBC9y6z79WtDmlDvULesEBeY2hNisD2WPVZVVbk7sluKhBC7N2/e3wU8CRoUBHUBDIEFxXLI9eTjO2nJJOtkea1RxNHa8n9rQMHkiOTfkVmyJIywrEAnauZX6ykL+ggqFOdW4PBI7s/IGfMMCoZx6sfdNHQD7frxYRy7adg89tjtt9txg3tDu33fmW1tC+gJFBiasDiBK5Ejarqvc6zRVW2OpGt9JkdaOFXsUfT8fF92i7tZlmoSlNJ+2pUslA5cgoDarMDYHB2eQV3qEA4vhOZ8+KlKlLkkTY1pQYayTWSavEm8zdmGtytmYydLph2B5VvFKc4Ybp90p0v4CHwKDZ/QylOM7uqv64v3mM6/tn5FLMvyGQAA///yPuq4AQIAAA
    objectset.rio.cattle.io/id: fleet-bootstrap
  creationTimestamp: "2021-10-21T14:28:12Z"
  generation: 10
  labels:
    objectset.rio.cattle.io/hash: 67f475f626e5473772f6084a291170a9de5942d1
  managedFields:
  - apiVersion: fleet.cattle.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:objectset.rio.cattle.io/applied: {}
          f:objectset.rio.cattle.io/id: {}
        f:labels:
          .: {}
          f:objectset.rio.cattle.io/hash: {}
      f:spec:
        .: {}
        f:selector:
          .: {}
          f:matchLabels:
            f:name: {}
      f:status:
        .: {}
        f:clusterCount: {}
        f:conditions: {}
        f:display:
          .: {}
          f:readyBundles: {}
          f:readyClusters: {}
          f:state: {}
        f:nonReadyClusterCount: {}
        f:nonReadyClusters: {}
        f:resourceCounts:
          .: {}
          f:desiredReady: {}
          f:missing: {}
          f:modified: {}
          f:notReady: {}
          f:orphaned: {}
          f:ready: {}
          f:unknown: {}
          f:waitApplied: {}
        f:summary:
          .: {}
          f:desiredReady: {}
          f:nonReadyResources: {}
          f:ready: {}
          f:waitApplied: {}
    manager: fleetcontroller
    operation: Update
    time: "2021-11-01T00:14:41Z"
  name: default
  namespace: fleet-local
  resourceVersion: "5431585"
  uid: 6b57f908-01b4-41a3-b70e-10ac31dd8b7c
spec:
  selector:
    matchExpressions: []
    matchLabels:
      name: local
status:
  clusterCount: 1
  conditions:
  - lastUpdateTime: "2021-11-01T00:14:45Z"
    message: WaitApplied(4) [Bundle vms-ms-1-vms-config-data]
    status: "False"
    type: Ready
  - lastUpdateTime: "2021-11-01T00:14:45Z"
    status: "True"
    type: Processed
  display:
    readyBundles: 1/5
    readyClusters: 0/1 (local)
    state: WaitApplied
  nonReadyClusterCount: 1
  nonReadyClusters:
  - local
  resourceCounts:
    desiredReady: 34
    missing: 0
    modified: 0
    notReady: 0
    orphaned: 0
    ready: 0
    unknown: 0
    waitApplied: 34
  summary:
    desiredReady: 5
    nonReadyResources:
    - bundleState: WaitApplied
      name: vms-ms-1-vms-config-data
    - bundleState: WaitApplied
      name: vms-ms-1-vms-ms-deployment-helm-vms-config
    - bundleState: WaitApplied
      name: vms-ms-1-vms-ms-deployment-helm-vms-customers
    - bundleState: WaitApplied
      name: vms-ms-1-vms-ms-deployment-helm-vms-discovery
    ready: 1
    waitApplied: 4
</pre>
</details>

<details>
<summary>Cluster YAML configuration</summary>
<pre>
apiVersion: fleet.cattle.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4ySz27bMAzGX2Xg2cnm9U9iAzsMOewwoId2L8BItKNFogyRThAEfvfBduJ6RVvkJpm/7+NHWmcIpGhREcozIHNUVBdZ+mvc/iWjQrpMLi4NqnpauvjVWSih8kS6ML4VpQTZh3A8MqVFfdhDCU2KBycusuN6hhzy7Mtvx/bH5kY3xkBQgo8G/U2wNGhoCj3qugxMomHaPy6QKIYGSm69z8Djlvywg4CMNQVinRlfpl5YJ43H09s8n2puzL5D2fWBv+Mai6IocP1AeV5V67vHh3t6zA2ZO1yt8/tVUW2rFWTjci2lVxMoAffSD/qm6ScrkYbM8BRqYn2acaPrYoYv5CRKATLYt1vaRK5c/UImkV5bTc+jN1bUVibr/uBR9IWIr1ufx+pTRn4mtKenaGlIMnGzgkD5LYP0LpfmUJeBJXGJ7KD95fSZmjjKL/8RynN3Uf1XTiSxTYY2sWUdRpg7DUhwIo7r8RytqxzZ4cJRX6mYmh3ypZKmzy3vOR55OB/R6c+m8aO+31sbAqbTu12vFl3X/QsAAP//2X4mvMkDAAA
    objectset.rio.cattle.io/id: fleet-cluster
    objectset.rio.cattle.io/owner-gvk: provisioning.cattle.io/v1, Kind=Cluster
    objectset.rio.cattle.io/owner-name: local
    objectset.rio.cattle.io/owner-namespace: fleet-local
  creationTimestamp: "2021-10-21T14:27:30Z"
  generation: 5
  labels:
    management.cattle.io/cluster-display-name: local
    management.cattle.io/cluster-name: local
    objectset.rio.cattle.io/hash: f2a8a9999a85e11ff83654e61cec3a781479fbf7
    provider.cattle.io: aks
  managedFields:
  - apiVersion: fleet.cattle.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:objectset.rio.cattle.io/applied: {}
          f:objectset.rio.cattle.io/id: {}
          f:objectset.rio.cattle.io/owner-gvk: {}
          f:objectset.rio.cattle.io/owner-name: {}
          f:objectset.rio.cattle.io/owner-namespace: {}
        f:labels:
          .: {}
          f:management.cattle.io/cluster-display-name: {}
          f:management.cattle.io/cluster-name: {}
          f:objectset.rio.cattle.io/hash: {}
          f:provider.cattle.io: {}
      f:spec:
        .: {}
        f:agentNamespace: {}
        f:kubeConfigSecret: {}
        f:redeployAgentGeneration: {}
    manager: rancher
    operation: Update
    time: "2021-11-01T00:14:46Z"
  - apiVersion: fleet.cattle.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:agent:
          f:lastSeen: {}
          f:readyNodeNames: {}
          f:readyNodes: {}
    manager: fleetagent
    operation: Update
    time: "2021-11-01T06:11:41Z"
  - apiVersion: fleet.cattle.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:clientID: {}
      f:status:
        .: {}
        f:agent:
          .: {}
          f:namespace: {}
          f:nonReadyNodeNames: {}
          f:nonReadyNodes: {}
        f:agentDeployedGeneration: {}
        f:agentMigrated: {}
        f:agentNamespaceMigrated: {}
        f:cattleNamespaceMigrated: {}
        f:conditions: {}
        f:desiredReadyGitRepos: {}
        f:display:
          .: {}
          f:readyBundles: {}
          f:readyNodes: {}
          f:sampleNode: {}
        f:namespace: {}
        f:readyGitRepos: {}
        f:resourceCounts:
          .: {}
          f:desiredReady: {}
          f:missing: {}
          f:modified: {}
          f:notReady: {}
          f:orphaned: {}
          f:ready: {}
          f:unknown: {}
          f:waitApplied: {}
        f:summary:
          .: {}
          f:desiredReady: {}
          f:ready: {}
    manager: fleetcontroller
    operation: Update
    time: "2021-11-01T06:11:41Z"
  name: local
  namespace: fleet-local
  resourceVersion: "5570548"
  uid: 5894f08d-03ef-4eae-b101-5a1c066ade05
spec:
  agentNamespace: cattle-fleet-local-system
  clientID: 2kssm7nqxqhdwl6nxlhh84mtc8hb4lpww85gjtjgfmf6dh8c5fvw86
  kubeConfigSecret: local-cluster
  paused: false
  redeployAgentGeneration: 2
status:
  agent:
    lastSeen: "2021-11-01T06:11:41Z"
    namespace: cattle-fleet-local-system
    nonReadyNodeNames: null
    nonReadyNodes: 0
    readyNodeNames:
    - aks-github-12857252-vmss000001
    - aks-main-12857252-vmss000000
    readyNodes: 2
  agentDeployedGeneration: 2
  agentMigrated: true
  agentNamespaceMigrated: true
  cattleNamespaceMigrated: true
  conditions:
  - lastUpdateTime: "2021-11-01T00:15:11Z"
    status: "True"
    type: Ready
  - lastUpdateTime: "2021-11-01T06:11:41Z"
    status: "True"
    type: Processed
  - lastUpdateTime: "2021-10-25T10:26:32Z"
    status: "True"
    type: Imported
  - lastUpdateTime: "2021-10-21T14:28:11Z"
    status: "True"
    type: Reconciled
  desiredReadyGitRepos: 0
  display:
    readyBundles: 1/1
    readyNodes: 2/2
    sampleNode: aks-github-12857252-vmss000001
  namespace: cluster-fleet-local-local-1a3d67d0a899
  readyGitRepos: 0
  resourceCounts:
    desiredReady: 0
    missing: 0
    modified: 0
    notReady: 0
    orphaned: 0
    ready: 0
    unknown: 0
    waitApplied: 0
  summary:
    desiredReady: 1
    ready: 1
</pre>
</details>

**Comment by paulchoi** [comment]
Similar issue for me...
In my case, `fleet-default` has a `local` cluster which maps to a downstream cluster.
There is a separate `local` cluster in `fleet-local`, but GitRepos/Bundles reporting that various resources are "missing".

**Comment by erSitzt** [comment]
Btw. this really sucks, because it removed my rancher-backup configuration... :)

I dont unterstand why this issue is this old... this seems to be an easy fix :(

**Comment by manno** [comment]
This is now tracked in https://github.com/rancher/fleet/issues/1079
