### ISSUE TITLE
Ensure filepaths are being handled as filepath objects and not strings

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#599]
In order to ensure Fleet becomes eventually OS-agnostic in the local cluster (likely low priority until Rancher ever is supported on non-Linux local clusters), we should ensure all filepaths are handled by libraries (standard or other) rather than manually via strings. We should remove all references to path separators if possible.

cc: @genexpr from https://github.com/rancher/fleet/pull/592#discussion_r745003050

**Comment by nickgerace** [comment]
This is mainly to ensure Fleet is as OS-agnostic as possible. Sometimes, we may need to use UNIX-style paths, but not always.

**Comment by kkaempf** [comment]
not planned
