### ISSUE TITLE
[SURE-3681] Different helm credentials required per helm repository in fleet git repo

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/fleet#617]
We have git repos where we have one single git repo for deployment of multiple different helm charts from different helm repositories.

In this scenario we need to be able to specify and use different credentials per helm repository.

Example: one git repo for "dev" and one for "prod" (targetCustomizations) but for dev we have to use a different helm login than for prod..

-> could we get some sort of helm credentials to be used per helm repo?

**Comment by manno** [comment]
We discussed something similar in https://github.com/rancher/fleet/issues/978#issuecomment-1362619396
The `path`, `helmSecret` assignment would need to be declared in the [`GitRepo`](https://fleet.rancher.io/ref-gitrepo) resource.

**Comment by raulcabello** [comment]
Credentials need to be defined in the `GitRepo` as mentioned previously. Here is an example of how it can be done:
```yaml
helmSecretsNameByPath:
  path1: secretName1
  path2: secretName2
  ....
```
Path and secrets need to exist otherwise an error will be returned.

The controller needs to read the content of the secrets, and pass them to the fleet cli. Currently this is done with the `--username` , `--password-file` , `--cacerts-file`  and  `--ssh-privatekey-file` flags. Since we now need to pass these values for multiple paths it is better to use a file. I propose to create a new flag `helm-secrets-name-by-path-file` that should have the path of a file with the following structure:

```yaml
path1: 
  username: test
  password: password
  caBundle: YnVuZGxl
  sshPrivateKey: c3No
path2:
...
```

This file will be automatically created from the secrets defined in the GitRepo, so the user will not see it. It will need to be created manually just if you are using the fleet cli (currently you need to provide the flags to cli in this case).

**Comment by raulcabello** [comment]
# QA Template

## Problem
Multiple `Bundles` can be created from the same `GitRepo`.  A `Bundle` will be created for each path in the `GitRepo` , more info here. Currently the same helm credentials will be used for all the `Bundles`.

## Solution
Allow users to provided helm credentials for each path. For that a new field `HelmSecretNameForPaths` is added in the GitRepo. This field must have the name of a secret that contains credentials for GitRepo paths. Example:

```
helm-test: # path helm-test must exist in the repository
  username: user
  password: pass
helm-test-two:  # path helm-test-two must exist in the repository
  username: user2
  password: pass2
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCiAgICBNSUlEblRDQ0FvV2dBd0lCQWdJVUNwMHB2SVJTb2c0eHJKN2Q1SUI2ME1ka0k1WXdEUVlKS29aSWh2Y05BUUVMCiAgICBCUUF3WGpFTE1Ba0dBMVVFQmhNQ1FWVXhFekFSQmdOVkJBZ01DbE52YldVdFUzUmhkR1V4SVRBZkJnTlZCQW9NCiAgICBHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpERVhNQlVHQTFVRUF3d09jbUZ1WTJobGNpNXRlUzV2CiAgICBjbWN3SGhjTk1qTXdOREkzTVRVd056VXpXaGNOTWpnd05ESTFNVFV3TnpVeldqQmVNUXN3Q1FZRFZRUUdFd0pCCiAgICBWVEVUTUJFR0ExVUVDQXdLVTI5dFpTMVRkR0YwWlRFaE1COEdBMVVFQ2d3WVNXNTBaWEp1WlhRZ1YybGtaMmwwCiAgICBjeUJRZEhrZ1RIUmtNUmN3RlFZRFZRUUREQTV5WVc1amFHVnlMbTE1TG05eVp6Q0NBU0l3RFFZSktvWklodmNOCiAgICBBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXBvZE5TMDB6NDc1dnVSc2ZZcTFRYTFHQVl3QU92anV4MERKTHY5CiAgICBrZFhwT091dGdjMU8yWUdqNUlCVGQzVmpISmFJYUg3SDR2Rm84RlBaMG9zcU9YaFg3eUM4STdBS3ZhOEE5VmVmCiAgICBJVXp6Vlo1cCs1elNxRjdtZTlOaUNiL0pVSkZLT0ZsTkF4cjZCcXhoMEIyN1VZTlpjaUIvL1V0L0I2eHJuVE55CiAgICBoRzJiNzk4bjg4bFZqY3EzbEE0djFyM3VzWGYxVG5aS2t2UEN4ZnFHYk5OdTlpTjdFZnZHOWoyekdHcWJvcDRYCiAgICBXY3VSa3N3QkgxZlRNS0ZrbGcrR1VsZkZPMGFzL3phalVOdmdweTlpdVBMZUtqZTVWcDBiMlBLd09qUENpV2d4CiAgICBabDJlVDlNRnJjV0F3NTg3emE5NDBlT1Era2pkdmVvUE5sU2k3eVJMMW96YlRka0NBd0VBQWFOVE1GRXdIUVlECiAgICBWUjBPQkJZRUZEQkNkYjE4M1hsU0tWYzBxNmJSTCt0dVNTV3lNQjhHQTFVZEl3UVlNQmFBRkRCQ2RiMTgzWGxTCiAgICBLVmMwcTZiUkwrdHVTU1d5TUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCCiAgICBBQ1BCVERkZ0dCVDVDRVoxd1pnQmhKdm9GZTk2MUJqVCtMU2RxSlpsSmNRZnlnS0hyNks5ZmZaY1ZlWlBoMVU0CiAgICB3czBuWGNOZiszZGJlTjl4dVBiY0VqUWlQaFJCcnRzalE1T1JiVHdYWEdBdzlYbDZYTkl6YjN4ZDF6RWFzQXZPCiAgICBJMjM2ZHZXQ1A0dWoycWZqR0FkQjJnaXU2b2xHK01CWHlneUZKMElzRENraldLZysyWEdmU3lyci9KZU1vZlFBCiAgICB1VU9wcFVGdERYd0lrUW1VTGNVVUxWcTdtUVNQb0lzVkNNM2hKNVQzczdUSWtHUDZVcGVSSjgzdU9LbURYMkRHCiAgICBwVWVQVHBuVWVLOVMzUEVKTi9XcmJSSVd3WU1OR29qdDRKWitaK1N6VE1aVkh0SlBzaGpjL1hYOWZNU1ZXQmlzCiAgICBQRW5MU256MDQ4OGFUQm5SUFlnVXFsdz0KICAgIC0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  sshPrivateKey: ICAgIC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQogICAgTUlJRFF6Q0NBaXNDRkgxTm5YUWI5SlV6anNBR3FSc3RCYncwRlFpak1BMEdDU3FHU0liM0RRRUJDd1VBTUY0eAogICAgQ3pBSkJnTlZCQVlUQWtGVk1STXdFUVlEVlFRSURBcFRiMjFsTFZOMFlYUmxNU0V3SHdZRFZRUUtEQmhKYm5SbAogICAgY201bGRDQlhhV1JuYVhSeklGQjBlU0JNZEdReEZ6QVZCZ05WQkFNTURuSmhibU5vWlhJdWJYa3ViM0puTUI0WAogICAgRFRJek1EUXlOekUxTVRBMU5Gb1hEVEkwTURReU5qRTFNVEExTkZvd1hqRUxNQWtHQTFVRUJoTUNRVlV4RXpBUgogICAgQmdOVkJBZ01DbE52YldVdFUzUmhkR1V4SVRBZkJnTlZCQW9NR0VsdWRHVnlibVYwSUZkcFpHZHBkSE1nVUhSNQogICAgSUV4MFpERVhNQlVHQTFVRUF3d09jbUZ1WTJobGNpNXRlUzV2Y21jd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQogICAgQTRJQkR3QXdnZ0VLQW9JQkFRRGd6UUJJTW8xQVFHNnFtYmozbFlYUTFnZjhYcURTbjdyM2lGcVZZZldDVWZOSwogICAgaGZwampTRGpOMmRWWEV2UXA3R0t3akFHUElFbXR5RmxyUW5rUGtnTGFSaU9jSDdNN0p2c3ZIa0Ewd0g0dzJ2QgogICAgUEp6aVlINWh2MUE2WS9NcFM5bVkvQUVxVm80TUJkdnNZQzc3MFpCbzVBMitIUEtMd1YzMVZyYlhhTytWeUJtNAogICAgSmJhZHlNUk40N3BKRWdPMjJaYVRXL3Y3S1dKdjNydGJTMlZVSkNlU0piWlpsN09ocHhLRTVocStmK0RWaU1mcQogICAgTWx4ODNEV2pVSlVkV3lqVUZYVlk0bEdVaUtrRWVtSlVuSlVyY1ErOXE1SzVaWmhyRjhoRXhKRjhiZTZjemVzeAogICAga1VWN3dKb1RjWkd2bUhYSk1FNmtrQXh4Mmh3bU8wSFcyQWdDdTJZekFnTUJBQUV3RFFZSktvWklodmNOQVFFTAogICAgQlFBRGdnRUJBS1BpTWdXc1dCTnJvRkY2aWpYL2xMM3FxaWc4TjlkR1VPWDIyRVJDU1RTekNONjM0ZTFkZUhsdQogICAgbTc5OU11Q3hvWSsyZWluNlV1cFMvTEV6cnpvU2dDVWllQzQrT3ZralF5eGJpTFR6bW1OWEFnd09TM3RvTHRGWAogICAgbytmWWpSMU9xcHVPS29kMkhiYjliczRWcXdaNHEvMlVKbXE2Q01pYjZKZUE2VFJvK2Rkc0pUM2dDOFhWL1Z1MAogICAgNnkwdjJxdTM0bm1MYjFxOHFTS1RwZXYyQmwzQUJGY3NyS0JvNHFieUM2bnBTbnpZenNYcS90SlFLclplNE4vMgogICAgUXIzd1dxQ0pDVWUrMWVsT3A2b0JVcXNWSnc3aHk3YzRLc1Fna09ERDJkc2NuNEF1NGJhWlY2QmpySm1USVY0aQogICAgeXJ1dk9oZ2lINklGUVdDWmVQM2s0MU5obWRzRTNHQT0KICAgIC0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
```


## Testing

Create a GitRepo with at least two paths. Each path should point to a directory that contains a helm release that need credentials. For example I used:

credentials file `secrets-path.yaml`:
```
helm-test: 
  username: user
  password: pass
helm-test-two:
  username: user2
  password: pass2
```

create secret:
```
kubectl create secret generic auth-test --from-file=secrets-path.yaml -n fleet-local
```

GitRepo:
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: test
  namespace: fleet-local
spec:
  repo: https://github.com/raulcabello/fleet-test
  branch: main
  helmSecretNameForPaths: auth-test  
  paths:
  - helm-test
  - helm-test-two
```

**Comment by l4zy0n3** [comment]
## Test Plan
✅ Indicates a successfully validated scenario
### Positive Scenarios:

1. **Unique Credentials for Each Path**: ✅ 
    - Description: Use different username and password for each path defined in the GitRepo. 
    - Expected Outcome: Each path's Bundle is created successfully with the appropriate Helm credentials.

### Negative Scenarios:

1. **Incorrect Secret Name**:  ✅ 
    - Description: Provide an incorrect or non-existent secret name in the HelmSecretNameForPaths field.
    - Expected Outcome: The creation of the Bundle fails.

2. **Mismatch in Credentials and Paths**:  ✅ 
    - Description: Add more paths than credentials in the secret file.
    - Expected Outcome: The paths with missing credentials fail to create Bundles.

3. **Missing HelmSecretNameForPaths Field**:  ✅ 
    - Description: Create a GitRepo resource without including the HelmSecretNameForPaths field.
    - Expected Outcome: The creation of all the path Bundles fail.

4. **Invalid Helm Credentials**:  ✅ 
    - Description: Provide invalid Helm credentials for a path in the secret file.
    - Expected Outcome: The Bundle creation for that path fails.

5. **Empty Helm Credentials**:  ✅ 
    - Description: Provide empty Helm credentials for a path in the secret file.
    - Expected Outcome: The Bundle creation for that path fails.
