### ISSUE TITLE
consider using "defaultNamespace", not "namespace" in fleet.yaml

### ISSUE THREAD

**Issue by fractal1977** [rancher/fleet#618]
When i try to deploy Velero in Gitops way via CI/CD Rancher i have this error on CRDs:

error while running post render on files: invalid cluster scoped object [name=backupstoragelocations.velero.io kind=CustomResourceDefinition apiVersion=apiextensions.k8s.io/v1] found, consider using "defaultNamespace", not "namespace" in fleet.yaml

I didn't found any reference about this

**Comment by Sandah** [comment]
I have the same error trying to deploy longhorn

**Comment by fractal1977** [comment]
@Sandah , do not deploy in a specific Namespace.
When some app/deployment are "Namespaced" this error occurs because crds or other ressource need cluster/higher access.

**Comment by asloan7** [comment]
@deniseschannon  This is also a problem with other projects, such as traefik https://doc.traefik.io/traefik/reference/dynamic-configuration/kubernetes-crd/ , there are a number of references to "scope: Namespaced", 

So to be compatible with fleet these "scope" lines should be removed? 
The deployment works fine without fleet, so this might be some conflict between a fleet resource and CRDs

**Comment by kkaempf** [comment]
Closing for lack of progress. Please reopen (with instructions how to reproduce) if it still happens in latest Rancher.
