### ISSUE TITLE
Expose polling rate for GitRepos in chart in Rancher UI

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#619]
Idea from meeting with me and @davidnuzik.

**Comment by nickgerace** [comment]
This is a UI issue, ultimately.

**Comment by SheilaghM** [comment]
Locate corresponding UI ticket.

**Comment by erSitzt** [comment]
This would be great ! Any news here ?

**Comment by kkaempf** [comment]
to be moved to rancher/dashboard

**Comment by kkaempf** [comment]
Transferred to rancher/dashboard#7824
