### ISSUE TITLE
caBundle not respected for git ls-remote on Fleet 0.3.7?

### ISSUE THREAD

**Issue by AshleyDumaine** [rancher/fleet#622]
Hello,

I'm trying to upgrade from Fleet 0.3.5 to 0.3.7 (going from Rancher 2.5.8 which uses the former to Rancher 2.6.2 which uses the latter). I also ensured I'm using a newer RKE2 for Rancher 2.6 as well (v1.21.6+rke2r1).  

However, I'm hitting an issue when Fleet tries to do a `git ls-remote` to check for newer commits where I was not running into this on 0.3.5:
![Screenshot 2021-11-17 at 16-49-44 Rancher](https://user-images.githubusercontent.com/5779804/142288449-38151548-0112-4848-94c4-e70f1f35b2bf.png)

All of my repos are using a `caBundle` in the GitRepo spec and https for the protocol on the repo since we cannot use ssh.

I haven't had luck at pinpointing the exact issue, but it looks like the fleet-agent Pods for 0.3.7 no longer have `fleet-agent-token-XXXX` unlike in 0.3.5:

from `kubectl describe` on a fleet-agent 0.3.5 Pod:
```
Volumes:
  fleet-agent-token-qg49k:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  fleet-agent-token-qg49k
    Optional:    false 
```

Same but on 0.3.7:
```
Volumes:
  kube-api-access-p9fnw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
```

**Comment by weyfonk** [comment]
See also #2824 (fixed).
