### ISSUE TITLE
Enhance naming conventions documentation

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#624]
- CRDs should be documented with their _short_ and _full_ names (e.g. `GitRepo` and `gitrepos.fleet.cattle.io`)
  - it can be easy to mistake `Cluster` for another `Cluster` CRD not in the same API scheme 
- How are names generated for BundleDeployments?
  - we should consider documenting how these object names are generated (e.g. `<user>-<date>-<random-hash>` would be example format we should expose)
- What is reserved?
  - we should mention that `fleet-agent` deployments are reserved in `cattle-fleet-system` for example
  - perhaps, having a table for namespaces and their corresponding deployments, secrets, etc. would be important
  - we want to help users prevent collisions 

The two examples above are important, but we should keep track of naming conventions for anything along the way.

**Comment by StrongMonkey** [comment]
To summurize what nick has said, we can do the following:
1. For CRD terms like clusters and gitrepos, we need to put reference to full crd name. For example, clusters refer to `clusters.fleet.cattle.io`, gitrepos refer to `gitrepo.fleet.cattle.io`. My suggestion is that we keep a list of these full crd names and in every page where the term is introduced in the first place, attach the link too.(@jtravee this is really up to you).This might be easier in the future where we add api reference doc, as we can just put api reference link.
2. For naming conversion:
- Bundle which is created from gitrepo follows the pattern `$gitrepoName-$path` in the same workspace/namespace where gitrepo is created, where $path is the path directory in git repository that contains the bundle(fleet.yaml).
- BundleDeployment which is created from bundle follows the pattern `$bundleName-$clusterName` in namespace `clusters-$workspace-$cluster-$generateHash`, where $clusterName is the cluster it is going to be deployed to.

> Note: if name exceeds k8s limits(63 characters) it will be automatically hashed and a hashkey will be appended to the end.
3. The name `fleet-agent-$clusterName` is reserved as it is used to manage fleet-agent itself in a bundle.
