### ISSUE TITLE
Showcase an example of nested GitRepo usage

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#625]
This example could also contain advanced usage combining the `dependsOn` feature (i.e. bundles waiting for other bundles to be `Active` before launching). The payload can be trivial, but perhaps, having a diagram showcasing nested GitRepo CRs with `dependsOn` functionality could be a great way to illustrate Fleet's benefits for cascading bundle delivery.

**Comment by StrongMonkey** [comment]
@nickgerace @jtravee I am not sure this needs to be addressed in docs. It is related to manage fleet with fleet(nested rancher/fleet installation) and we don't official support that.

**Comment by nickgerace** [comment]
We should probably make a mention of it to the advanced section still. It's a real thing users do. However, we should indicate that it is not "officially support yet" since I could see it being covered in the future.

**Comment by jtravee** [comment]
Leaving open for potential future support.

**Comment by ngoeddel-openi** [comment]
At the moment we are deploying `GitRepo` resources using a master `GitRepo`.
It's all good until the deployed `GitRepo`s are in the ready state. But if one of these `GitRepo` is not ready for a certain amount of time, all of them will be redeployed and with them all the applications which are already running.

We tried different things to avoid that behavior but they did not work:
- Set `helm.timeoutSeconds` to 315360000 seconds (10 years)
- Set `metadata.labels.fleet.cattle.io/managed="true"` on every deployed `GitRepo` like mentioned here: https://fleet.rancher.io/ref-configuration#labels
- Setting `immutable=true` on every GitRepo.
- Pausing the master `GitRepo` after all GitRepos are deployed correctly so they can do their thing

In every case after a certain time it all starts again from the beginning.

So after seeing this ticket and the point [Nested GitRepo CRs](https://fleet.rancher.io/troubleshooting#nested-gitrepo-crs) in the documentation it seems this is really not possible. Or do you have an idea for a workaround? We really want to install a pure Git based deployment with nested `GitRepo`s and other dependencies. Is there really no hidden option or flag we can convince Fleet to not completely redeploy every `GitRepo` if just one is not in a ready state for a while?

**Comment by manno** [comment]
Removed the milestone. We're currently not planning to work on it.

> Managing Fleet within Fleet (nested GitRepo usage) is not currently supported. We will update the documentation if support becomes available.

**Comment by manno** [comment]
Fleet 0.7 will add an option to fleet.yaml to ignore conditions: https://github.com/rancher/fleet/pull/1482
