### ISSUE TITLE
Add general troubleshooting section for Fleet in the Rancher UI

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#626]
Examples:
- read logs from the `fleet-controller` deployment pod in the local cluster for the vast majority of issue solving
- indicate where the error logs for `GitRepos` and `Bundles` are coming from (i.e. are they from X pod in Y namespace? What should I do when those error logs appear?)
- if `kustomize` logs a failure with a `BundleDeployment`, where does that log come from?
- error propagation: do we tidy up `kubectl` output or leave it raw?
- how do concatenated errors work and how do I look at them individually? (e.g. there are multiple views of the same thing when you view errors for Bundles, BundleDeployments, and GitRepos. We should clarify their origins and who propagates them)

**Comment by StrongMonkey** [comment]
We can add this in troubleshooting section like this(I am thinking that it can be done in Q&A section)

**How do I fetch log from fleet-controller for troubleshooting**

Run this command in local management cluster where fleet-controler is deployed
```
$ kubectl logs -f $fleet-controller-pod-name -n cattle-fleet-system
```

 **How do I get log from fleet-agent?**

Go to each downstream cluster and run(for local cluster, 

```
# Downstream cluster
$ kubectl logs -f $fleet-agent-pod-name -n cattle-fleet-system
# Local cluster
$ kubectl logs -f $fleet-agent-pod-name -n cattle-local-fleet-system
```

**How do I get detail error logs from `GitRepos` and `Bundles`?**

Normally error should show up in UI, but if there is not enough information, user can select it, click on `View Yaml` and check `status.conditions`. It should have detail error message recorded there. Also checking fleet-controller for syncing error would also help. If something is wronge when deploying the actually bundle, check `fleet-agent` log in downstream cluster.

** How do I check chart rendering error like `kustomize`?**

Check fleet-controller logs as well as fleet-agent log.

**How do I check errors related to watching/checking out gitRepo or download Helm repo in fleet.yaml?**

Check gitjob-controller logs:
```
$ kubectl logs -f $gitjob-pod-name -n cattle-fleet-system
```

Check git checkout job pod(revise my word, not sure how to say pods created by k8s job) logs in local management cluster. These pods usually have images `rancher/tekton-utils` with gitRepo name as prefix.
```
$ kubectl logs -f $gitRepoName-pod-name -n cattle-fleet-system
```


Not sure about kubectl tidy that nick is refering to, but if it is about managedfields, it should be resolved with kubectl 1.21. @nickgerace are you also talking about the same thing?
