### ISSUE TITLE
Showcase the lifecycle of a bundle (via GitRepo CR) from creation to deployment (and updates upon new commits)

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#627]
We should answer:
- how does a connection happen from token creation to downstream agent bundle deployment?
- what happens when a new commit is pushed? how does Fleet see that change and how does that affect the bundle?
- what are the pods that the bundle information is passed through to the eventual target?

This can likely be easier to manage if we base this off of the [multi-cluster/helm](https://github.com/rancher/fleet-examples/tree/master/multi-cluster/helm) example and use it as the example payload.

**Comment by StrongMonkey** [comment]
@jtravee Here is the lifecycle of the a bundle and you can modify word. Let's take [multi-cluster/helm](https://github.com/rancher/fleet-examples/tree/master/multi-cluster/helm) as an example.
1. User creates a GitRepo(gitrepos.fleet.cattle.io) that points to https://github.com/rancher/fleet-examples/tree/master/multi-cluster/helm.
2. Gitjob controller syncs changes from gitRepo, detect changes from poll/webhook, and for every commit change, it creates a job that clone the git repository, read content(fleet.yaml and other manifests) from it and create fleet bundle(bundles.fleet.cattle.io)
3. Fleet-controller syncs changes from bundle, and according to the targets, it creates bundledeployment(bundledeployment.fleet.cattle.io) resources, which is a combination of bundle + target clusters.
4. Fleet-agent pulls bundledeployment from fleet controlplane, deploy real application/configuration as a helm chart from bundledeployment into downstream clusters.
5. Fleet-agent monitors the application bundle, report status back to bundledeployment -> bundle -> gitRepo -> cluster.
