### ISSUE TITLE
Add all known Bundle, GitRepo, and BundleDeployment states to docs with descriptions

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#629]
We should also include troubleshooting for associated states (e.g. "what should I do if I see this state? Wait and go make coffee? Re-deploy with a field changed?")

**Comment by StrongMonkey** [comment]
@jtravee I think it will be great if we add these following tips to thoubleshooting sections regarding to states:

> What happen if my GitRepo/Bundle is in modified state?

Modified means there is a mismatch bewteen the actual state and the desired state(source of truth) which lives in git repository. Check https://fleet.rancher.io/bundle-diffs/ for more information. You can also force update gitrepo to perform a manual resync. Select gitrepo -> Force Update

> What if cluster is unavailable or in WaitCheckIn state?

Select cluster -> Click Force Update. This will reimport the cluster and restart registration process.
