### ISSUE TITLE
app deployments do not work -- fleet upgrade did not complete with upgrade of rancher from 2.5.x to 2.6.2

### ISSUE THREAD

**Issue by sw34** [rancher/fleet#643]
In troubleshooting why a gitrepo would not deploy new application I found that the "local" rancher cluster has some errors in the fleet upgrade

![image](https://user-images.githubusercontent.com/49248567/143051171-8707b0f5-b866-4644-915b-0d2e2d465608.png)

I tried to "upgrade"  cattle-fleet-system/fleet to see if it would finish but the following error comes up:

```timeout trying to get secret for service account: cattle-system/pod-impersonation-helm-op-xx25b```

I get that same error if I try deleting "fleet-system/fleet-agent"

**Comment by Quving** [comment]
I've got the same problem here! :)

**Comment by mimizone** [comment]
In my case on Rancher 2.6.8, I only see the fleet-agent-local app stuck in Pending-Upgrade.
The fleet-system namespace doesn't exist. Everything is cattle-XXX
the fleet-default and fleet-local namespaces are still there but without any workload.
Is it safe to delete both namespaces and the fleet-agent-local app?

**Comment by kkaempf** [comment]
too old
