### ISSUE TITLE
Clarify special purposes of `fleet-local` and `fleet-defaults` in Fleet in Rancher

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#654]
For example: clusters added to `fleet-local` manually will not be included in default target specifications.

Relevant issue: https://github.com/rancher/dashboard/issues/3826

**Comment by StrongMonkey** [comment]
@jtravee I am thinking adding the following in https://fleet.rancher.io/gitrepo-add/#proper-namespace

> By default rancher will create two fleetworkspaces `fleet-default` and `fleet-local`. `fleet-default` will contain all the downstream clusters that are already registered through rancher. `fleet-local` will contain local cluster by default. User is able to create new workspaces and move clusters across workspaces.

**Comment by nickgerace** [comment]
It may also be a good idea to mention that clusters can be moved _out_ of either workspace, but we only recommend the local cluster living in `fleet-local`. Users may want to include the local cluster in the GitRepo payload for configuration use cases (no active deployments or payloads, but things like ConfigMaps and Secrets).

**Comment by StrongMonkey** [comment]
haha thanks @nickgerace
