### ISSUE TITLE
How to add ConfigMap when HELM chart is depending on it

### ISSUE THREAD

**Issue by elmariofredo** [rancher/fleet#672]
My usecase is to add configmap to ingress-nginx helm chart where helm chart pods directly depend on this configmap. When I add this configmap as static resource alongside fleet.yaml, it is present in Bundle, but is not deployed as it seems that agent is processing helm chart first and waiting for successful deployment and then it is deploying other resources. Due to dependency helm chart will never finish deployment. I have also tried add resource as overlay with same result.

Is there any way to set static resources priority over helm chart? I have resolve it by creating separate GitRepo with ConfigMap and set ingress-nginx repo to depend on this GitRepo then it is working but it is bit cumbersome.

**Comment by ron1** [comment]
You can try using a tool like kyverno to generate or clone resources like ConfigMaps or Secrets into the namespace on namespace creation. Or you could try using kustomize as a helm post-renderer to create the resources.

**Comment by elmariofredo** [comment]
> You can try using a tool like kyverno to generate or clone resources like ConfigMaps or Secrets into the namespace on namespace creation. Or you could try using kustomize as a helm post-renderer to create the resources.

Yes 🎉 that worked! All I had to do was using kuztomize post render as described here https://github.com/rancher/fleet-examples/blob/master/single-cluster/helm-kustomize/overlays/dev/kustomization.yaml but with `resources:` instead of `patches:`.

Thanks for the hint, but it might be useful for others to add this also to examples as adding resource on which helm chart depends might be quite common. Let me know and I can send PR to fleet-examples repo.
