### ISSUE TITLE
Bundle is not deleted when it is removed from a git repo

### ISSUE THREAD

**Issue by bashofmann** [rancher/fleet#676]
When a bundle is removed from a Git Repo, it is not deleted from fleet and the resources remain in the clusters.

# Steps to reproduce

* Create a git repo with two bundles (example: https://github.com/bashofmann/fleet-testing)
* Add it as a Git Repo to fleet
* Wait until both bundles and the resources have been deployed successfully
* Remove one of the bundles from git

# Expected behaviour

The deleted bundled is removed from fleet and the resources are removed from the cluster.

# Actual behaviour

The git repo in fleet is on the correct commit hash. But the bundle remains and the resources in the cluster remain.

# Environment

Rancher 2.6.3-rc1
Fleet 0.3.8-rc1

There are no errors in the fleet-controller or tekton-utils job logs.

Logs of the fleet container in the tekton-utils job that was triggered because of the removal:

```
  |  
-- | --
Wed, Dec 8 2021 4:39:26 pm | KUBERNETES_SERVICE_PORT_HTTPS=443
Wed, Dec 8 2021 4:39:26 pm | KUBERNETES_SERVICE_PORT=443
Wed, Dec 8 2021 4:39:26 pm | HOSTNAME=abc-755a3-ldqkq
Wed, Dec 8 2021 4:39:26 pm | COMMIT=98d86b704a9f79bf7da3cbbc6eeaeb718023172d
Wed, Dec 8 2021 4:39:26 pm | PWD=/workspace/source
Wed, Dec 8 2021 4:39:26 pm | EVENT_TYPE=
Wed, Dec 8 2021 4:39:26 pm | HOME=/home/fleet-apply
Wed, Dec 8 2021 4:39:26 pm | KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
Wed, Dec 8 2021 4:39:26 pm | ARCH=amd64
Wed, Dec 8 2021 4:39:26 pm | SHLVL=1
Wed, Dec 8 2021 4:39:26 pm | KUBERNETES_PORT_443_TCP_PROTO=tcp
Wed, Dec 8 2021 4:39:26 pm | KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
Wed, Dec 8 2021 4:39:26 pm | KUBERNETES_SERVICE_HOST=10.43.0.1
Wed, Dec 8 2021 4:39:26 pm | KUBERNETES_PORT=tcp://10.43.0.1:443
Wed, Dec 8 2021 4:39:26 pm | KUBERNETES_PORT_443_TCP_PORT=443
Wed, Dec 8 2021 4:39:26 pm | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Wed, Dec 8 2021 4:39:26 pm | _=/usr/bin/env
Wed, Dec 8 2021 4:39:26 pm | time="2021-12-08T15:39:26Z" level=info msg="updated: fleet-default/abc\n"
Wed, Dec 8 2021 4:39:26 pm | time="2021-12-08T15:39:26Z" level=info msg="updated: fleet-default/abc-hello-world-with-overlay\n"
```

The deleted `abc-ingress-cluster-labels` bundle remains in fleet and the resources remain in the cluster.

SURE-3826

**Comment by StrongMonkey** [comment]
By default we don't purge bundles that no longer exists in git repo but I understand that's an valid usecase. Maybe we need to add `prune: true` so it can clean up bundles that are already deleted.

**Comment by shailesh83** [comment]
**Case a)** To extend the use-case, If you add "single-file" like README.md on same GitRepo , you will see the Fleet will show that it has cleaned up all deployment, But when you actually look at Node of a Cluster where it was running, It still shows pod running and nothing changed.
**Case b)** Now delete the README.md and it shows below warning :
"time="2021-12-08T13:58:27Z" level=warning msg=".: no resources found to deploy"
time="2021-12-08T13:58:27Z" level=fatal msg="no resource found at the following paths to deploy: [.]"

But all the **resources** under fleet - deployment config remain active and running , this is weird as message says no resource found ?

**Comment by MKlimuszka** [comment]
SURE-4492
SURE-4516 
Confirm once this ticket is complete.

**Comment by aiyengar2** [comment]
SURE-3826
Confirm once this ticket is complete.

**Comment by izaac** [comment]
Rancher version: `v2.6.6`

Reproduced following the steps to reproduce in the issue description.

**Comment by izaac** [comment]
I am still getting fleet `v0.3.9` on Rancher `v2.6-head` and `v2.6.7-rc1`
Do we still have to update the min max chart version?

**Comment by prachidamle** [comment]
Yes, is it possible to test by updating fleet in "Installed Apps", to version: "v0.3.10-rc1"

I will put the PR to update Fleet version in rancher and the next Rancher rc should point to correct version; in the meantime you can test by updating the version.

**Comment by prachidamle** [comment]
New Fleet RC version v0.3.10-rc2 is out and should be tested with a new Rancher RC

**Comment by izaac** [comment]
Rancher `v2.6-head` `ed25172` (07/18/2022)
`fleet:v0.3.10-rc2`

I used https repository URL only as SSH is [blocked](https://github.com/rancher/rancher/issues/38242). 
Validation can be done with https only.


I validated bundle is removed when using a single bundle path.
- Removed the bundle from the git repository.
- GitRepo updates to the latest commit.
- GitRepo goes into a failing state as the path no longer exist (Expected)
- Bundle is removed after editing the GitRepo configured path to a valid one.

Validation done on a GitRepo path with multiple bundles.
- One of the Bundles is removed from the git repository (git rm -r <bundle folder>; git commit -m ""; git push)
- The GitRepo updates to the latest commit.
- The bundle removed from the git repository is also removed from the installed Bundles in Rancher.

Validation done with a Bundle that had a long name
- Create a new bundle in the git repository where the folder has a long name  (longer than 63 characters)
  - ex. `helm-superlongname-longerlongerlongerlongerlongerlonger`
- The bundle with a long name is truncated with a randomly generated suffix in Rancher
  -  ex. `t1-multi-cluster-helm-superlongname-longerlongerlongerlon-573eb`
- The long name bundle is removed from the git repository (git rm -r <bundle folder>; git commit -m ""; git push)
- The GitRepo updates to the latest commit.
- The bundle with the truncated long name is removed from the list of bundles installed in Rancher
