### ISSUE TITLE
Agent Registration - not able to connect to manager cluster behind Rancher API proxy  

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/fleet#68]
Steps:
- run Rancher:master-head
- provision 2 clusters 
- cluster-1 runs the Fleet manager: https://fleet.rancher.io/multi-cluster-install/
- cluster-2 runs the Fleet agent: https://fleet.rancher.io/agent-initiated/

Result:
- see the following errors in the logs of the agent pods in cluster-2
`time="2020-09-02T22:28:06Z" level=error msg="Failed to register agent: looking up secret fleet-system/fleet-agent-bootstrap: the server has asked for the client to provide credentials (post clusterregistrations.meta.k8s.io)"`

More info:
 It turns out I cannot use the Rancher’s Endpoint for the cluster, instead I need to use the authorized cluster endpoint and its corresponding CA cert:
```
https://<fqdn>/k8s/clusters/c-vx96p - NO
https://<ip>:6443 - YES
```

**Comment by izaac** [comment]
Rancher version: `master-head (09/02/2020)` _ef11fe3b0_

```
kubectl -n fleet-system logs -l app=fleet-agent
time="2020-09-03T18:33:03Z" level=error msg="Failed to register agent: looking up secret fleet-system/fleet-agent-bootstrap: Post \"https://<host>/k8s/clusters/c-vkp5v/apis/fleet.cattle.io/v1alpha1/namespaces/clusters/clusterregistrations\": x509: certificate signed by unknown authority"
time="2020-09-03T18:34:03Z" level=error msg="Failed to register agent: looking up secret fleet-system/fleet-agent-bootstrap: Post \"https://<host>/k8s/clusters/c-vkp5v/apis/fleet.cattle.io/v1alpha1/namespaces/clusters/clusterregistrations\": x509: certificate signed by unknown authority
```

**Comment by izaac** [comment]
This is still happening with Rancher `master-c08b0bb17fee40c76468020b352e2b146756aa4b-head` cc @jiaqiluo

**Comment by StrongMonkey** [comment]
Won't fix this. User are expected to use api_url:6443 instead of rancher_url/k8s/clusters/id to register agent, since the token created by fleet has has no permission to authenticate with rancher server URL.

**Comment by maggieliu** [comment]
closing this since it's a won't fix.

**Comment by johnjcool** [comment]
would be nice if it works. 

`kubectl -n clusters get secret new-token -o 'jsonpath={.data.values}' | base64 -d > values.yaml` exports rancher api endpoint instead of kubernetes api endpoint. 

creating an rancher api token could be an option.
