### ISSUE TITLE
General fleet UI enhancement

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/fleet#681]
- We need to better display the status of a bundle. A lot of useful information has been stored on bundle but only a minimal portion of it is shown on UI. We need to figure out a better way to extract information from bundle CR and display it from UI.
- For bundle/gitrepo, we can show human-readable timestamp from the last time it was sync/deployed
- We need to add viewApi action to each fleet resource
- We can show resource dependency gragh in fleet UI

**Comment by kkaempf** [comment]
Transferred to rancher/dashboard#7823
