### ISSUE TITLE
[SURE-2653] fleet-agent cannot accept the certificate signed by a local CA in Rancher single-install setup

### ISSUE THREAD

**Issue by kazh000** [rancher/fleet#687]
I have installed Rancher single-install v2.6.2 using the certificate signed by a corporate CA. Also I have created a custom kubernetes cluster from Rancher using the option of rancher-agent "-e SSL_CERT_DIR". The cluster had been created but the fleet-agent of the custom cluster can't connect to Rancher:
`time="2021-12-16T10:09:40Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: Post \"https://[skiped]:8443/apis/fleet.cattle.io/v1alpha1/namespaces/fleet-default/clusterregistrations\": x509: certificate signed by unknown authority"`
![screen01](https://user-images.githubusercontent.com/20112118/146358778-3e99e063-aadd-4f4f-9933-7c6c70b22ec7.png)

**Comment by kkaempf** [comment]
SURE-2653

**Comment by raulcabello** [comment]
I can't reproduce this with `Rancher` 2.7.3 and `Fleet` 0.6.0. 
`fleet-agent` works as expected when using a custom CA. I can see the CA in the kubeconfig in the `fleet-agent` secret, and everything works as expected.

Make sure you follow the [Updating a Private CA certificate docs](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/update-rancher-certificate#updating-a-private-ca-certificate)
I was getting the `x509: certificate signed by unknown authority` error before Reconfiguring the Rancher deployment as described in the [docs](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/update-rancher-certificate#3b-update-the-helm-values-for-rancher)
