### ISSUE TITLE
TargetCustomizations -> Helm -> Version not taken in account

### ISSUE THREAD

**Issue by mkindalov** [rancher/fleet#699]
First, I like the idea behind fleet a lot. Good job so far!

Having the possibility to update the helm chart version for targeted cluster makes a lot of sense.
One use-case is to test the release upgrade on one cluster and then if this works ok to do the upgrade for all other clusters.

I can notice that  pkg/options/calculate.go takes a lots of parameters in consideration but not the "Version". 

If you think that this can work and this file is the only place that needs to be changed I can create a PR.

**Comment by carneiroskeeled** [comment]
Any update or alternative on this @mkindalov ? 🤔

It would be a really nice feature to have.
