### ISSUE TITLE
Support for setting a cluster registry 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/fleet#711]
Feature Request
Cluster-level registry, most likely to be a field in the `fleet.Cluster` object.

Usage
If the registry is set, all images will be pulled from the registry when a bundle is installed into the cluster. 

Related Issues:
https://github.com/rancher/rancher/issues/36281

Update 1:
It will be even better if we can configure the registry at the Bundle level, which will allow the system components ( i.e. the fleet-agent) and user's Bundles to use different registries.

**Comment by aiyengar2** [comment]
this is blocked by the same issue described in https://github.com/rancher/rancher/issues/35834#issuecomment-1033004363

**Comment by shurkanTwo** [comment]
We would also appriciate this addition very much.

**Comment by shurkanTwo** [comment]
Has there been any update so far?

**Comment by manno** [comment]
We are tracking this i nhttps://github.com/rancher/fleet/issues/948
I think it's the same issue, so I'm closing this one here.
