### ISSUE TITLE
EPIC: Managed Fleet Agents should support cluster-specific overrides

### ISSUE THREAD

**Issue by aiyengar2** [rancher/fleet#712]
As described in https://github.com/rancher/rancher/issues/35834#issuecomment-1033004363:

> the configuration of the managed Fleet agent is generated solely from the configuration of Fleet in the local cluster, as seen in the following code: https://github.com/rancher/fleet/blob/d3356b2f029a487236ef96864752a03972717ff9/pkg/controllers/manageagent/manageagent.go#L147-L151
> As a result, if you we were to support supplying agent tolerations here, it would be tolerations that are applied on a global level (e.g. you if you tolerated a taint in one cluster, you would also be tolerating that taint in all your clusters).

Fleet should support the ability to configure some options of managed Fleet agents on a cluster-specific level.

Some examples:
- Ability to set tolerations on a fleet agent: https://github.com/rancher/rancher/issues/35834
- Ability to set a cluster-specific registry: https://github.com/rancher/fleet/issues/711

**Comment by MKlimuszka** [comment]
We want this in 2.6.5

**Comment by aiyengar2** [comment]
Moving to Triage to ensure a milestone is added to the issue

**Comment by mattfarina** [comment]
This is related by different to #869. #869 is set by us (SUSE/Rancher) which this issue has to do with configuration set by the end user. They will be accessed with different settings.

**Comment by kkaempf** [comment]
closing for now for rancher/rancher#35834
