### ISSUE TITLE
rate limited gitjobs and bundle

### ISSUE THREAD

**Issue by mmclane** [rancher/fleet#721]
We have fleet managing our clusters and have started using imagescan to pick up new container versions and push those out automatically.  It's taken me a bit to reverse engineer this feature (the documentation is very light if you ask me) but I think I have figured some things out.  

Currently imagescan runs (once a minute) and identifies a new version.  We can see that it has identified the new version in Rancher.  It doesn't however always write that new version to github right away.  Sometimes it can take 5-10 minutes between when imagescan identifies the new version and when the pods get rolled out.  From my understanding this is because something is keeping imagescan from writing to github and then we also need to wait for fleet to run an update (default is 5m).  

What I noticed today is that I am getting a whole bunch of these "errors" in my fleet-controller logs.  I am guessing they are relavent.

```
time="2022-03-01T16:20:55Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:682559dbf9496c6e24d53b2dc5182519e59c4aaf]) 1.007998787s"
time="2022-03-01T16:20:57Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:41112036500a9095791775c74a4b4e19736a63ee]) 1.005525709s"
time="2022-03-01T16:21:03Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:41112036500a9095791775c74a4b4e19736a63ee]) 1.019539797s"
time="2022-03-01T16:21:03Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:682559dbf9496c6e24d53b2dc5182519e59c4aaf]) 1.013903984s"
time="2022-03-01T16:21:05Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:41112036500a9095791775c74a4b4e19736a63ee]) 1.001365362s"
time="2022-03-01T16:21:07Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:41112036500a9095791775c74a4b4e19736a63ee]) 1.0093039s"
time="2022-03-01T16:21:07Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:913163cbf43b76cd3323f081009b1e9f27c16339]) 1.000876569s"
time="2022-03-01T16:21:13Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:682559dbf9496c6e24d53b2dc5182519e59c4aaf]) 1.080280077s"
time="2022-03-01T16:21:15Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:682559dbf9496c6e24d53b2dc5182519e59c4aaf]) 1.013273527s"
time="2022-03-01T16:21:17Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:913163cbf43b76cd3323f081009b1e9f27c16339]) 1.009198779s"
time="2022-03-01T16:21:21Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:913163cbf43b76cd3323f081009b1e9f27c16339]) 1.005216911s"
time="2022-03-01T16:21:23Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:682559dbf9496c6e24d53b2dc5182519e59c4aaf]) 1.001977497s"
time="2022-03-01T16:21:25Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:913163cbf43b76cd3323f081009b1e9f27c16339]) 1.013316583s"
time="2022-03-01T16:21:27Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:41112036500a9095791775c74a4b4e19736a63ee]) 1.035538455s"
time="2022-03-01T16:21:29Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:41112036500a9095791775c74a4b4e19736a63ee]) 1.042925181s"
time="2022-03-01T16:21:31Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:913163cbf43b76cd3323f081009b1e9f27c16339]) 1.036878823s"
time="2022-03-01T16:21:34Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:913163cbf43b76cd3323f081009b1e9f27c16339]) 1.002652309s"
time="2022-03-01T16:23:03Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:89d7068a84a4c0db9680d3366e8da0ae93bc34e9]) 1.00166136s"
time="2022-03-01T16:23:19Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:682559dbf9496c6e24d53b2dc5182519e59c4aaf]) 1.071210448s"
time="2022-03-01T16:23:23Z" level=info msg="rate limited gitjobs(map[objectset.rio.cattle.io/hash:682559dbf9496c6e24d53b2dc5182519e59c4aaf]) 1.007082612s"
```

So my question is, what can I do about this?  The gitrepo is configured with creds so I believe it should be making authenticated requests.  I believe that means we should be able to make 1000 requests per hour or 80 per minute.   In my k8s cluster I have that repo configured three times pointed to different folders but since they are only running every 5 minutes that should keep me well below the 1000 requests limit.  

Am I missing something here?  Is there anything we can do to make this better?

**Comment by johnjcool** [comment]
we also see this error. and also a high amount of cpu usage in fleet-controller. 

how we can find out to which bundle the hash belongs?

**Comment by mmclane** [comment]
Nothing??

**Comment by mmclane** [comment]
So frustrating.  I have asked here and in slack and I just get no response.

**Comment by mmclane** [comment]
Well.. it seems that the only way I can even get someone to look at this is if we pay tens of thousands of dollars.

**Comment by johnjcool** [comment]
Or fork and start a spin of 😉

**Comment by moio** [comment]
As per https://github.com/rancher/fleet/issues/606#issuecomment-1476008054, several patches went into the latest fleet which did improve the situation for many users.

If anybody here is able to reproduce symptoms on the latest version, I am glad to take a deeper look.

Otherwise I am going to close this issue in a week - and be ready to take a look whenever a new one is opened.

Thanks for your understanding

**Comment by brooksphilip** [comment]
do you mean latest version as in 2.7.3? I am experiencing this in 2.7.1

**Comment by moio** [comment]
Most patches went into fleet 0.6.0, which means Rancher 2.7.2 - a few others went into the `master` branch which is still not in any Rancher released versions.

I am interested to see symptoms in a 0.6.0+ standalone fleet installation OR Rancher 2.7.2+

Please open a new issue! TIA
