### ISSUE TITLE
Force Update API

### ISSUE THREAD

**Issue by czterocyty** [rancher/fleet#722]
Hi,

On Rancher UI Dashboard there is a "Force Update" button.

Is there any other way to force sync in fleet in more command line mode - using some REST API of Kubernates or custom API of fleet subsystem? I couldn't find it in the documentation.

Regards,
Adam.

**Comment by superseb** [comment]
See https://github.com/rancher/fleet/blob/master/pkg/apis/fleet.cattle.io/v1alpha1/git.go#L71

Example (bash):

```
kubectl patch gitrepos.fleet.cattle.io -n your_namespace your_gitrepo -p '{"spec":{"forceSyncGeneration":'$(($(kubectl get gitrepos.fleet.cattle.io -n your_namespace your_gitrepo  -o jsonpath={.spec.forceSyncGeneration})+1))}}'' --type=merge
```
