### ISSUE TITLE
[SURE-4420] Empty bundle is created and deployed to target cluster

### ISSUE THREAD

**Issue by aDisplayName** [rancher/fleet#737]
Rancher 2.6.3

Here is the the folder structure of our gitrepo, which contains three different helm charts under folder lib:
* crd
* crd-sample
* ref
```
/
│  .gitignore
│  README.md
│
├─doc
│      notes.md
└─lib
    ├─crd
    │  └─helm
    │      │  Chart.yaml
    │      │  fleet.yaml
    │      │
    │      └─templates
    │              chart-crd.yml
    │
    ├─crd-sample
    │  └─helm
    │      │  Chart.yaml
    │      │  fleet.yaml
    │      │
    │      └─templates
    │              crd-sample.yaml
    │
    └─ref
        └─helm
            │  Chart.yaml
            │  fleet.yaml
            │
            └─templates
                    app.yaml
```

We've set-up a git repo using the name of "edge-app" with path set to "/lib', and here are the bundles created from the git repo:

![image](https://user-images.githubusercontent.com/19527258/162221606-49e48985-802d-46f3-8b64-7ea362260187.png)

We are not expecting the bundle of "edge-app-lib". And it is annoying that that bundle has littered almost every namespaces in  our downstream cluster:
![image](https://user-images.githubusercontent.com/19527258/162222716-d6b29a85-c36a-4678-99eb-dd1c1716e6d5.png)

It appears every time when a new namespace is created and a normal helm chart is deployed, the same "edge-app-lib" will be placed into that namespace as well.

How to avoid this happening?

SURE-4420

**Comment by aDisplayName** [comment]
By changing the setting of the paths of the git repo from single `/lib` to individual 
* `/lib/crd`
* `/lib/crd-sampel`
* `/lib/ref`

We are able to get rid of the empty bundle. It just that we need to maintain all the path entries every time the subfolders are changed.

**Comment by aDisplayName** [comment]
I believe we have found problem. During the pre-install-hook, we are copying all secret from default namespace to our target namespace, including all the secret with `type` set to `helm.sh/release.v1". Everytime once such secret is copied over to the target namespace, a new bundle is deployed into the same namespace. 

Please close this bug if it is the reason under the hood.

**Comment by manno** [comment]
I believe this is a valid bug, as fleet will always build a bundle for the "root": https://github.com/rancher/fleet/blob/master/modules/cli/apply/apply.go#L79-L86

Only happens for the top level dir, though.

**Comment by raulcabello** [comment]
I can reproduce this bug. Fleet creates an empty bundle for the root directory if it doesn't contain any resources or fleet.yaml. 
Moving to the backlog as I'm currently not working on it

**Comment by kkaempf** [comment]
Reopen for QA

**Comment by localleon** [comment]
We are facing the same issue in our clusters!

**Comment by olblak** [comment]
The fix is available in https://github.com/rancher/fleet/releases/tag/v0.7.0-AGENT-rc.1 but it appears we are still missing a QA template.

**Comment by raulcabello** [comment]
@rancher/qa
## Additionnal QA

### Problem
We were always creating a `Bundle` for the root path. However, it should not be created if there are no resources or `fleet.yaml` in the root path and all the subdirectories contains a `fleet.yaml`. 

### Solution
Add a check to create a Bundle for the root path just if any of the following conditions is true:

It contains a `fleet.yaml` in the root path
It has resources in the root path
It has resources in any subdirectory that doesn't contain a `fleet.yaml`

### Testing

Create a GitRepo for a folder structure that shouldn't create a Bundle for the root directory. Check conditions for this in the `Solution` section of this QA template.

For example https://github.com/raulcabello/fleet-test/tree/main/empty has the following structure:
```
/
│
└─grafana
    ├─fleet.yaml
```
Verify that there is no Bundle created for he root path. In the previous example just one Bundle should be created.

#### Automated Testing

Integration tests added
https://github.com/raulcabello/fleet/blob/8a24771ee2361d3400279e30ea60b6c65568b923/integrationtests/cli/apply/apply_test.go#L73

**Comment by olblak** [comment]
Thanks @raulcabello

**Comment by sbulage** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1| Test if two separate helm charts are placed in one directory, creates only helm deployment not the empty deployment which don't have fleet.yaml available in the directory.|

**Comment by sbulage** [comment]
Verified first two test cases QE Test Plan in above comment.
```
Rancher Version: 2.7.5-rc1
fleet version: 0.7.0-rc.2
```

**TEST RESULT**

Scenarios
|Scenario|Test Case| Result
|---|---|---|
|1| Test if two separate helm charts are placed in one directory, creates only helm deployment not the empty deployment which don't have fleet.yaml available in the directory.| :white_check_mark:|


**REPRO STEPS**

**Scenario 1**
1. Login as an admin user, add `GitRepo` described in next steps.
2. Navigated back to Rancher > Continuous Delivery.
3. Created a GitRepo using `https://github.com/sbulage/test-fleet` and path `/empty_bundle`
4. Navigate to the Cluster Management and Pods.
5. Select all namespaces from the drop-down menu.
6. Verified that both `nginx` and `grafana` app deployed on respective namespaces.
7. Verified that no empty deployement is created in the rancher.

**Comment by sbulage** [comment]
![Selection_005](https://github.com/rancher/fleet/assets/12134754/fe999122-5b3e-4421-a4ac-8f3287175f26)

**Comment by kkaempf** [comment]
See also SURE-6077
