### ISSUE TITLE
Docs: fleet.yaml reference, document "defaultNamespace" property in targetCustomizations

### ISSUE THREAD

**Issue by kodachimaru** [rancher/fleet#742]
Hi.

I was working on a Bundle and it's corresponding fleet.yaml
I was using the "defaultNamespace", as my Bundle contains ClusterRoles.

I needed a "targetCustomization" for a specific cluster where I needed to change the "defaultNamespace".

But, according to [the fleet.yaml reference](https://fleet.rancher.io/gitrepo-structure/#reference), "targetCustomizations" has the "namespace" option, but not the "defaultNamespace" one.

However, if you set "defaultNamespace" in the targetCustomization, it works as expected, so it's just a documentation error.

**Comment by MKlimuszka** [comment]
Please improve documentation, @prachidamle
