### ISSUE TITLE
fleet-agent has a conflict with current rancher-monitoring charts

### ISSUE THREAD

**Issue by w13915984028** [rancher/fleet#744]
Related issues:
https://github.com/rancher/charts/issues/1863
https://github.com/harvester/harvester/issues/2152

The rancher-monitoring chart, which is used by Harvester, is at https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-monitoring/100.1.0%2Bup19.0.3

When` install/upgrade`, the `admissionWebhooks.failurePolicy` value is set to: Ignore if patch.enabled is true, seems for skipping any potential patch failure
file:` templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml`

A `post-install/post-upgrade` hook is used to set back the value of admissionWebhooks.failurePolicy as per defined in values.yaml.
file: `templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml`.

When checking release status from HELM binary, it is `"Upgrade complete"`
```
./helm history rancher-monitoring --namespace cattle-monitoring-system
REVISION	UPDATED                 	STATUS    	CHART                              	APP VERSION	DESCRIPTION     
1       	Tue Apr 19 13:11:58 2022	superseded	rancher-monitoring-100.1.0+up19.0.3	0.50.0     	Install complete
2       	Tue Apr 19 13:14:59 2022	superseded	rancher-monitoring-100.1.0+up19.0.3	0.50.0     	Upgrade complete
3       	Tue Apr 19 13:21:52 2022	superseded	rancher-monitoring-100.1.0+up19.0.3	0.50.0     	Upgrade complete
4       	Tue Apr 19 14:59:02 2022	superseded	rancher-monitoring-100.1.0+up19.0.3	0.50.0     	Upgrade complete
5       	Tue Apr 19 21:00:46 2022	superseded	rancher-monitoring-100.1.0+up19.0.3	0.50.0     	Upgrade complete
6       	Tue Apr 19 21:01:30 2022	superseded	rancher-monitoring-100.1.0+up19.0.3	0.50.0     	Upgrade complete
7       	Tue Apr 19 21:11:09 2022	superseded	rancher-monitoring-100.1.0+up19.0.3	0.50.0     	Upgrade complete

8       	Wed Apr 20 08:38:08 2022	superseded	rancher-monitoring-100.1.0+up19.0.3	0.50.0     	Upgrade complete
9       	Wed Apr 20 08:47:49 2022	deployed  	rancher-monitoring-100.1.0+up19.0.3	0.50.0     	Upgrade complete
```

When checking bundledeployment, it says "modified"
![image](https://user-images.githubusercontent.com/31133476/164216636-63e78d66-b339-4ee7-b9be-3a9616460cc5.png)

The fleet-agent will always treat it as "modified" and retry forever, it is a meaningless deadloop.

For any charts managed by fleet-agent via embedded HELM, as long as a post-instll/post-upgrade hook has a "writing" operation.

I am not sure, https://github.com/rancher/charts/issues/1863 can be solved from rancher charts itself.

The user may still use `post-upgrade/post-intall hook` to do "writing" in rare cases, https://github.com/harvester/harvester/issues/2088 also does.

**Meanwhile, for fleet-agent, is it possible to check a bundledeployment status with considering the potential post-* hook writing ? **  fleet-agent is on top of HELM, but has more strict checking than HELM.

**Comment by w13915984028** [comment]
https://github.com/helm/helm/issues/7891  related?

**Comment by w13915984028** [comment]
It looks https://github.com/harvester/harvester-installer/pull/274 may solve this issue.

**Comment by R-Studio** [comment]
@w13915984028 how did you even install "rancher-monitoring" with fleet?

All I get when I try to install "rancher-monitoring" is an error in the fleet bundle: 
`Template: rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml:116:13: executing "rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml" at <include "call-nested" (list . "grafana" "grafana.fullname")>: error calling include: template: rancher-monitoring/templates/_helpers.tpl:21:4: executing "call-nested" at <include $template (dict "Chart" (dict "Name" (last $subchart)) "Values" $values "Release" $dot.Release "Capabilities" $dot.Capabilities)>: error calling include: template: no template "grafana.fullname" associated with template "gotpl"`

More information's: https://github.com/rancher/fleet/issues/399#issuecomment-1116082023

**Comment by w13915984028** [comment]
@R-Studio The related versions:
images:
docker.io/rancher/fleet-agent:v0.3.9
docker.io/rancher/fleet:v0.3.9   (fleet-controller)

charts:
/charts/rancher-monitoring-crd-100.1.0+up19.0.3.tgz
/charts/rancher-monitoring-100.1.0+up19.0.3.tgz

They are integrted in Harvester:
https://github.com/harvester/harvester/releases
The latest ISO:
https://releases.rancher.com/harvester/v1.0.2-rc1/harvester-v1.0.2-rc1-amd64.iso

The installation guide (KVM/vmware based VM is fine to hold a sinlge-node cluster) :
https://docs.harvesterhci.io/v1.0/install/iso-install/

**Comment by R-Studio** [comment]
@w13915984028 Thanks for your help! 👍🏽 
In the meantime I was able to deploy "rancher-monitoring". 

I run in three errors:
- **Fleet Bug:** The [error above](https://github.com/rancher/fleet/issues/744#issuecomment-1116226064) occurs because Fleet has a **[bug with the capability check](https://github.com/rancher/fleet/issues/399)**. This bug only occurs if I disable Grafana in the Helm values. -> So as a workaround I simply enabled Grafana. 🙆🏽‍♂️ 
- **Internal error occurred with the webhooks:** Sometimes the `validatingwebhookconfiguration` and `mutatingwebhookconfiguration` makes some problems -> so I removed this and redeploy the Helm release.
- **Always Modified:** To prevent this I added some diffs in my `fleet.yaml`


**Remove webhook `validatingwebhookconfiguration` and `mutatingwebhookconfiguration` :**
```
kubectl get validatingwebhookconfiguration -A
NAME                           WEBHOOKS   AGE
rancher-monitoring-admission   1          52d

kubectl delete validatingwebhookconfiguration/rancher-monitoring-admission -A
validatingwebhookconfiguration.admissionregistration.k8s.io "rancher-monitoring-admission" deleted

kubectl get mutatingwebhookconfiguration -A
NAME                           WEBHOOKS   AGE
rancher-monitoring-admission   1          52d

kubectl delete mutatingwebhookconfiguration/rancher-monitoring-admission -A
mutatingwebhookconfiguration.admissionregistration.k8s.io "rancher-monitoring-admission" deleted
```
-> More informations: https://github.com/prometheus-community/helm-charts/issues/108



**Always modified: add the following diffs in your `fleet.yaml`:**
```yaml
diff:
  comparePatches:
    - apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      name: rancher-monitoring-admission
      operations:
        - {"op":"remove", "path":"/webhooks"}
    - apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: rancher-monitoring-admission
      operations:
        - {"op":"remove", "path":"/webhooks"}
```


Now always works as expected. 😃

**Comment by w13915984028** [comment]
@R-Studio Thanks for your solution.

BTW, is it possible that fleet-agent has an option/ by default  to enhance the consistency check, which adopts all those potential "writing" operations in the post-install/post-upgrade hook.

Now, for those post-upgrade/post-install hooks, which have "writing" operations, need to add things to "diff".

**Comment by R-Studio** [comment]
@w13915984028 I am not sure. I am Fleet newby (I use Fleet since this week) 😆 

I can recommend this [Fleet Guide](https://rancher.support/training/fleet/fleet-training-guide/#common-issues).

**Comment by manno** [comment]
If I understand correctly the bundle diff resolved the issue. Can we close this? Thanks :)

**Comment by w13915984028** [comment]
@manno Yes, the `diff` can solve such `modified` issue, we can close this issue, thanks.
