### ISSUE TITLE
valuesFiles not working in fleet.yaml on v0.3.5

### ISSUE THREAD

**Issue by waterss** [rancher/fleet#753]
On Fleet v0.3.5, I'm using helm.valuesFiles in the fleey.yaml and the additional values are not being picked up from the .yaml file. I've attempted using the following values:

filename.yaml
./filename.yaml
otherfolder/filename.yaml
./otherfolder/filename.yaml

Is the solution to upgrade to v0.3.6+? The v0.3.5 release notes mention the addition of the valuesFiles attribute in the fleet.yaml file

**Comment by waterss** [comment]
Note: valuesFiles only works when using the fleet.yaml file helm.yaml is set. My bad on this one.

**Comment by bawafack-paradocs** [comment]
@waterss  please could you explain what you did exactly? I'm facing the same problem.
What is the "helm.yaml" file that mentioned? What should I put into it?
