### ISSUE TITLE
Wait Check-In - [Error] missing apiServerURL in fleet config for cluster auto registration

### ISSUE THREAD

**Issue by aleksey005** [rancher/fleet#787]
Rancher v2.6.5 - clear install (not update)
Custom
Baremetal

Imported | False | 18 hours ago | [Error] missing apiServerURL in fleet config for cluster auto registration
-- | -- | -- | --
Processed | True | 18 hours ago | —
Ready | False | 18 hours ago | WaitApplied(1) [Bundle fleet-agent-c-j78sh]
Reconciled | True | 18 hours ago | —
![Снимок экрана_2022-06-01_18-06-05](https://user-images.githubusercontent.com/6145279/171437441-f25f4c97-ed01-4c8c-84f1-b81999a9a1fc.png)

**Comment by moio** [comment]
Are you using the [agent initiated registration](https://fleet.rancher.io/cluster-overview/#agent-initiated-registration) workflow by any chance?

If so, #789 might be related.

**Comment by MKlimuszka** [comment]
@aleksey005, if you can provide more step by step instructions to reproduce, that would be very helpful.

**Comment by aleksey005** [comment]
> @aleksey005, if you can provide more step by step instructions to reproduce, that would be very helpful. 

1. Install new cluster v2.6.5
2. Open - Global Aps - Continuous Delivery
3. Open Cluster and view error - Wait Check-In (Missing apiServerURL in fleet config for cluster auto registration)
4. Search pod fleet-agent and fleet controller in new cluster - not exist.

Maybe it's not the exact sequence, but I can't seem to get the fleet.

**Comment by kkaempf** [comment]
closing
