### ISSUE TITLE
Agent cluster is not appearing in the Fleet section but is listed in the Cluster explorer

### ISSUE THREAD

**Issue by izaac** [rancher/fleet#80]
Clusters (besides local) are shown properly in the Cluster Explorer:

https://<rancher_server>/dashboard/c/c-xxxxx/explorer/fleet.cattle.io.cluster

![Screen Shot 2020-09-11 at 7 03 58 PM](https://user-images.githubusercontent.com/27659/92984848-46cc7c00-f462-11ea-88a4-9be93cd906a4.png)

This Agent cluster is not shown in the Fleet "explorer"

_* Check the URL is different in the fleet explorer_

https://<rancher_server>/dashboard/c/c-xxxxx/**fleet**/fleet.cattle.io.cluster

![Screen Shot 2020-09-11 at 7 09 38 PM](https://user-images.githubusercontent.com/27659/92984858-5b107900-f462-11ea-9696-5ef1c1ad0235.png)

Rancher `master-c08b0bb17fee40c76468020b352e2b146756aa4b-head` Single install

- 2 DO clusters One Manager and One Agent

```
kubectl -n clusters get clusters.fleet.cattle.io
NAME                   BUNDLES-READY   NODES-READY   SAMPLE-NODE                  LAST-SEEN              STATUS
cluster-cd5078be17d0   1/1             1/1           izaac-linode-single2-all-1   2020-09-12T02:02:48Z
```

**Comment by StrongMonkey** [comment]
@izaac I don't know if this is still a valid test case for now. As it is today in master, the fleet manager will always get installed on local cluster, and the cluster you provisioned on rancher will automatically join as the fleet downstream cluster. I am seeing all the clusters on both case. Can you test this use case? I don't think it makes much sense to initilize another manager on a separate cluster.

**Comment by izaac** [comment]
Rancher version `master-head (09/16/2020)` _59936f7_ k8s HA

I see the clusters listed in the Cluster Explorer and in Fleet CRD UI.

### Fleet View

<img width="1882" alt="Screen Shot 2020-09-16 at 2 23 51 PM" src="https://user-images.githubusercontent.com/27659/93393994-53691f80-f828-11ea-9015-20a2f1dac8c4.png">

### Cluster Explorer view

<img width="1904" alt="Screen Shot 2020-09-16 at 2 24 06 PM" src="https://user-images.githubusercontent.com/27659/93394054-6bd93a00-f828-11ea-9492-06057c951b83.png">
