### ISSUE TITLE
Switch Container Image to Suse BCI

### ISSUE THREAD

**Issue by manno** [rancher/fleet#802]
We want supported images in all containers. 

The currently used alpine image 3.15.0 is outdated. 3.15.x no longer receives bug fixes, however security fixes are still available. The latest 3.15.x release is 3.15.4, which we are not using.

There is a significant difference in image sizes between BCI and Alpine. Since fleet is mostly go binaries, we could switch the controllers to `scratch` and get rid of any maintenance surface. 

However, I'm told the fleet-agent image is used for debugging and has debugging tools (git, ssh) installed for that purpose. A possibility could be to release a separate debug image, which could be activated by `kubectl set image ...`, or patching in a debug container (very easy command line, e.g.`kubectl patch deployments -n kube-system coredns --type=json -p '[{"op": "add", "path": "/spec/template/spec/containers/-", "value": {"name": "tools", "image": "giantswarm/tiny-tools", "command": ["sleep","9000"]}}]'`).

- [x] Switch image in rancher/fleet https://github.com/rancher/fleet/pull/812
- [x] Switch image in https://github.com/rancher/build-tekton https://github.com/rancher/build-tekton/pull/7
- [x] Bump image in https://github.com/rancher/gitjob https://github.com/rancher/gitjob/pull/52
- [x] gitjob uses BCI
- [x] [Update fleet components](https://github.com/rancher/fleet/blob/master/DEVELOPING.md#updating-fleet-components) so BCI is used for gitjob's tekton job.

**Comment by mattfarina** [comment]
Note, we should also update Dapper in the fleet repo to use the BCI

**Comment by thardeck** [comment]
Fixed by #916
