### ISSUE TITLE
Run controller deployments as non-root with read-only filesystem

### ISSUE THREAD

**Issue by manno** [rancher/fleet#845]
Add security contexts to runAsNonRoot and switch the filesystem to read-only.

The UIDs have to match the user/group that were created in the the container
images.

Example:
https://github.com/epinio/helm-charts/blob/bd2308024c8d9218fe3bf0fd6a71814e52102f69/chart/epinio/templates/server.yaml#L308-L314

TODO:

- [ ] check for filesystem writes (ssh known_hosts?)
- [ ] test on public providers (gke/aks/eks)

**Comment by mattfarina** [comment]
Need to test this in EKS, AKS, and GKE (with the agent) to make sure running as non-root is able to get a service account and operate.

**Comment by mattfarina** [comment]
Moving to v2.7.0 as it's not going to make it in to v2.6.7

**Comment by izaac** [comment]
Rancher `v2.6.9-rc2 `

Agents
Fleet `v0.4.0-rc3`

Controller
Fleet `v0.4.0-rc3`
Fleet-controller `v0.4.0-rc3`
Gitjob `v.0.1.32`

This block was applied as expected in the agents
```
securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
```

The Fleet test repository: https://github.com/rancher/fleet-examples.git

Cluster versions under test

AKS `v1.23.8`
EKS `v1.22.13-eks-15b7512`
GKE `v1.22.12-gke.2300`

Validation of P0 test scenario passed, bundles are created, app is deployed in the downstream cluster.
