### ISSUE TITLE
Support configurable registry for fleet images

### ISSUE THREAD

**Issue by mattfarina** [rancher/fleet#869]
Fleet is currently hard coded to use images for itself from Docker Hub (in the `rancher` namespace) or (I think) for air gapped situations. The hard coded version is the build time default.

We need to add an option to override the built in default. So, there will be the built in default, an override to that (likely passed in as an env var), and then the end user configurable option for air gapped like setups.

**Comment by manno** [comment]
It's been a few weeks since we discussed this and I might be missing some context. 

I looked at the images and I can't find a place where images hard-coded. All references to [basic.Deployment](https://github.com/rancher/fleet/blob/master/pkg/basic/objects.go#L44) are using an image variable from options/config.

```
charts/fleet/templates/deployment.yaml
28:        image: '{{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}'
29-        name: fleet-controller
30-        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
```

```
charts/fleet-agent/templates/deployment.yaml
20:        image: '{{ template "system_default_registry" . }}{{.Values.image.repository}}:{{.Values.image.tag}}'
```

```
charts/fleet/charts/gitjob/templates/deployment.yaml
16:        - image: "{{ template "system_default_registry" . }}{{ .Values.gitjob.repository }}:{{ .Values.gitjob.tag }}"
...
23:          - --tekton-image
24:          - "{{ template "system_default_registry" . }}{{ .Values.tekton.repository }}:{{ .Values.tekton.tag }}"
```

So the changes will probably be limited to the release workflows?

**Comment by manno** [comment]
AgentImage for downstream cluster has the default registry prepended in here:

https://github.com/rancher/fleet/blob/master/charts/fleet/templates/configmap.yaml#L8

**Comment by mattfarina** [comment]
This can be closed at the  "system_default_registry" passed to fleet by Rancher is now setup to handle registries properly. When Rancher launches Fleet the proper registry will be passed in. Also, when the chart is launched stand alone it's possible to set this as well.
