### ISSUE TITLE
Fleet Manager / Controller on GKE - connection issues

### ISSUE THREAD

**Issue by mumblez** [rancher/fleet#91]
Hi,

Strange issue, I kinda got this working but for the past couple days I've been getting connection issues.

My setup:

GKE (google managed kubernetes), public cluster, master authorized network list contains public IPs of various IOT kubernetes clusters and myself.
kubectl configured and can use kubectl cli commands.

But, things like curl'ing fails, like in the guide for multi-cluster-install:

`curl -fLk https://<master ip>:6443/version`

results in `Operation timed out`

This appears to affect registration of clusters as I also see connection timeout errors.

```sh
kubectl get nodes
NAME                                      STATUS   ROLES    AGE   VERSION
gke-cluster-1-node-pool-1-294d904c-8sd0   Ready    <none>   36m   v1.15.12-gke.20
gke-cluster-1-node-pool-1-294d904c-b6df   Ready    <none>   36m   v1.15.12-gke.20
gke-cluster-1-node-pool-1-294d904c-bh9d   Ready    <none>   36m   v1.15.12-gke.20

curl -fLk ${API_SERVER_URL}/version
curl: (7) Failed to connect to <...master ip...> port 6443: Operation timed out

```

Have tried destroying and rebuilding the GKE cluster (fleet manager) in various zones with same result, not sure what's going on.

I understand this is more an issue with Google, just wondering if anyone has got this working on GKE, any advice is appreciated.

Thanks
Yusuf

**Comment by thirdeye-yusuf** [comment]
version: 0.3.0-alpha7

registering a cluster (with clientID):

```sh
kubectl -n fleet-system logs -l app=fleet-agent
time="2020-09-18T11:53:29Z" level=error msg="Failed to register agent: looking up secret fleet-system/fleet-agent-bootstrap or fleet-system/fleet-agent: Post \"http://<master ip>/apis/fleet.cattle.io/v1alpha1/namespaces/clusters/clusterregistrations\": dial tcp 35.195.188.217:80: i/o timeout"
```

ah, I just noticed, it's trying on port 80.

I amended the values.yaml apiServerURL value from <ip> to https://<ip>:6443, re-installed the agent:

```sh
13:02:29 $ kubectl -n fleet-system logs -l app=fleet-agent -f
time="2020-09-18T12:01:03Z" level=error msg="Failed to register agent: looking up secret fleet-system/fleet-agent-bootstrap or fleet-system/fleet-agent: Post \"https://<ip>:6443/apis/fleet.cattle.io/v1alpha1/namespaces/clusters/clusterregistrations\": dial tcp <ip>:6443: i/o timeout"
```

**Comment by mumblez** [comment]
version: 0.3.0-alpha7

registering a cluster (with clientID):

```sh
kubectl -n fleet-system logs -l app=fleet-agent
time="2020-09-18T11:53:29Z" level=error msg="Failed to register agent: looking up secret fleet-system/fleet-agent-bootstrap or fleet-system/fleet-agent: Post \"http://<master ip>/apis/fleet.cattle.io/v1alpha1/namespaces/clusters/clusterregistrations\": dial tcp <ip>: i/o timeout"
```

ah, I just noticed, it's trying on port 80.

I amended the values.yaml apiServerURL value from <ip> to https://<ip>:6443, re-installed the agent:

```sh
13:02:29 $ kubectl -n fleet-system logs -l app=fleet-agent -f
time="2020-09-18T12:01:03Z" level=error msg="Failed to register agent: looking up secret fleet-system/fleet-agent-bootstrap or fleet-system/fleet-agent: Post \"https://<ip>:6443/apis/fleet.cattle.io/v1alpha1/namespaces/clusters/clusterregistrations\": dial tcp <ip>:6443: i/o timeout"
```

**Comment by mumblez** [comment]
version: 0.3.0-alpha91

```sh
time="2020-09-18T14:07:41Z" level=error msg="Current credential failed, failing back to reregistering: Get \"https://34.77.105.21/apis/fleet.cattle.io/v1alpha1/namespaces/cluster-clusters-cluster-9813719905ac/bundledeployments\": dial tcp <ip>:443: i/o timeout"
```

(didn't have to patch apiServerURL in values.yaml) but still timeout :(

**Comment by mumblez** [comment]
when I re-install a new gke cluster (fleet manager) with a new ip and re-install the agent on the cluster devices, I notice:

```sh
time="2020-09-18T14:23:10Z" level=error msg="Current credential failed, failing back to reregistering: Get \"https://<old ip>/apis/fleet.cattle.io/v1alpha1/namespaces/cluster-clusters-cluster-9813719905ac/bundledeployments\": dial tcp <old ip>:443: i/o timeout"
```

appears to be using the old cluster ip, after a helm uninstall, do I need to clear any other resources?

**Comment by mumblez** [comment]
nvm, google changed the api IP port to 443, reinstalled everything and can connect the agent clusters. Closing.
