### ISSUE TITLE
Multiple paths in gitrepo cause charts to uninstall

### ISSUE THREAD

**Issue by xhejtman** [rancher/fleet#926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As of version 0.3.10, if gitrepo object contains more than 1 path, only the last one is deployed, the others are removed. Budles are created for all the paths, however, they are immediately deleted and only the last one persists. This worked in 0.3.9.

### Expected Behavior

Deploy all the paths.

### Steps To Reproduce

1. create gitrepo with multiple paths
2. see it deployed

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.3.10
- Cluster:
  - Provider: RKE2
  - Options: 3
  - Kubernetes Version: 1.21.11
```

**Comment by dtrouillet** [comment]
Maybe link with #920 ?

**Comment by xhejtman** [comment]
yes, it seems so, so sorry, closing this one. 

dupe of #920
