### ISSUE TITLE
Feature Request: add ability to utilize --atomic option of helm

### ISSUE THREAD

**Issue by mattfarina** [rancher/fleet#928]
### Is your feature request related to a problem?

When an update to a deployment fails a workload can be and remain offline.

### Solution you'd like

The ability to specify Helm `--atomic` flag which will do a rollback on failure.

### Alternatives you've considered

N/A

### Anything else?

SURE-3302

**Comment by MSpencer87** [comment]
Seeing an issue when setting the atomic flag to true when adding a new GitRepo
`An error occurred while rolling back the release. original upgrade error: context deadline exceeded: release atomic-test-single-cluster-ms-example failed: context deadline exceeded`

Steps to reproduce:
1) Fork the fleet-examples repo
2) Bring up HA Rancher on v2.6.9-rc, ensure the local cluster has Fleet v0.4.0
3) Create two downstream clusters (following Fleet p0)
4) Inside the forked fleet-examples repo, navigate to single-cluster and copy the helm folder and rename it
5) Add `atomic: true` to fleet.yaml
6) Push up the changes to the forked fleet-examples repo and navigate Continuous Delivery inside Rancher's main menu
7) Select Git Repos tab, select Add Repository
8) Enter a simple name for this test repo and enter the URL and branch of the forked fleet examples repo/branch
9) Enter the path of the copied/renamed folder inside the fleet-examples repo (ex: single-cluster/ms-example)
10) Select Create and note error messages `An error occurred while rolling back the release. original upgrade error: context deadline exceeded: release atomic-test-single-cluster-ms-example failed: context deadline exceeded`

**Comment by mattfarina** [comment]
@MSpencer87 @bmdepesa I was able to reproduce the using the _steps to reproduce_ but I also found an issue with the test that is causing the problem.

The single cluster _helm_ example sets the `timeout: 0`. This tells Fleet to not wait on Helm. That will cause the error you are seeing. If you change that to `timeout: 300` (which is 5 minutes) then it works. The issue here is that _atomic_ installs require waiting and you can't actually wait when you instantly timeout.

There is an issue though. Once you get it working and then you intentionally break an install to force a rollback you get a message like...

```
error syncing 'cluster-fleet-default-mft1-1f3fa270415c/atomic-atomic': handler bundle-deploy: release guestbook failed, and has been rolled back due to atomic being set: timed out waiting for the condition, requeuing
```

In the user interface you will see the error..
```
Release guestbook failed, and has been rolled back due to atomic being set: timed out waiting for the condition
```

While the error seems a little cryptic it's reporting the actual issue in my case. It was timing out waiting for the app to come online because it couldn't pull the image. So, it rolled back.

The **real issue** is that it keeps requeuing and trying again over and over. It tries to install, fails, rolls back, requeues, and tries again. In a loop.

**Comment by MSpencer87** [comment]
_Verified on Rancher `2.6.9-rc4` with Fleet v0.4.0_

Following repro steps above and setting `timeoutSeconds: 300` on fleet.yaml allows for successful creation of new GitRepo with `--atomic` flag set for passthrough
