### ISSUE TITLE
CIS v2 scan on a hardened cluster fails when fleet is deployed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/fleet#94]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On a cluster - CIS 1.5 hardened - Deploy CIS v2, OPA, Logging, monitoring and istio charts
- The CIS 1.5 hardened cluster scan when run, shows 2 tests - 5.1.5 and 5.3.2 as failures.

- following namespaces break test 5.1.5
```
kubectl get serviceaccounts --all-namespaces -o json | jq -r '.items[] | select(.metadata.name=="default") | select((.automountServiceAccountToken == null) or (.automountServiceAccountToken == true))' | jq .metadata.namespace
"cattle-gatekeeper-system"
"cattle-logging-system"
"cattle-monitoring-system"
"dashboard-shells"
"default"
"fleet-system"
"istio-system"
"kube-system"
```

**Expected Result:**
The charts should comply with hardening steps

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `8fd81a9b4`
- Installation option (single install/HA): Single node

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/pull/29054 addresses `dashboard-shells`

**Comment by sowmyav27** [comment]
**On master-head - commit id:`2229f5cd7`**

- Deploy a CIS 1.5 hardened cluster. (verified both 1.19.2 and 1.18.9 k8s clusters)
- Test 5.1.5 fails.
- `"fleet-system"` fails and is resulted in the below script when run

```
kubectl get serviceaccounts --all-namespaces -o json | jq -r '.items[] | select(.metadata.name=="default") | select((.automountServiceAccountToken == null) or (.automountServiceAccountToken == true))' | jq .metadata.namespace
```
Reopening the issue

**Comment by prachidamle** [comment]
After the above PR is merged, we will need a fleet release and new fleet-agent chart

**Comment by sowmyav27** [comment]
Reopening the issue as the fleet's tag deployed on latest master - commit id: `3950b8e` is `fleet:v0.3.0-beta300` and fix is not available.

**Comment by prachidamle** [comment]
fleet-agent chart is not updated with the latest fleet release: 0.3.0-beta5

@StrongMonkey is fixing CI to deliver update this release tag to https://github.com/rancher/charts/tree/dev-v2.5

**Comment by sowmyav27** [comment]
Validated using Fleet image tag: `rancher/fleet-agent:v0.3.0-beta5` and rancher commit id: `7154bdb`

Scan run Hardened CIS cluster still has 5.1.5 test as failure 
```
kubectl get serviceaccounts --all-namespaces -o json | jq -r '.items[] | select(.metadata.name=="default") | select((.automountServiceAccountToken == null) or (.automountServiceAccountToken == true))' | jq .metadata.namespace
"fleet-system"
```

Reopening the issue

**Comment by StrongMonkey** [comment]
Fleet is updated to have the CIS fix in this [pr](https://github.com/rancher/charts/pull/714)

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f7878`**

- Deploy a cis 1.5 hardened cluster. 
- Run rke-profile-hardened scan on the cluster
- No failures are seen

<img width="1411" alt="Screen Shot 2020-09-27 at 3 29 10 PM" src="https://user-images.githubusercontent.com/26032343/94377458-9f448000-00d6-11eb-91a9-e23e7709a332.png">
