### ISSUE TITLE
external-secrets

### ISSUE THREAD

**Issue by Giancarlo1974** [rancher/fleet#954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Rancher Fleet says it can't install the app because the kubernetes version must be> 1.18
My cluster uses 1.21

I am able to install the app manually without any problems

### Expected Behavior

install the app

### Steps To Reproduce

defaultNamespace: external-secrets
helm:
  repo: https://charts.external-secrets.io
  chart: external-secrets
  version: 0.5.2
  releaseName: external-secrets

### Environment

```markdown
- Rancher: 2.5.12
- Fleet Version: fleet:0.3.500
- Cluster:
  - Provider: Rke
  - Kubernetes Version: v1.20.10
```

**Comment by olblak** [comment]
Hi @Giancarlo1974 ,
Thanks for opening this issue but I am bit confused which version of Kubernetes are you running? 
According the support Matrix https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-5-12/
Kubernetes 1.21.x is not supported with Rancher 2.5.12

Could you upgrade your Rancher version to 2.6.7 which support Kubernetes version from 1.20 to 1.24
https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-7/

**Comment by Giancarlo1974** [comment]
Yes i use Kubernetes v1.20.10 and Rancher 2.5.12

On Rancher 2.6.8 + v1.24.4+rke2r1
Rancher Fleet works perfectly

**Comment by Giancarlo1974** [comment]
However, I encountered a problem:
manually I can install version 0.5.901 (linux only),
but i don't see version 0.5.9

via fleet, exactly the opposite: I can only install external-secrets: 0.5.9

**Comment by mattfarina** [comment]
@Giancarlo1974 Rancher 2.5.12 is an older version of Rancher 2.5 using and older version of fleet. Newer versions of Rancher 2.5, like 2.5.15, use newer versions of Fleet. Can you upgrade to a newer version of Rancher 2.5?
