### ISSUE TITLE
Feature Request: Better control of when helmSecretName is used

### ISSUE THREAD

**Issue by uivraeus** [rancher/fleet#978]
### Is your feature request related to a problem?

Yes.

We specify `GitRepo` definitions with `helmSecretName` to provide (reference to) credentials for accessing private chart registries. In these `GitRepo` definitions, we refer to several different paths to monitor, each containing its own "fleet.yaml".

This works as long as each "fleet.yaml" refers to the same _intended_ (private) registry source, but it is too easy to make a mistake and include a chart reference to some other registry (public or private). If such a mistake is made, the credentials are automatically sent in the request to that registry, which is really bad from a security perspective.

### Solution you'd like

Make it possible to specify applicability/scope for the credentials referred to by `helmSecretName`, e.g. a  URL or hostname regex.

This could be done by introducing another key next to `helmSecretName`, e.g. `helmSecretScope` or similar.

When this has been defined, the chart fetching in Fleet (`go-getter`?) should only provide credentials if the source matches what has been specified. Otherwise, no credentials must be provided.

### Alternatives you've considered

The scope (i.e. regex) for each set of credentials could also be defined via some custom annotations in the Secrets object, which would imply that no new key has to be introduced in the `GitRepo` definition.

**Comment by mattfarina** [comment]
Can you please share what version of Rancher and Fleet you are experiencing this problem with? [This was fixed in Helm 3.6.1](https://github.com/helm/helm/security/advisories/GHSA-56hp-xqp3-w2jf). Fleet uses the Helm SDK. We need to make sure this issue isn't still present in the latest Fleet.

**Comment by uivraeus** [comment]
@mattfarina I don't think anything has changed wrt. the situation I described above and I have verified that it's still possible to reproduce with Fleet v. 0.5.0.

But maybe I can clarify a bit;

The scenario I try to describe involves fetching of a chart (tgz-file) via the general "gogetter" support for the `chart`  key in `fleet.yaml`. 

Let's imagine a `GitRepo` definition like this:

```yaml
spec:
  # ...
  helmSecretName: helmsecret-dummy
  paths:
    - releases/gogetter-simple
    - releases/app-example
  # ...
```
The `helmSecretName` is needed for accessing `private-registry.com` (see below)

Content of `releases/app-example/fleet.yaml`:

```yaml
helm:
  # ...
  chart: oci://private-registry.com/example/charts/spa-example
  version: 0.7.0
```

Content of `releases/gogetter-simple/fleet.yaml`:

```yaml
helm:
  # ...
  chart: https://some-public-place.com/chart-0.1.0.tgz&archive=tgz
  # ...
```

This kind of GitRepo definition, where I mix public/private chart registry sources (indirect via `fleet.yaml` files), is not a good idea given the current behavior in Fleet because Fleet will include the Helm secret credentials as a Basic auth header in the HEAD/GET requests when connecting to `some-public-place.com`.

I used a simple HTTP server to log the requests from Fleet:

```log
User-Agent: Go-http-client/1.1
Authorization: Basic c29tZXVzZXI6czNjcjN0
Accept-Encoding: gzip


10.244.8.210 - - [23/Nov/2022 10:44:56] code 404, message File not found
10.244.8.210 - - [23/Nov/2022 10:44:56] "GET /chart-0.1.0.tgz&archive=tgz?terraform-get=1 HTTP/1.1" 404 -
```

I'm not sure I consider this a "bug" as Fleet only does what I've configured it to do, i.e. use `helmSecretName` when authenticating. Without a way of specifying "to what", I guess Fleet must use these credentials unconditionally when it connects to the registries.

Note that I don't know if there is any issue when connecting to a public _OCI registry_ (which should correspond to a `helm registry login` operation). I.e. when not leveraging the general gogetter-flexibility for `chart`  (I haven't investigated that scenario).

**Comment by manno** [comment]
We discussed this and want to add another `helmSecretName` option to the `helm:` section in `fleet.yaml`. This would make it possible to specify a secret per helm chart. We keep the old `helmSecretName` on the `gitrepo` resource for compatibility, warnings were added to the documentation.

**Comment by uivraeus** [comment]
By using explicit `helmSecretName` in each `fleet.yaml` the risk of accidentally providing credentials (or the wrong credentials) is greatly reduced, which is an improvement.

My only concern regarding this approach is that it puts a lot of trust on the individuals with (write) access to the tracked Git repositories where the various `fleet.yaml` files are defined. 

With the current (“legacy”) approach, the knowledge of the secrets, both name and content, is limited to those who have access to the cluster namespaces where all `GitRepo` resources are defined (e.g. `fleet-default` or `fleet-local`). 

Depending on an organization’s size and setup, I think there are situations where it makes sense to have a tighter access policy around the configuration of Fleet and its `GitRepo` and `Secret` definitions while allowing a broader community to define the content of the tracked repositories. These repositories would then be managed by different groups/teams with access to their own repositories but not necessarily to others. It would be good if that would also hold for the usage of (reference to) different chart registry credentials.

**Comment by raulcabello** [comment]
> Depending on an organization’s size and setup, I think there are situations where it makes sense to have a tighter access policy around the configuration of Fleet and its GitRepo and Secret definitions while allowing a broader community to define the content of the tracked repositories. These repositories would then be managed by different groups/teams with access to their own repositories but not necessarily to others. It would be good if that would also hold for the usage of (reference to) different chart registry credentials.

I agree with that.

In addition to that,  we currently fetch the helm secret in the fleet controller and mount it in a [volume](https://github.com/rancher/fleet/blob/master/pkg/controllers/git/git.go#L603-L617) in the `Job` that will run `fleet apply`. This would need to change if we move it to the `fleet.yaml` as this rendering happens inside the Job when running `fleet apply`. This `Job` doesn't have permission to fetch `Secrets` at the moment.

I would keep the `helmSecretName` in the `GitRepo` and I would make it possible to specify applicability/scope for the credentials referred to by helmSecretName, e.g. a URL or hostname regex as described [here](https://github.com/rancher/fleet/issues/978#issue-1374586095)

**Comment by raulcabello** [comment]
@rancher/qa
## Additionnal QA

### Problem
credentials are passed to all repositories in the `helmSecretName` is provided. We want to allow users to choose the repositories where the credentials should be passed

### Solution
`helmRepoUrlRegex` new field is added to the `GitRepo`.  Credentials will only be passed to the repo if the helm repo url matches the `helmRepoUrlRegex` 
 
### Testing
### Engineering Testing
#### Manual Testing
integration tests for this were added [here](https://github.com/rancher/fleet/tree/master/integrationtests/cli/helm)
I tested with a local helm repo

### QA Testing Considerations
It should work as before if the new `helmRepoUrlRegex`  parameter is not specified

**Comment by kkaempf** [comment]
QA is asking for clearer steps to reproduce @raulcabello

**Comment by raulcabello** [comment]
> QA is asking for clearer steps to reproduce @raulcabello

I added more information in the manual testing section [here](https://github.com/rancher/fleet/issues/978#issuecomment-1406677724)

**Comment by tkazmierczak-tt** [comment]
Hi, I'm also very interested in this functionality. Been testing fleet-0.6.0-rc.3 today and found that the current implementation does not cover authentication for charts from private OCI registries when property `helmRepoURLRegex` actually matches the OCI registry URL.

Below is a modified example based on [helm-oci-with-auth.yaml](https://github.com/rancher/fleet/blob/master/e2e/assets/single-cluster/helm-oci-with-auth.yaml) including helmRepoURLRegex set to match `oci://ghcr.io/fleetrepoci/guestbook-private` url of the *guestbook-private* chart.
```yaml
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
spec:
  repo: https://github.com/rancher/fleet-examples
  helmSecretName: helm-oci-secret
  helmRepoURLRegex: "oci://ghcr.io/fleetrepoci/*"
  paths:
  - single-cluster/helm-oci-with-auth
  targets:
  - clusterSelector:
      matchExpressions:
      - key: provider.cattle.io
        operator: NotIn
        values:
        - harvester
 ```

I expect this to work, but currently get failure message `failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden` when creating bundle.

Problem currently lies [here](https://github.com/rancher/fleet/blob/d2b8d7cb1fc0e2b913e6f539187f0debea7887f5/pkg/bundlereader/resources.go#L184-L189). The `repo` var is empty for charts configured from OCI registries. 

I think in "OCI mode" `helmRepoURLRegex` should be checked against `Chart` property of `HelmOptions`.

**Comment by raulcabello** [comment]
@tkazmierczak-tt Thanks for the feedback! https://github.com/rancher/fleet/pull/1341 should fix it

**Comment by jameson-mcghee** [comment]
@raulcabello, should [the issue mentioned above](https://github.com/rancher/fleet/issues/978#issuecomment-1435142942) be addressed before this is ready for testing?

**Comment by raulcabello** [comment]
@jameson-mcghee it has been addressed in https://github.com/rancher/fleet/pull/1341 . However it is not included in this release, so it will go in the next one.
Just to clarify for this release `helmRepoURLRegex` will be applied just to the `repo` field and not the `chart` field. I just updated https://github.com/rancher/fleet/issues/978#issuecomment-1406677724 to clarify that the helm repo url must be in the `repo` field

**Comment by tkazmierczak-tt** [comment]
@raulcabello by next release, you mean next RC release of 2.7.2 or 2.7.3? Trying to plan whether I will need to divide GitRepos.

**Comment by raulcabello** [comment]
@tkazmierczak-tt 2.7.3 
In 2.7.2 just the `repo` field will be checked. In 2.7.3 `chart` field will also be checked

**Comment by jameson-mcghee** [comment]
> @jameson-mcghee it has been addressed in #1341 . However it is not included in this release, so it will go in the next one. Just to clarify for this release `helmRepoURLRegex` will be applied just to the `repo` field and not the `chart` field. I just updated [#978 (comment)](https://github.com/rancher/fleet/issues/978#issuecomment-1406677724) to clarify that the helm repo url must be in the `repo` field

@raulcabello, if the fix will not be included in this release, then a separate ticket should be created on the release that will contain the fix to ensure validation of this issue occurs.

**Comment by sowmyav27** [comment]
@kkaempf @raulcabello wrt this issue - https://github.com/rancher/fleet/issues/978#issuecomment-1443766308, can you confirm  if [978](https://github.com/rancher/fleet/issues/978) issue is tracking that repo field changes only? And is there a separate ticket logged for chart field changes? Could you also confirm which fleet RC is this fix available in?

**Comment by raulcabello** [comment]
@sowmyav27 yes. https://github.com/rancher/fleet/issues/978 is checking just the `repo` field.
I created https://github.com/rancher/fleet/issues/1405 for checking the `chart` field. https://github.com/rancher/fleet/issues/1405 is not available in an RC yet.

https://github.com/rancher/fleet/issues/978 is available in the latest RC [v0.6.0-rc.5](https://github.com/rancher/fleet/releases/tag/v0.6.0-rc.5)

**Comment by slickwarren** [comment]
I tested this using rancher v2.7-head (4a9b7ba) with fleet v0.6.0-rc5, however I encountered an issue with the secrets which is either related to this ticket's changes, or at minimum is blocking me from testing the changes here. 

https://github.com/rancher/fleet/issues/1449

**Comment by slickwarren** [comment]
using [this test template](https://github.com/rancher/fleet/issues/978#issuecomment-1406677724) I performed the following tests on v2.7-head (087dd09):
* deploy a git repo using fleet with no `helmRepoURLRegex` defined -- git job provisions successfully
* deploy a git repo using fleet with `helmRepoURLRegex` defined:
  * matching the repo in the helm chart -- git job provisions successfully
  * not matching the repo in the helm chart -- git job gives user an error `... , error code: 401, response body: {\"error\":\"unauthorized\"}"`
